<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - Multilevel Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-circle-right')) {
    f.classList.add('fa-circle-down')
    f.classList.remove('fa-circle-right')
} else {
    f.classList.add('fa-circle-right')
    f.classList.remove('fa-circle-down')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR3</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./csstests.html" rel="" target="">
 <span class="menu-text">CSS tests</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-multi-level-models" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Multi Level Models</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-multi-level-models">    
        <li>
    <a class="dropdown-item" href="./01_regressionrefresh.html" rel="" target="">
 <span class="dropdown-text">1: Linear Regression | Clustered Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_intromlm.html" rel="" target="">
 <span class="dropdown-text">2: Multilevel Models</span></a>
  </li>  
        <li class="dropdown-header">3: Assumptions, Diagnostics &amp; Random Effect Structures</li>
        <li class="dropdown-header">4: Centering in MLM | Logistic</li>
        <li class="dropdown-header">5: Recap</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dimension-reduction--sem" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Dimension reduction &amp; SEM</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dimension-reduction--sem">    
        <li class="dropdown-header">7: Path Analysis</li>
        <li class="dropdown-header">8: Path Mediation</li>
        <li class="dropdown-header">9: Dimension Reduction</li>
        <li class="dropdown-header">10: EFA: Part 1</li>
        <li class="dropdown-header">11: EFA: Part 2</li>
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-extra" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Extra</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-extra">    
        <li class="dropdown-header">Example: Repeated Measures MLM</li>
        <li class="dropdown-header">Example: Intervention Study</li>
        <li class="dropdown-header">Example: Many Trials</li>
        <li class="dropdown-header">Example: ANOVA (rpt measures &amp; mixed)</li>
        <li class="dropdown-header">Example: Exploratory Factor Analysis</li>
        <li class="dropdown-header">Likelihood vs Probability</li>
        <li class="dropdown-header">Writing 3-level MLM equations</li>
        <li class="dropdown-header">PCA and Unequal Variances</li>
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introducing-multilevel-models" id="toc-introducing-multilevel-models" class="nav-link active" data-scroll-target="#introducing-multilevel-models">Introducing Multilevel Models</a></li>
  <li><a href="#fitting-multilevel-models" id="toc-fitting-multilevel-models" class="nav-link" data-scroll-target="#fitting-multilevel-models">Fitting Multilevel Models</a>
  <ul class="collapse">
  <li><a href="#model-formula" id="toc-model-formula" class="nav-link" data-scroll-target="#model-formula">Model Formula</a></li>
  <li><a href="#model-estimation" id="toc-model-estimation" class="nav-link" data-scroll-target="#model-estimation">Model Estimation</a>
  <ul class="collapse">
  <li><a href="#maximum-likelihood-ml" id="toc-maximum-likelihood-ml" class="nav-link" data-scroll-target="#maximum-likelihood-ml">Maximum Likelihood (ML)</a></li>
  <li><a href="#restricted-maximum-likelihood-reml" id="toc-restricted-maximum-likelihood-reml" class="nav-link" data-scroll-target="#restricted-maximum-likelihood-reml">Restricted Maximum Likelihood (REML)</a></li>
  <li><a href="#model-convergence" id="toc-model-convergence" class="nav-link" data-scroll-target="#model-convergence">Model Convergence</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exercises-intro-mlm" id="toc-exercises-intro-mlm" class="nav-link" data-scroll-target="#exercises-intro-mlm">Exercises: Intro MLM</a>
  <ul class="collapse">
  <li><a href="#wellbeing-across-scotland-cross-sectional" id="toc-wellbeing-across-scotland-cross-sectional" class="nav-link" data-scroll-target="#wellbeing-across-scotland-cross-sectional">Wellbeing Across Scotland (Cross-Sectional)</a></li>
  <li><a href="#audio-interference-in-executive-functioning-rpt-measures" id="toc-audio-interference-in-executive-functioning-rpt-measures" class="nav-link" data-scroll-target="#audio-interference-in-executive-functioning-rpt-measures">Audio Interference in Executive Functioning (Rpt Measures)</a></li>
  <li><a href="#wellbeing-over-time-longitudinal" id="toc-wellbeing-over-time-longitudinal" class="nav-link" data-scroll-target="#wellbeing-over-time-longitudinal">Wellbeing Over Time (Longitudinal)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multilevel Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="lo">
<p><strong>A Note on terminology</strong></p>
<p>The methods we’re going to learn about in the first five weeks of this course are known by lots of different names: “multilevel models”; “hierarchical linear models”; “mixed-effect models”; “mixed models”; “nested data models”; “random coefficient models”; “random-effects models”; “random parameter models”… and so on).</p>
<p>What the idea boils down to is that <strong>model parameters vary at more than one level.</strong> This week, we’re going to explore what that means.</p>
<p>Throughout this course, we will tend to use the terms “mixed effect model”, “linear mixed model (LMM)” and “multilevel model (MLM)” interchangeably.</p>
</div>
<section id="introducing-multilevel-models" class="level1">
<h1>Introducing Multilevel Models</h1>
<p>Multilevel Models (MLMs) (or “Linear Mixed Models” (LMMs)) take the approach of allowing the groups/clusters to vary around our <span class="math inline">\(\beta\)</span> estimates.</p>
<p>In the lectures, we saw this as:</p>
<p><span class="math display">\[
\begin{align}
&amp; \text{for observation }j\text{ in group }i \\
\quad \\
&amp; \text{Level 1:} \\
&amp; \color{red}{y_{ij}}\color{black} = \color{blue}{\beta_{0i} \cdot 1 + \beta_{1i} \cdot x_{ij}}\color{black} + \varepsilon_{ij} \\
&amp; \text{Level 2:} \\
&amp; \color{blue}{\beta_{0i}}\color{black} = \gamma_{00} + \color{orange}{\zeta_{0i}} \\
&amp; \color{blue}{\beta_{1i}}\color{black} = \gamma_{10} + \color{orange}{\zeta_{1i}} \\
\quad \\
&amp; \text{Where:} \\
&amp; \gamma_{00}\text{ is the population intercept, and }\color{orange}{\zeta_{0i}}\color{black}\text{ is the deviation of group }i\text{ from }\gamma_{00} \\
&amp; \gamma_{10}\text{ is the population slope, and }\color{orange}{\zeta_{1i}}\color{black}\text{ is the deviation of group }i\text{ from }\gamma_{10} \\
\end{align}
\]</span></p>
<p>We are now assuming <span class="math inline">\(\color{orange}{\zeta_0}\)</span>, <span class="math inline">\(\color{orange}{\zeta_1}\)</span>, and <span class="math inline">\(\varepsilon\)</span> to be normally distributed with a mean of 0, and we denote their variances as <span class="math inline">\(\sigma_{\color{orange}{\zeta_0}}^2\)</span>, <span class="math inline">\(\sigma_{\color{orange}{\zeta_1}}^2\)</span>, <span class="math inline">\(\sigma_\varepsilon^2\)</span> respectively.</p>
<p>The <span class="math inline">\(\color{orange}{\zeta}\)</span> components also get termed the “random effects” part of the model, Hence names like “random effects model”, etc.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternative notation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Many people use the symbol <span class="math inline">\(u\)</span> in place of <span class="math inline">\(\zeta\)</span>.<br>
In various resources, you are likely to see <span class="math inline">\(\alpha\)</span> used to denote the intercept instead of <span class="math inline">\(\beta_0\)</span>.</p>
<p>Sometimes, you will see the levels collapsed into one equation, as it might make for more intuitive reading. This often fits with the name “mixed effects” for these models:</p>
<p><span class="math display">\[
\color{red}{y_{ij}}\color{black} = (\color{blue}{\beta_0}\color{black} + \color{orange}{\zeta_{0i}}\color{black}) \cdot 1 + ( \color{blue}{\beta_{1}}\color{black} + \color{orange}{\zeta_{1i}} \color{black}) \cdot x_{ij}  +  \varepsilon_{ij} \\
\]</span></p>
<p>And then we also have the condensed matrix form of the model, in which the Z matrix represents the grouping structure, and the <span class="math inline">\(u\)</span> (or <span class="math inline">\(\zeta\)</span>) are the estimated random deviations. <span class="math display">\[
\mathbf{y} = \boldsymbol{X\beta} + \boldsymbol{Zu} + \boldsymbol{\varepsilon}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="fitting-multilevel-models" class="level1">
<h1>Fitting Multilevel Models</h1>
<p>To fit multilevel models, qe’re going to use the <code>lme4</code> package, and specifically the functions <code>lmer()</code> and <code>glmer()</code>.<br>
“(g)lmer” here stands for “(generalised) linear mixed effects regression”.</p>
You will have seen some use of these functions in the lectures. The broad syntax is:<br>
<br>
<div style="margin-left:50px;">
<strong>lmer(<em>formula</em>, data = <em>dataframe</em>, REML = <em>logical</em>, control = lmerControl(<em>options</em>))</strong>
</div>
<p><br></p>
<section id="model-formula" class="level2">
<h2 class="anchored" data-anchor-id="model-formula">Model Formula</h2>
<p>We write the first bit of our <strong>formula</strong> just the same as our old friend the normal linear model <code>y ~ 1 + x + x2 + ...</code>, where <code>y</code> is the name of our outcome variable, <code>1</code> is the intercept (which we don’t have to explicitly state as it will be included anyway) and <code>x</code>, <code>x2</code> etc are the names of our explanatory variables.</p>
<p>With <strong>lme4</strong>, we now have the addition of <strong>random effect terms</strong>, specified in parenthesis with the <code>|</code> operator (the vertical line | is often found to the left of the z key on QWERTY keyboards). We use the <code>|</code> operator to separate the parameters (intercept, slope etc.) on the LHS, from the grouping variable(s) on the RHS, by which we would like to model these parameters as varying.</p>
<div class="statbox">
<p><strong>Random Intercepts</strong><br>
Let us suppose that we wish to model our intercept not as a fixed constant, but as varying randomly according to some grouping around a fixed center. We can such a model by allowing the intercept to vary by our grouping variable (<code>g</code> below):</p>
<center>
<code>lmer(y ~ 1 + x + (1|g), data = df)</code>
</center>
<p><span class="math display">\[
\begin{align}
&amp; \text{Level 1:} \\
&amp; \color{red}{Y_{ij}} = \color{blue}{\beta_{0i} \cdot 1 + \beta_{1} \cdot X_{ij}} + \varepsilon_{ij} \\
&amp; \text{Level 2:} \\
&amp; \color{blue}{\beta_{0i}} = \gamma_{00} + \color{orange}{\zeta_{0i}} \\
\end{align}
\]</span></p>
</div>
<div class="statbox">
<p><strong>Random Intercepts and Slopes</strong><br>
By extension we can also allow the effect <code>y~x</code> to vary between groups, by including the <code>x</code> on the left hand side of <code>|</code> in the random effects part of the call to <code>lmer()</code>.</p>
<center>
<code>lmer(y ~ 1 + x + (1 + x |g), data = df)</code>
</center>
<p><span class="math display">\[
\begin{align}
&amp; \text{Level 1:} \\
&amp; \color{red}{y_{ij}} = \color{blue}{\beta_{0i} \cdot 1 + \beta_{1i} \cdot x_{ij}} + \varepsilon_{ij} \\
&amp; \text{Level 2:} \\
&amp; \color{blue}{\beta_{0i}} = \gamma_{00} + \color{orange}{\zeta_{0i}} \\
&amp; \color{blue}{\beta_{1i}} = \gamma_{10} + \color{orange}{\zeta_{1i}} \\
\end{align}
\]</span></p>
</div>
</section>
<section id="model-estimation" class="level2">
<h2 class="anchored" data-anchor-id="model-estimation">Model Estimation</h2>
<section id="maximum-likelihood-ml" class="level3">
<h3 class="anchored" data-anchor-id="maximum-likelihood-ml">Maximum Likelihood (ML)</h3>
<p>Remember back to DAPR2 when we introduced logistic regression, and we briefly discussed <strong>Maximum likelihood</strong> in an explanation of how models are fitted.</p>
<p>The key idea of <em>maximum likelihood estimation</em> (MLE) is that we (well, the computer) iteratively finds the set of estimates for our model which it considers to best reproduce our observed data. Recall our simple linear regression model of how time spent outdoors (hrs per week) is associated with mental wellbeing: <span class="math display">\[
\color{red}{Wellbeing_i} = \color{blue}{\beta_0 \cdot{} 1 + \beta_1 \cdot{} OutdoorTime_{i}} + \varepsilon_i
\]</span> There are values of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\sigma_\varepsilon\)</span> which maximise the probability of observing the data that we have. For linear regression, these we obtained these same values a different way, via minimising the sums of squares. And we saw that this is not possible for more complex models (e.g., logistic), which is where we turn to MLE.</p>
<div class="statbox">
<p>To read about the subtle difference between “likelihood” and “probability”, you can find a short explanation <a href="./lvp.html" target="_blank">here</a></p>
</div>
<p>If we are estimating just one single parameter (e.g.&nbsp;a mean), then we can imagine the process of <em>maximum likelihood estimation</em> in a one-dimensional world - simply finding the top of the curve:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mle" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/intro/mle.png" class="img-fluid figure-img" width="350"></p>
<figcaption class="figure-caption">Figure&nbsp;1: MLE</figcaption>
</figure>
</div>
</div>
</div>
<p>However, our typical models estimate a whole bunch of parameters. The simple regression model above is already having to estimate <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\sigma_\varepsilon\)</span>, and our multi-level models have far more! With lots of parameters being estimated and all interacting to influence the likelihood, our nice curved line becomes a complex surface (see Left panel of <a href="#fig-multisurf">Figure&nbsp;2</a>). So what we (our computers) need to do is find the maximum, but avoid local maxima and singularities (see <a href="#fig-maxima">Figure&nbsp;3</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-multisurf" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/multisurftb.png" class="img-fluid figure-img" style="width:49.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;2: MLE for a more complex model</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="restricted-maximum-likelihood-reml" class="level3">
<h3 class="anchored" data-anchor-id="restricted-maximum-likelihood-reml">Restricted Maximum Likelihood (REML)</h3>
<p>When it comes to estimating multilevel models, maximum likelihood will consider the fixed effects as fixed, known values in its estimation of the variance components (the random effect variances). This leads to biased estimates of the variance components, specifically biasing them toward being too small, especially if <span class="math inline">\(n_\textrm{clusters} - n_\textrm{level 2 predictors} - 1 &lt; 50\)</span>. This leads to the standard errors of the fixed effects being too small, thereby inflating our type 1 error rate (i.e.&nbsp;greater chance of incorrectly rejecting our null hypothesis).</p>
<p>Restricted Maximum Likelihood (REML) is a method that separates the estimation of fixed and random parts of the model, leading to unbiased estimates of the variance components.</p>
<div class="rtip">
<p>We can choose whether to fit with ML or REML with the <code>REML</code> argument of <code>lmer()</code>:</p>
<p><code>lmer(formula, data = data.frame, **REML = TRUE/FALSE**)</code></p>
<p><code>lmer()</code> models are by default fitted with REML. This is better for small samples.</p>
</div>
<!-- :::sticky -->
<!-- __Model Comparisons in MLM__ -->
<!-- When we compare models that differ in their fixed effects via comparing model deviance (e.g. the likelihood ratio), REML should __not__ be used as only the variance components are included in the likelihood. Functions like `anova()` will automatically refit your models with `ML` for you, but it is worth checking.    -->
<!-- We __cannot__ compare (either with ML or REML) models that differ in both the fixed and random parts.  -->
<!-- ::: -->
</section>
<section id="model-convergence" class="level3">
<h3 class="anchored" data-anchor-id="model-convergence">Model Convergence</h3>
<p>For large datasets and/or complex models (lots of random-effects terms), it is quite common to get a <em>convergence warning</em>. There are lots of different ways to <a href="https://rstudio-pubs-static.s3.amazonaws.com/33653_57fc7b8e5d484c909b615d8633c01d51.html">deal with these</a> (to try to rule out hypotheses about what is causing them).</p>
<p>For now, if <code>lmer()</code> gives you convergence errors, you could try changing the optimizer. Bobyqa is a good one: add <code>control = lmerControl(optimizer = "bobyqa")</code> when you run your model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(y <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> ... <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> .... <span class="sc">|</span> g), <span class="at">data =</span> df, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">"bobyqa"</span>))</span></code></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What <em>is</em> a convergence warning??
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There are different techniques for maximum likelihood estimation, which we apply by using different ‘optimisers’. Technical problems to do with <strong>model convergence</strong> and <strong>‘singular fit’</strong> come into play when the optimiser we are using either can’t find a suitable maximum, or gets stuck in a singularity (think of it like a black hole of likelihood, which signifies that there is not enough variation in our data to construct such a complex model).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-maxima" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/intro/mle2.png" class="img-fluid figure-img" style="width:49.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: local/global maxima and singularities</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="exercises-intro-mlm" class="level1">
<h1>Exercises: Intro MLM</h1>
<section id="wellbeing-across-scotland-cross-sectional" class="level2">
<h2 class="anchored" data-anchor-id="wellbeing-across-scotland-cross-sectional">Wellbeing Across Scotland (Cross-Sectional)</h2>
<div class="frame">
<p>Recall our dataset from last week, in which we used linear regression to determine how outdoor time (hours per week) is associated with wellbeing in different local authority areas (LAAs) of Scotland. We have data from various LAAs, from Glasgow City, to the Highlands.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>scotmw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/LAAwellbeing.csv"</span>)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="cszbzfmzgo" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#cszbzfmzgo .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cszbzfmzgo .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cszbzfmzgo .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cszbzfmzgo .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cszbzfmzgo .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cszbzfmzgo .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cszbzfmzgo .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cszbzfmzgo .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cszbzfmzgo .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cszbzfmzgo .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cszbzfmzgo .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cszbzfmzgo .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cszbzfmzgo .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cszbzfmzgo .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cszbzfmzgo .gt_from_md > :first-child {
  margin-top: 0;
}

#cszbzfmzgo .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cszbzfmzgo .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cszbzfmzgo .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cszbzfmzgo .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cszbzfmzgo .gt_row_group_first td {
  border-top-width: 2px;
}

#cszbzfmzgo .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cszbzfmzgo .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cszbzfmzgo .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cszbzfmzgo .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cszbzfmzgo .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cszbzfmzgo .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cszbzfmzgo .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cszbzfmzgo .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cszbzfmzgo .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cszbzfmzgo .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cszbzfmzgo .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cszbzfmzgo .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cszbzfmzgo .gt_left {
  text-align: left;
}

#cszbzfmzgo .gt_center {
  text-align: center;
}

#cszbzfmzgo .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cszbzfmzgo .gt_font_normal {
  font-weight: normal;
}

#cszbzfmzgo .gt_font_bold {
  font-weight: bold;
}

#cszbzfmzgo .gt_font_italic {
  font-style: italic;
}

#cszbzfmzgo .gt_super {
  font-size: 65%;
}

#cszbzfmzgo .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#cszbzfmzgo .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cszbzfmzgo .gt_indent_1 {
  text-indent: 5px;
}

#cszbzfmzgo .gt_indent_2 {
  text-indent: 10px;
}

#cszbzfmzgo .gt_indent_3 {
  text-indent: 15px;
}

#cszbzfmzgo .gt_indent_4 {
  text-indent: 20px;
}

#cszbzfmzgo .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true">
<thead class="gt_col_headings">
<tr class="header">
<th id="variable" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">variable</th>
<th id="description" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">description</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="variable">ppt</td>
<td class="gt_row gt_left" headers="description">Participant ID</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="variable">name</td>
<td class="gt_row gt_left" headers="description">Participant Name</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="variable">laa</td>
<td class="gt_row gt_left" headers="description">Local Authority Area</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="variable">outdoor_time</td>
<td class="gt_row gt_left" headers="description">Self report estimated number of hours per week spent outdoors</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="variable">wellbeing</td>
<td class="gt_row gt_left" headers="description">Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="variable">density</td>
<td class="gt_row gt_left" headers="description">LAA Population Density (people per square km)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Using <code>lmer()</code> from the <strong>lme4</strong> package, fit a model predict <code>wellbeing</code> from <code>outdoor_time</code>, with by-LAA random intercepts.<br>
Pass the model to <code>summary()</code> to see the output.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-1" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')"> Solution </span>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ri_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(wellbeing <span class="sc">~</span> outdoor_time <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> laa), <span class="at">data =</span> scotmw)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ri_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: wellbeing ~ outdoor_time + (1 | laa)
   Data: scotmw

REML criterion at convergence: 866.6

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.2218 -0.7192  0.1217  0.6395  1.8287 

Random effects:
 Groups   Name        Variance Std.Dev.
 laa      (Intercept) 106.23   10.307  
 Residual              25.46    5.046  
Number of obs: 132, groups:  laa, 20

Fixed effects:
             Estimate Std. Error t value
(Intercept)  38.18979    2.64778   14.42
outdoor_time  0.21349    0.07236    2.95

Correlation of Fixed Effects:
            (Intr)
outdoor_tim -0.463</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Sometimes the easiest way to start understanding your model is to visualise it.</p>
<p>Load the package <strong>broom.mixed</strong>. Along with some handy functions <code>tidy()</code> and <code>glance()</code> which give us the information we see in <code>summary()</code>, there is a handy function called <code>augment()</code> which returns us the data in the model plus the fitted values, residuals, hat values, Cook’s D etc..</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ri_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(wellbeing <span class="sc">~</span> outdoor_time <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> laa), <span class="at">data =</span> scotmw)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(ri_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 132 × 14
   wellbeing outdoor_t…¹ laa   .fitted .resid  .hat .cooksd .fixed   .mu .offset
       &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1        37          20 West…    32.4  4.64  0.139 7.91e-2   42.5  32.4       0
 2        34          23 Falk…    31.7  2.28  0.192 3.00e-2   43.1  31.7       0
 3        39          29 Falk…    33.0  6.00  0.195 2.13e-1   44.4  33.0       0
 4        42          21 Scot…    40.1  1.95  0.163 1.74e-2   42.7  40.1       0
 5        37          10 Dumf…    37.4 -0.407 0.167 7.84e-4   40.3  37.4       0
 6        42          19 Argy…    43.9 -1.91  0.122 1.12e-2   42.2  43.9       0
 7        38          13 Pert…    46.1 -8.06  0.139 2.39e-1   41.0  46.1       0
 8        44          21 East…    44.4 -0.414 0.168 8.17e-4   42.7  44.4       0
 9        47          16 Inve…    42.7  4.30  0.193 1.07e-1   41.6  42.7       0
10        35          12 Midl…    33.1  1.94  0.161 1.69e-2   40.8  33.1       0
# … with 122 more rows, 4 more variables: .sqrtXwt &lt;dbl&gt;, .sqrtrwt &lt;dbl&gt;,
#   .weights &lt;dbl&gt;, .wtres &lt;dbl&gt;, and abbreviated variable name ¹​outdoor_time</code></pre>
</div>
</div>
<p>Add to the code below to plot the model fitted values, and color them according to LAA. (you will need to edit <code>ri_model</code> to be whatever name you assigned to your model).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(ri_model) <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> outdoor_time, <span class="at">y =</span> ...... </span></code></pre></div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(ri_model) <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> outdoor_time, <span class="at">y =</span> .fitted, <span class="at">col =</span> laa)) <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02_intromlm_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>We have just fitted the model: <span class="math display">\[
\begin{align}
&amp; \text{For person } j \text{ in LAA } i \\
&amp; \color{red}{\textrm{Wellbeing}_{ij}}\color{black} = \color{blue}{\beta_{0i} \cdot 1 + \beta_{1} \cdot \textrm{Outdoor Time}_{ij}}\color{black} + \varepsilon_{ij} \\
&amp; \color{blue}{\beta_{0i}}\color{black} = \gamma_{00} + \color{orange}{\zeta_{0i}} \\
\end{align}
\]</span></p>
<p>For our estimates of <span class="math inline">\(\gamma_{00}\)</span> (the fixed value around which LAA intercepts vary) and <span class="math inline">\(\beta_1\)</span> (the fixed estimate of the relationship between wellbeing and outdoor time), we can use <code>fixef()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(ri_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept) outdoor_time 
   38.189795     0.213492 </code></pre>
</div>
</div>
<p>Can you add to the plot in the previous question, a thick black line with the intercept and slope given by <code>fixef()</code>?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Hint:</strong> <code>geom_abline()</code></p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(ri_model) <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> outdoor_time, <span class="at">y =</span> .fitted, <span class="at">col =</span> laa)) <span class="sc">+</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">fixef</span>(ri_model)[<span class="dv">1</span>], <span class="at">slope =</span> <span class="fu">fixef</span>(ri_model)[<span class="dv">2</span>], <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02_intromlm_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
By now, you should have a plot which looks more or less like the left-hand figure below (we have added on the raw data - the points).<br>

<div style="display:inline-block; width: 55%;vertical-align: top;">
<div class="cell" data-layout-align="center" data-fig.asp="1">
<div class="cell-output-display">
<div id="fig-modfit" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="02_intromlm_files/figure-html/fig-modfit-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Model fitted values</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div style="display:inline-block; width: 40%;vertical-align: top;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lmersummap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/intro/summarylmer2.png" class="img-fluid figure-img" width="400"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Summary model output<br>lmer(wellbeing~1 + outdoor_time + (1|laa),<br>data = scotmw)</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><br> <br> We’re going to map the parts of the plot in <a href="#fig-modfit">Figure&nbsp;4</a> to the <code>summary()</code> output of the model in <a href="#fig-lmersummap">Figure&nbsp;5</a>. Match the coloured sections Red, Orange, Yellow and Blue in <a href="#fig-lmersummap">Figure&nbsp;5</a> to the descriptions below of <a href="#fig-modfit">Figure&nbsp;4</a> A through D.</p>
<ol type="A">
<li>where the black line cuts the y axis</li>
<li>the standard deviation of the distances from all the individual LAA lines to the black line</li>
<li>the slope of the black line</li>
<li>the standard deviation of the distances from all the individual observations to the line for the LAA to which it belongs.</li>
</ol>
<p>Can you also match those same coloured sections in <a href="#fig-lmersummap">Figure&nbsp;5</a> to the mathematical terms in the model equation:</p>
<p><span class="math display">\[
\begin{align}
&amp; \text{Level 1:} \\
&amp; \color{red}{Wellbeing_{ij}}\color{black} = \color{blue}{\beta_{0i} \cdot 1 + \beta_{1} \cdot OutdoorTime_{ij}}\color{black} + \varepsilon_{ij} \\
&amp; \text{Level 2:} \\
&amp; \color{blue}{\beta_{0i}}\color{black} = \gamma_{00} + \color{orange}{\zeta_{0i}} \\
\quad \\
&amp; \text{where} \\
&amp; \color{orange}{\zeta_0}\color{black} \sim N(0, \sigma_{\color{orange}{\zeta_{0}}}\color{black})  \text{ independently} \\
&amp; \varepsilon \sim N(0, \sigma_{\varepsilon}) \text{ independently} \\
\end{align}
\]</span></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<ul>
<li>Yellow = B = <span class="math inline">\(\sigma_{\color{orange}{\zeta_{0}}}\)</span></li>
<li>Red = D = <span class="math inline">\(\sigma_{\varepsilon}\)</span><br>
</li>
<li>Blue = A = <span class="math inline">\(\gamma_{00}\)</span><br>
</li>
<li>Orange = C = <span class="math inline">\(\beta_{1}\)</span></li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Fit a model which allows <em>also</em> (along with the intercept) the effect of <code>outdoor_time</code> to vary by-LAA.</p>
<p>Then, using <code>augment()</code> again, plot the model fitted values. What do you think you will see?<br>
Does it look like this model better represents the individual LAAs? Take a look at, for instance, Glasgow City.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-5" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"> Solution </span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rs_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">|</span> laa), <span class="at">data =</span> scotmw)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(rs_model) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> outdoor_time, <span class="at">y =</span> .fitted, <span class="at">col =</span> laa)) <span class="sc">+</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>wellbeing), <span class="at">alpha=</span>.<span class="dv">4</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02_intromlm_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="audio-interference-in-executive-functioning-rpt-measures" class="level2">
<h2 class="anchored" data-anchor-id="audio-interference-in-executive-functioning-rpt-measures">Audio Interference in Executive Functioning (Rpt Measures)</h2>
<p>While the wellbeing example considers the groupings or ‘clusters’ of different LAAs, a more relate-able grouping in psychological research is that of several observations belonging to the same individual. One obvious benefit of this is that we can collect many more observations with fewer participants but control for the resulting dependency of observations.</p>
<div class="frame">
<p>Recall the data from the previous week, from an experiment in which executive functioning was measured (via the SDMT) for people when listening to different types of audio, either via normal speakers or via noise-cancelling headphones.</p>
<p>This week, we have data from a replication of that study, in which the researchers managed to recruit 30 participants. Unfortunately, some participants did not complete all the trials, so we have an unbalanced design. The data is available at <a href="https://uoepsy.github.io/data/ef_replication.csv">https://uoepsy.github.io/data/ef_replication.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="fptnpbqagc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#fptnpbqagc .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#fptnpbqagc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fptnpbqagc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#fptnpbqagc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#fptnpbqagc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#fptnpbqagc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fptnpbqagc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fptnpbqagc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#fptnpbqagc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#fptnpbqagc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#fptnpbqagc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#fptnpbqagc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#fptnpbqagc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#fptnpbqagc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#fptnpbqagc .gt_from_md > :first-child {
  margin-top: 0;
}

#fptnpbqagc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#fptnpbqagc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#fptnpbqagc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#fptnpbqagc .gt_row_group_first td {
  border-top-width: 2px;
}

#fptnpbqagc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#fptnpbqagc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#fptnpbqagc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fptnpbqagc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#fptnpbqagc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#fptnpbqagc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fptnpbqagc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fptnpbqagc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fptnpbqagc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_left {
  text-align: left;
}

#fptnpbqagc .gt_center {
  text-align: center;
}

#fptnpbqagc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#fptnpbqagc .gt_font_normal {
  font-weight: normal;
}

#fptnpbqagc .gt_font_bold {
  font-weight: bold;
}

#fptnpbqagc .gt_font_italic {
  font-style: italic;
}

#fptnpbqagc .gt_super {
  font-size: 65%;
}

#fptnpbqagc .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#fptnpbqagc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#fptnpbqagc .gt_indent_1 {
  text-indent: 5px;
}

#fptnpbqagc .gt_indent_2 {
  text-indent: 10px;
}

#fptnpbqagc .gt_indent_3 {
  text-indent: 15px;
}

#fptnpbqagc .gt_indent_4 {
  text-indent: 20px;
}

#fptnpbqagc .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true">
<thead class="gt_col_headings">
<tr class="header">
<th id="variable" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">variable</th>
<th id="description" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">description</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="variable">PID</td>
<td class="gt_row gt_left" headers="description">Participant ID</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="variable">trial_n</td>
<td class="gt_row gt_left" headers="description">Trial Number (1-15)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="variable">audio</td>
<td class="gt_row gt_left" headers="description">Audio heard during the test ('no_audio', 'white_noise','music')</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="variable">headphones</td>
<td class="gt_row gt_left" headers="description">Whether the participant listened via speakers in the room or via noise cancelling headphones</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="variable">SDMT</td>
<td class="gt_row gt_left" headers="description">Symbol Digit Modalities Test (SDMT) score</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>How many participants are there in the data?<br>
How many have complete data (15 trials)?<br>
What is the average number of trials that participants completed? What is the minimum?<br>
Does every participant have <em>some</em> data for each type of audio?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>count()</code> function will likely be useful here.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>efdata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/ef_replication.csv"</span>)</span></code></pre></div>
</div>
<p>Here are the counts of trials for each participant. We can see that no participant completed all 15 trials. Everyone completed at least 10, and the median was 12.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>efdata <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(PID) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     PID                  n     
 Length:30          Min.   :10  
 Class :character   1st Qu.:11  
 Mode  :character   Median :12  
                    Mean   :12  
                    3rd Qu.:13  
                    Max.   :14  </code></pre>
</div>
</div>
<p>We can add in <code>audio</code> to our counting to see that everyone has data from <span class="math inline">\(\geq 2\)</span> trials for a given audio type.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>efdata <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(PID,audio) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     PID                    audio          n    
 Length:90          no_audio   :30   Min.   :2  
 Class :character   white_noise:30   1st Qu.:4  
 Mode  :character   music      :30   Median :4  
                                     Mean   :4  
                                     3rd Qu.:5  
                                     Max.   :5  </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Set the reference levels of the <code>audio</code> and <code>headphones</code> variables to “no audio” and “speakers” respectively.<br>
Fit a multilevel model to address the research question below.</p>
<blockquote class="blockquote">
<p>How do different types of audio interfere with executive functioning, and does this interference differ depending upon whether or not noise-cancelling headphones are used?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
things to think about:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>what is our outcome variable of interest?</li>
<li>what are our predictor variables that we are interested in?
<ul>
<li>these should be in the fixed effects part.<br>
</li>
</ul></li>
<li>what is the clustering?
<ul>
<li>this should be the random effects <code>(1 | cluster)</code> part</li>
</ul></li>
<li>does audio type (<code>audio</code>) vary within clusters, or between?
<ul>
<li>if so, we might be able to fit a random slope of <code>audio | cluster</code>. if not, then it doesn’t make sense to do so.<br>
</li>
</ul></li>
<li>does delivery mode (<code>headphones</code>) vary within clusters, or between? - if so, we might be able to fit a random slope of <code>headphones | cluster</code>. if not, then it doesn’t make sense to do so.</li>
</ul>
<p><em>If you get an error about model convergence, consider changing the optimiser (see <a href="02_intromlm.html#Estimation">above</a>)</em></p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>efdata <span class="ot">&lt;-</span> efdata <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">audio =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(audio), <span class="st">"no_audio"</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">headphones =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(headphones), <span class="st">"speakers"</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>sdmt_mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(SDMT <span class="sc">~</span> audio <span class="sc">*</span> headphones <span class="sc">+</span> </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>              (<span class="dv">1</span> <span class="sc">+</span> audio <span class="sc">|</span> PID), <span class="at">data =</span> efdata,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">REML =</span> <span class="cn">TRUE</span>, <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer=</span><span class="st">"bobyqa"</span>))</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sdmt_mod)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: SDMT ~ audio * headphones + (1 + audio | PID)
   Data: efdata
Control: lmerControl(optimizer = "bobyqa")

REML criterion at convergence: 2376.2

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.34520 -0.62861  0.05762  0.60807  2.21250 

Random effects:
 Groups   Name             Variance Std.Dev. Corr       
 PID      (Intercept)      51.17    7.153               
          audiowhite_noise 15.22    3.901    -0.25      
          audiomusic       13.69    3.700     0.03 -0.16
 Residual                  31.49    5.612               
Number of obs: 360, groups:  PID, 30

Fixed effects:
                                          Estimate Std. Error t value
(Intercept)                               33.25800    1.98899  16.721
audiowhite_noise                          -0.03044    1.44501  -0.021
audiomusic                                -8.01731    1.41148  -5.680
headphonesanc_headphones                   6.85313    2.81173   2.437
audiowhite_noise:headphonesanc_headphones  8.02458    2.04497   3.924
audiomusic:headphonesanc_headphones       -3.58747    2.00128  -1.793

Correlation of Fixed Effects:
            (Intr) adwht_ audmsc hdphn_ adw_:_
audiowht_ns -0.352                            
audiomusic  -0.174  0.192                     
hdphnsnc_hd -0.707  0.249  0.123              
adwht_ns:h_  0.249 -0.707 -0.136 -0.351       
admsc:hdph_  0.123 -0.135 -0.705 -0.173  0.191</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>We now have a model, but we don’t have any p-values, confidence intervals, or inferential criteria on which to draw conclusions.</p>
<p>Pick a method of your choosing and perform a test of/provide an interval for the relevant effect of interest.<br>
Provide a brief write-up of the results along with a visualisation.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Options
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>As with normal regression, we have two main ways in which we can conduct inference. We can focus on our coefficients, or we can compare models.</p>
<p>There are a whole load of different methods available for drawing inferences from multilevel models, which means it can be a bit of a never-ending rabbit hole. For the purposes of this course, we’ll limit ourselves to these two:</p>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 44%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>df approximations</th>
<th>likelihood-based</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>model parameters</td>
<td><code>library(parameters)</code><br><code>model_parameters(model, ci_method="kr")</code></td>
<td><code>confint(model, type="profile")</code></td>
</tr>
<tr class="even">
<td>model comparison</td>
<td><code>library(pbkrtest)</code><br><code>KRmodcomp(model1,model0)</code></td>
<td><code>anova(model0,model)</code></td>
</tr>
<tr class="odd">
<td></td>
<td>fit models with <code>REML=TRUE</code>.<br>good option for small samples</td>
<td>fit models with <code>REML=FALSE</code>.<br>needs large N at both levels (40+)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>In this case we have <span class="math inline">\(n=30\)</span> participants (our level 2 sample size), and each participant has at most 15 observations (and some have fewer). These numbers are possibly a bit small for standard likelihood based methods. We would be better off using models fitted with REML because they will provide more accurate estimates of the variance components (the <code>(1 + audio | PID)</code> bit), and so better estimates of the standard errors for our fixed effects.</p>
<p>The easiest option here is to use the <strong>parameters</strong> package:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(sdmt_mod, <span class="at">ci_method=</span><span class="st">"kr"</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter                                         | Coefficient |   SE |          95% CI |     t |    df |      p
-----------------------------------------------------------------------------------------------------------------
(Intercept)                                       |       33.26 | 1.99 | [ 29.18, 37.34] | 16.71 | 27.97 | &lt; .001
audio [white_noise]                               |       -0.03 | 1.45 | [ -3.00,  2.94] | -0.02 | 27.59 | 0.983 
audio [music]                                     |       -8.02 | 1.41 | [-10.92, -5.12] | -5.67 | 27.42 | &lt; .001
headphones [anc_headphones]                       |        6.85 | 2.81 | [  1.09, 12.62] |  2.44 | 27.94 | 0.021 
audio [white_noise] × headphones [anc_headphones] |        8.02 | 2.05 | [  3.83, 12.22] |  3.92 | 27.73 | &lt; .001
audio [music] × headphones [anc_headphones]       |       -3.59 | 2.00 | [ -7.69,  0.52] | -1.79 | 27.77 | 0.084 

# Random Effects

Parameter                              | Coefficient |   SE |        95% CI
---------------------------------------------------------------------------
SD (Intercept: PID)                    |        7.15 | 1.11 | [ 5.28, 9.69]
SD (audiowhite_noise: PID)             |        3.90 | 1.04 | [ 2.31, 6.58]
SD (audiomusic: PID)                   |        3.70 | 1.10 | [ 2.07, 6.62]
Cor (Intercept~audiowhite_noise: PID)  |       -0.25 | 0.31 | [-0.72, 0.37]
Cor (Intercept~audiomusic: PID)        |        0.03 | 0.32 | [-0.53, 0.58]
Cor (audiowhite_noise~audiomusic: PID) |       -0.16 | 0.41 | [-0.76, 0.58]
SD (Residual)                          |        5.61 | 0.24 | [ 5.16, 6.10]</code></pre>
</div>
</div>
<p>And if we want to go down the model comparison route, we just need to isolate the relevant part(s) of the model that we are interested in. For instance, to test the interaction:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>sdmt_res <span class="ot">&lt;-</span> <span class="fu">lmer</span>(SDMT <span class="sc">~</span> audio <span class="sc">+</span> headphones <span class="sc">+</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>              (<span class="dv">1</span> <span class="sc">+</span> audio <span class="sc">|</span> PID), <span class="at">data =</span> efdata,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">REML =</span> <span class="cn">TRUE</span>, <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer=</span><span class="st">"bobyqa"</span>))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pbkrtest)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">KRmodcomp</span>(<span class="at">largeModel =</span> sdmt_mod, <span class="at">smallModel =</span> sdmt_res)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>large : SDMT ~ audio * headphones + (1 + audio | PID)
small : SDMT ~ audio + headphones + (1 + audio | PID)
        stat    ndf    ddf F.scaling   p.value    
Ftest 10.637  2.000 26.756   0.96406 0.0003987 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p>Inclusion of the interaction between headphones and audio-type was found to improve model fit (<span class="math inline">\(F(2, 26.8^*) = 10.64, p &lt; .001\)</span>).</p>
<p>When listening via speakers, music (but not white noise) was associated with lower scores on the SDMT (TODO) compared to no audio. Wearing ANC-headphones (but not listening to any audio) was associated with higher SDMT scores (TODO) compared to no headphones. This was also evidenced when listening to white-noise (TODO). The apparent detrimental influence of music was not found to differ depending on whether headphones were worn (TODO). These results are displayed in <a href="#fig-efplot">Figure&nbsp;6</a>.<br>
<span class="math inline">\(\textrm{ }^*\)</span>: denominator degrees of freedom approximated using Kenward-Rogers method.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(sdmt_mod, <span class="at">type=</span><span class="st">"int"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div id="fig-efplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="02_intromlm_files/figure-html/fig-efplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Interaction between the type (no audio/white noise/music) and the delivery (speakers/ANC headphones) on executive functioning task (SDMT)</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="wellbeing-over-time-longitudinal" class="level2">
<h2 class="anchored" data-anchor-id="wellbeing-over-time-longitudinal">Wellbeing Over Time (Longitudinal)</h2>
<p>Another very crucial advantage of these methods is that we can use them to study how people change over time.</p>
<div class="frame">
<p><strong>Wellbeing in Work: Longitudinal Data</strong></p>
<p>The “Wellbeing in Work” dataset contains information on employees who were randomly assigned to one of three employment conditions:</p>
<ul>
<li>control: No change to employment. Employees continue at 5 days a week, with standard allocated annual leave quota.<br>
</li>
<li>unlimited_leave : Employees were given no limit to their annual leave, but were still expected to meet required targets as specified in their job description.</li>
<li>fourday_week: Employees worked a 4 day week for no decrease in pay, and were still expected to meet required targets as specified in their job description.</li>
</ul>
<p>Wellbeing was was assessed at baseline (start of maintenance), 12 months post, 24 months post, and 36 months post.</p>
<p>The researchers had two main questions:</p>
<ul>
<li>Q1): Overall, did the participants’ wellbeing stay the same or did it change?</li>
<li>Q2): Did the employment condition groups differ in the how wellbeing changed over the assessment period?</li>
</ul>
<p>The data is available, in <strong>.rda</strong> format, at <a href="https://uoepsy.github.io/data/wellbeingwork3.rda">https://uoepsy.github.io/data/wellbeingwork3.rda</a>. You can read it directly into your R environment using:</p>
<div class="cell" data-layout-align="center" data-code-copy="true">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://uoepsy.github.io/data/wellbeingwork3.rda"</span>))</span></code></pre></div>
</div>
<p>After running the code above you will find the data in an object called <code>wellbeingwork3</code> in your environment.</p>
</div>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<blockquote class="blockquote">
<p>Q1): Overall, did the participants’ wellbeing stay the same or did it change?</p>
</blockquote>
<p>Each of our participants have measurements at 4 assessments. We need to think about what this means for the <strong>random effects</strong> that we will include in our model (our <strong>random effect structure</strong>). Would we like our models to accommodate individuals to vary in their overall wellbeing, to vary in how they change in wellbeing over the course of the assessment period, or both?</p>
<p>To investigate whether wellbeing changed over the course of the assessments, or whether it stayed the same, we can fit and compare 2 models:</p>
<ol type="1">
<li>The “null” or “intercept-only” model.</li>
<li>A model with wellbeing predicted by time point.</li>
</ol>
<p>And we can then compare them in terms of model fit (as mentioned above, there are lots of different ways we might do this).</p>
<p>Our sample size here (180 participants, each with 4 observations) is reasonably large given the relative simplicity of our model. We might consider running a straightforward Likelihood Ratio Test using <code>anova(restricted_model, full_model)</code> to compare our two models (in which case we should fit them with <code>REML=FALSE</code>)</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Remember, we shouldn’t use likelihood ratio tests to compare models with different random effect structures.<br>
</li>
<li>(For now, don’t worry too much about “singular fits”. We’ll talk more about how we might deal with them next week!)</li>
</ul>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p>This is our null model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>m.null <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> ID), <span class="at">data=</span>wellbeingwork3, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.null)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: Wellbeing ~ 1 + (1 | ID)
   Data: wellbeingwork3

     AIC      BIC   logLik deviance df.resid 
  4400.8   4414.6  -2197.4   4394.8      717 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.5224 -0.6067 -0.0426  0.5918  3.6020 

Random effects:
 Groups   Name        Variance Std.Dev.
 ID       (Intercept)  4.762   2.182   
 Residual             22.479   4.741   
Number of obs: 720, groups:  ID, 180

Fixed effects:
            Estimate Std. Error t value
(Intercept)  40.0431     0.2402   166.7</code></pre>
</div>
</div>
<p>We can see the <code>4.76 / (4.76 + 22.48)</code>, or 0.17 of the total variance is attributable to participant-level variation.</p>
<p>Now lets suppose we want to compare this null model with a model with an effect of <code>TimePoint</code> (to assess whether there is overall change over time). Which model should we compare <code>m.null</code> to?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>modA <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">|</span> ID), <span class="at">data=</span>wellbeingwork3, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>modB <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> ID), <span class="at">data=</span>wellbeingwork3, <span class="at">REML=</span><span class="cn">FALSE</span>)</span></code></pre></div>
</div>
<p>A comparison between these <code>m.null</code> and <code>modA</code> will not be assessing the influence of <em>only</em> the fixed effect of TimePoint (remember, we shouldn’t compare models that differ in both fixed and random effects)<br>
However, <code>modB</code> doesn’t include our by-participant random effects of timepoint, so comparing this to <code>m.null</code> is potentially going to mis-attribute random deviations in participants’ change to being an overall effect of timepoint.</p>
<p>If we want to conduct a model comparison to isolate the effect of overall change over time (a fixed effect of <code>TimePoint</code>), we <em>might</em> want to compare these two models:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>m.base0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">|</span> ID), <span class="at">data=</span>wellbeingwork3, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>m.base <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">|</span> ID), <span class="at">data=</span>wellbeingwork3, <span class="at">REML=</span><span class="cn">FALSE</span>)</span></code></pre></div>
</div>
<p>The first of these models is a bit weird to think about - how can we have by-participant random deviations of <code>TimePoint</code> if we don’t have a fixed effect of <code>TimePoint</code>? That makes very little sense. What it is actually fitting is a model where there is assumed to be <strong>no overall effect</strong> of TimePoint. So the fixed effect is 0.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Straightforward LRT</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m.base0, m.base)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: wellbeingwork3
Models:
m.base0: Wellbeing ~ 1 + (1 + TimePoint | ID)
m.base: Wellbeing ~ 1 + TimePoint + (1 + TimePoint | ID)
        npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
m.base0    5 4202.4 4225.2 -2096.2   4192.4                         
m.base     6 4171.7 4199.2 -2079.8   4159.7 32.649  1  1.104e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<blockquote class="blockquote">
<p>Q: Did the employment condition groups differ in the how wellbeing changed over the assessment period?</p>
</blockquote>
<div class="hints">
<p><strong>Hint:</strong> It helps to break it down. There are two questions here:</p>
<ol type="1">
<li>do groups differ overall?<br>
</li>
<li>do groups differ over time?</li>
</ol>
<p>We can begin to see that we’re asking two questions about the <code>Condition</code> variable here: “is there an effect of Condition?” and “Is there an interaction between TimePoint and Condition?”.</p>
<p>Try fitting two more models which incrementally build these levels of complexity, and compare them (perhaps to one another, perhaps to models from the previous question - think about what each comparison is testing!)</p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>m.int <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">+</span> Condition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">|</span> ID), </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>wellbeingwork3, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>m.full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Wellbeing <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span> TimePoint<span class="sc">*</span>Condition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> TimePoint <span class="sc">|</span> ID), </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">data=</span>wellbeingwork3, <span class="at">REML=</span><span class="cn">FALSE</span>)</span></code></pre></div>
</div>
<p>We’re going to compare each model to the previous one to examine the improvement in fit due to inclusion of each parameter. We could do this quickly with</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m.base0, m.base, m.int, m.full)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: wellbeingwork3
Models:
m.base0: Wellbeing ~ 1 + (1 + TimePoint | ID)
m.base: Wellbeing ~ 1 + TimePoint + (1 + TimePoint | ID)
m.int: Wellbeing ~ 1 + TimePoint + Condition + (1 + TimePoint | ID)
m.full: Wellbeing ~ 1 + TimePoint * Condition + (1 + TimePoint | ID)
        npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
m.base0    5 4202.4 4225.2 -2096.2   4192.4                         
m.base     6 4171.7 4199.2 -2079.8   4159.7 32.649  1  1.104e-08 ***
m.int      8 4164.3 4200.9 -2074.2   4148.3 11.393  2   0.003358 ** 
m.full    10 4144.6 4190.4 -2062.3   4124.6 23.711  2  7.098e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p>Conditions differed overall in wellbeing change <span class="math inline">\(\chi^2(2)=11.39, p = .003\)</span><br>
Conditions differed in change over assessment period <span class="math inline">\(\chi^2(2)=23.71, p &lt; .001\)</span></p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Visualise the model estimated change in wellbeing over time for each Condition.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There are lots of ways you can visualise the model, try a couple:</p>
<ol type="1">
<li>Using the <strong>effects</strong> package, this might help: <code>as.data.frame(effect("TimePoint:Condition", model))</code><br>
</li>
<li>We can also use <strong>sjPlot</strong>, as we have seen in DAPR2</li>
</ol>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-11" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')"> Solution </span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>Using the <code>effect()</code> function (and then adding the means and SEs from the original data):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>ef <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">effect</span>(<span class="st">"TimePoint:Condition"</span>, m.full))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ef, <span class="fu">aes</span>(TimePoint, fit, <span class="at">color=</span>Condition)) <span class="sc">+</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper,<span class="at">fill=</span>Condition), <span class="at">alpha=</span>.<span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">data=</span>wellbeingwork3, <span class="fu">aes</span>(<span class="at">y=</span>Wellbeing), </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">fun.data=</span>mean_se, <span class="at">geom=</span><span class="st">"pointrange"</span>, <span class="at">size=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02_intromlm_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Additionally, <strong>sjPlot</strong> can give us the model fitted values, but it’s trickier to add on the observed means. We can add the raw data using <code>show.data=TRUE</code>, but that will make it a bit messier</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m.full, <span class="at">type=</span><span class="st">"int"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02_intromlm_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>Examine the parameter estimates and interpret them (i.e., what does each parameter represent?<br>
Can you match them with parts of the plot obtained from <code>plot_model(m.full, type="int")</code>?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can get the fixed effects using <code>fixef(model)</code>, and we can also use <code>tidy(model)</code> from the <strong>broom.mixed</strong> package, and similar to <code>lm</code> models in DAPR2, we can pull out the bit of the <code>summary()</code> using <code>summary(model)$coefficients</code>.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa-solid fa-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>                                   Estimate Std. Error t value
(Intercept)                          38.352      0.394  97.270
TimePoint                            -0.023      0.322  -0.072
Conditionunlimited_leave             -0.018      0.558  -0.033
Conditionfourday_week                -0.260      0.558  -0.466
TimePoint:Conditionunlimited_leave    1.357      0.456   2.976
TimePoint:Conditionfourday_week       2.282      0.456   5.005</code></pre>
</div>
</div>
<ul>
<li><code>(Intercept)</code> ==&gt; Wellbeing at baseline in ‘control’ group.<br>
</li>
<li><code>TimePoint</code> ==&gt; Slope of welleing change in ‘control’ group.<br>
</li>
<li><code>Conditionunlimited_leave</code> ==&gt; baseline wellbeing difference from ‘unlimited_leave’ group relative to ‘control’ group.<br>
</li>
<li><code>Conditionfourday_week</code> ==&gt; baseline wellbeing difference from ‘fourday_week’ group relative to ‘control’ group.<br>
</li>
<li><code>TimePoint:Conditionunlimited_leave</code> ==&gt; slope of wellbeing change in ‘unlimited_leave’ group relative to ‘control’ group.<br>
</li>
<li><code>TimePoint:Conditionfourday_week</code> ==&gt; slope of wellbeing change in ‘fourday_week’ group relative to ‘control’ group.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m.full, <span class="at">type=</span><span class="st">"int"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div id="fig-wblplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="02_intromlm_files/figure-html/fig-wblplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Well-being over time, for employees working in different conditions</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><code>(Intercept)</code> ==&gt; the height of the red line at timepoint 0.<br>
</li>
<li><code>TimePoint</code> ==&gt; slope of the red line (basically flat).<br>
</li>
<li><code>Conditionunlimited_leave</code> ==&gt; the difference at timepoint 0 in height of the blue line from height of the red line (basically 0, but blue line starts ever so slightly below the red).<br>
</li>
<li><code>Conditionfourday_week</code> ==&gt; the difference at timepoint 0 in height of the green line from height of the red line (also very small, but it is a bit further below the red than the blue is).<br>
</li>
<li><code>TimePoint:Conditionunlimited_leave</code> ==&gt; the difference from slope of red line to slope of blue line. i.e.&nbsp;while the red line goes -0.023 for every 1 across, the blue line goes <span class="math inline">\(-0.023+1.357=1.334\)</span> up for every 1 across.<br>
</li>
<li><code>TimePoint:Conditionfourday_week</code> ==&gt; difference from slope of red line to slope of green line. i.e.&nbsp;while the red line goes -0.023 for every 1 across, the green line goes <span class="math inline">\(-0.023+2.282=2.259\)</span> up for every 1 across.</li>
</ul>
<div class="int">
<p>Compared to the control group, wellbeing increased by 1.36 points/year more for employees with unlimited leave, and by 2.28 points/year for employees on the 4 day week.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>