<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - 3. Assumptions and Diagnostics | Centering</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('jk-circle-right')) {
    f.classList.add('jk-circle-down')
    f.classList.remove('jk-circle-right')
} else {
    f.classList.add('jk-circle-right')
    f.classList.remove('jk-circle-down')
}
}
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_regressionrefresh.html">Multilevel Models</a></li><li class="breadcrumb-item"><a href="./03_assumptcent.html">3. Assumptions and Diagnostics | Centering</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DAPR3</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Multilevel Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_regressionrefresh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Regression Refresh | Clustered Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_intromlm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Intro to Multilevel Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_assumptcent.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">3. Assumptions and Diagnostics | Centering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_ranefglmer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Random Effect Structures | Logistic MLM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Recap &amp; Practice Datasets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b_lmmdatasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LMM Datasets</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Additional Docs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example_00_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis Example: Rpt &amp; Mixed ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lvp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Likelihood vs Probability</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">- Break Week -</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Path Analysis and Data Reduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_path1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Path Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_path2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Mediation</span></a>
  </div>
</li>
          <li class="sidebar-item">
 <span class="menu-text">9. PCA</span>
  </li>
          <li class="sidebar-item">
 <span class="menu-text">10. EFA I</span>
  </li>
          <li class="sidebar-item">
 <span class="menu-text">11. EFA II</span>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Additional Docs</span></span>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercises-assumptions-diagnostics" id="toc-exercises-assumptions-diagnostics" class="nav-link active" data-scroll-target="#exercises-assumptions-diagnostics">Exercises: Assumptions &amp; Diagnostics</a></li>
  <li><a href="#exercises-centering-in-the-mlm" id="toc-exercises-centering-in-the-mlm" class="nav-link" data-scroll-target="#exercises-centering-in-the-mlm">Exercises: Centering in the MLM</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">3. Assumptions and Diagnostics | Centering</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="exercises-assumptions-diagnostics" class="level1">
<h1>Exercises: Assumptions &amp; Diagnostics</h1>
<div class="frame">
<p><strong>Data: Wellbeing Across Scotland</strong></p>
<p>For these next set of exercises we continue with our recurring study in which researchers want to look at the relationship between time spent outdoors and mental wellbeing, across all of Scotland. Data is collected from 20 of the Local Authority Areas and is accessible at <a href="https://uoepsy.github.io/data/LAAwellbeing.csv">https://uoepsy.github.io/data/LAAwellbeing.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="dmrtuvnelx" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#dmrtuvnelx table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#dmrtuvnelx thead, #dmrtuvnelx tbody, #dmrtuvnelx tfoot, #dmrtuvnelx tr, #dmrtuvnelx td, #dmrtuvnelx th {
  border-style: none;
}

#dmrtuvnelx p {
  margin: 0;
  padding: 0;
}

#dmrtuvnelx .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#dmrtuvnelx .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#dmrtuvnelx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#dmrtuvnelx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#dmrtuvnelx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#dmrtuvnelx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#dmrtuvnelx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#dmrtuvnelx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#dmrtuvnelx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#dmrtuvnelx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#dmrtuvnelx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#dmrtuvnelx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#dmrtuvnelx .gt_spanner_row {
  border-bottom-style: hidden;
}

#dmrtuvnelx .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#dmrtuvnelx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#dmrtuvnelx .gt_from_md > :first-child {
  margin-top: 0;
}

#dmrtuvnelx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#dmrtuvnelx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#dmrtuvnelx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#dmrtuvnelx .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#dmrtuvnelx .gt_row_group_first td {
  border-top-width: 2px;
}

#dmrtuvnelx .gt_row_group_first th {
  border-top-width: 2px;
}

#dmrtuvnelx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#dmrtuvnelx .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#dmrtuvnelx .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#dmrtuvnelx .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#dmrtuvnelx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#dmrtuvnelx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#dmrtuvnelx .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#dmrtuvnelx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#dmrtuvnelx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#dmrtuvnelx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#dmrtuvnelx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#dmrtuvnelx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#dmrtuvnelx .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#dmrtuvnelx .gt_left {
  text-align: left;
}

#dmrtuvnelx .gt_center {
  text-align: center;
}

#dmrtuvnelx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#dmrtuvnelx .gt_font_normal {
  font-weight: normal;
}

#dmrtuvnelx .gt_font_bold {
  font-weight: bold;
}

#dmrtuvnelx .gt_font_italic {
  font-style: italic;
}

#dmrtuvnelx .gt_super {
  font-size: 65%;
}

#dmrtuvnelx .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#dmrtuvnelx .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#dmrtuvnelx .gt_indent_1 {
  text-indent: 5px;
}

#dmrtuvnelx .gt_indent_2 {
  text-indent: 10px;
}

#dmrtuvnelx .gt_indent_3 {
  text-indent: 15px;
}

#dmrtuvnelx .gt_indent_4 {
  text-indent: 20px;
}

#dmrtuvnelx .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="variable">variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="description">description</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="variable" class="gt_row gt_left">ppt</td>
<td headers="description" class="gt_row gt_left">Participant ID</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">name</td>
<td headers="description" class="gt_row gt_left">Participant Name</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">laa</td>
<td headers="description" class="gt_row gt_left">Local Authority Area</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">outdoor_time</td>
<td headers="description" class="gt_row gt_left">Self report estimated number of hours per week spent outdoors</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">wellbeing</td>
<td headers="description" class="gt_row gt_left">Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">density</td>
<td headers="description" class="gt_row gt_left">LAA Population Density (people per square km)</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>The code below will read in the data and fit the model with by-LAA random intercepts and slopes of outdoor time.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>scotmw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/LAAwellbeing.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>rs_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">|</span> laa), <span class="at">data =</span> scotmw)</span></code></pre></div>
</div>
<ol type="1">
<li>Plot the residuals vs fitted values, and assess the extend to which the assumption holds that the residuals are zero mean.</li>
<li>Construct a scale-location plot. This is where the square-root of the absolute value of the standardised residuals is plotted against the fitted values, and allows you to more easily assess the assumption of constant variance.</li>
</ol>
<ul>
<li>Optional: can you create the same plot using ggplot, starting with the <code>augment()</code> function from the <strong>broom.mixed</strong> package?</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>plot(model)</code> will give you this plot, but you might want to play with the <code>type = c(......)</code> argument to get the smoothing line</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-1" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')">
Solution
</button>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rs_model, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>As we can see, the mean value of the residuals is quite close to zero, right the way across the fitted values. This is good.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>To change labels for the x and y axes, add the following arguments to the plot() function:</p>
<ul>
<li><code>xlab = "Fitted values"</code></li>
<li><code>ylab = "Residuals"</code></li>
</ul>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rs_model,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">form =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.))) <span class="sc">~</span> <span class="fu">fitted</span>(.),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>In this plot we can see that the variance of the residuals is fairly constant across the fitted values. There is a slight dip at the lower end. We can see this in the previous plot too - all the points at the LHS of the plot are slightly more tightly grouped around the line. This is not enough to worry me, personally.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(rs_model) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sqrtr =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(.resid))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>.fitted, <span class="at">y=</span>sqrtr)) <span class="sc">+</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>To remove the confidence bands (in grey) from the smoothed line, you can change the last command to:</p>
<p><code>geom_smooth(se = FALSE)</code></p>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Examine the normality of both the level 1 and level 2 residuals.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Use <code>hist()</code> if you like, or <code>qqnorm(residuals)</code> followed by <code>qqline(residuals)</code></li>
<li>Extracting the level 2 residuals (the random effects) can be difficult. <code>ranef(model)</code> will get you some of the way.</li>
</ul>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-2" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')">
Solution
</button>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p><strong>Level 1</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(rs_model))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(rs_model))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(rs_model))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Indexing random effects</strong></p>
<p>The output of <code>ranef()</code> is a type of data container called “list”. The list includes different named slots and you can find the names as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">ranef</span>(rs_model))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "laa"</code></pre>
</div>
</div>
<p>You have a named slot for each group in your lmer specification. In this case, we only specified <code>laa</code> as grouping. To access the random effects for the specific group, type <code>ranef(model)</code> followed by <code>$groupname</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      (Intercept) outdoor_time
Angus                  -4.8568066  0.095850303
Argyll and Bute         1.6488121 -0.005181049
City of Edinburgh      10.8163125  0.199034174
Dumfries and Galloway  -2.6893688 -0.012005965
East Ayrshire          -5.6749200 -0.232750990
East Renfrewshire       0.5024800  0.084907037
Falkirk                -7.4525578 -0.156694328
Glasgow City          -10.9101439 -0.464232183
Highland                6.7315989  0.280992008
Inverclyde             -1.2966048  0.197142062
Midlothian             -1.7585791 -0.485961786
Moray                  -2.2165380  0.133392034
Na h-Eileanan Siar     14.0595006  0.399493656
Orkney Islands          0.1789928  0.154590585
Perth and Kinross       1.4894924  0.256689754
Scottish Borders       -0.2638474 -0.148174460
Shetland Islands        4.7262680  0.388873631
Stirling                6.5060959 -0.075781592
West Dunbartonshire    -6.4127140 -0.266515096
West Lothian           -3.1274727 -0.343667797</code></pre>
</div>
</div>
<p>You will have multiple columns, one for each random effect.</p>
<p>You can get the random intercepts by laa, by selecting the first column as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">1</span>]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  -4.8568066   1.6488121  10.8163125  -2.6893688  -5.6749200   0.5024800
 [7]  -7.4525578 -10.9101439   6.7315989  -1.2966048  -1.7585791  -2.2165380
[13]  14.0595006   0.1789928   1.4894924  -0.2638474   4.7262680   6.5060959
[19]  -6.4127140  -3.1274727</code></pre>
</div>
</div>
<p>Respectively, for the random slopes by laa, you select the second column as follows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">2</span>]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  0.095850303 -0.005181049  0.199034174 -0.012005965 -0.232750990
 [6]  0.084907037 -0.156694328 -0.464232183  0.280992008  0.197142062
[11] -0.485961786  0.133392034  0.399493656  0.154590585  0.256689754
[16] -0.148174460  0.388873631 -0.075781592 -0.266515096 -0.343667797</code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Level 2</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">1</span>], <span class="at">main =</span> <span class="st">"Random intercept"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">1</span>])</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">2</span>], <span class="at">main =</span> <span class="st">"Random slope"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">2</span>])</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The normality of the residuals at both levels looks pretty decent here. This is especially good given that we only actually have 20 clusters (the LAAs). We have quite a small sample at this level.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<ol type="1">
<li>Which person in the dataset has the greatest influence on our model?<br>
</li>
<li>For which person is the model fit the worst (i.e., who has the highest residual?)</li>
<li>Which <em>LAA</em> has the greatest influence on our model?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>as well as <code>hlm_influence()</code> in the <strong>HLMdiag</strong> package there is another nice function, <code>hlm_augment()</code></li>
<li>we can often end up in confusion because the <span class="math inline">\(i^{th}\)</span> observation inputted to our model (and therefore the <span class="math inline">\(i^{th}\)</span> observation of <code>hlm_influence()</code> output) <strong>might not be</strong> the <span class="math inline">\(i^{th}\)</span> observation in our original dataset - there may be missing data! (Luckily, we have no missing data in this dataset).</li>
</ul>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-3" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')">
Solution
</button>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HLMdiag)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>l1_inf <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(rs_model,<span class="at">level=</span><span class="dv">1</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(l1_inf<span class="sc">$</span>cooksd, <span class="at">cutoff=</span><span class="st">"internal"</span>)<span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,.<span class="dv">15</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Greatest influence:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(cooksd))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 132 × 15
      id wellbeing outdoor_time laa          .resid .fitted .ls.resid .ls.fitted
   &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt; &lt;fct&gt;         &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1    74        35           33 Scottish Bo…  -5.15    40.2    -3.73        38.7
 2   129        60            5 City of Edi…   8.89    51.1     6.43        53.6
 3   109        31            8 Inverclyde    -9.22    40.2    -3.03        34.0
 4    59        32            7 Scottish Bo…  -6.43    38.4    -7.45        39.5
 5    31        35            7 Moray         -3.44    38.4     0.198       34.8
 6    90        70           34 Na h-Eilean…  -3.16    73.2    -1.19        71.2
 7    87        54           29 Highland      -5.33    59.3    -5.66        59.7
 8    62        26           21 Midlothian    -4.77    30.8     0.214       25.8
 9    67        37            7 East Ayrshi…   4.58    32.4     4.62        32.4
10    64        46           18 City of Edi… -10.5     56.5   -10.1         56.1
# ℹ 122 more rows
# ℹ 7 more variables: .mar.resid &lt;dbl&gt;, .mar.fitted &lt;dbl&gt;, cooksd &lt;dbl&gt;,
#   mdffits &lt;dbl&gt;, covtrace &lt;dbl&gt;, covratio &lt;dbl&gt;, leverage.overall &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>scotmw[<span class="dv">74</span>, ]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  ppt   name                 laa              outdoor_time wellbeing density
  &lt;chr&gt; &lt;chr&gt;                &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 ID46  Groundskeeper Willie Scottish Borders           33        35      29</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/intro/willie.jpg" class="img-fluid figure-img" width="100"></p>
</figure>
</div>
</div>
</div>
<p>Highest residual:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(.resid)))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 132 × 15
      id wellbeing outdoor_time laa          .resid .fitted .ls.resid .ls.fitted
   &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt; &lt;fct&gt;         &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1    64        46           18 City of Edi… -10.5     56.5    -10.1        56.1
 2   107        22           12 East Ayrshi… -10.3     32.3    -10.1        32.1
 3    72        22           24 West Lothian -10.0     32.0     -9.24       31.2
 4   109        31            8 Inverclyde    -9.22    40.2     -3.03       34.0
 5   130        22           16 West Dunbar…  -8.98    31.0     -8.61       30.6
 6   129        60            5 City of Edi…   8.89    51.1      6.43       53.6
 7    93        65           18 City of Edi…   8.51    56.5      8.90       56.1
 8    85        47           15 City of Edi…  -8.25    55.2     -8.52       55.5
 9     7        38           13 Perth and K…  -7.84    45.8     -5.28       43.3
10   121        31           16 Dumfries an…  -7.78    38.8     -7.70       38.7
# ℹ 122 more rows
# ℹ 7 more variables: .mar.resid &lt;dbl&gt;, .mar.fitted &lt;dbl&gt;, cooksd &lt;dbl&gt;,
#   mdffits &lt;dbl&gt;, covtrace &lt;dbl&gt;, covratio &lt;dbl&gt;, leverage.overall &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>scotmw[<span class="dv">64</span>, ]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  ppt   name            laa               outdoor_time wellbeing density
  &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 ID37  Nicola Sturgeon City of Edinburgh           18        46    1958</code></pre>
</div>
</div>
<p>Most influential LAA:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="st">"laa"</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(cooksd))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 10
   laa       .ranef.intercept .ranef.outdoor_time .ls.intercept .ls.outdoor_time
   &lt;chr&gt;                &lt;dbl&gt;               &lt;dbl&gt;         &lt;dbl&gt;            &lt;dbl&gt;
 1 Midlothi…           -1.76             -0.486           8.75           -1.26  
 2 Na h-Eil…           14.1               0.399          21.4             0.0553
 3 Glasgow …          -10.9              -0.464          -9.45           -0.593 
 4 City of …           10.8               0.199          16.2            -0.144 
 5 Stirling             6.51             -0.0758         13.3            -0.500 
 6 Shetland…            4.73              0.389           3.69            0.424 
 7 Angus               -4.86              0.0959         -6.82            0.265 
 8 West Lot…           -3.13             -0.344           4.13           -0.725 
 9 Falkirk             -7.45             -0.157         -12.3            -0.0360
10 Invercly…           -1.30              0.197         -14.5             1.17  
11 Highland             6.73              0.281           8.95            0.155 
12 West Dun…           -6.41             -0.267          -4.87           -0.395 
13 Moray               -2.22              0.133          -5.81            0.267 
14 Perth an…            1.49              0.257         -20.4             1.76  
15 East Ayr…           -5.67             -0.233          -3.63           -0.391 
16 Orkney I…            0.179             0.155          -0.816           0.212 
17 Scottish…           -0.264            -0.148           3.28           -0.367 
18 Dumfries…           -2.69             -0.0120         -7.27            0.261 
19 Argyll a…            1.65             -0.00518         4.67           -0.187 
20 East Ren…            0.502             0.0849          1.40            0.0247
# ℹ 5 more variables: cooksd &lt;dbl&gt;, mdffits &lt;dbl&gt;, covtrace &lt;dbl&gt;,
#   covratio &lt;dbl&gt;, leverage.overall &lt;dbl&gt;</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<ol type="1">
<li>Looking at the random effects, which LAA shows the least benefit to wellbeing as outdoor time increases, and which shows the greatest benefit?<br>
</li>
<li>What is the estimated wellbeing for people from City of Edinburgh with zero hours of outdoor time per week, and what is their associated increases in wellbeing for every hour per week increase in outdoor time?</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-4" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')">
Solution
</button>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>It looks like the residents of Midlothian have the least improvement, and the Western Isles (Na h-Eileanan Siar) show the most increases of wellbeing with outdoor time. We can see this from the LAA-random slopes of outdoor time:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(rs_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$laa
                      (Intercept) outdoor_time
Angus                  -4.8568066  0.095850303
Argyll and Bute         1.6488121 -0.005181049
City of Edinburgh      10.8163125  0.199034174
Dumfries and Galloway  -2.6893688 -0.012005965
East Ayrshire          -5.6749200 -0.232750990
East Renfrewshire       0.5024800  0.084907037
Falkirk                -7.4525578 -0.156694328
Glasgow City          -10.9101439 -0.464232183
Highland                6.7315989  0.280992008
Inverclyde             -1.2966048  0.197142062
Midlothian             -1.7585791 -0.485961786
Moray                  -2.2165380  0.133392034
Na h-Eileanan Siar     14.0595006  0.399493656
Orkney Islands          0.1789928  0.154590585
Perth and Kinross       1.4894924  0.256689754
Scottish Borders       -0.2638474 -0.148174460
Shetland Islands        4.7262680  0.388873631
Stirling                6.5060959 -0.075781592
West Dunbartonshire    -6.4127140 -0.266515096
West Lothian           -3.1274727 -0.343667797

with conditional variances for "laa" </code></pre>
</div>
</div>
<p>We can get the cluster-specific coefficients either by adding the <code>fixef()</code> and <code>ranef()</code> together, or using <code>coef()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(rs_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$laa
                      (Intercept) outdoor_time
Angus                    33.36700   0.31050188
Argyll and Bute          39.87261   0.20947052
City of Edinburgh        49.04011   0.41368575
Dumfries and Galloway    35.53443   0.20264561
East Ayrshire            32.54888  -0.01809942
East Renfrewshire        38.72628   0.29955861
Falkirk                  30.77124   0.05795725
Glasgow City             27.31366  -0.24958061
Highland                 44.95540   0.49564358
Inverclyde               36.92720   0.41179364
Midlothian               36.46522  -0.27131021
Moray                    36.00726   0.34804361
Na h-Eileanan Siar       52.28330   0.61414523
Orkney Islands           38.40280   0.36924216
Perth and Kinross        39.71329   0.47134133
Scottish Borders         37.95995   0.06647711
Shetland Islands         42.95007   0.60352520
Stirling                 44.72990   0.13886998
West Dunbartonshire      31.81109  -0.05186352
West Lothian             35.09633  -0.12901622

attr(,"class")
[1] "coef.mer"</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(rs_model)<span class="sc">$</span>laa[<span class="st">"City of Edinburgh"</span>,]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept) outdoor_time
City of Edinburgh    49.04011    0.4136857</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<br>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="exercises-centering-in-the-mlm" class="level1">
<h1>Exercises: Centering in the MLM</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Centering &amp; Scaling in LM
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We have some data from a study investigating how perceived persuasiveness of a speaker is influenced by the rate at which they speak.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>dap2 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/dapr2_2122_report1.csv"</span>)</span></code></pre></div>
</div>
<p>We can fit a simple linear regression (one predictor) to evaluate how speech rate (variable <code>sp_rate</code> in the dataset) influences perceived persuasiveness (variable <code>persuasive</code> in the dataset). There are various ways in which we can transform the predictor variable <code>sp_rate</code>, which in turn can alter the interpretation of some of our estimates:</p>
<div class="panelset">
<section id="raw-x" class="level4 panel">
<h4 class="anchored" data-anchor-id="raw-x">Raw X</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(persuasive <span class="sc">~</span> sp_rate, <span class="at">data =</span> dap2)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)<span class="sc">$</span>coefficients</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 55.532060  6.4016670  8.674625 6.848945e-15
sp_rate     -0.190987  0.4497113 -0.424688 6.716809e-01</code></pre>
</div>
</div>
<p>The intercept and the coefficient for speech rate are interpreted as:</p>
<ul>
<li><code>(Intercept)</code>: A audio clip of someone speaking at zero phones per second is estimated as having an average persuasive rating of 55.53.<br>
</li>
<li><code>sp_rate</code>: For every increase of one phone per second, perceived persuasiveness is estimated to decrease by -0.19.</li>
</ul>
</section>
<section id="mean-centered-x" class="level4 panel">
<h4 class="anchored" data-anchor-id="mean-centered-x">Mean-Centered X</h4>
<p>We can mean center our predictor and fit the model again:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>dap2 <span class="ot">&lt;-</span> dap2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">sp_rate_mc =</span> sp_rate <span class="sc">-</span> <span class="fu">mean</span>(sp_rate))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(persuasive <span class="sc">~</span> sp_rate_mc, <span class="at">data =</span> dap2)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)<span class="sc">$</span>coefficients</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 52.874667  1.3519418 39.110165 6.429541e-80
sp_rate_mc  -0.190987  0.4497113 -0.424688 6.716809e-01</code></pre>
</div>
</div>
<ul>
<li><code>(Intercept)</code>: A audio clip of someone speaking at the <strong>mean</strong> phones per second is estimated as having an average persuasive rating of 52.87.<br>
</li>
<li><code>sp_rate_mc</code>: For every increase of one phone per second, perceived persuasiveness is estimated to decrease by -0.19.</li>
</ul>
</section>
<section id="standardised-x" class="level4 panel">
<h4 class="anchored" data-anchor-id="standardised-x">Standardised X</h4>
<p>We can <em>standardise</em> our predictor and fit the model yet again:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dap2 <span class="ot">&lt;-</span> dap2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">sp_rate_z =</span> <span class="fu">scale</span>(sp_rate))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(persuasive <span class="sc">~</span> sp_rate_z, <span class="at">data =</span> dap2)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)<span class="sc">$</span>coefficients</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 52.874667   1.351942 39.110165 6.429541e-80
sp_rate_z   -0.576077   1.356471 -0.424688 6.716809e-01</code></pre>
</div>
</div>
<ul>
<li><code>(Intercept)</code>: A audio clip of someone speaking at the <strong>mean</strong> phones per second is estimated as having an average persuasive rating of 52.87.<br>
</li>
<li><code>sp_rate_z</code>: For every increase of one <strong>standard deviation</strong> in phones per second, perceived persuasiveness is estimated to decrease by -0.58.</li>
</ul>
<p>Remember that the <code>scale(sp_rate)</code> is subtracting the mean from each value, then dividing those by the standard deviation. The standard deviation of <code>dap2$sp_rate</code> is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(dap2<span class="sc">$</span>sp_rate)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.016315</code></pre>
</div>
</div>
<p>so in our variable <code>dap2$sp_rate_z</code>, a change of 3.02 gets scaled to be a change of 1 (because we are dividing by <code>sd(dap2$sp_rate)</code>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">sd</span>(dap2<span class="sc">$</span>sp_rate)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sp_rate 
-0.576077 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m3)[<span class="dv">2</span>]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sp_rate_z 
-0.576077 </code></pre>
</div>
</div>
</section>
</div>
<p>Note that these models are identical. When we conduct a model comparison between the 3 models, the residual sums of squares is identical for all models:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1,m2,m3)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: persuasive ~ sp_rate
Model 2: persuasive ~ sp_rate_mc
Model 3: persuasive ~ sp_rate_z
  Res.Df   RSS Df Sum of Sq F Pr(&gt;F)
1    148 40576                      
2    148 40576  0         0         
3    148 40576  0         0         </code></pre>
</div>
</div>
<p>What changes when you center or scale a predictor in a standard regression model (one fitted with <code>lm()</code>)?</p>
<ul>
<li>The variance explained by the predictor remains exactly the same</li>
<li>The intercept will change to be the estimated mean outcome where that predictor is “0”. Scaling and centering changes what “0” represents, thereby changing this estimate (the significance test will therefore also change because the intercept now has a different meaning)</li>
<li>The slope of the predictor will change according to any scaling (e.g.&nbsp;if you divide your predictor by 10, the slope will multiply by 10).</li>
<li>The <strong>test</strong> of the slope of the predictor remains exactly the same.</li>
</ul>
</div>
</div>
</div>
<div class="frame">
<p><strong>Data: Hangry</strong></p>
<p>The study is interested in evaluating whether hunger influences peoples’ levels of irritability (i.e., “the hangry hypothesis”), and whether this is different for people following a diet that includes fasting. 81 participants were recruited into the study. Once a week for 5 consecutive weeks, participants were asked to complete two questionnaires, one assessing their level of hunger, and one assessing their level of irritability. The time and day at which participants were assessed was at a randomly chosen hour between 7am and 7pm each week. 46 of the participants were following a five-two diet (five days of normal eating, 2 days of fasting), and the remaining 35 were following no specific diet.</p>
<p>The data are available at: <a href="https://uoepsy.github.io/data/hangry.csv">https://uoepsy.github.io/data/hangry.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">q_irritability</td>
<td style="text-align: left;">Score on irritability questionnaire (0:100)</td>
</tr>
<tr class="even">
<td style="text-align: left;">q_hunger</td>
<td style="text-align: left;">Score on hunger questionnaire (0:100)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ppt</td>
<td style="text-align: left;">Participant</td>
</tr>
<tr class="even">
<td style="text-align: left;">fivetwo</td>
<td style="text-align: left;">Whether the participant follows the five-two diet</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Read carefully the description of the study above, and try to write out (in <code>lmer</code> syntax) an appropriate model to test the research aims.<br>
e.g.:</p>
<pre><code>outcome ~ explanatory variables + (???? | grouping)</code></pre>
<p>Try to think about the maximal random effect structure (i.e.&nbsp;everything that can vary by-grouping is estimated as doing so).</p>
<p>To help you think through the steps to get from a description of a research study to a model specification, think about your answers to the following questions.</p>
<p>Q: What is our outcome variable?<br>
Q: What are our explanatory variables?<br>
Q: Is there any grouping (or “clustering”) of our data that we consider to be a random sample? If so, what are the groups?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>The research is looking at how hunger influences irritability, and whether this is different for people on the fivetwo diet.</li>
<li>We can split our data in to groups of each participant. We can also split it into groups of each diet. Which of these groups have we randomly sampled? Do we have a random sample of participants? Do we have a random sample of diets? Another way to think of this is “if i repeated the experiment, what these groups be different?”</li>
</ul>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-5" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')">
Solution
</button>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>Our outcome is irritability here, because it is the thing that we are trying to explain through peoples’ hunger levels and diets.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(irritability <span class="sc">~</span>  explanatory variables <span class="sc">+</span> (???? <span class="sc">|</span> grouping))</span></code></pre></div>
</div>
<p>We are interested in the effect of hunger on irritability, and whether this effect is different for the five-two diet. So we are interested in the interaction:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(irritability <span class="sc">~</span>  hunger <span class="sc">+</span> diet <span class="sc">+</span> hunger<span class="sc">:</span>diet <span class="sc">+</span> (???? <span class="sc">|</span> grouping))</span></code></pre></div>
</div>
<p>(remember that <code>hunger + diet + hunger:diet</code> is just a more explicit way of writing <code>hunger*diet</code>).</p>
<p>If we did this experiment again, would we have different participants?<br>
Yes. If we did this experiment again, would we have different diets? No, because we’re interested in the specific differences between the five-two diet and no dieting. This means we will likely want to by-participant random deviations (e.g.&nbsp;the <code>( ... | participant)</code> bit in <code>lmer</code>). But we won’t have by-diet random effects <code>(1 | diet)</code> because the diet differences are the specific differences that we wish to test.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(irritability <span class="sc">~</span>  hunger <span class="sc">+</span> diet <span class="sc">+</span> hunger<span class="sc">:</span>diet <span class="sc">+</span> (???? <span class="sc">|</span> participant))</span></code></pre></div>
</div>
<p>Thinking about what <strong>can</strong> be modelled as randomly varying between participants, we have some options:</p>
<ol type="1">
<li>participants vary in how irritable they are on average<br>
(the intercept, <code>1 | participant</code>)</li>
<li>participants vary in how much hunger influences their irritability<br>
(the effect of hunger, <code>hunger | participant</code>)</li>
<li>participants vary in how much diet influences irritability<br>
(the effect of diet, <code>diet | participant</code>)</li>
<li>participants vary in how much diet effects hunger’s influence on irritability<br>
(the interaction between diet and hunger, <code>diet:hunger | participant</code>)</li>
</ol>
<p>We can vary 1 and 2, but not 3 and 4. This is because each participant is <em>either</em> following the five-two diet <em>or</em> they are not. So for a <em>single</em> participant, we can’t assess “the effect diet has” on anything, because we haven’t seen that participant under different diets. if we try to plot a single participants’ data, we can see that it is impossible for us to assess “the effect of diet”:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>By contrast, we <strong>can</strong> vary the intercept and the effect of hunger, because each participant has multiple values of irritability, and multiple different observations of hunger. We can think about a single participant’s “effect of hunger on irritability” and how we might fit a line to their data:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(irritability <span class="sc">~</span>  hunger <span class="sc">+</span> diet <span class="sc">+</span> hunger<span class="sc">:</span>diet <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hunger <span class="sc">|</span> participant))</span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Total, Within, Between
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Recall our research aim:</p>
<blockquote class="blockquote">
<p><strong>… whether hunger influences peoples’ levels of irritability (i.e., “the hangry hypothesis”)</strong>, and whether this is different for people following a diet that includes fasting.</p>
</blockquote>
<p>Forgetting about any differences due to diet, let’s just think about the relationship between irritability and hunger. How should we interpret this research aim?<br>
Was it:</p>
<ol type="a">
<li>“Are people more irritable if they are, <strong>on average</strong>, more hungry <strong>than other people</strong>?”<br>
</li>
<li>“Are people more irritable if they are, <strong>for them</strong>, more hungry <strong>than they usually are</strong>?”<br>
</li>
<li>Some combination of both a. and b.</li>
</ol>
<p>This is just one demonstration of how the statistical methods we use can constitute an integral part of our development of a research project, and part of the reason that data analysis for scientific cannot be so easily outsourced after designing the study and collecting the data.</p>
<p>As our data currently is currently stored, the relationship between <code>irritability</code> and the raw scores on the hunger questionnaire <code>q_hunger</code> represents some ‘total effect’ of hunger on irritability. This is a bit like interpretation <strong>c.</strong> above - it’s a composite of both the ‘within’ ( <strong>b.</strong> ) and ‘between’ ( <strong>a.</strong> ) effects. The problem with this is that the ‘total effect’ isn’t necessarily all that meaningful. It may tell us that ‘being higher on the hunger questionnaire is associated with being more irritable’, but how can we apply this information? It is not specifically about the comparison between hungry people and less hungry people, and nor is it about how person i changes when they are more hungry than usual. It is both these things smushed together.</p>
<p>To disaggregate the ‘within’ and ‘between’ effects of hunger on irritability, we can group-mean center. For ‘between’, we are interested in how irritability is related to the average hunger levels of a participant, and for ‘within’, we are asking how irritability is related to a participants’ <em>relative levels</em> of hunger (i.e., how far above/below their average hunger level they are.).</p>
</div>
</div>
</div>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Add to the data these two columns:</p>
<ol type="1">
<li>a column which contains the average hungriness score for each participant.</li>
<li>a column which contains the deviation from each person’s hunger score to that person’s average hunger score.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You’ll find <code>group_by() %&gt;% mutate()</code> very useful here.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-6" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')">
Solution
</button>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>hangry <span class="ot">&lt;-</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    hangry <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(ppt) <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_hunger =</span> <span class="fu">mean</span>(q_hunger),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">hunger_gc =</span> q_hunger <span class="sc">-</span> avg_hunger</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hangry)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
# Groups:   ppt [2]
  q_irritability q_hunger ppt   fivetwo avg_hunger hunger_gc
           &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt;        &lt;dbl&gt;     &lt;dbl&gt;
1             17       30 N1p1  1             26.6     3.4  
2             19       27 N1p1  1             26.6     0.400
3             19       29 N1p1  1             26.6     2.4  
4             20       33 N1p1  1             26.6     6.4  
5             24       14 N1p1  1             26.6   -12.6  
6             30       28 N1p2  1             32.6    -4.6  </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>For each of the new variables you just added, plot the irritability scores against those variables.</p>
<ul>
<li>Does it look like hungry people are more irritable than less hungry people?<br>
</li>
<li>Does it look like when people are more hungry than normal, they are more irritable?</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-7" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')">
Solution
</button>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>We might find it easier to look at a plot where each participant is represented as their mean plus an indication of their range of irritability scores:</p>
<div class="cell" data-layout-align="center" data-fig.asp="0.5">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hangry,<span class="fu">aes</span>(<span class="at">x=</span>avg_hunger,<span class="at">y=</span>q_irritability))<span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>There appears to be a slight positive relationship between a persons’ average hunger and their irritability scores.</p>
<p>It is harder to tell what the relationship is between participant-centered hunger and irritability, because there are a lot of different lines (one for each participant). To make it easier to get an idea of what’s happening, we’ll make the plot fit a simple lm() (a straight line) for each participants’ data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hangry,<span class="fu">aes</span>(<span class="at">x=</span>hunger_gc,<span class="at">y=</span>q_irritability, <span class="at">color=</span>ppt)) <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">lwd=</span>.<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'none'</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>I think there might be a positive trend in here, in that participants tend to be higher irritability when they are higher (for them) on the hunger score.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>We have taken the raw hunger scores and separated them into two parts (raw hunger scores = participants’ average hunger score + observation level deviations from those averages), that represent two different aspects of the relationship between hunger and irritability.</p>
<p>Adjust your model specification to include these two separate variables as predictors, instead of the raw hunger scores.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><code>hunger * diet</code> could be replaced by <code>(hunger1 + hunger2) * diet</code>, thereby allowing each aspect of hunger to interact with diet.</li>
<li>We can only put one of these variables in the random effects <code>(1 + hunger | participant)</code>. Recall that above we discussed how we cannot have <code>(diet | participant)</code>, because “an effect of diet” makes no sense for a single participant (they are either on the diet or they are not, so there is no ‘effect’). Similarly, each participant has only one value for their average hungriness.</li>
</ul>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-8" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')">
Solution
</button>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>hangrywb <span class="ot">&lt;-</span> <span class="fu">lmer</span>(q_irritability <span class="sc">~</span> (avg_hunger <span class="sc">+</span> hunger_gc)<span class="sc">*</span> fivetwo <span class="sc">+</span> </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>                (<span class="dv">1</span> <span class="sc">+</span> hunger_gc <span class="sc">|</span> ppt), </span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> hangry,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer=</span><span class="st">"bobyqa"</span>))</span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Hopefully, you have fitted a model similar to the below:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>hangrywb <span class="ot">&lt;-</span> <span class="fu">lmer</span>(q_irritability <span class="sc">~</span> (avg_hunger <span class="sc">+</span> hunger_gc) <span class="sc">*</span> fivetwo <span class="sc">+</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>                (<span class="dv">1</span> <span class="sc">+</span> hunger_gc <span class="sc">|</span> ppt), <span class="at">data =</span> hangry,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer=</span><span class="st">"bobyqa"</span>))</span></code></pre></div>
</div>
<p>Below, we have obtained p-values using the Kenward Rogers Approximation of <span class="math inline">\(df\)</span> for the test of whether the fixed effects are zero, so we can see the significance of each estimate.</p>
<p>Provide an answer for each of these questions:</p>
<ol type="1">
<li>For those following no diet, is there evidence to suggest that people who are <em>on average</em> more hungry are more irritable?</li>
<li>Is there evidence to suggest that this is different for those following the five-two diet? In what way?</li>
<li>Do people following no diet tend to be more irritable when they are more hungry than they usually are?</li>
<li>Is there evidence to suggest that this is different for those following the five-two diet? In what way?</li>
<li><strong>(Trickier:)</strong> What does the <code>fivetwo</code> coefficient represent?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="usealrsnvq" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#usealrsnvq table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#usealrsnvq thead, #usealrsnvq tbody, #usealrsnvq tfoot, #usealrsnvq tr, #usealrsnvq td, #usealrsnvq th {
  border-style: none;
}

#usealrsnvq p {
  margin: 0;
  padding: 0;
}

#usealrsnvq .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 100%;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#usealrsnvq .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#usealrsnvq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#usealrsnvq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#usealrsnvq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#usealrsnvq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#usealrsnvq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#usealrsnvq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#usealrsnvq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#usealrsnvq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#usealrsnvq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#usealrsnvq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#usealrsnvq .gt_spanner_row {
  border-bottom-style: hidden;
}

#usealrsnvq .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#usealrsnvq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#usealrsnvq .gt_from_md > :first-child {
  margin-top: 0;
}

#usealrsnvq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#usealrsnvq .gt_row {
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#usealrsnvq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#usealrsnvq .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#usealrsnvq .gt_row_group_first td {
  border-top-width: 2px;
}

#usealrsnvq .gt_row_group_first th {
  border-top-width: 2px;
}

#usealrsnvq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#usealrsnvq .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#usealrsnvq .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#usealrsnvq .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#usealrsnvq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#usealrsnvq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#usealrsnvq .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#usealrsnvq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#usealrsnvq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#usealrsnvq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#usealrsnvq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#usealrsnvq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#usealrsnvq .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#usealrsnvq .gt_left {
  text-align: left;
}

#usealrsnvq .gt_center {
  text-align: center;
}

#usealrsnvq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#usealrsnvq .gt_font_normal {
  font-weight: normal;
}

#usealrsnvq .gt_font_bold {
  font-weight: bold;
}

#usealrsnvq .gt_font_italic {
  font-style: italic;
}

#usealrsnvq .gt_super {
  font-size: 65%;
}

#usealrsnvq .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#usealrsnvq .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#usealrsnvq .gt_indent_1 {
  text-indent: 5px;
}

#usealrsnvq .gt_indent_2 {
  text-indent: 10px;
}

#usealrsnvq .gt_indent_3 {
  text-indent: 15px;
}

#usealrsnvq .gt_indent_4 {
  text-indent: 20px;
}

#usealrsnvq .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="7" class="gt_heading gt_title gt_font_normal gt_bottom_border" style="">Model Summary</td>
    </tr>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Parameter">Parameter</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Coefficient">Coefficient</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="SE">SE</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="95% CI">95% CI</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="t">t</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="df">df</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="p">p</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="7" class="gt_group_heading" scope="colgroup" id="Fixed Effects ">Fixed Effects </th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Fixed Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">(Intercept)</td>
<td headers="Fixed Effects   Coefficient" class="gt_row gt_center">17.13</td>
<td headers="Fixed Effects   SE" class="gt_row gt_center">5.21</td>
<td headers="Fixed Effects   95% CI" class="gt_row gt_center">(6.75, 27.51)</td>
<td headers="Fixed Effects   t" class="gt_row gt_center">3.29</td>
<td headers="Fixed Effects   df" class="gt_row gt_center">77.00</td>
<td headers="Fixed Effects   p" class="gt_row gt_center">0.002 </td></tr>
    <tr><td headers="Fixed Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">avg hunger</td>
<td headers="Fixed Effects   Coefficient" class="gt_row gt_center">3.86e-03</td>
<td headers="Fixed Effects   SE" class="gt_row gt_center">0.11</td>
<td headers="Fixed Effects   95% CI" class="gt_row gt_center">(-0.21, 0.22)</td>
<td headers="Fixed Effects   t" class="gt_row gt_center">0.04</td>
<td headers="Fixed Effects   df" class="gt_row gt_center">77.00</td>
<td headers="Fixed Effects   p" class="gt_row gt_center">0.971 </td></tr>
    <tr><td headers="Fixed Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">hunger gc</td>
<td headers="Fixed Effects   Coefficient" class="gt_row gt_center">0.19</td>
<td headers="Fixed Effects   SE" class="gt_row gt_center">0.08</td>
<td headers="Fixed Effects   95% CI" class="gt_row gt_center">(0.03, 0.34)</td>
<td headers="Fixed Effects   t" class="gt_row gt_center">2.45</td>
<td headers="Fixed Effects   df" class="gt_row gt_center">70.40</td>
<td headers="Fixed Effects   p" class="gt_row gt_center">0.017 </td></tr>
    <tr><td headers="Fixed Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">fivetwo (1)</td>
<td headers="Fixed Effects   Coefficient" class="gt_row gt_center">-10.85</td>
<td headers="Fixed Effects   SE" class="gt_row gt_center">6.62</td>
<td headers="Fixed Effects   95% CI" class="gt_row gt_center">(-24.03, 2.32)</td>
<td headers="Fixed Effects   t" class="gt_row gt_center">-1.64</td>
<td headers="Fixed Effects   df" class="gt_row gt_center">77.00</td>
<td headers="Fixed Effects   p" class="gt_row gt_center">0.105 </td></tr>
    <tr><td headers="Fixed Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">avg hunger × fivetwo (1)</td>
<td headers="Fixed Effects   Coefficient" class="gt_row gt_center">0.47</td>
<td headers="Fixed Effects   SE" class="gt_row gt_center">0.14</td>
<td headers="Fixed Effects   95% CI" class="gt_row gt_center">(0.20, 0.74)</td>
<td headers="Fixed Effects   t" class="gt_row gt_center">3.44</td>
<td headers="Fixed Effects   df" class="gt_row gt_center">77.00</td>
<td headers="Fixed Effects   p" class="gt_row gt_center">&lt; .001</td></tr>
    <tr><td headers="Fixed Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">hunger gc × fivetwo (1)</td>
<td headers="Fixed Effects   Coefficient" class="gt_row gt_center">0.38</td>
<td headers="Fixed Effects   SE" class="gt_row gt_center">0.10</td>
<td headers="Fixed Effects   95% CI" class="gt_row gt_center">(0.18, 0.58)</td>
<td headers="Fixed Effects   t" class="gt_row gt_center">3.75</td>
<td headers="Fixed Effects   df" class="gt_row gt_center">73.64</td>
<td headers="Fixed Effects   p" class="gt_row gt_center">&lt; .001</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="7" class="gt_group_heading" scope="colgroup" id="Random Effects ">Random Effects </th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Random Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">SD (Intercept: ppt)</td>
<td headers="Random Effects   Coefficient" class="gt_row gt_center">6.93</td>
<td headers="Random Effects   SE" class="gt_row gt_center"></td>
<td headers="Random Effects   95% CI" class="gt_row gt_center"></td>
<td headers="Random Effects   t" class="gt_row gt_center"></td>
<td headers="Random Effects   df" class="gt_row gt_center"></td>
<td headers="Random Effects   p" class="gt_row gt_center"></td></tr>
    <tr><td headers="Random Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">SD (hunger_gc: ppt)</td>
<td headers="Random Effects   Coefficient" class="gt_row gt_center">0.38</td>
<td headers="Random Effects   SE" class="gt_row gt_center"></td>
<td headers="Random Effects   95% CI" class="gt_row gt_center"></td>
<td headers="Random Effects   t" class="gt_row gt_center"></td>
<td headers="Random Effects   df" class="gt_row gt_center"></td>
<td headers="Random Effects   p" class="gt_row gt_center"></td></tr>
    <tr><td headers="Random Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">Cor (Intercept~hunger_gc: ppt)</td>
<td headers="Random Effects   Coefficient" class="gt_row gt_center">-0.01</td>
<td headers="Random Effects   SE" class="gt_row gt_center"></td>
<td headers="Random Effects   95% CI" class="gt_row gt_center"></td>
<td headers="Random Effects   t" class="gt_row gt_center"></td>
<td headers="Random Effects   df" class="gt_row gt_center"></td>
<td headers="Random Effects   p" class="gt_row gt_center"></td></tr>
    <tr><td headers="Random Effects   Parameter" class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;">SD (Residual)</td>
<td headers="Random Effects   Coefficient" class="gt_row gt_center">4.83</td>
<td headers="Random Effects   SE" class="gt_row gt_center"></td>
<td headers="Random Effects   95% CI" class="gt_row gt_center"></td>
<td headers="Random Effects   t" class="gt_row gt_center"></td>
<td headers="Random Effects   df" class="gt_row gt_center"></td>
<td headers="Random Effects   p" class="gt_row gt_center"></td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="7"></td>
    </tr>
  </tfoot>
  
</table>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-9" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')">
Solution
</button>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p><strong>1: For those following no diet, is there evidence to suggest that people who are <em>on average</em> more hungry are more irritable?</strong><br>
A: ‘No diet’ is the reference level of the five-two variable, and because we have an interaction, that means the <code>avg_hunger</code> coefficient will provide the relevant estimate. There is no evidence (<span class="math inline">\(p&gt;.05\)</span>) to suggest that when not dieting, hungrier people are more irritable than less hungry people.</p>
<p><strong>2: Is there evidence to suggest that this is different for those following the five-two diet? In what way?</strong><br>
A: This is the interaction between <code>avg_hunger:fivetwo1</code>. We can see that, for every increase of 1 in average hunger, irritability is estimated to increase by 0.47 more for those in the five-two diet than it does for those following no diet.<br>
These units are still in terms of the original scale (i.e.&nbsp;0 to 100).</p>
<p><strong>3: Do people following no diet tend to be more irritable when they are more hungry than they usually are?</strong> A: This is the estimate for the coefficient of <code>hunger_gc</code>. For people following no diet, there is an estimated 0.19 increase in irritability for every 1 unit more hungry they become.</p>
<p><strong>4: Is there evidence to suggest that this is different for those following the five-two diet? In what way?</strong> A: This effect of a 1 unit change on within-person hunger increasing irritability is increased for those who are following the five-two diet by an additional 0.38</p>
<p><strong>5: What does the <code>fivetwo1</code> coefficient represent?</strong> A: This represents the group difference of irritability between those on the five-two diet vs those not dieting, for someone who has an average hunger score of 0.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Construct two plots showing the two model estimated interactions. Think about your answers to the previous question, and check that they match with what you are seeing in the plots (do not underestimate the utility of this activity for helping understanding!).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This isn’t as difficult as it sounds. the sjPlot package can do it in one line of code!</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-10" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')">
Solution
</button>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(hangrywb, <span class="at">type =</span> <span class="st">"int"</span>)[[<span class="dv">1</span>]]</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>We saw in the model coefficients that for the reference level of <code>fivetwo</code>, the “No Diet” group, there was no association between how hungry a person is <em>on average</em> and their irritability. This is the red line we see in the plot above. We also saw the interaction <code>avg_hunger:fivetwo1</code> indicates that irritability is estimated to increase by 0.47 more for those in the five-two diet than it does for those following no diet. So the blue line is should be going up more steeply than the red line (which is flat). And it is!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(hangrywb, <span class="at">type =</span> <span class="st">"int"</span>)[[<span class="dv">2</span>]]</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptcent_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>From the coefficient of <code>hunger_gc</code> we get the estimated amount by which irritability increases for every 1 more hungry that a person becomes (when they’re on “No Diet”). This is the slope of the red line. The interaction <code>hunger_gc:fivetwo1</code> gave us the adjustment to get from the red line to the blue line. It is positive and significant, which matches with the fact that the blue line is clearly steeper in this plot.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Provide tests or confidence intervals for the parameters of interest, and write-up the results.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Remember: some options for inference
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 44%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>df approximations</th>
<th>likelihood-based</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tests or CIs for model parameters</td>
<td><code>library(parameters)</code><br><code>model_parameters(model, ci_method="kr")</code></td>
<td><code>confint(model, type="profile")</code></td>
</tr>
<tr class="even">
<td>model comparison<br><small>(different fixed effects, same random effects)</small></td>
<td><code>library(pbkrtest)</code><br><code>KRmodcomp(model1,model0)</code></td>
<td><code>anova(model0,model)</code></td>
</tr>
<tr class="odd">
<td></td>
<td>fit models with <code>REML=TRUE</code>.<br>good option for small samples</td>
<td>fit models with <code>REML=FALSE</code>.<br>needs large N at both levels (40+)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-11" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')">
Solution
</button>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(hangrywb, <span class="at">ci_method =</span> <span class="st">"kr"</span>, <span class="at">ci_random =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter                | Coefficient |   SE |          95% CI |     t |    df |      p
----------------------------------------------------------------------------------------
(Intercept)              |       17.13 | 5.21 | [  6.75, 27.51] |  3.29 | 77.00 | 0.002 
avg hunger               |    3.86e-03 | 0.11 | [ -0.21,  0.22] |  0.04 | 77.00 | 0.971 
hunger gc                |        0.19 | 0.08 | [  0.03,  0.34] |  2.45 | 70.40 | 0.017 
fivetwo [1]              |      -10.85 | 6.62 | [-24.03,  2.32] | -1.64 | 77.00 | 0.105 
avg hunger × fivetwo [1] |        0.47 | 0.14 | [  0.20,  0.74] |  3.44 | 77.00 | &lt; .001
hunger gc × fivetwo [1]  |        0.38 | 0.10 | [  0.18,  0.58] |  3.75 | 73.64 | &lt; .001

# Random Effects

Parameter                      | Coefficient
--------------------------------------------
SD (Intercept: ppt)            |        6.93
SD (hunger_gc: ppt)            |        0.38
Cor (Intercept~hunger_gc: ppt) |       -0.01
SD (Residual)                  |        4.83</code></pre>
</div>
</div>
<p>To investigate the association between irritability and hunger, and whether this relationship is different depending on whether or not participants are on a restricted diet such as the five-two, a multilevel linear model was fitted.<br>
To disaggregate between the differences in irritability due to people being in general more/less hungry, and those due to people being more/less hungry than usual for them, irritability was regressed onto both participants’ average hunger scores their relative hunger levels. Both of these were allowed to interact with whether or not participants were on the five-two diet. Random intercepts and slopes of relative-hunger level were included for participants. The model was fitting with restricted maximum likelihood estimation with the <strong>lme4</strong> package (Bates et al., 2015), using the <em>bobyqa</em> optimiser from the <strong>lme4</strong>. <span class="math inline">\(P\)</span>-values were obtained using Wald tests with Kenward-Roger approximation of denominator degrees of freedom.</p>
<p>Results indicate that for people on no diet, being more hungry than normal was associated with greater irritability (<span class="math inline">\(\beta = 0.19,\ SE = 0.08,\ t(2.45) = 70.4,\ p=0.017\)</span>), and that this was increased for those following the five-two diet (<span class="math inline">\(\beta = 0.38,\ SE = 0.1,\ t(3.75) = 73.64,\ p&lt;0.001\)</span>). Although for those not on a specific diet there was no evidence for an association between irritability and being generally a more hungry person (<span class="math inline">\(p=0.971\)</span>), there a significant interaction was found between average hunger and being on the five-two diet (<span class="math inline">\(\beta = 0.47,\ SE = 0.14,\ t(3.44) = 77,\ p&lt;0.001\)</span>), suggesting that when dieting, hungrier people tend to be more irritable than less hungry people.<br>
Results suggest that the ‘hangry hypothesis’ may occur <em>within</em> people (when a person is more hungry than they usually are, they tend to be more irritable), but not necessarily between hungry/less hungry people. Dieting was found to increase the association of both between-person hunger and within-person hunger with irritability.</p>
</div>
<p class="solution-end">
</p>
<div class="statbox">
<p><strong>Other within-group transformations</strong></p>
<p>As well as within-group mean centering a predictor (like we have done above), we can within-group <em>standardise</em> a predictor. This would disagregate within and between effects, but interpretation would of the within effect would be the estimated change in <span class="math inline">\(y\)</span> associated with being 1 standard deviation higher in <span class="math inline">\(x\)</span> <em>for that group</em>.</p>
</div>
<p><br></p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2023 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>