<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - 9. Principal Component Analysis (PCA)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('jk-circle-right')) {
    f.classList.add('jk-circle-down')
    f.classList.remove('jk-circle-right')
} else {
    f.classList.add('jk-circle-right')
    f.classList.remove('jk-circle-down')
}
}
</script>
<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07_path1.html">Path Analysis and Data Reduction</a></li><li class="breadcrumb-item"><a href="./09_pca.html">9. PCA</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DAPR3</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Multilevel Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_regressionrefresh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Regression Refresh | Clustered Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_intromlm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Intro to Multilevel Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_assumptcent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Assumptions and Diagnostics | Centering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_ranefglmer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Random Effect Structures | Logistic MLM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Recap &amp; Practice Datasets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b_lmmdatasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LMM Datasets</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Additional Docs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example_00_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis Example: Rpt &amp; Mixed ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lvp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Likelihood vs Probability</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">- Break Week -</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Path Analysis and Data Reduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_path1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Path Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_path2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Mediation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_pca.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">9. PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_efa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. EFA I</span></a>
  </div>
</li>
          <li class="sidebar-item">
 <span class="menu-text">11. EFA II</span>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Additional Docs</span></span>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercises-police-performance" id="toc-exercises-police-performance" class="nav-link active" data-scroll-target="#exercises-police-performance">Exercises: Police Performance</a>
  <ul class="collapse">
  <li><a href="#explore" id="toc-explore" class="nav-link" data-scroll-target="#explore">1. Explore</a></li>
  <li><a href="#is-pca-needed" id="toc-is-pca-needed" class="nav-link" data-scroll-target="#is-pca-needed">2. Is PCA needed?</a></li>
  <li><a href="#cov-vs-cor" id="toc-cov-vs-cor" class="nav-link" data-scroll-target="#cov-vs-cor">3. Cov vs Cor?</a></li>
  <li><a href="#perform-pca" id="toc-perform-pca" class="nav-link" data-scroll-target="#perform-pca">4. Perform PCA</a></li>
  <li><a href="#how-many-components-to-keep" id="toc-how-many-components-to-keep" class="nav-link" data-scroll-target="#how-many-components-to-keep">5. How many components to keep?</a></li>
  <li><a href="#retaining-n-components" id="toc-retaining-n-components" class="nav-link" data-scroll-target="#retaining-n-components">6. Retaining N Components</a></li>
  <li><a href="#using-pca-scores" id="toc-using-pca-scores" class="nav-link" data-scroll-target="#using-pca-scores">7. Using PCA scores</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">9. Principal Component Analysis (PCA)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="lo">
<p><strong>Relevant packages</strong></p>
<ul>
<li>psych</li>
</ul>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The goal of PCA
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="statbox">
<p>The goal of principal component analysis (PCA) is to find a <em>smaller</em> number of uncorrelated variables which are linear combinations of the original ( <em>many</em> ) variables and explain most of the variation in the data.</p>
</div>
<p>Take a moment to think about the various constructs that you are often interested in as a researcher. This might be anything from personality traits, to language proficiency, social identity, anxiety etc. How we measure such constructs is a very important consideration for research. The things we’re interested in are very rarely the things we are <em>directly</em> measuring.</p>
<p>Consider how we might assess levels of anxiety or depression. Can we ever directly measure anxiety? <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. More often than not, we measure these things using questionnaire based methods, to capture the multiple dimensions of the thing we are trying to assess. Twenty questions all measuring different aspects of anxiety are (we hope) going to correlate with one another if they are capturing some commonality (the construct of “anxiety”). But they introduce a problem for us, which is how to deal with 20 variables that represent (in broad terms) the same thing. How can we assess “effects on anxiety”, rather than “effects on anxiety q1 + effects on anxiety q2 + …”, etc.</p>
<p>This leads us to the idea of <em>reducing the dimensionality of our data</em>. Can we capture a reasonable amount of the information from our 20 questions in a smaller number of variables?</p>
</div>
</div>
</div>
<section id="exercises-police-performance" class="level1">
<h1>Exercises: Police Performance</h1>
<div class="frame">
<p><strong>Data: police_performance.csv</strong></p>
<p>The file <a href="https://uoepsy.github.io/data/police_performance.csv">police_performance.csv</a> (available at https://uoepsy.github.io/data/police_performance.csv) contains data on fifty police officers who were rated in six different categories as part of an HR procedure. The rated skills were:</p>
<ul>
<li>communication skills: <code>commun</code></li>
<li>problem solving: <code>probl_solv</code></li>
<li>logical ability: <code>logical</code></li>
<li>learning ability: <code>learn</code></li>
<li>physical ability: <code>physical</code></li>
<li>appearance: <code>appearance</code></li>
</ul>
<p>The data also contains information on each police officer’s arrest rate (proportion of arrests that lead to criminal charges).</p>
<p>We are interested in if the skills ratings by HR are a good set of predictors of police officer success (as indicated by their arrest rate).</p>
</div>
<section id="explore" class="level2">
<h2 class="anchored" data-anchor-id="explore">1. Explore</h2>
<p>First things first, we should always plot and describe our data. This is always a sensible thing to do - while many of the datasets we give you are nice and clean and organised, the data you get out of questionnaire tools, experiment software etc, are almost always quite a bit messier. It is also very useful to just eyeball the patterns of relationships between variables.</p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Load the job performance data into R and call it <code>job</code>. Check whether or not the data were read correctly into R - do the dimensions correspond to the description of the data above?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-1" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')">
Solution
</button>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<p>Let’s load the data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>job <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://uoepsy.github.io/data/police_performance.csv'</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(job)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50  7</code></pre>
</div>
</div>
<p>There are 50 observations on 6 variables.</p>
<p>The top 6 rows in the data are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(job)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  commun probl_solv logical learn physical appearance arrest_rate
   &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;
1     12         52      20    44       48         16      0.613 
2     12         57      25    45       50         16      0.419 
3     12         54      21    45       50         16      0     
4     13         52      21    46       51         17      0.645 
5     14         54      24    46       51         17      0.0645
6     14         48      20    47       51         18      0.645 </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Provide descriptive statistics for each variable in the dataset.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-2" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')">
Solution
</button>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p>We now inspect some descriptive statistics for each variable in the dataset:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick summary</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(job)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     commun       probl_solv      logical       learn         physical   
 Min.   :12.0   Min.   :48.0   Min.   :20   Min.   :44.0   Min.   :48.0  
 1st Qu.:16.0   1st Qu.:52.2   1st Qu.:22   1st Qu.:48.0   1st Qu.:52.2  
 Median :18.0   Median :54.0   Median :24   Median :50.0   Median :54.0  
 Mean   :17.7   Mean   :54.2   Mean   :24   Mean   :50.3   Mean   :54.2  
 3rd Qu.:19.8   3rd Qu.:56.0   3rd Qu.:26   3rd Qu.:52.0   3rd Qu.:56.0  
 Max.   :24.0   Max.   :59.0   Max.   :31   Max.   :56.0   Max.   :59.0  
   appearance    arrest_rate   
 Min.   :16.0   Min.   :0.000  
 1st Qu.:19.0   1st Qu.:0.371  
 Median :21.0   Median :0.565  
 Mean   :21.1   Mean   :0.512  
 3rd Qu.:23.0   3rd Qu.:0.669  
 Max.   :28.0   Max.   :0.935  </code></pre>
</div>
</div>
<p><strong>OPTIONAL</strong></p>
<p>If you wish to create a nice looking table for a report, you could try the following code. However, I should warn you: this code is quite difficult to understand so, if you are interested, attend a lab!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean and SD of each variable</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>job <span class="sc">%&gt;%</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="fu">list</span>(<span class="at">M =</span> mean, <span class="at">SD =</span> sd))) <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">value =</span> <span class="fu">round</span>(value, <span class="dv">2</span>),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">str_replace</span>(name, <span class="st">'_M'</span>, <span class="st">'.M'</span>),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">str_replace</span>(name, <span class="st">'_SD'</span>, <span class="st">'.SD'</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(name, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">'variable'</span>, <span class="st">'summary'</span>), <span class="at">sep =</span> <span class="st">'</span><span class="sc">\\</span><span class="st">.'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> summary, <span class="at">values_from =</span> value) <span class="sc">%&gt;%</span> </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>()</span></code></pre></div>
<div class="cell-output-display">

<div id="edsrqxtaea" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#edsrqxtaea table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#edsrqxtaea thead, #edsrqxtaea tbody, #edsrqxtaea tfoot, #edsrqxtaea tr, #edsrqxtaea td, #edsrqxtaea th {
  border-style: none;
}

#edsrqxtaea p {
  margin: 0;
  padding: 0;
}

#edsrqxtaea .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#edsrqxtaea .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#edsrqxtaea .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#edsrqxtaea .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#edsrqxtaea .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#edsrqxtaea .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edsrqxtaea .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#edsrqxtaea .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#edsrqxtaea .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#edsrqxtaea .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#edsrqxtaea .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#edsrqxtaea .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#edsrqxtaea .gt_spanner_row {
  border-bottom-style: hidden;
}

#edsrqxtaea .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#edsrqxtaea .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#edsrqxtaea .gt_from_md > :first-child {
  margin-top: 0;
}

#edsrqxtaea .gt_from_md > :last-child {
  margin-bottom: 0;
}

#edsrqxtaea .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#edsrqxtaea .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#edsrqxtaea .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#edsrqxtaea .gt_row_group_first td {
  border-top-width: 2px;
}

#edsrqxtaea .gt_row_group_first th {
  border-top-width: 2px;
}

#edsrqxtaea .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#edsrqxtaea .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#edsrqxtaea .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#edsrqxtaea .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edsrqxtaea .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#edsrqxtaea .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#edsrqxtaea .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#edsrqxtaea .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#edsrqxtaea .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#edsrqxtaea .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#edsrqxtaea .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#edsrqxtaea .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#edsrqxtaea .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#edsrqxtaea .gt_left {
  text-align: left;
}

#edsrqxtaea .gt_center {
  text-align: center;
}

#edsrqxtaea .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#edsrqxtaea .gt_font_normal {
  font-weight: normal;
}

#edsrqxtaea .gt_font_bold {
  font-weight: bold;
}

#edsrqxtaea .gt_font_italic {
  font-style: italic;
}

#edsrqxtaea .gt_super {
  font-size: 65%;
}

#edsrqxtaea .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#edsrqxtaea .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#edsrqxtaea .gt_indent_1 {
  text-indent: 5px;
}

#edsrqxtaea .gt_indent_2 {
  text-indent: 10px;
}

#edsrqxtaea .gt_indent_3 {
  text-indent: 15px;
}

#edsrqxtaea .gt_indent_4 {
  text-indent: 20px;
}

#edsrqxtaea .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="variable">variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="M">M</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="SD">SD</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="variable" class="gt_row gt_left">commun</td>
<td headers="M" class="gt_row gt_right">17.68</td>
<td headers="SD" class="gt_row gt_right">2.74</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">probl_solv</td>
<td headers="M" class="gt_row gt_right">54.16</td>
<td headers="SD" class="gt_row gt_right">2.41</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">logical</td>
<td headers="M" class="gt_row gt_right">24.02</td>
<td headers="SD" class="gt_row gt_right">2.49</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">learn</td>
<td headers="M" class="gt_row gt_right">50.28</td>
<td headers="SD" class="gt_row gt_right">2.84</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">physical</td>
<td headers="M" class="gt_row gt_right">54.16</td>
<td headers="SD" class="gt_row gt_right">2.41</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">appearance</td>
<td headers="M" class="gt_row gt_right">21.06</td>
<td headers="SD" class="gt_row gt_right">2.99</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">arrest_rate</td>
<td headers="M" class="gt_row gt_right">0.51</td>
<td headers="SD" class="gt_row gt_right">0.23</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="is-pca-needed" class="level2">
<h2 class="anchored" data-anchor-id="is-pca-needed">2. Is PCA needed?</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
When might we want to reduce dimensionality?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There are many reasons we might want to reduce the dimensionality of data:</p>
<ul>
<li>Theory testing
<ul>
<li>What are the number and nature of dimensions that best describe a theoretical construct?</li>
</ul></li>
<li>Test construction
<ul>
<li>How should I group my items into sub-scales?</li>
<li>Which items are the best measures of my constructs?</li>
</ul></li>
<li>Pragmatic
<ul>
<li>I have multicollinearity issues/too many variables, how can I defensibly combine my variables?</li>
</ul></li>
</ul>
<p>PCA is most often used for the latter - we are less interested in the theory behind our items, we just want a useful way of simplifying lots of variables down to a smaller number.</p>
<p>Recall that we are wanting to see how well the skills ratings predict arrest rate.<br>
We might fit this model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(arrest_rate <span class="sc">~</span> commun <span class="sc">+</span> probl_solv <span class="sc">+</span> logical <span class="sc">+</span> learn <span class="sc">+</span> physical <span class="sc">+</span> appearance, <span class="at">data =</span> job)</span></code></pre></div>
</div>
<p>However, we might have reason to think that many of these predictors might be quite highly correlated with one another, and so we may be unable to draw accurate inferences. This is borne out in our variance inflation factor (VIF):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(mod)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    commun probl_solv    logical      learn   physical appearance 
     34.67       1.17       1.23      43.56      34.98      21.78 </code></pre>
</div>
</div>
<p>As the original variables are highly correlated, it is possible to reduce the dimensionality of the problem under investigation without losing too much information.</p>
<p>On the other side, if the correlation between the variables under study are weak, a larger number of components is needed in order to explain sufficient variability.</p>
</div>
</div>
</div>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Working with <em>only</em> the skills ratings (not the arrest rate - we’ll come back to that right at the end), investigate whether or not the variables are highly correlated and explain whether or not you PCA might be useful in this case.</p>
<p><strong>Hint:</strong> We only have 6 variables here, but if we had many, how might you visualise <code>cor(job)</code>?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-3" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')">
Solution
</button>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>Let’s start by looking at the correlation matrix of the data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pheatmap)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>job_skills <span class="ot">&lt;-</span> job <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>arrest_rate)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="fu">cor</span>(job_skills)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">pheatmap</span>(R, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>))</span></code></pre></div>
<div class="cell-output-display">
<div id="fig-jobcor" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="09_pca_files/figure-html/fig-jobcor-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Correlation between the variables in the ``Job’’ dataset</figcaption>
</figure>
</div>
</div>
</div>
<p>The correlation between the variables seems to be quite large (it doesn’t matter about direction here, only magnitude; if negative correlations were present, we would think in absolute value).</p>
<p>There appears to be a group of highly correlated variables comprising physical ability, appearance, communication skills, and learning ability which are correlated among themselves but uncorrelated with another group of variables. The second group comprises problem solving and logical ability.</p>
<p>This suggests that PCA might be useful in this problem to reduce the dimensionality without a significant loss of information.</p>
</div>
<p class="solution-end">
</p>
</section>
<section id="cov-vs-cor" class="level2">
<h2 class="anchored" data-anchor-id="cov-vs-cor">3. Cov vs Cor?</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Should we perform PCA on the covariance or the correlation matrix?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This depends on the variances of the variables in the dataset. If the variables have large differences in their variances, then the variables with the largest variances will tend to dominate the first few principal components.<br>
A solution to this is to standardise the variables prior to computing the covariance matrix - i.e., compute the correlation matrix!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show that the correlation matrix and the covariance matrix of the standardized variables are identical</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">cor</span>(job_skills), <span class="fu">cov</span>(<span class="fu">scale</span>(job_skills)))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Look at the variance of the skills ratings in the data set. Do you think that PCA should be carried on the covariance matrix or the correlation matrix?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-4" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')">
Solution
</button>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>Let’s have a look at the standard deviation of each variable:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>job_skills <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), sd))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  commun probl_solv logical learn physical appearance
   &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
1   2.74       2.41    2.49  2.84     2.41       2.99</code></pre>
</div>
</div>
<p>As the standard deviations appear to be fairly similar (and so will the variances) we can perform PCA using the covariance matrix.</p>
</div>
<p class="solution-end">
</p>
</section>
<section id="perform-pca" class="level2">
<h2 class="anchored" data-anchor-id="perform-pca">4. Perform PCA</h2>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Using the <code>principal()</code> function from the <code>psych</code> package, we can perform a PCA of the job performance data, Call the output <code>job_pca</code>.</p>
<pre><code>job_pca &lt;- principal(job_skills, nfactors = ncol(job_skills), covar = ..., rotate = 'none')</code></pre>
<p>Depending on your answer to the previous question, either set <code>covar = TRUE</code> or <code>covar = FALSE</code> within the <code>principal()</code> function.</p>
<p><strong>Warning:</strong> the output of the function will be in terms of standardized variables nevertheless. So you will see output with standard deviation of 1.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-5" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')">
Solution
</button>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>job_pca <span class="ot">&lt;-</span> <span class="fu">principal</span>(job_skills, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">covar =</span> <span class="cn">TRUE</span>, <span class="at">rotate =</span> <span class="st">'none'</span>)</span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
PCA OUTPUT
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can print the output by just typing the name of our PCA:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>job_pca</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Principal Components Analysis
Call: principal(r = job_skills, nfactors = 2, rotate = "none", covar = TRUE)
Standardized loadings (pattern matrix) based upon correlation matrix
            PC1   PC2   h2    u2 com
commun     0.98 -0.12 0.98 0.017 1.0
probl_solv 0.22  0.81 0.71 0.295 1.2
logical    0.33  0.75 0.67 0.335 1.4
learn      0.99 -0.11 0.99 0.014 1.0
physical   0.99 -0.08 0.98 0.017 1.0
appearance 0.98 -0.13 0.97 0.026 1.0

                       PC1  PC2
SS loadings           4.04 1.26
Proportion Var        0.67 0.21
Cumulative Var        0.67 0.88
Proportion Explained  0.76 0.24
Cumulative Proportion 0.76 1.00

Mean item complexity =  1.1
Test of the hypothesis that 2 components are sufficient.

The root mean square of the residuals (RMSR) is  0.08 
 with the empirical chi square  9.97  with prob &lt;  0.041 

Fit based upon off diagonal values = 0.98</code></pre>
</div>
</div>
<p>The output is made up of two parts.</p>
<p>First, it shows the <em>loading matrix</em>. In each column of the loading matrix we find how much each of the measured variables contributes to the computed new axis/direction (that is, the principal component). Notice that there are as many principal components as variables.</p>
<p>The second part of the output displays the contribution of each component to the total variance:</p>
<ul>
<li>SS loadings: The sum of the squared loadings. The eigenvalues (see <a href="https://uoepsy.github.io/dapr3/2324/lectures/dapr3_08_pca#24" target="_blank">Lecture</a>).<br>
</li>
<li>Proportion Var: how much of the overall variance the component accounts for out of all the variables.</li>
<li>Cumulative Var: cumulative sum of Proportion Var.</li>
<li>Proportion Explained: relative amount of variance explained (<span class="math inline">\(\frac{\text{Proportion Var}}{\text{sum(Proportion Var)}}\)</span>.</li>
<li>Cumulative Proportion: cumulative sum of Proportion Explained.</li>
</ul>
<p>Let’s focus on the row of that output called “Cumulative Var”. This displays the cumulative sum of the variances of each principal component. Taken all together, the six principal components taken explain all of the total variance in the original data. In other words, the total variance of the principal components (the sum of their variances) is equal to the total variance in the original data (the sum of the variances of the variables).</p>
<p>However, our goal is to reduce the dimensionality of our data, so it comes natural to wonder which of the six principal components explain most of the variability, and which components instead do not contribute substantially to the total variance.</p>
<p>To that end, the second row “Proportion Var” displays the proportion of the total variance explained by each component, i.e.&nbsp;the variance of the principal component divided by the total variance.</p>
<p>The last row, as we saw, is the cumulative proportion of explained variance: <code>0.67</code>, <code>0.67 + 0.21</code>, <code>0.67 + 0.21 + 0.11</code>, and so on.</p>
<p>We also notice that the first PC alone explains 67.3% of the total variability, while the first two components together explain almost 90% of the total variability. From the third component onwards, we do not see such a sharp increase in the proportion of explained variance, and the cumulative proportion slowly reaches the total ratio of 1 (or 100%).</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional: (some of) the math behind it
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Doing data reduction can feel a bit like magic, and in part that’s just because it’s quite complicated.</p>
<p><strong>The intuition</strong></p>
<p>Consider one way we might construct a correlation matrix - as the product of vector <span class="math inline">\(\mathbf{f}\)</span> with <span class="math inline">\(\mathbf{f'}\)</span> (f transposed): <span class="math display">\[
\begin{equation*}
\mathbf{f} =
\begin{bmatrix}
0.9 \\
0.8 \\
0.7 \\
0.6 \\
0.5 \\
0.4 \\
\end{bmatrix}
\qquad
\mathbf{f} \mathbf{f'} =
\begin{bmatrix}
0.9 \\
0.8 \\
0.7 \\
0.6 \\
0.5 \\
0.4 \\
\end{bmatrix}
\begin{bmatrix}
0.9, 0.8, 0.7, 0.6, 0.5, 0.4 \\
\end{bmatrix}
\qquad = \qquad
\begin{bmatrix}
0.81, 0.72, 0.63, 0.54, 0.45, 0.36 \\
0.72, 0.64, 0.56, 0.48, 0.40, 0.32 \\
0.63, 0.56, 0.49, 0.42, 0.35, 0.28 \\
0.54, 0.48, 0.42, 0.36, 0.30, 0.24 \\
0.45, 0.40, 0.35, 0.30, 0.25, 0.20 \\
0.36, 0.32, 0.28, 0.24, 0.20, 0.16 \\
\end{bmatrix}
\end{equation*}
\]</span></p>
<p>But we constrain this such that the diagonal has values of 1 (the correlation of a variable with itself is 1), and lets call it <strong>R</strong>. <span class="math display">\[
\begin{equation*}
\mathbf{R} =
\begin{bmatrix}
1.00, 0.72, 0.63, 0.54, 0.45, 0.36 \\
0.72, 1.00, 0.56, 0.48, 0.40, 0.32 \\
0.63, 0.56, 1.00, 0.42, 0.35, 0.28 \\
0.54, 0.48, 0.42, 1.00, 0.30, 0.24 \\
0.45, 0.40, 0.35, 0.30, 1.00, 0.20 \\
0.36, 0.32, 0.28, 0.24, 0.20, 1.00 \\
\end{bmatrix}
\end{equation*}
\]</span></p>
<p>PCA is about trying to determine a vector <strong>f</strong> which generates the correlation matrix <strong>R</strong>. a bit like unscrambling eggs!</p>
<p>in PCA, we express <span class="math inline">\(\mathbf{R = CC'}\)</span>, where <span class="math inline">\(\mathbf{C}\)</span> are our principal components.<br>
If <span class="math inline">\(n\)</span> is number of variables in <span class="math inline">\(R\)</span>, then <span class="math inline">\(i^{th}\)</span> component <span class="math inline">\(C_i\)</span> is the linear sum of each variable multiplied by some weighting:<br>
<span class="math display">\[
C_i = \sum_{j=1}^{n}w_{ij}x_{j}
\]</span></p>
<p><strong>How do we find <span class="math inline">\(C\)</span>?</strong></p>
<p>This is where “eigen decomposition” comes in.<br>
For the <span class="math inline">\(n \times n\)</span> correlation matrix <span class="math inline">\(\mathbf{R}\)</span>, there is an <strong>eigenvector</strong> <span class="math inline">\(x_i\)</span> that solves the equation <span class="math display">\[
\mathbf{x_i R} = \lambda_i \mathbf{x_i}
\]</span> Where the vector multiplied by the correlation matrix is equal to some <strong>eigenvalue</strong> <span class="math inline">\(\lambda_i\)</span> multiplied by that vector.<br>
We can write this without subscript <span class="math inline">\(i\)</span> as: <span class="math display">\[
\begin{align}
&amp; \mathbf{R X} = \mathbf{X \lambda} \\
&amp; \text{where:} \\
&amp; \mathbf{R} = \text{correlation matrix} \\
&amp; \mathbf{X} = \text{matrix of eigenvectors} \\
&amp; \mathbf{\lambda} = \text{vector of eigenvalues}
\end{align}
\]</span> the vectors which make up <span class="math inline">\(\mathbf{X}\)</span> must be orthogonal <a href="https://miro.medium.com/max/700/1*kyg5XbrY1AOB946IE5nWWg.png">(<span class="math inline">\(\mathbf{XX' = I}\)</span>)</a>, which means that <span class="math inline">\(\mathbf{R = X \lambda X'}\)</span></p>
<p>We can actually do this in R manually. Creating a correlation matrix</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># lets create a correlation matrix, as the produce of ff'</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">seq</span>(.<span class="dv">9</span>,.<span class="dv">4</span>,<span class="sc">-</span>.<span class="dv">1</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> f <span class="sc">%*%</span> <span class="fu">t</span>(f)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">#give rownames and colnames</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(R)<span class="ot">&lt;-</span><span class="fu">colnames</span>(R)<span class="ot">&lt;-</span><span class="fu">paste0</span>(<span class="st">"V"</span>,<span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co">#constrain diagonals to equal 1</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(R)<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>R</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     V1   V2   V3   V4   V5   V6
V1 1.00 0.72 0.63 0.54 0.45 0.36
V2 0.72 1.00 0.56 0.48 0.40 0.32
V3 0.63 0.56 1.00 0.42 0.35 0.28
V4 0.54 0.48 0.42 1.00 0.30 0.24
V5 0.45 0.40 0.35 0.30 1.00 0.20
V6 0.36 0.32 0.28 0.24 0.20 1.00</code></pre>
</div>
</div>
<p>Eigen Decomposition</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># do eigen decomposition</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">eigen</span>(R)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(e, <span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>eigen() decomposition
$values
[1] 3.16 0.82 0.72 0.59 0.44 0.26

$vectors
      [,1]   [,2]   [,3]  [,4]   [,5]   [,6]
[1,] -0.50 -0.061  0.092  0.14  0.238  0.816
[2,] -0.47 -0.074  0.121  0.21  0.657 -0.533
[3,] -0.43 -0.096  0.182  0.53 -0.675 -0.184
[4,] -0.39 -0.142  0.414 -0.78 -0.201 -0.104
[5,] -0.34 -0.299 -0.860 -0.20 -0.108 -0.067
[6,] -0.28  0.934 -0.178 -0.10 -0.067 -0.045</code></pre>
</div>
</div>
<p>The eigenvectors are orthogonal (<span class="math inline">\(\mathbf{XX' = I}\)</span>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(e<span class="sc">$</span>vectors <span class="sc">%*%</span> <span class="fu">t</span>(e<span class="sc">$</span>vectors),<span class="dv">2</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    0    0    0    0    0
[2,]    0    1    0    0    0    0
[3,]    0    0    1    0    0    0
[4,]    0    0    0    1    0    0
[5,]    0    0    0    0    1    0
[6,]    0    0    0    0    0    1</code></pre>
</div>
</div>
<p>The Principal Components <span class="math inline">\(\mathbf{C}\)</span> are the eigenvectors scaled by the square root of the eigenvalues:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#eigenvectors</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>vectors</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1]    [,2]    [,3]   [,4]    [,5]    [,6]
[1,] -0.496 -0.0611  0.0923  0.139  0.2385  0.8155
[2,] -0.468 -0.0743  0.1210  0.214  0.6566 -0.5327
[3,] -0.433 -0.0963  0.1820  0.530 -0.6751 -0.1842
[4,] -0.390 -0.1416  0.4143 -0.778 -0.2006 -0.1036
[5,] -0.340 -0.2992 -0.8604 -0.197 -0.1076 -0.0669
[6,] -0.282  0.9338 -0.1784 -0.100 -0.0667 -0.0452</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#scaled by sqrt of eigenvalues</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(<span class="fu">sqrt</span>(e<span class="sc">$</span>values))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]  [,2]  [,3]  [,4]  [,5]  [,6]
[1,] 1.78 0.000 0.000 0.000 0.000 0.000
[2,] 0.00 0.906 0.000 0.000 0.000 0.000
[3,] 0.00 0.000 0.848 0.000 0.000 0.000
[4,] 0.00 0.000 0.000 0.769 0.000 0.000
[5,] 0.00 0.000 0.000 0.000 0.664 0.000
[6,] 0.00 0.000 0.000 0.000 0.000 0.512</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> e<span class="sc">$</span>vectors <span class="sc">%*%</span> <span class="fu">diag</span>(<span class="fu">sqrt</span>(e<span class="sc">$</span>values))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>C</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1]    [,2]    [,3]    [,4]    [,5]    [,6]
[1,] -0.883 -0.0554  0.0782  0.1070  0.1584  0.4174
[2,] -0.833 -0.0673  0.1025  0.1648  0.4361 -0.2727
[3,] -0.770 -0.0873  0.1542  0.4077 -0.4483 -0.0943
[4,] -0.694 -0.1284  0.3512 -0.5987 -0.1332 -0.0530
[5,] -0.604 -0.2712 -0.7293 -0.1514 -0.0715 -0.0342
[6,] -0.502  0.8464 -0.1513 -0.0771 -0.0443 -0.0231</code></pre>
</div>
</div>
<p>And we can reproduce our correlation matrix, because <span class="math inline">\(\mathbf{R = CC'}\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>C <span class="sc">%*%</span> <span class="fu">t</span>(C)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1.00 0.72 0.63 0.54 0.45 0.36
[2,] 0.72 1.00 0.56 0.48 0.40 0.32
[3,] 0.63 0.56 1.00 0.42 0.35 0.28
[4,] 0.54 0.48 0.42 1.00 0.30 0.24
[5,] 0.45 0.40 0.35 0.30 1.00 0.20
[6,] 0.36 0.32 0.28 0.24 0.20 1.00</code></pre>
</div>
</div>
<p>Now lets imagine we only consider 1 principal component.<br>
We can do this with the <code>principal()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>pc1<span class="ot">&lt;-</span><span class="fu">principal</span>(R, <span class="at">nfactors =</span> <span class="dv">1</span>, <span class="at">covar =</span> <span class="cn">FALSE</span>, <span class="at">rotate =</span> <span class="st">'none'</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>pc1</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Principal Components Analysis
Call: principal(r = R, nfactors = 1, rotate = "none", covar = FALSE)
Standardized loadings (pattern matrix) based upon correlation matrix
    PC1   h2   u2 com
V1 0.88 0.78 0.22   1
V2 0.83 0.69 0.31   1
V3 0.77 0.59 0.41   1
V4 0.69 0.48 0.52   1
V5 0.60 0.37 0.63   1
V6 0.50 0.25 0.75   1

                PC1
SS loadings    3.16
Proportion Var 0.53

Mean item complexity =  1
Test of the hypothesis that 1 component is sufficient.

The root mean square of the residuals (RMSR) is  0.09 

Fit based upon off diagonal values = 0.95</code></pre>
</div>
</div>
<p>Look familiar? It looks like the first component we computed manually. The first column of <span class="math inline">\(\mathbf{C}\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(pc1<span class="sc">$</span>loadings, <span class="at">C=</span>C[,<span class="dv">1</span>])</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     PC1      C
V1 0.883 -0.883
V2 0.833 -0.833
V3 0.770 -0.770
V4 0.694 -0.694
V5 0.604 -0.604
V6 0.502 -0.502</code></pre>
</div>
</div>
<p>We can now ask “how well does this component (on its own) recreate our correlation matrix?”</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>C[,<span class="dv">1</span>] <span class="sc">%*%</span> <span class="fu">t</span>(C[,<span class="dv">1</span>])</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]  [,2]  [,3]  [,4]  [,5]  [,6]
[1,] 0.780 0.735 0.680 0.613 0.534 0.444
[2,] 0.735 0.693 0.641 0.578 0.503 0.418
[3,] 0.680 0.641 0.592 0.534 0.465 0.387
[4,] 0.613 0.578 0.534 0.481 0.419 0.348
[5,] 0.534 0.503 0.465 0.419 0.365 0.304
[6,] 0.444 0.418 0.387 0.348 0.304 0.252</code></pre>
</div>
</div>
<p>It looks close, but not quite. How much not quite? Measurably so!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>R <span class="sc">-</span> (C[,<span class="dv">1</span>] <span class="sc">%*%</span> <span class="fu">t</span>(C[,<span class="dv">1</span>]))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        V1      V2      V3      V4      V5      V6
V1  0.2200 -0.0154 -0.0498 -0.0727 -0.0838 -0.0836
V2 -0.0154  0.3067 -0.0809 -0.0976 -0.1033 -0.0982
V3 -0.0498 -0.0809  0.4075 -0.1140 -0.1153 -0.1066
V4 -0.0727 -0.0976 -0.1140  0.5187 -0.1193 -0.1085
V5 -0.0838 -0.1033 -0.1153 -0.1193  0.6346 -0.1036
V6 -0.0836 -0.0982 -0.1066 -0.1085 -0.1036  0.7477</code></pre>
</div>
</div>
<p>Notice the values on the diagonals of <span class="math inline">\(\mathbf{c_1}\mathbf{c_1}'\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(C[,<span class="dv">1</span>] <span class="sc">%*%</span> <span class="fu">t</span>(C[,<span class="dv">1</span>]))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.780 0.693 0.592 0.481 0.365 0.252</code></pre>
</div>
</div>
<p>These aren’t 1, like they are in <span class="math inline">\(R\)</span>. But they are proportional: this is the amount of variance in each observed variable that is explained by this first component. Sound familiar?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>pc1<span class="sc">$</span>communality</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   V1    V2    V3    V4    V5    V6 
0.780 0.693 0.592 0.481 0.365 0.252 </code></pre>
</div>
</div>
<p>And likewise the 1 minus these is the unexplained variance:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">diag</span>(C[,<span class="dv">1</span>] <span class="sc">%*%</span> <span class="fu">t</span>(C[,<span class="dv">1</span>]))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.220 0.307 0.408 0.519 0.635 0.748</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>pc1<span class="sc">$</span>uniquenesses</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   V1    V2    V3    V4    V5    V6 
0.220 0.307 0.408 0.519 0.635 0.748 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="how-many-components-to-keep" class="level2">
<h2 class="anchored" data-anchor-id="how-many-components-to-keep">5. How many components to keep?</h2>
<p>There is no single best method to select the optimal number of components to keep, while discarding the remaining ones (which are then considered as noise components).</p>
<p>The following three heuristic rules are commonly used in the literature:</p>
<ul>
<li>The cumulative proportion of explained variance criterion</li>
<li>Kaiser’s rule</li>
<li>The scree plot</li>
<li>Velicer’s Minimum Average Partial method</li>
<li>Parallel analysis</li>
</ul>
<p>In the next sections we will look at each of them in turn.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The cumulative proportion of explained variance criterion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The rule suggests to <em>keep as many principal components as needed in order to explain approximately 80-90% of the total variance.</em></p>
</div>
</div>
</div>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Looking again at the PCA output, how many principal components would you keep if you were following the cumulative proportion of explained variance criterion?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-6" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')">
Solution
</button>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>Let’s look again at the PCA summary:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>job_pca<span class="sc">$</span>loadings</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
           PC1    PC2   
commun      0.984 -0.120
probl_solv  0.223  0.810
logical     0.329  0.747
learn       0.987 -0.110
physical    0.988       
appearance  0.979 -0.125

                 PC1   PC2
SS loadings    4.035 1.261
Proportion Var 0.673 0.210
Cumulative Var 0.673 0.883</code></pre>
</div>
</div>
<p>The following part of the output tells us that the first two components explain 88.3% of the total variance.</p>
<pre><code>Cumulative Var 0.673 0.883 0.988 0.994 0.997 1.000</code></pre>
<p>According to this criterion, we should keep 2 principal components.</p>
</div>
<p class="solution-end">
</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kaiser’s rule
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>According to Kaiser’s rule, we should <strong>keep the principal components having variance larger than 1</strong>. Standardized variables have a variance equal 1. Because we have 6 variables in the data set, and the total variance is 6, the value 1 represents the average variance in the data: <span class="math display">\[
\frac{1 + 1 + 1 + 1 + 1 + 1}{6} = 1
\]</span></p>
<p><strong>Hint:</strong></p>
<p>The variances of each PC are shown in the row of the output named <code>SS loadings</code> and also in <code>job_pca$values</code>. The average variance is:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(job_pca<span class="sc">$</span>values)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Looking again at the PCA output, how many principal components would you keep if you were following Kaiser’s criterion?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-7" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')">
Solution
</button>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>job_pca<span class="sc">$</span>loadings</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
           PC1    PC2   
commun      0.984 -0.120
probl_solv  0.223  0.810
logical     0.329  0.747
learn       0.987 -0.110
physical    0.988       
appearance  0.979 -0.125

                 PC1   PC2
SS loadings    4.035 1.261
Proportion Var 0.673 0.210
Cumulative Var 0.673 0.883</code></pre>
</div>
</div>
<p>The variances are shown in the row</p>
<pre><code>SS loadings    4.035 1.261 0.631 0.035 0.022 0.016</code></pre>
<p>From the result we see that only the first two principal components have variance greater than 1, so this rule suggests to keep 2 PCs only.</p>
</div>
<p class="solution-end">
</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The scree plot
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The scree plot is a graphical criterion which involves plotting the variance for each principal component. This can be easily done by calling <code>plot</code> on the variances, which are stored in <code>job_pca$values</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(job_pca<span class="sc">$</span>values), <span class="at">y =</span> job_pca<span class="sc">$</span>values, </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">'b'</span>, <span class="at">xlab =</span> <span class="st">''</span>, <span class="at">ylab =</span> <span class="st">'Variance'</span>, </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">'Police officers: scree plot'</span>, <span class="at">frame.plot =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_pca_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>where the argument <code>type = 'b'</code> tells R that the plot should have <em>both</em> points and lines.</p>
<p>A typical scree plot features higher variances for the initial components and quickly drops to small variances where the curve is almost flat. The flat part of the curve represents the noise components, which are not able to capture the main sources of variability in the system.</p>
<p>According to the scree plot criterion, we should <strong>keep as many principal components as where the “elbow” in the plot occurs.</strong> By elbow we mean the variance before the curve looks almost flat.</p>
<p>Alternatively, some people prefer to use the function <code>scree()</code> from the <code>psych</code> package:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scree</span>(job_skills, <span class="at">factors =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_pca_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>This also draws a horizontal line at y = 1. So, if you are making a decision about how many PCs to keep by looking at where the plot falls below the y = 1 line, you are basically following Kaiser’s rule. In fact, Kaiser’s criterion tells you to keep as many PCs as are those with a variance (= eigenvalue) greater than 1.</p>
<p><strong>NOTE: Scree plots are subjective and may have multiple or no obvious kinks/elbows, making them hard to interpret</strong></p>
</div>
</div>
</div>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>According to the scree plot, how many principal components would you retain?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-8" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')">
Solution
</button>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>This criterion then suggests to keep three principal components.</p>
</div>
<p class="solution-end">
</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Velicer’s Minimum Average Partial (MAP) method
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The Minimum Average Partial (MAP) test computes the partial correlation matrix (removing and adjusting for a component from the correlation matrix), sequentially partialling out each component. At each step, the partial correlations are squared and their average is computed.<br>
At first, the components which are removed will be those that are most representative of the shared variance between 2+ variables, meaning that the “average squared partial correlation” will decrease. At some point in the process, the components being removed will begin represent variance that is specific to individual variables, meaning that the average squared partial correlation will increase.<br>
The MAP method is to keep the number of components for which the average squared partial correlation is at the minimum.</p>
<p>We can conduct MAP in R using:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VSS</span>(data, <span class="at">plot =</span> <span class="cn">FALSE</span>, <span class="at">method=</span><span class="st">"pc"</span>, <span class="at">n =</span> <span class="fu">ncol</span>(data))</span></code></pre></div>
</div>
<p>(be aware there is a lot of other information in this output too! For now just focus on the map column)</p>
<p><strong>NOTE: The MAP method will sometimes tend to under-extract (suggest too few components)</strong></p>
</div>
</div>
</div>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>How many components should we keep according to the MAP method?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-9" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')">
Solution
</button>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VSS</span>(job_skills, <span class="at">plot=</span><span class="cn">FALSE</span>, <span class="at">method=</span><span class="st">"pc"</span>, <span class="at">n =</span> <span class="fu">ncol</span>(job_skills))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Very Simple Structure
Call: vss(x = x, n = n, rotate = rotate, diagonal = diagonal, fm = fm, 
    n.obs = n.obs, plot = plot, title = title, use = use, cor = cor, 
    method = "pc")
VSS complexity 1 achieves a maximimum of 0.95  with  3  factors
VSS complexity 2 achieves a maximimum of 0.98  with  3  factors

The Velicer MAP achieves a minimum of 0.12  with  2  factors 
BIC achieves a minimum of  -24.1  with  1  factors
Sample Size adjusted BIC achieves a minimum of  -2.87  with  2  factors

Statistics by number of factors 
  vss1 vss2  map dof   chisq prob sqresid  fit RMSEA BIC SABIC complex  eChisq
1 0.89 0.00 0.17   9 1.1e+01 0.27   2.046 0.89 0.065 -24   4.1     1.0 1.1e+01
2 0.92 0.96 0.12   4 2.3e-01 0.99   0.802 0.96 0.000 -15  -2.9     1.1 1.5e-03
3 0.95 0.98 0.29   0 1.5e-01   NA   0.044 1.00    NA  NA    NA     1.1 1.8e-04
4 0.92 0.96 0.50  -3 9.2e-07   NA   0.777 0.96    NA  NA    NA     1.1 1.6e-09
5 0.92 0.96 1.00  -5 5.1e-11   NA   0.788 0.96    NA  NA    NA     1.1 1.5e-13
6 0.92 0.96   NA  -6 5.0e-11   NA   0.788 0.96    NA  NA    NA     1.1 1.5e-13
     SRMR  eCRMS eBIC
1 8.5e-02 0.1096  -24
2 1.0e-03 0.0019  -16
3 3.5e-04     NA   NA
4 1.0e-06     NA   NA
5 9.8e-09     NA   NA
6 9.8e-09     NA   NA</code></pre>
</div>
</div>
<p>According to the MAP criterion we should keep 2 principal components.</p>
</div>
<p class="solution-end">
</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Parallel analysis
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Parallel analysis involves simulating lots of datasets of the same dimension but in which the variables are uncorrelated. For each of these simulations, a PCA is conducted on its correlation matrix, and the eigenvalues are extracted. We can then compare our eigenvalues from the PCA on our <em>actual</em> data to the average eigenvalues across these simulations. In theory, for uncorrelated variables, no components should explain more variance than any others, and eigenvalues should be equal to 1. In reality, variables are rarely truly uncorrelated, and so there will be slight variation in the magnitude of eigenvalues simply due to chance. The parallel analysis method suggests keeping those components for which the eigenvalues are greater than those from the simulations.</p>
<p>It can be conducted in R using:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.parallel</span>(job_skills, <span class="at">fa=</span><span class="st">"pc"</span>, <span class="at">n.iter =</span> <span class="dv">500</span>)</span></code></pre></div>
</div>
<p><strong>NOTE: Parallel analysis will sometimes tend to over-extract (suggest too many components)</strong></p>
</div>
</div>
</div>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>How many components should we keep according to parallel analysis?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-10" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')">
Solution
</button>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.parallel</span>(job_skills, <span class="at">fa=</span><span class="st">"pc"</span>, <span class="at">n.iter =</span> <span class="dv">500</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_pca_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  NA  and the number of components =  1 </code></pre>
</div>
</div>
<p>Parallel analysis suggests to keep 1 principal component only as there is only one PC with an eigenvalue higher than the simulated random ones in red.</p>
</div>
<p class="solution-end">
</p>
</section>
<section id="retaining-n-components" class="level2">
<h2 class="anchored" data-anchor-id="retaining-n-components">6. Retaining N Components</h2>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Based on the set of criteria above, make a decision on how many components you will keep.</p>
<p>Sometimes, there may also be pragmatic reasons for keeping a certain number (e.g.&nbsp;if you want specifically 1 dimension, you may be willing to accept a lower proportion of explained variance).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-11" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')">
Solution
</button>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>It’s a common thing to see disagreement between the methods to determine how many components we keep, and ultimately this is a decision that we as researchers have to make and explain.</p>
<table class="table">
<thead>
<tr class="header">
<th>method</th>
<th>recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>explaining &gt;80% variance</td>
<td>keep 2 components</td>
</tr>
<tr class="even">
<td>kaiser’s rule</td>
<td>keep 2 components</td>
</tr>
<tr class="odd">
<td>scree plot</td>
<td>keep 3 components? (subjective)</td>
</tr>
<tr class="even">
<td>MAP</td>
<td>keep 2 components</td>
</tr>
<tr class="odd">
<td>parallel analysis</td>
<td>keep 1 component</td>
</tr>
</tbody>
</table>
<p>Because three out of the five selection criteria above suggest to keep 2 principal components, here we will keep 2 components. This solution explains a reasonable proportion of the variance (88%), and it would be perfectly defensible to instead go for 3, explaining 98%</p>
</div>
<p class="solution-end">
</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Examining loadings
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Let’s have a look at the selected principal components:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>job_pca<span class="sc">$</span>loadings[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             PC1     PC2
commun     0.984 -0.1197
probl_solv 0.223  0.8095
logical    0.329  0.7466
learn      0.987 -0.1097
physical   0.988 -0.0784
appearance 0.979 -0.1253</code></pre>
</div>
</div>
<p>and at their corresponding proportion of total variance explained:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>job_pca<span class="sc">$</span>values <span class="sc">/</span> <span class="fu">sum</span>(job_pca<span class="sc">$</span>values)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.67253 0.21016 0.10510 0.00577 0.00372 0.00273</code></pre>
</div>
</div>
<p>We see that the first PC accounts for 67.3% of the total variability. All loadings seem to have the same magnitude apart from <code>probl_solv</code> and <code>logical</code> which are closer to zero. The first component looks like a sort of average of the officers performance scores excluding problem solving and logical ability.</p>
<p>The second principal component, which explains only 21% of the total variance, has two loadings clearly distant from zero: the ones associated to problem solving and logical ability. It distinguishes police officers with strong logical and problem solving skills and low scores on other skills (note the negative magnitudes).</p>
<p>We have just seen how to interpret the first components by looking at the magnitude and sign of the coefficients for each measured variable.</p>
<div class="rtip">
<p>For interpretation purposes, it might help hiding very small loadings. This can be done by specifying the cutoff value in the <code>print()</code> function. However, this only works when you pass the loadings for <strong>all</strong> the PCs:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(job_pca<span class="sc">$</span>loadings, <span class="at">cutoff =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
           PC1    PC2   
commun      0.984       
probl_solv         0.810
logical     0.329  0.747
learn       0.987       
physical    0.988       
appearance  0.979       

                 PC1   PC2
SS loadings    4.035 1.261
Proportion Var 0.673 0.210
Cumulative Var 0.673 0.883</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional: How well are the units represented in the reduced space?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We now focus our attention on the following question: Are all the statistical units (police officers) well represented in the 2D plot?</p>
<p>The 2D representation of the original data, which comprise 6 measured variables, is an approximation and henceforth it may happen that not all units are well represented in this new space.</p>
<p>Typically, it is good to assess the approximation for each statistical unit by inspecting the scores on the discarded principal components. If a unit has a high score on those components, then this is a sign that the unit might be highly misplaced in the new space and misrepresented.</p>
<p>Consider the 3D example below. There are three cases (= units or individuals). In the original space they are all very different from each other. For example, cases 1 and 2 are very different in their x and y values, but very similar in their z value. Cases 2 and 3 are very similar in their x and y values but very different in their z value. Cases 1 and 3 have very different values for all three variables x, y, and z.</p>
<p>However, when represented in the 2D space given by the two principal components, units 2 and 3 seems like they are very similar when, in fact, they were very different in the original space which also accounted for the z variable.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/pcaefa/pca_bad_representation.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We typically measure how badly a unit is represented in the new coordinate system by considering the <strong>sum of squared scores on the discarded principal components:</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>scores_discarded <span class="ot">&lt;-</span> job_pca<span class="sc">$</span>scores[, <span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)]</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>sum_sq <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(scores_discarded<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>sum_sq</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
[39] 0 0 0 0 0 0 0 0 0 0 0 0</code></pre>
</div>
</div>
<p>Units with a high score should be considered for further inspection as it may happen that they are represented as close to another unit when, in fact, they might be very different.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(sum_sq)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_pca_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>There seem to be only five outliers, and they are not too high compared to the rest of the scores. For this reason, we will consider the 2D representation of the data to be satisfactory.</p>
</div>
</div>
</div>
</section>
<section id="using-pca-scores" class="level2">
<h2 class="anchored" data-anchor-id="using-pca-scores">7. Using PCA scores</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
PCA scores
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Now that we have decided to reduce our six variables down to two principal components, we can, for each of our observations, get their <em>scores</em> on each of our components.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>job_pca2 <span class="ot">&lt;-</span> <span class="fu">principal</span>(job_skills, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">covar =</span> <span class="cn">TRUE</span>, <span class="at">rotate =</span> <span class="st">'none'</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(job_pca2<span class="sc">$</span>scores)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       PC1    PC2
[1,] -6.10 -1.796
[2,] -4.69  4.164
[3,] -5.18 -0.131
[4,] -4.31 -1.758
[5,] -3.71  1.207
[6,] -3.88 -5.200</code></pre>
</div>
</div>
<p>PCA scores are essentially weighted combinations of an individuals responses to the items.<br>
<span class="math display">\[
\text{score}_{\text{component j}} = w_{1j}x_1 + w_{2j}x_2 + w_{3j}x_3 +\, ... \, + w_{pj}x_p
\]</span> Where <span class="math inline">\(w\)</span> are the weights, <span class="math inline">\(x\)</span> the variable scores.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Optional: How are weights calculated?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The weights are calculated from the eigenvectors as <span class="math display">\[
w_{ij} = \frac{a_{ij}}{\sqrt(\lambda_j)}
\]</span> where <span class="math inline">\(w_{ij}\)</span> is the weight for a given variable <span class="math inline">\(i\)</span> on component <span class="math inline">\(j\)</span> , <span class="math inline">\(a_{ij}\)</span> is the value from the eigenvector for item <span class="math inline">\(i\)</span> on component <span class="math inline">\(j\)</span> and <span class="math inline">\(\lambda_{j}\)</span> is the eigenvalue for that component.</p>
</div>
</div>
</div>
<p>In the literature, some authors also suggest to look at the correlation between the principal component scores and the measured variables:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First PC</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(job_pca2<span class="sc">$</span>scores[,<span class="dv">1</span>], job_skills)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     commun probl_solv logical learn physical appearance
[1,]  0.985      0.214   0.319 0.988    0.989      0.981</code></pre>
</div>
</div>
<p>The first PC is strongly correlated with all the measured variables except <code>probl_solv</code> and <code>logical</code>. As mentioned when looking at loadings, all these variables seem to contributed to the first PC.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Second PC</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(job_pca2<span class="sc">$</span>scores[,<span class="dv">2</span>], job_skills)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     commun probl_solv logical  learn physical appearance
[1,] -0.163      0.792   0.738 -0.154   -0.122     -0.169</code></pre>
</div>
</div>
<p>The second PC is strongly correlated with <code>probl_solv</code> and <code>logical</code>, and slightly negatively correlated with the remaining variables. This separates police officers with clear logical and problem solving skills and a low rating on other skills.</p>
<p>We can also visualise our observations (the police officers) in the reduced space given by the retained principal component scores.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">pc1 =</span> job_pca2<span class="sc">$</span>scores[, <span class="dv">1</span>],</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">pc2 =</span> job_pca2<span class="sc">$</span>scores[, <span class="dv">2</span>]) <span class="sc">%&gt;%</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(.,<span class="fu">aes</span>(<span class="at">x=</span>pc1,<span class="at">y=</span>pc2))<span class="sc">+</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09_pca_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>We have reduced our six variables down to two principal components, and we are now able to use the scores on each component in a subsequent analysis!</p>
<p>Join the principal component scores for your retained components to the original dataset which has the arrest rates in.</p>
<p>Then fit a linear model to look at how the arrest rate of police officers is predicted by the two components representing different composites of the skills ratings by HR.</p>
<p>Check for multicollinearity between your predictors.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-12" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')">
Solution
</button>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add the PCA scores to the dataset</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>job <span class="ot">&lt;-</span> </span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  job <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">pc1 =</span> job_pca2<span class="sc">$</span>scores[,<span class="dv">1</span>],</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">pc2 =</span> job_pca2<span class="sc">$</span>scores[,<span class="dv">2</span>]</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="co"># use the scores in an analysis</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(arrest_rate <span class="sc">~</span> pc1 <span class="sc">+</span> pc2, <span class="at">data =</span> job)</span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a><span class="co"># multicollinearity isn't a problem, because the components are orthogonal!! </span></span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(mod)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pc1 pc2 
  1   1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = arrest_rate ~ pc1 + pc2, data = job)

Residuals:
   Min     1Q Median     3Q    Max 
-0.385 -0.119 -0.016  0.160  0.384 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.51161    0.02943   17.38   &lt;2e-16 ***
pc1          0.03583    0.01089    3.29   0.0019 ** 
pc2         -0.00923    0.01210   -0.76   0.4490    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.208 on 47 degrees of freedom
Multiple R-squared:   0.2,  Adjusted R-squared:  0.166 
F-statistic: 5.86 on 2 and 47 DF,  p-value: 0.00532</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Even if we cut open someone’s brain, it’s unclear what we would be looking for in order to ‘measure’ it. It is unclear whether anxiety even exists as a physical thing, or rather if it is simply the overarching concept we apply to a set of behaviours and feelings<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2023 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>