<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - 11. EFA 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('jk-circle-right')) {
    f.classList.add('jk-circle-down')
    f.classList.remove('jk-circle-right')
} else {
    f.classList.add('jk-circle-right')
    f.classList.remove('jk-circle-down')
}
}
</script>

<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07_path1.html">Path Analysis and Data Reduction</a></li><li class="breadcrumb-item"><a href="./11_efa2.html">11. EFA 2</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DAPR3</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Multilevel Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_regressionrefresh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Regression Refresh | Clustered Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_intromlm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Intro to Multilevel Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_assumptcent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Assumptions and Diagnostics | Centering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_ranefglmer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Random Effect Structures | Logistic MLM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Recap &amp; Practice Datasets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b_lmmdatasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LMM Datasets</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Additional Docs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example_00_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis Example: Rpt &amp; Mixed ANOVA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lvp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Likelihood vs Probability</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">- Break Week -</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Path Analysis and Data Reduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_path1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Path Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_path2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Mediation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_efa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. EFA 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_efa2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">11. EFA 2</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Additional Docs</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explainer_pcavar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PCA and unequal variances</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#practical-issues-with-efa" id="toc-practical-issues-with-efa" class="nav-link active" data-scroll-target="#practical-issues-with-efa">Practical Issues with EFA</a></li>
  <li><a href="#replicability" id="toc-replicability" class="nav-link" data-scroll-target="#replicability">Replicability</a></li>
  <li><a href="#factor-scores" id="toc-factor-scores" class="nav-link" data-scroll-target="#factor-scores">Factor Scores</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">11. EFA 2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="lo">
<p><strong>Relevant packages</strong></p>
<ul>
<li>tidyverse</li>
<li>psych</li>
<li>GPArotation</li>
</ul>
</div>
<section id="practical-issues-with-efa" class="level1">
<h1>Practical Issues with EFA</h1>
<div class="frame">
<p><strong>Data: pgpets.csv</strong></p>
<p>A pet food company has conducted a questionnaire on the internet (<span class="math inline">\(n = 620\)</span>) to examine whether owning a pet influences low mood. They asked 16 questions on a Likert scale (1-7, detailed below) followed by a simple Yes/No question concerning whether the respondent owned a pet.<br>
There are lots of questions, and the researchers don’t really know much about the theory of mood disorders, but they think that they are likely picking up on multiple different types of “low mood”. They want to conduct a factor analysis to examine this, and then plan on investigating the group differences (pet owners vs not pet owners) on the factor scores.</p>
<p>The data is available at https://uoepsy.github.io/data/pgpets.csv</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">QuestionNumber</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Over the last 2 weeks, how much have you had/have you been...</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">item1</td>
<td style="text-align: left;">Little interest or pleasure in doing things?</td>
</tr>
<tr class="even">
<td style="text-align: left;">item2</td>
<td style="text-align: left;">Feeling down, depressed, or hopeless?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">item3</td>
<td style="text-align: left;">Trouble falling or staying asleep, or sleeping too much?</td>
</tr>
<tr class="even">
<td style="text-align: left;">item4</td>
<td style="text-align: left;">Feeling tired or having little energy?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">item5</td>
<td style="text-align: left;">Poor appetite or overeating?</td>
</tr>
<tr class="even">
<td style="text-align: left;">item6</td>
<td style="text-align: left;">Feeling bad about yourself - or that you are a failure or have let yourself or your family down?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">item7</td>
<td style="text-align: left;">Reading the newspaper or watching television?</td>
</tr>
<tr class="even">
<td style="text-align: left;">item8</td>
<td style="text-align: left;">Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">item9</td>
<td style="text-align: left;">A lack of motivation to do anything at all?</td>
</tr>
<tr class="even">
<td style="text-align: left;">item10</td>
<td style="text-align: left;">Feeling nervous, anxious or on edge?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">item11</td>
<td style="text-align: left;">Not being able to stop or control worrying?</td>
</tr>
<tr class="even">
<td style="text-align: left;">item12</td>
<td style="text-align: left;">Worrying too much about different things?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">item13</td>
<td style="text-align: left;">Trouble relaxing?</td>
</tr>
<tr class="even">
<td style="text-align: left;">item14</td>
<td style="text-align: left;">Being so restless that it is hard to sit still?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">item15</td>
<td style="text-align: left;">Becoming easily annoyed or irritable?</td>
</tr>
<tr class="even">
<td style="text-align: left;">item16</td>
<td style="text-align: left;">Feeling afraid as if something awful might happen?</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Read the data into R.<br>
Create a new object in R that contains a subset the data. It should include all variables except for the participant ID and the variable corresponding to whether or not they have a pet (we’re going to come back to these later on).<br>
In this new object, change the names of the columns to match the question number, rather than the question itself (see the data description above). This will be easier to work with.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Check the output of the code <code>paste0("item", 1:10)</code>. Consider this code in combination with another function: <code>names(data)</code>. How could you combine the two codes to assign the new names to the current variable names?</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-1" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')">
Solution
</button>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pgpets <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/pgpets.csv"</span>)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pgpets)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "little_interest_or_pleasure_in_doing_things"                                                                                                                          
 [2] "feeling_down_depressed_or_hopeless"                                                                                                                                   
 [3] "trouble_falling_or_staying_asleep_or_sleeping_too_much"                                                                                                               
 [4] "feeling_tired_or_having_little_energy"                                                                                                                                
 [5] "poor_appetite_or_overeating"                                                                                                                                          
 [6] "feeling_bad_about_yourself_or_that_you_are_a_failure_or_have_let_yourself_or_your_family_down"                                                                        
 [7] "trouble_concentrating_on_things_such_as_reading_the_newspaper_or_watching_television"                                                                                 
 [8] "moving_or_speaking_so_slowly_that_other_people_could_have_noticed_or_the_opposite_being_so_fidgety_or_restless_that_you_have_been_moving_around_a_lot_more_than_usual"
 [9] "a_lack_of_motivation_to_do_anything_at_all"                                                                                                                           
[10] "feeling_nervous_anxious_or_on_edge"                                                                                                                                   
[11] "not_being_able_to_stop_or_control_worrying"                                                                                                                           
[12] "worrying_too_much_about_different_things"                                                                                                                             
[13] "trouble_relaxing"                                                                                                                                                     
[14] "being_so_restless_that_it_is_hard_to_sit_still"                                                                                                                       
[15] "becoming_easily_annoyed_or_irritable"                                                                                                                                 
[16] "feeling_afraid_as_if_something_awful_might_happen"                                                                                                                    
[17] "do_you_own_a_pet"                                                                                                                                                     
[18] "ppt_id"                                                                                                                                                               </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> pgpets <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>ppt_id, <span class="sc">-</span>do_you_own_a_pet)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"item"</span>, <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(df))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 16
  item1 item2 item3 item4 item5 item6 item7 item8 item9 item10 item11 item12
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1     5     5     5     4     6     7     4     3     6      4      4      5
2     4     4     3     5     3     5     2     4     4      3      3      5
3     5     5     5     5     3     7     5     5     6      5      5      5
4     4     5     5     6     4     5     4     6     7      6      6      4
5     2     1     3     3     3     3     5     4     2      3      3      3
6     6     4     6     5     5     4     3     5     6      5      4      4
# ℹ 4 more variables: item13 &lt;dbl&gt;, item14 &lt;dbl&gt;, item15 &lt;dbl&gt;, item16 &lt;dbl&gt;</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Visualise the items (this might be the histograms of all marginal distributions, or a scatterplot matrix, or both).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The function <code>multi.hist()</code> from the <strong>psych</strong> package can be pretty useful if we’re just wanting the distributions. Things like <code>pairs.panels()</code> can get pretty chaotic when we have lots of variables, so you might need to use that on subsets.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-2" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')">
Solution
</button>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">multi.hist</span>(df)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The data have 6 variables, so we will create two plots each focusing on 8 at a time:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs.panels</span>(df[, <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>])</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs.panels</span>(df[, <span class="dv">9</span><span class="sc">:</span><span class="dv">16</span>])</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Compute the correlation matrix for the items, and assess the suitability for factor analysis, using the Bartlett test and the Kaiser-Meyer-Olkin factor adequacy.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Look back in last week’s lab to see how Bartlett &amp; KMO are conducted in R</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-3" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')">
Solution
</button>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>cordf <span class="ot">=</span> <span class="fu">cor</span>(df)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cortest.bartlett</span>(cordf, <span class="at">n =</span> <span class="fu">nrow</span>(df))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$chisq
[1] 3008

$p.value
[1] 0

$df
[1] 120</code></pre>
</div>
</div>
<div class="int">
<p>Bartlett’s test indicates that the correlation matrix is proportionally different from the identity matrix (<span class="math inline">\(\chi^2 (120) = 3008, p&lt;.001\)</span>), suggesting our correlations are significantly different from zero.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">KMO</span>(cordf)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kaiser-Meyer-Olkin factor adequacy
Call: KMO(r = cordf)
Overall MSA =  0.9
MSA for each item = 
 item1  item2  item3  item4  item5  item6  item7  item8  item9 item10 item11 
  0.90   0.91   0.93   0.90   0.92   0.89   0.40   0.92   0.88   0.91   0.90 
item12 item13 item14 item15 item16 
  0.92   0.94   0.88   0.90   0.91 </code></pre>
</div>
</div>
<div class="int">
<p>The KMO for individual items are mainly “meritorious” or “marvelous”. The only item that may need further investigation is item 7, having an “unacceptable” KMO. The overall measure of sampling adequacy is 0.90, which suggests we have suitable data to perform a factor analysis</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Determine how many factors you will extract.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>As always, there are lots of methods to help you decide, but the ultimate decision is yours.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-4" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')">
Solution
</button>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>Using parallel analysis:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.parallel</span>(df, <span class="at">fa =</span> <span class="st">'fa'</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  2  and the number of components =  NA </code></pre>
</div>
</div>
<p>Using Velicer’s Minimum Average Partial:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VSS</span>(df)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Very Simple Structure
Call: vss(x = x, n = n, rotate = rotate, diagonal = diagonal, fm = fm, 
    n.obs = n.obs, plot = plot, title = title, use = use, cor = cor)
VSS complexity 1 achieves a maximimum of 0.67  with  3  factors
VSS complexity 2 achieves a maximimum of 0.86  with  8  factors

The Velicer MAP achieves a minimum of 0.01  with  2  factors 
BIC achieves a minimum of  -477  with  2  factors
Sample Size adjusted BIC achieves a minimum of  -195  with  2  factors

Statistics by number of factors 
  vss1 vss2   map dof  chisq     prob sqresid  fit  RMSEA  BIC SABIC complex
1 0.66 0.00 0.035 104 1014.1 4.0e-149    12.1 0.66 0.1188  345   676     1.0
2 0.66 0.81 0.012  89   94.8  3.2e-01     6.8 0.81 0.0101 -477  -195     1.2
3 0.67 0.80 0.020  75   75.2  4.7e-01     6.5 0.82 0.0015 -407  -169     1.3
4 0.64 0.81 0.028  62   60.4  5.3e-01     5.9 0.83 0.0000 -338  -141     1.3
5 0.63 0.82 0.042  50   38.1  8.9e-01     5.2 0.85 0.0000 -283  -125     1.3
6 0.64 0.84 0.058  39   28.4  8.9e-01     4.4 0.88 0.0000 -222   -99     1.3
7 0.62 0.84 0.076  29   18.8  9.3e-01     4.0 0.89 0.0000 -168   -76     1.4
8 0.63 0.86 0.089  20    9.6  9.7e-01     3.7 0.89 0.0000 -119   -55     1.4
  eChisq   SRMR eCRMS eBIC
1 1880.5 0.1124 0.121 1212
2   73.0 0.0221 0.026 -499
3   55.9 0.0194 0.025 -426
4   40.9 0.0166 0.023 -358
5   25.1 0.0130 0.020 -296
6   16.1 0.0104 0.018 -235
7    9.2 0.0078 0.016 -177
8    4.4 0.0054 0.013 -124</code></pre>
</div>
</div>
<div class="int">
<p>Both parallel analysis and Velicer’s Minimum Average Partial suggested retaining 2 factors.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Choosing an appropriate estimation method and rotation, perform a factor analysis to extract the desired number of factors (based on your answer to the previous question).</p>
<p>If you get an error, you may need to install the “GPArotation” package: <code>install.packages("GPArotation")</code>.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-5" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')">
Solution
</button>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>We probably shouldn’t use MLE as an estimation method here, because we’re going to be treating what looks like some sort of Likert data (ordinal, responses of 1-7) as if it is continuous.<br>
Let’s use <code>minres</code> here.</p>
<p>Finally, do we have any reason to think that the factors we are going to extract are orthogonal? Given what the questions look to be evaluating, it’s hard to see distinctly unrelated constructs within the 16 items.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>pgmod <span class="ot">&lt;-</span> <span class="fu">fa</span>(df, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">rotate =</span> <span class="st">"oblimin"</span>, <span class="at">fm =</span> <span class="st">"minres"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>pgmod</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Factor Analysis using method =  minres
Call: fa(r = df, nfactors = 2, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
         MR1   MR2     h2   u2 com
item1   0.45 -0.02 0.1947 0.81 1.0
item2   0.54 -0.05 0.2685 0.73 1.0
item3   0.50  0.44 0.6071 0.39 2.0
item4   0.75  0.04 0.5871 0.41 1.0
item5   0.44 -0.12 0.1678 0.83 1.1
item6   0.81 -0.02 0.6464 0.35 1.0
item7   0.01  0.03 0.0012 1.00 1.4
item8   0.57 -0.02 0.3112 0.69 1.0
item9   0.84 -0.03 0.6921 0.31 1.0
item10  0.01  0.68 0.4669 0.53 1.0
item11 -0.05  0.63 0.3778 0.62 1.0
item12  0.05  0.41 0.1887 0.81 1.0
item13  0.07  0.51 0.2933 0.71 1.0
item14 -0.03  0.77 0.5818 0.42 1.0
item15 -0.04  0.65 0.4033 0.60 1.0
item16  0.01  0.59 0.3579 0.64 1.0

                       MR1  MR2
SS loadings           3.23 2.92
Proportion Var        0.20 0.18
Cumulative Var        0.20 0.38
Proportion Explained  0.53 0.47
Cumulative Proportion 0.53 1.00

 With factor correlations of 
     MR1  MR2
MR1 1.00 0.39
MR2 0.39 1.00

Mean item complexity =  1.1
Test of the hypothesis that 2 factors are sufficient.

df null model =  120  with the objective function =  4.91 with Chi Square =  3008
df of  the model are 89  and the objective function was  0.16 

The root mean square of the residuals (RMSR) is  0.02 
The df corrected root mean square of the residuals is  0.03 

The harmonic n.obs is  620 with the empirical chi square  73  with prob &lt;  0.89 
The total n.obs was  620  with Likelihood Chi Square =  94.8  with prob &lt;  0.32 

Tucker Lewis Index of factoring reliability =  0.997
RMSEA index =  0.01  and the 90 % confidence intervals are  0 0.025
BIC =  -477
Fit based upon off diagonal values = 0.99
Measures of factor score adequacy             
                                                   MR1  MR2
Correlation of (regression) scores with factors   0.94 0.92
Multiple R square of scores with factors          0.88 0.85
Minimum correlation of possible factor scores     0.77 0.69</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
EFA output
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If we think about a factor analysis being a set of regressions (convention in factor analysis is to use <span class="math inline">\( {\lambda_{,}} \)</span> instead of <span class="math inline">\(\beta\)</span>), then we can think of a given item being the manifestation of some latent factors, plus a bit of randomness (or ‘stray causes’):</p>
<span class="math display">\[\begin{aligned}
\text{Item}_{1}   &amp;=  {\lambda_{1,1}}  \cdot  \text{Factor}_{1}  +  {\lambda_{2,1}}  \cdot  \text{Factor}_{2}  + u_{1} \\
\text{Item}_{2}   &amp;=  {\lambda_{1,2}}  \cdot  \text{Factor}_{1}  +  {\lambda_{2,2}}  \cdot  \text{Factor}_{2}  + u_{2} \\
&amp;\vdots \\
\text{Item}_{16}  &amp;=  {\lambda_{1,16}}  \cdot  \text{Factor}_{1}  +  {\lambda_{2,16}}  \cdot  \text{Factor}_{2}  + u_{16}
\end{aligned}\]</span>
<p>As you can see from the above, the 16 different items all stem from the same two factors (<span class="math inline">\( \text{Factor}_{1} ,  \text{Factor}_{2} \)</span>), plus some item-specific errors (<span class="math inline">\(u_{1}, \dots, u_{16}\)</span>). The <span class="math inline">\( {\lambda_{,}} \)</span> terms are called factor loadings, or loadings in short</p>
<p><strong>Communality</strong> is sum of the squared factor loadings for each item.</p>
<p>Intuitively, for each row, the two <span class="math inline">\( {\lambda_{,}} \)</span>s tell us how much each item depends on the two factors shared by the 16 items. The sum of the squared loadings tells us how much of one item’s information is due to the shared factors.</p>
<p>The communality is a bit like the <span class="math inline">\(R^2\)</span> (the proportion of variance of an item that is explained by the factor structure). And the standardised loadings are the proportion of variance in an item explained by each factor after accounting for other other factors.</p>
<p>The <strong>Uniqueness</strong> of each item is simply <span class="math inline">\(1 - \text{communality}\)</span>.<br>
This is the leftover bit; the variance in each item that is left unexplained by the latent factors (this could be specific variance, or it could be error variance. the one thing we know is, it’s not common variance).</p>
<p><em>Side note: this is what sets Factor Analysis apart from PCA, which is the linear combination of total variance (including error) in all our items. FA allows some of the variance to be shared by the underlying factors, and considers the remainder to be unique to the individual items (or, in another, error in how each item measures the construct).</em></p>
<p>The <strong>Complexity</strong> of an item corresponds to how well an item reflects a <em>single</em> underlying construct. Specifically, it is <span class="math inline">\({(\sum \lambda_i^2)^2}/{\sum \lambda_i^4}\)</span>, where <span class="math inline">\(\lambda_i\)</span> is the loading on to the <span class="math inline">\(i^{th}\)</span> factor. It will be equal to 1 for an item which loads <em>only</em> on one factor, and 2 if it loads evenly on to two factors, and so on.</p>
<div class="rtip">
<p>In R, we will often see these estimats under specific columns:</p>
<ul>
<li><strong>h2</strong> = item communality<br>
</li>
<li><strong>u</strong> = item uniqueness<br>
</li>
<li><strong>com</strong> = item complexity</li>
</ul>
</div>
</div>
</div>
</div>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Using <code>fa.sort()</code>, examine the loadings of each item onto the factors, along with communalities, uniqueness and complexity scores.</p>
<ul>
<li>Do all factors load on 3+ items at a salient level?</li>
<li>Do all items have at least one loading above a salient cut off?</li>
<li>Are there any Heywood cases (communalities or standardised loadings <span class="math inline">\(\geq1\)</span>)?</li>
<li>Should we perhaps remove some complex items?</li>
<li>Does the solution account for an acceptable level of variance?<br>
</li>
<li>Is the factor structure (items that load on to each factor) coherent, and does it make theoretical sense?</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-6" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')">
Solution
</button>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.sort</span>(pgmod)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Factor Analysis using method =  minres
Call: fa(r = df, nfactors = 2, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
         MR1   MR2     h2   u2 com
item9   0.84 -0.03 0.6921 0.31 1.0
item6   0.81 -0.02 0.6464 0.35 1.0
item4   0.75  0.04 0.5871 0.41 1.0
item8   0.57 -0.02 0.3112 0.69 1.0
item2   0.54 -0.05 0.2685 0.73 1.0
item3   0.50  0.44 0.6071 0.39 2.0
item1   0.45 -0.02 0.1947 0.81 1.0
item5   0.44 -0.12 0.1678 0.83 1.1
item14 -0.03  0.77 0.5818 0.42 1.0
item10  0.01  0.68 0.4669 0.53 1.0
item15 -0.04  0.65 0.4033 0.60 1.0
item11 -0.05  0.63 0.3778 0.62 1.0
item16  0.01  0.59 0.3579 0.64 1.0
item13  0.07  0.51 0.2933 0.71 1.0
item12  0.05  0.41 0.1887 0.81 1.0
item7   0.01  0.03 0.0012 1.00 1.4

                       MR1  MR2
SS loadings           3.23 2.92
Proportion Var        0.20 0.18
Cumulative Var        0.20 0.38
Proportion Explained  0.53 0.47
Cumulative Proportion 0.53 1.00

 With factor correlations of 
     MR1  MR2
MR1 1.00 0.39
MR2 0.39 1.00

Mean item complexity =  1.1
Test of the hypothesis that 2 factors are sufficient.

df null model =  120  with the objective function =  4.91 with Chi Square =  3008
df of  the model are 89  and the objective function was  0.16 

The root mean square of the residuals (RMSR) is  0.02 
The df corrected root mean square of the residuals is  0.03 

The harmonic n.obs is  620 with the empirical chi square  73  with prob &lt;  0.89 
The total n.obs was  620  with Likelihood Chi Square =  94.8  with prob &lt;  0.32 

Tucker Lewis Index of factoring reliability =  0.997
RMSEA index =  0.01  and the 90 % confidence intervals are  0 0.025
BIC =  -477
Fit based upon off diagonal values = 0.99
Measures of factor score adequacy             
                                                   MR1  MR2
Correlation of (regression) scores with factors   0.94 0.92
Multiple R square of scores with factors          0.88 0.85
Minimum correlation of possible factor scores     0.77 0.69</code></pre>
</div>
</div>
<ul>
<li>Both factors load on 3+ items at a salient level.</li>
<li>All except item7 has loadings <span class="math inline">\(&gt;0.3\)</span>.</li>
<li>There are no Heywood cases.</li>
<li>Item 3 loads quite highly on both factors (high complexity)</li>
<li>The solution explains 38% of the variance.<br>
</li>
<li>The coherence of the factor structure will require us to look back at the questions themselves. We’ll not do this right now, but do that later on.</li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>If you think any items should be removed, do so now, and perform the factor analysis once more.</p>
<p>Really, this starts the whole process again, so we’ll have to go through our steps to get to our new factor model on the reduced set of items.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-7" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')">
remove items
</button>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>We’re going to remove that problematic item 7 (which seems to be about “reading the newspaper and watching tv”), as well as item 3 (which seems to be about sleepiness, and relates to both factors quite highly).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>item7,<span class="sc">-</span>item3)</span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-8" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')">
assess factorability
</button>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>As before we removed items 3 and 7, these all look fine:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cortest.bartlett</span>(<span class="fu">cor</span>(df2), <span class="at">n =</span> <span class="fu">nrow</span>(df2))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$chisq
[1] 2516

$p.value
[1] 0

$df
[1] 91</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">KMO</span>(<span class="fu">cor</span>(df2))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kaiser-Meyer-Olkin factor adequacy
Call: KMO(r = cor(df2))
Overall MSA =  0.88
MSA for each item = 
 item1  item2  item4  item5  item6  item8  item9 item10 item11 item12 item13 
  0.90   0.92   0.88   0.91   0.87   0.91   0.85   0.89   0.89   0.91   0.92 
item14 item15 item16 
  0.86   0.89   0.90 </code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-9" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')">
how many factors?
</button>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p>Both parallel analysis and MAP suggest 2:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.parallel</span>(df2, <span class="at">fa =</span> <span class="st">'fa'</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  2  and the number of components =  NA </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VSS</span>(df2)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Very Simple Structure
Call: vss(x = x, n = n, rotate = rotate, diagonal = diagonal, fm = fm, 
    n.obs = n.obs, plot = plot, title = title, use = use, cor = cor)
VSS complexity 1 achieves a maximimum of 0.73  with  3  factors
VSS complexity 2 achieves a maximimum of 0.83  with  8  factors

The Velicer MAP achieves a minimum of 0.01  with  2  factors 
BIC achieves a minimum of  -342  with  2  factors
Sample Size adjusted BIC achieves a minimum of  -139  with  2  factors

Statistics by number of factors 
  vss1 vss2   map dof chisq     prob sqresid  fit RMSEA  BIC SABIC complex
1 0.62 0.00 0.046  77 983.7 2.8e-157    10.9 0.62 0.138  489   733     1.0
2 0.73 0.81 0.015  64  69.6  2.9e-01     5.6 0.81 0.012 -342  -139     1.1
3 0.73 0.80 0.024  52  51.3  5.0e-01     5.3 0.81 0.000 -283  -118     1.2
4 0.71 0.81 0.039  41  34.4  7.6e-01     4.7 0.84 0.000 -229   -99     1.2
5 0.67 0.81 0.056  31  21.9  8.9e-01     4.3 0.85 0.000 -177   -79     1.3
6 0.64 0.81 0.075  22  13.5  9.2e-01     3.9 0.86 0.000 -128   -58     1.3
7 0.71 0.82 0.100  14   4.9  9.9e-01     4.0 0.86 0.000  -85   -41     1.4
8 0.64 0.83 0.149   7   2.3  9.4e-01     3.4 0.88 0.000  -43   -20     1.5
   eChisq   SRMR eCRMS eBIC
1 1857.56 0.1283 0.139 1362
2   50.68 0.0212 0.025 -361
3   34.68 0.0175 0.023 -300
4   21.55 0.0138 0.021 -242
5   12.82 0.0107 0.018 -186
6    6.65 0.0077 0.016 -135
7    2.50 0.0047 0.012  -88
8    0.88 0.0028 0.010  -44</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-10" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')">
conduct and inspect EFA
</button>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>pgmod2 <span class="ot">&lt;-</span> <span class="fu">fa</span>(df2, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">rotate =</span> <span class="st">"oblimin"</span>, <span class="at">fm =</span> <span class="st">"minres"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>pgmod2<span class="sc">$</span>loadings</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
       MR1    MR2   
item1   0.438       
item2   0.531       
item4   0.743       
item5   0.431 -0.113
item6   0.806       
item8   0.564       
item9   0.837       
item10         0.676
item11         0.629
item12         0.408
item13         0.509
item14         0.766
item15         0.639
item16         0.593

                 MR1   MR2
SS loadings    2.894 2.644
Proportion Var 0.207 0.189
Cumulative Var 0.207 0.396</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.sort</span>(pgmod2)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Factor Analysis using method =  minres
Call: fa(r = df2, nfactors = 2, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
         MR1   MR2   h2   u2 com
item9   0.84 -0.01 0.70 0.30 1.0
item6   0.81  0.00 0.65 0.35 1.0
item4   0.74  0.06 0.59 0.41 1.0
item8   0.56 -0.01 0.31 0.69 1.0
item2   0.53 -0.03 0.27 0.73 1.0
item1   0.44 -0.02 0.19 0.81 1.0
item5   0.43 -0.11 0.16 0.84 1.1
item14 -0.02  0.77 0.58 0.42 1.0
item10  0.02  0.68 0.47 0.53 1.0
item15 -0.02  0.64 0.40 0.60 1.0
item11 -0.03  0.63 0.38 0.62 1.0
item16  0.03  0.59 0.36 0.64 1.0
item13  0.08  0.51 0.29 0.71 1.0
item12  0.06  0.41 0.19 0.81 1.0

                       MR1  MR2
SS loadings           2.89 2.64
Proportion Var        0.21 0.19
Cumulative Var        0.21 0.40
Proportion Explained  0.52 0.48
Cumulative Proportion 0.52 1.00

 With factor correlations of 
     MR1  MR2
MR1 1.00 0.35
MR2 0.35 1.00

Mean item complexity =  1
Test of the hypothesis that 2 factors are sufficient.

df null model =  91  with the objective function =  4.1 with Chi Square =  2516
df of  the model are 64  and the objective function was  0.11 

The root mean square of the residuals (RMSR) is  0.02 
The df corrected root mean square of the residuals is  0.03 

The harmonic n.obs is  620 with the empirical chi square  50.7  with prob &lt;  0.89 
The total n.obs was  620  with Likelihood Chi Square =  69.6  with prob &lt;  0.29 

Tucker Lewis Index of factoring reliability =  0.997
RMSEA index =  0.012  and the 90 % confidence intervals are  0 0.028
BIC =  -342
Fit based upon off diagonal values = 0.99
Measures of factor score adequacy             
                                                   MR1  MR2
Correlation of (regression) scores with factors   0.93 0.91
Multiple R square of scores with factors          0.87 0.83
Minimum correlation of possible factor scores     0.75 0.66</code></pre>
</div>
</div>
<ul>
<li>Both factors load on 3+ items at a salient level.</li>
<li>All items have a loading <span class="math inline">\(&gt;0.3\)</span>.</li>
<li>There are no Heywood cases.</li>
<li>No items have high loadings on multiple factors (complexity is low for all items)</li>
<li>The solution explains 40% of the variance.</li>
</ul>
<p>This looks much better!</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reliability
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<!-- parallel tests -->
<!-- test-retest reliability   -->
<!-- split-half reliability   -->
<!-- cronbach's alpha   -->
<!-- mcdonald's omega   -->
<!-- inter-rater reliability   -->
<!-- intra-class correlations!    -->
<!-- - link back to MLM   -->
<!-- attenuation for measurement error -->
<p><strong>Measurement Error &amp; Reliability</strong></p>
<p>You will often find research that foregoes the measurement model by taking a scale score (i.e., the sum or mean of a set of likert-type questions). For instance, think back to our exercises on path mediation, where “Health Locus of Control” was measured as the “average score on a set of items relating to perceived control over ones own health”. In doing so, we make the assumption that these variables provide measurements of the underlying latent construct <strong>without error</strong>.<br>
In fact, if we think about it a little, in our simple regression framework <span class="math inline">\(y = \beta_0 + \beta_1x_1 + ... + \beta_kx_k + \varepsilon\)</span> all our predictor variables <span class="math inline">\(x_1\)</span> to <span class="math inline">\(x_k\)</span> are assumed to be measured without error - it is only our outcome <span class="math inline">\(y\)</span> that our model considers to have some randomness included (the <span class="math inline">\(\varepsilon\)</span>). This seems less problematic if our variables are representing something that is quite easily and reliably measured (time, weight, height, age, etc.), but it seems inappropriate when we are concerned with something more abstract. For instance, two people both scoring 11 on the Generalised Anxiety Disorder 7 (GAD-7) scale does not necessarily mean that they have <em>identical</em> levels of anxiety.</p>
<p>The inconsistency with which an observed variable reflects the underlying construct that we consider it to be measuring is termed the <em>reliability</em>.</p>
<div class="frame">
<p><strong>Reliability: A silly example</strong></p>
<p>Suppose I’m trying to weigh <a href="https://photos.app.goo.gl/f26FrRDyJxTvXvGS9">my dog</a>. I have a set of scales, and I put him on the scales. He weighs in at 13.53kg. I immediately do it again, and the scales this time say 13.41kg. I do it again. 13.51kg, and again, 13.60kg. What is happening? Is Dougal’s weight (Dougal is the dog, by the way) randomly fluctuating by 100g? Or are my scales just a bit inconsistent, and my observations contain measurement error?</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>I take him to the vets, where they have a much better set of weighing scales, and I do the same thing (measure him 4 times). The weights are 13.47, 13.49, 13.48, 13.48.<br>
The scales at the vets are clearly <em>more <strong>reliable</strong></em>. We still don’t know Dougal’s <em>true</em> weight, but we are better informed to estimate it if we go on the measurements from the scales at the vet.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p>Another way to think about reliability is to consider the idea that more error means less reliability: <span class="math display">\[\text{observations = truth + error}\]</span></p>
<p>There are different types of reliability:</p>
<ul>
<li><strong>test re-test reliability:</strong> correlation between values over repeated measurements.</li>
<li><strong>alternate-form reliability:</strong> correlation between scores on different forms/versions of a test (we might want different versions to avoid practice effects).</li>
<li><strong>Inter-rater reliability:</strong> correlation between values obtained from different raters.</li>
<li><strong>split-half reliability:</strong> correlation between scores of two equally sized subsets of items.</li>
</ul>
<p>The form of reliability we are going to be most concerned with here is known as <strong>Internal Consistency</strong>. This is the extent to which items within a scale are correlated with one another. There are two main measures of this:</p>
<p><strong>Alpha &amp; Omega</strong></p>
<p><strong>Cronbach’s <span class="math inline">\(\alpha\)</span></strong> ranges from 0 to 1 (higher is better). You can get this using the <code>alpha()</code> function from the <strong>psych</strong> package. The formula is:</p>
<p><span class="math display">\[
\begin{aligned}
\text{Cronbach's } \alpha &amp;= \frac{n \cdot \overline{cov(ij)}}{\overline{\sigma^2_i} + (n-1) \cdot \overline{cov(ij)}}  \\
\\
\text{where}:  &amp; \qquad
&amp; n = \text{number of items} \\
&amp; \overline{cov(ij)} = \text{average covariance between item-pairs}  \\
&amp; \overline{\sigma^2_i} = \text{average item variance}  \\
\end{aligned}
\]</span></p>
<p><strong>McDonald’s Omega (<span class="math inline">\(\omega\)</span>)</strong> is substantially more complicated, but avoids the limitation that Cronbach’s alpha which assumes that all items are equally related to the construct. You can get it using the <code>omega()</code> function from the <strong>psych</strong> package. If you want more info about it then the help docs (<code>?omega()</code>) are a good place to start.</p>
</div>
</div>
</div>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Using the relevant function, obtain alpha for the set of items in each factor from your final factor analysis model of low mood.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-11" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')">
Solution
</button>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>The first factor has high loadings for items 1 to 9 (we have excluded 3 and 7).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df2)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "item1"  "item2"  "item4"  "item5"  "item6"  "item8"  "item9"  "item10"
 [9] "item11" "item12" "item13" "item14" "item15" "item16"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">alpha</span>(<span class="fu">select</span>(df2, item1<span class="sc">:</span>item9))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: alpha(x = select(df2, item1:item9))

  raw_alpha std.alpha G6(smc) average_r S/N  ase mean   sd median_r
      0.82      0.81     0.8      0.37 4.2 0.01    4 0.98     0.35

    95% confidence boundaries 
         lower alpha upper
Feldt     0.79  0.82  0.84
Duhachek  0.80  0.82  0.84

 Reliability if an item is dropped:
      raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
item1      0.82      0.81    0.80      0.41 4.2    0.010 0.022  0.43
item2      0.81      0.79    0.78      0.39 3.9    0.011 0.024  0.35
item4      0.77      0.76    0.75      0.35 3.2    0.013 0.016  0.31
item5      0.82      0.81    0.80      0.42 4.3    0.010 0.020  0.43
item6      0.76      0.75    0.74      0.34 3.0    0.013 0.015  0.30
item8      0.80      0.79    0.78      0.38 3.8    0.011 0.023  0.35
item9      0.76      0.75    0.73      0.33 3.0    0.014 0.014  0.30

 Item statistics 
        n raw.r std.r r.cor r.drop mean  sd
item1 620  0.54  0.57  0.44   0.40  4.0 1.1
item2 620  0.61  0.63  0.52   0.48  4.0 1.2
item4 620  0.79  0.77  0.75   0.68  4.0 1.5
item5 620  0.50  0.54  0.40   0.36  4.0 1.1
item6 620  0.83  0.80  0.79   0.72  4.1 1.7
item8 620  0.64  0.65  0.56   0.51  4.0 1.2
item9 620  0.85  0.82  0.82   0.74  3.9 1.8

Non missing response frequency for each item
         1    2    3    4    5    6    7 miss
item1 0.01 0.07 0.26 0.33 0.23 0.08 0.01    0
item2 0.02 0.09 0.22 0.34 0.23 0.09 0.02    0
item4 0.06 0.10 0.20 0.28 0.20 0.11 0.06    0
item5 0.01 0.07 0.24 0.36 0.24 0.06 0.01    0
item6 0.07 0.12 0.17 0.22 0.21 0.13 0.08    0
item8 0.02 0.09 0.23 0.30 0.27 0.07 0.02    0
item9 0.13 0.12 0.15 0.20 0.17 0.14 0.10    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">alpha</span>(<span class="fu">select</span>(df2, item10<span class="sc">:</span>item16))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: alpha(x = select(df2, item10:item16))

  raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
      0.81       0.8    0.78      0.37 4.1 0.012    4 0.89     0.37

    95% confidence boundaries 
         lower alpha upper
Feldt     0.78  0.81  0.83
Duhachek  0.78  0.81  0.83

 Reliability if an item is dropped:
       raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
item10      0.77      0.77    0.74      0.35 3.3    0.014 0.0072  0.35
item11      0.78      0.78    0.75      0.37 3.5    0.013 0.0085  0.37
item12      0.81      0.80    0.78      0.41 4.1    0.012 0.0035  0.41
item13      0.79      0.79    0.76      0.38 3.7    0.013 0.0077  0.41
item14      0.76      0.75    0.72      0.34 3.1    0.015 0.0045  0.35
item15      0.78      0.77    0.75      0.36 3.4    0.013 0.0072  0.35
item16      0.78      0.78    0.75      0.37 3.5    0.013 0.0077  0.37

 Item statistics 
         n raw.r std.r r.cor r.drop mean  sd
item10 620  0.74  0.73  0.67   0.61  4.0 1.4
item11 620  0.69  0.69  0.61   0.55  4.0 1.3
item12 620  0.54  0.56  0.43   0.38  4.0 1.2
item13 620  0.62  0.63  0.53   0.48  3.9 1.2
item14 620  0.79  0.77  0.74   0.66  3.9 1.5
item15 620  0.69  0.69  0.62   0.56  4.0 1.3
item16 620  0.67  0.67  0.60   0.54  4.0 1.2

Non missing response frequency for each item
          1    2    3    4    5    6    7 miss
item10 0.04 0.10 0.22 0.27 0.24 0.08 0.04    0
item11 0.04 0.08 0.19 0.33 0.24 0.10 0.03    0
item12 0.01 0.09 0.24 0.32 0.25 0.08 0.01    0
item13 0.03 0.08 0.25 0.35 0.19 0.10 0.01    0
item14 0.06 0.11 0.22 0.27 0.20 0.10 0.05    0
item15 0.03 0.10 0.24 0.31 0.20 0.10 0.03    0
item16 0.02 0.09 0.23 0.30 0.25 0.08 0.01    0</code></pre>
</div>
</div>
<div class="int">
<p>Cronbach’s <span class="math inline">\(\alpha\)</span> of 0.82 and 0.81 for the two factors and suggests high internal consistency.</p>
</div>
</div>
<p class="solution-end">
</p>
<!-- :::frame -->
<!-- You can't test the structural model if the measurement model is bad -->
<!-- if you test the relationships between a set of latent factors, and they are not reliably measured by the observed items, then this error propagates up to influence the fit of the model.   -->
<!-- To test the measurement model, it is typical to *saturate* the structural model (i.e., allow all the latent variables to correlate with one another). This way any misfit is due to the measurement model.   -->
<!-- ::: -->
<!-- what can we __do__ with this knowledge?   -->
<!-- attenuation due to measurement error -->
<p><br></p>
</section>
<section id="replicability" class="level1">
<h1>Replicability</h1>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Split the dataset in half, and assess the replicability of your factor structure of low mood by examining the factor congruence in scores on each subset of the data.</p>
<p><strong>Hint:</strong> see the lectures!</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-12" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')">
Solution
</button>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>set1 <span class="ot">&lt;-</span> df2 <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_frac</span>(.<span class="dv">5</span>) <span class="co"># randomly select one half</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>set2 <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(df2, set1) <span class="co"># select the non-matching cases</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>res1 <span class="ot">&lt;-</span> <span class="fu">fa</span>(set1, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">rotate =</span> <span class="st">"oblimin"</span>)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>res2 <span class="ot">&lt;-</span> <span class="fu">fa</span>(set2, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">rotate =</span> <span class="st">"oblimin"</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.congruence</span>(res1, res2) </span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     MR1  MR2
MR1 0.99 0.00
MR2 0.03 0.98</code></pre>
</div>
</div>
<p>We can see there is a high level of factor congruence across the two subsets of data.</p>
</div>
<p class="solution-end">
</p>
<p><br></p>
</section>
<section id="factor-scores" class="level1">
<h1>Factor Scores</h1>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Extract the factor scores for each factor of low-mood from your model, and attach them to original dataset (the one which has information on pet ownership).<br>
Then, conduct a <span class="math inline">\(t\)</span>-test to examine whether the pet-owners differ from non-pet-owners in their levels of each factor of low mood.</p>
<p>As a bonus, can you come up with some description of the two factors? you will have to look back to what the items represent (i.e.&nbsp;the questions that each item is asking.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
reminder of questions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="grsaezwtvq" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#grsaezwtvq table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#grsaezwtvq thead, #grsaezwtvq tbody, #grsaezwtvq tfoot, #grsaezwtvq tr, #grsaezwtvq td, #grsaezwtvq th {
  border-style: none;
}

#grsaezwtvq p {
  margin: 0;
  padding: 0;
}

#grsaezwtvq .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#grsaezwtvq .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#grsaezwtvq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#grsaezwtvq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#grsaezwtvq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#grsaezwtvq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#grsaezwtvq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#grsaezwtvq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#grsaezwtvq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#grsaezwtvq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#grsaezwtvq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#grsaezwtvq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#grsaezwtvq .gt_spanner_row {
  border-bottom-style: hidden;
}

#grsaezwtvq .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#grsaezwtvq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#grsaezwtvq .gt_from_md > :first-child {
  margin-top: 0;
}

#grsaezwtvq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#grsaezwtvq .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#grsaezwtvq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#grsaezwtvq .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#grsaezwtvq .gt_row_group_first td {
  border-top-width: 2px;
}

#grsaezwtvq .gt_row_group_first th {
  border-top-width: 2px;
}

#grsaezwtvq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#grsaezwtvq .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#grsaezwtvq .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#grsaezwtvq .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#grsaezwtvq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#grsaezwtvq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#grsaezwtvq .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#grsaezwtvq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#grsaezwtvq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#grsaezwtvq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#grsaezwtvq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#grsaezwtvq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#grsaezwtvq .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#grsaezwtvq .gt_left {
  text-align: left;
}

#grsaezwtvq .gt_center {
  text-align: center;
}

#grsaezwtvq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#grsaezwtvq .gt_font_normal {
  font-weight: normal;
}

#grsaezwtvq .gt_font_bold {
  font-weight: bold;
}

#grsaezwtvq .gt_font_italic {
  font-style: italic;
}

#grsaezwtvq .gt_super {
  font-size: 65%;
}

#grsaezwtvq .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#grsaezwtvq .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#grsaezwtvq .gt_indent_1 {
  text-indent: 5px;
}

#grsaezwtvq .gt_indent_2 {
  text-indent: 10px;
}

#grsaezwtvq .gt_indent_3 {
  text-indent: 15px;
}

#grsaezwtvq .gt_indent_4 {
  text-indent: 20px;
}

#grsaezwtvq .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="QuestionNumber">QuestionNumber</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Over the last 2 weeks, how much have you had/have you been...">Over the last 2 weeks, how much have you had/have you been...</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item1</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Little interest or pleasure in doing things?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item2</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Feeling down, depressed, or hopeless?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item3</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">~~Trouble falling or staying asleep, or sleeping too much?~~</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item4</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Feeling tired or having little energy?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item5</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Poor appetite or overeating?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item6</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Feeling bad about yourself - or that you are a failure or have let yourself or your family down?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item7</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">~~Reading the newspaper or watching television?~~</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item8</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item9</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">A lack of motivation to do anything at all?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item10</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Feeling nervous, anxious or on edge?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item11</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Not being able to stop or control worrying?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item12</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Worrying too much about different things?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item13</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Trouble relaxing?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item14</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Being so restless that it is hard to sit still?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item15</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Becoming easily annoyed or irritable?</td></tr>
    <tr><td headers="QuestionNumber" class="gt_row gt_left">item16</td>
<td headers="Over the last 2 weeks, how much have you had/have you been..." class="gt_row gt_left">Feeling afraid as if something awful might happen?</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-13" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')">
Solution
</button>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<p>It looks like all the items 1-9 (excluding items 3 and 7, which aren’t in our factor model in the end) are all about lower mood or lack of energy - i.e.&nbsp;‘depression’.<br>
The latter items that load onto the second factor (items 10-16) all seem related to ‘anxiety’.</p>
<p>So we can use the estimated factor scores as a representation of peoples’ relative standings on those underlying latent variables of ‘depression’ and ‘anxiety’, and we can then look at whether people who own a pet significantly differ on those two constructs from those who don’t own a pet!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>pgpets <span class="ot">&lt;-</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  pgpets <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">depression =</span> pgmod2<span class="sc">$</span>scores[,<span class="dv">1</span>],</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">anxiety =</span> pgmod2<span class="sc">$</span>scores[,<span class="dv">2</span>],</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">pet =</span> <span class="fu">factor</span>(do_you_own_a_pet)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pgpets<span class="sc">$</span>depression <span class="sc">~</span> pgpets<span class="sc">$</span>pet)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  pgpets$depression by pgpets$pet
t = 1, df = 600, p-value = 0.3
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.0691  0.2273
sample estimates:
mean in group 0 mean in group 1 
         0.0375         -0.0416 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pgpets, <span class="fu">aes</span>(<span class="at">x=</span>pet, <span class="at">y=</span>depression))<span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pgpets<span class="sc">$</span>anxiety<span class="sc">~</span>pgpets<span class="sc">$</span>pet)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  pgpets$anxiety by pgpets$pet
t = 4, df = 597, p-value = 0.00004
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 0.159 0.444
sample estimates:
mean in group 0 mean in group 1 
          0.143          -0.158 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pgpets, <span class="fu">aes</span>(<span class="at">x=</span>pet, <span class="at">y=</span>anxiety))<span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="11_efa2_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Of course this all assuming that the scales aren’t completely miscalibrated<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2023 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>