project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
  output-dir: ./wipdocs/

website:  
  title: "DAPR3 Flashcards"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - section: "Block 1: LMMs"
        contents:
            # week 1
          - block1/groupstruc.qmd
          - block1/dgp.qmd
            # week 2
          - block1/fixef.qmd
          - block1/ranef.qmd
          - block1/rdint.qmd
          - block1/rdslp.qmd  
          - block1/extracting.qmd
          - block1/plot-ranefs.qmd
          - block1/plot-fitted.qmd
            # week 3
          - block1/shrinkage.qmd
          - block1/pooling.qmd
          - block1/assump.qmd
            # week 4
          - block1/maxmodel.qmd
          - block1/simplify.qmd
          - block1/troubleshoot.qmd
            # week 5
          - block1/reporting.qmd
          - block1/pvals.qmd
      - section: "BLOCK 2 name"
        contents:
          - csstests.qmd


format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-readings.scss
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


