project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
  output-dir: ./wipdocs/

website:  
  title: "DAPR3 Flashcards"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "BLOCK 1 name"
        contents:
          - csstests.qmd
      - section: "BLOCK 2 name"
        contents:


format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-readings.scss
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


