project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
  output-dir: ./wipdocs/

website:  
  title: "DAPR3 Flashcards"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - index.qmd
      - section: "Block 1: LMMs"
        contents:
          - section: "Concepts"
            contents:
              # week 1
            - block1/groupstruc.qmd
            - block1/dgp.qmd
              # week 2
            - block1/rdint.qmd
            - block1/rdslp.qmd  
            - block1/ranef.qmd
            - block1/fixef.qmd
              # week 3
            - block1/assump.qmd
              # week 4
            - block1/maxmodel.qmd
              # week 5
            - block1/reporting.qmd
          - section: "Coding"
            contents:
              # week 1
            - block1/identify-group.qmd
              # week 2
            - block1/plot-group.qmd
            - block1/describe.qmd
              # week 3
            - block1/extract-ranefs.qmd
            - block1/plot-ranefs.qmd
            - block1/plot-fitted.qmd
            - block1/check-assump.qmd
              # week 4
            - block1/simplify.qmd
            - block1/troubleshoot.qmd
            - block1/pvals.qmd
      - section: "Block 2: TODO"
        contents:
          - csstests.qmd
      - section: "More resources"
        contents:
          - resources/workflow.qmd


format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-readings.scss
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


