---
title: "DAPR3 flash cards (2026/27)"
---

lorem ipsum


::: {.callout-caution collapse="false"}
#### Find extra content down rabbit holes!

If you want to dive deeper or work toward a more complete understanding of certain topics, we've added **"rabbit holes"** (like this one!) throughout the flash cards that you can head down.

**We will not assess any content introduced in the rabbit holes.
If you only want to know the basics, you can safely ignore them.**
But if you're interested in learning more (or if you find yourself doing more complex data analysis in your minidiss or diss in the future), you might like the extra information.
:::


::: {.callout-warning collapse="false"}
#### Trip hazards warn you about common mistakes

You'll also encounter **"trip hazards"** when we want to flag common mistakes, misconceptions, or other things that might go wrong.
But as long as you take care, you'll be absolutely fine.

:::




These flash cards have been developed by [Elizabeth Pankratz](https://edwebprofiles.ed.ac.uk/profile/elizabethpankratz) and [Josiah King](https://edwebprofiles.ed.ac.uk/profile/josiahking) (Josiah drew the cute icons!).
