<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 Lab Exercises - Week 2 Exercises: Introducing MLM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('jk-circle-right')) {
    f.classList.add('jk-circle-down')
    f.classList.remove('jk-circle-right')
} else {
    f.classList.add('jk-circle-right')
    f.classList.remove('jk-circle-down')
}
}
</script>
<link href="site_libs/panelset-0.3.0/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.3.0/panelset.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02ex.html">Week 2 Exercises: Introducing MLM</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DAPR3 Lab Exercises</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00prereq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prerequisites</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1 Exercises: Regression Refresher</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02ex.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Week 2 Exercises: Introducing MLM</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3 Exercises: Nested and Crossed Structures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4 Exercises: Centering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5 Exercises:</span></a>
  </div>
</li>
        <li class="sidebar-item">
 <span class="menu-text">- break week -</span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-toy-example" id="toc-a-toy-example" class="nav-link active" data-scroll-target="#a-toy-example">A Toy Example</a></li>
  <li><a href="#cross-sectional-new" id="toc-cross-sectional-new" class="nav-link" data-scroll-target="#cross-sectional-new">Cross Sectional: NEW</a></li>
  <li><a href="#repeated-measures-audio-interference-in-executive-functioning" id="toc-repeated-measures-audio-interference-in-executive-functioning" class="nav-link" data-scroll-target="#repeated-measures-audio-interference-in-executive-functioning">Repeated Measures: Audio Interference in Executive Functioning</a></li>
  <li><a href="#longitudinal-dominance-in-great-apes" id="toc-longitudinal-dominance-in-great-apes" class="nav-link" data-scroll-target="#longitudinal-dominance-in-great-apes">Longitudinal: Dominance in Great Apes</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 2 Exercises: Introducing MLM</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="a-toy-example" class="level1">
<h1>A Toy Example</h1>
<p>For our first foray into the multilevel model, we’re going to start with little toy example, and we’re just going to ask you to plot the predictions from a) a simple linear model, b) a model with a random intercept, and c) a model with random intercepts and slopes.</p>
<p>This is to build the understanding of the structure of multilevel models. When it comes to actually building models for research purposes, it is not necessary to slowly build up the complexity in this way.</p>
<div class="frame">
<p><strong>Data: New Toys!</strong></p>
<p>Recall the example from last semesters’ USMR course, where the lectures explored linear regression with a toy dataset of how practice influences the reading age of toy characters (see <a href="https://uoepsy.github.io/usmr/2324/lectures/lecture06.html#/learning-to-read-1" target="_blank">USMR Week 7 Lecture</a>). We’re going to now broaden our scope to the investigation of how practice affects reading age for <strong>all</strong> toys (not just Martin’s Playmobil characters).</p>
<p>You can find a dataset at <a href="https://uoepsy.github.io/data/toy2.csv" target="_blank">https://uoepsy.github.io/data/toy2.csv</a> containing information on 129 different toy characters that come from a selection of different families/types of toy. You can see the variables in the table below<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.<br>
<br></p>
<div class="columns">
<div class="column" style="width:45%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/toys.png" class="img-fluid figure-img" width="300"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:45%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="wpxshxfiar" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#wpxshxfiar table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#wpxshxfiar thead, #wpxshxfiar tbody, #wpxshxfiar tfoot, #wpxshxfiar tr, #wpxshxfiar td, #wpxshxfiar th {
  border-style: none;
}

#wpxshxfiar p {
  margin: 0;
  padding: 0;
}

#wpxshxfiar .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wpxshxfiar .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#wpxshxfiar .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wpxshxfiar .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wpxshxfiar .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wpxshxfiar .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wpxshxfiar .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wpxshxfiar .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wpxshxfiar .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wpxshxfiar .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wpxshxfiar .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wpxshxfiar .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wpxshxfiar .gt_spanner_row {
  border-bottom-style: hidden;
}

#wpxshxfiar .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#wpxshxfiar .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wpxshxfiar .gt_from_md > :first-child {
  margin-top: 0;
}

#wpxshxfiar .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wpxshxfiar .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wpxshxfiar .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#wpxshxfiar .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#wpxshxfiar .gt_row_group_first td {
  border-top-width: 2px;
}

#wpxshxfiar .gt_row_group_first th {
  border-top-width: 2px;
}

#wpxshxfiar .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wpxshxfiar .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#wpxshxfiar .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#wpxshxfiar .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wpxshxfiar .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wpxshxfiar .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wpxshxfiar .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#wpxshxfiar .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wpxshxfiar .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wpxshxfiar .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wpxshxfiar .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wpxshxfiar .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wpxshxfiar .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wpxshxfiar .gt_left {
  text-align: left;
}

#wpxshxfiar .gt_center {
  text-align: center;
}

#wpxshxfiar .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wpxshxfiar .gt_font_normal {
  font-weight: normal;
}

#wpxshxfiar .gt_font_bold {
  font-weight: bold;
}

#wpxshxfiar .gt_font_italic {
  font-style: italic;
}

#wpxshxfiar .gt_super {
  font-size: 65%;
}

#wpxshxfiar .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#wpxshxfiar .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#wpxshxfiar .gt_indent_1 {
  text-indent: 5px;
}

#wpxshxfiar .gt_indent_2 {
  text-indent: 10px;
}

#wpxshxfiar .gt_indent_3 {
  text-indent: 15px;
}

#wpxshxfiar .gt_indent_4 {
  text-indent: 20px;
}

#wpxshxfiar .gt_indent_5 {
  text-indent: 25px;
}

#wpxshxfiar .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#wpxshxfiar div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="variable">variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="description">description</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="variable" class="gt_row gt_left">toy_type</td>
<td headers="description" class="gt_row gt_left">Type of Toy</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">year</td>
<td headers="description" class="gt_row gt_left">Year Released</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">toy</td>
<td headers="description" class="gt_row gt_left">Character</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">hrs_week</td>
<td headers="description" class="gt_row gt_left">Hours of practice per week</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">R_AGE</td>
<td headers="description" class="gt_row gt_left">Reading Age</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Read in the data and plot the relationship between hours-per-week practice (<code>hrs_week</code>) and reading age (<code>R_AGE</code>).<br>
Facet the plot by the type of toy.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>“facet” is the key word here! See <a href="01a_clustered.html#visualisations" target="_blank">1A #visualisations</a></p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-1" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')">
Solution
</button>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>toy2 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/toy2.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(toy2)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  toy_type  year toy    hrs_week R_AGE
  &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;
1 Barbie    1959 Summer     4.04     8
2 Barbie    1959 Nikki      2.36     6
3 Barbie    1959 Barbie     4.02     8
4 Barbie    1959 Midge      4.97     8
5 Barbie    1959 Teresa     3.37     6
6 Barbie    1959 Ken        4.56     8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(toy2,<span class="fu">aes</span>(<span class="at">x=</span>hrs_week,<span class="at">y=</span>R_AGE))<span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>toy_type)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Below is the code to fit a simple linear model and produce some diagnostic plots.<br>
After running the code, do you think that we have violated any assumptions?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(R_AGE <span class="sc">~</span> hrs_week, <span class="at">data =</span> toy2)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod1)</span></code></pre></div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-2" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')">
Solution
</button>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p>We have violated an assumption here, and we don’t need to look at the plots to realise it! As it happens, the plots don’t actually look <em>terrible</em> (the scale-location plot is a bit meh, but other than that things look okay).</p>
<p>The assumption we have violated is that of <strong>independence</strong>. This is something we know through our understanding of the sampling procedure that has led to this data. We have got a random sample of different types of toys (e.g.&nbsp;power-rangers, toy-story, furbies etc), and within those types, we have a random sample of characters.</p>
<p>But it is entirely likely that the type of toy is going to influence their reading age (i.e.&nbsp;farm animals might read worse than playmobil, etc).</p>
<p>So this is something we can’t really “see” in the data - we have to <em>think</em>. What do we know about the data generating process? (i.e.&nbsp;the process that led to this data)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(R_AGE <span class="sc">~</span> hrs_week, <span class="at">data =</span> toy2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod1)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>There are lots of ways in R to get predicted values for a linear model (e.g.&nbsp;we saw <code>augment()</code> a lot in USMR).</p>
<p>The simplest way is to use functions like <code>predict()</code> or <code>fitted()</code> (they do the same thing), which gives us a vector of predicted values, which we can append to our dataframe (provided we don’t have missing data):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>predictedvalues <span class="ot">&lt;-</span> <span class="fu">predict</span>(model)</span></code></pre></div>
</div>
<p>Add the predictions from the linear model in the previous question to the facetted plot that you created in the earlier question. How well does the model fit each type of toy?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-3" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')">
1 - add predictions to data
</button>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>This only works because we don’t have missing data (and so the length of <code>predict(mod1)</code> is the same as <code>nrow(toy2)</code>, and the predictions are in the correct order)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add predictions to data:</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>toy2<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1)</span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-4" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')">
2 - add predictions to the plot
</button>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot both predictions and observations:</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>toy2 <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hrs_week))<span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>R_AGE)) <span class="sc">+</span> <span class="co"># observations</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred)) <span class="sc">+</span> <span class="co"># predictions</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>toy_type)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Load the <strong>lme4</strong> package, and fit a model with random intercepts for each toy type.</p>
<p>Using either <code>predict()</code> again, or this time you can use <code>augment()</code> from the <strong>broom.mixed</strong> package, plot the predicted values and the observations.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can see a model with a random intercept fitted in <a href="01b_lmm.html#fitting-multilevel-models-in-r" target="_blank">1B# fitting-multilevel-models-in-r</a>.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-5" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')">
Solution
</button>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>Here’s our model, with a random intercept by toy-type:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> toy_type), <span class="at">data =</span> toy2)</span></code></pre></div>
</div>
<p>We can use <code>augment()</code> from the <strong>broom.mixed</strong> package, and which gives us the variables in the model along with things like fitted values (in the <code>.fitted</code> column)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(mod2)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 129 × 14
  R_AGE hrs_week toy_type .fitted  .resid  .hat  .cooksd .fixed   .mu .offset
  &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1     8     4.04 Barbie      7.43  0.574  0.158 0.0144     7.14  7.43       0
2     6     2.36 Barbie      6.23 -0.229  0.183 0.00282    5.94  6.23       0
3     8     4.02 Barbie      7.41  0.587  0.158 0.0151     7.12  7.41       0
4     8     4.97 Barbie      8.09 -0.0855 0.170 0.000354   7.80  8.09       0
5     6     3.37 Barbie      6.95 -0.950  0.161 0.0404     6.66  6.95       0
# ℹ 124 more rows
# ℹ 4 more variables: .sqrtXwt &lt;dbl&gt;, .sqrtrwt &lt;dbl&gt;, .weights &lt;dbl&gt;,
#   .wtres &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(mod2) <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hrs_week))<span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>R_AGE)) <span class="sc">+</span> <span class="co"># observations</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>.fitted)) <span class="sc">+</span> <span class="co"># predictions</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>toy_type)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Note that the model predictions are now a lot better than they were for the single level linear model. The line has moved up for the “Scooby Doos”, and down for the “Farm Animals”, etc. But the lines are all still the same slope. The slope is “fixed”.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Now fit a model with random intercepts <em>and</em> slopes for each toy type.</p>
<p>As before, plot the predicted values of this model alongside the observations</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-6" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')">
Solution
</button>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week<span class="sc">|</span> toy_type), </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> toy2)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(mod3) <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hrs_week))<span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>R_AGE)) <span class="sc">+</span> <span class="co"># observations</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>.fitted)) <span class="sc">+</span> <span class="co"># predictions</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>toy_type)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>This looks even better - the lines are at good heights and good angles for each type of toy. Why? Because we have modelled the intercept (line height) and slope of <code>hrs_week</code> (line angle) as varying across types of toy!</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Finally, add a <code>geom_smooth</code> to the plot from the previous question (making sure that this is has <code>y=R_AGE</code>).<br>
This will add a separate linear model <code>lm()</code> line for each of the facets in the plot.</p>
<p>What differences (look closely!) do you notice between the predictions from the model with random intercepts and slopes, and the simple geom_smooths?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You could try changing <code>col</code>, <code>lty</code>, and <code>lwd</code> to make things easier to see.</p>
<p>What we’re doing here is showing to ourselves ‘partial pooling’ in action (<a href="01b_lmm.html#partial-pooling" target="_blank">1B #partial-pooling</a>).</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-7" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')">
1 - adding geom_smooths to the plot
</button>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>here’s the model we are using:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week<span class="sc">|</span> toy_type), </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> toy2)</span></code></pre></div>
</div>
<p>and here is our plot:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(mod3) <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hrs_week))<span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>R_AGE)) <span class="sc">+</span> <span class="co"># observations</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>.fitted)) <span class="sc">+</span> <span class="co"># predictions</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y=</span>R_AGE), <span class="at">method=</span>lm, <span class="at">se=</span>F) <span class="sc">+</span> <span class="co"># simple smooths</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>toy_type)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-8" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')">
2 - why?
</button>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>I’ve made it a bit clearer here by changing up the colours and linewidths (<code>lwd</code>), and subsetting to just a select few of the toy types:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(mod3) <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(toy_type <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Farm Animals"</span>,<span class="st">"Scooby Doo"</span>,<span class="st">"Sock Puppets"</span>,<span class="st">"Polly Pocket"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hrs_week))<span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>R_AGE), <span class="at">alpha=</span>.<span class="dv">2</span>) <span class="sc">+</span> <span class="co"># observations</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>.fitted), <span class="at">col=</span><span class="st">"orange"</span>, <span class="at">lwd=</span><span class="dv">1</span>) <span class="sc">+</span> <span class="co"># predictions</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y=</span>R_AGE), <span class="at">method=</span>lm, <span class="at">se=</span>F, <span class="at">lty=</span><span class="st">"dashed"</span>) <span class="sc">+</span> <span class="co"># simple smooths</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>toy_type)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>For most of the toy types things look pretty similar. However, for “Sock Puppets” (only has 3 data points) the model predicted slope is shrunk back towards the average. It is also possible to see this in the “Farm Animals” and “Scooby Doo” - the shrinkage is more noticeable on these because they are further away from the average.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Here is the model with the random intercepts (but not random slopes) that we fitted in an earlier question.</p>
<p>Below is the code that produces a plot of the fitted values:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A. Model Equation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>$$ <span class="math display">\[\begin{align}
\text{For Toy }j\text{ of Type }i &amp; \\
\text{Level 1 (Toy):}&amp; \\
\text{R\_AGE}_{ij} &amp;= b_{0i} + b_1 \cdot \text{hrs\_week}_{ij} + \epsilon_{ij} \\
\text{Level 2 (Type):}&amp; \\
b_{0i} &amp;= \gamma_{00} + \zeta_{0i} \\
\text{Where:}&amp; \\
\zeta_{0i} &amp;\sim N(0,\sigma_{0}) \\
\varepsilon &amp;\sim N(0,\sigma_{e}) \\
\end{align}\]</span></p>
<p>$$</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
B. Model output
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> toy_type), </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> toy2)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: R_AGE ~ 1 + hrs_week + (1 | toy_type)
   Data: toy2

REML criterion at convergence: 544.7

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.8809 -0.4687  0.0541  0.5579  3.3220 

Random effects:
 Groups   Name        Variance Std.Dev.
 toy_type (Intercept) 7.278    2.698   
 Residual             2.550    1.597   
Number of obs: 129, groups:  toy_type, 20

Fixed effects:
            Estimate Std. Error t value
(Intercept)   4.2594     0.9157   4.652
hrs_week      0.7118     0.1651   4.312

Correlation of Fixed Effects:
         (Intr)
hrs_week -0.736</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
C. Plot of fitted values
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(mod2) <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>hrs_week, <span class="at">col=</span>toy_type))<span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>R_AGE),<span class="at">alpha=</span>.<span class="dv">3</span>) <span class="sc">+</span> <span class="co"># observations</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>.fitted)) <span class="sc">+</span> <span class="co"># predictions </span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">fixef</span>(mod2)[<span class="dv">1</span>], </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> <span class="fu">fixef</span>(mod2)[<span class="dv">2</span>], <span class="at">lwd=</span><span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># fixed effect line</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">col=</span><span class="st">"none"</span>) <span class="sc">+</span> <span class="co"># remove legend</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">7</span>) <span class="co"># extent to x=0</span></span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Match the parameters from the model equation, as well as coefficients from model output, to the corresponding points on the plot of fitted values.</p>
<div class="columns">
<div class="column" style="width:20%;">
<p><strong>Model Equation</strong></p>
<ul>
<li><strong>A1:</strong> <span class="math inline">\(\sigma_{0}\)</span><br>
</li>
<li><strong>A2:</strong> <span class="math inline">\(\sigma_{\varepsilon}\)</span><br>
</li>
<li><strong>A3:</strong> <span class="math inline">\(\gamma_{00}\)</span><br>
</li>
<li><strong>A4:</strong> <span class="math inline">\(b_{1}\)</span></li>
</ul>
</div><div class="column" style="width:20%;">
<p><strong>Model Output</strong></p>
<ul>
<li><strong>B1:</strong> 0.7118<br>
</li>
<li><strong>B2:</strong> 2.698<br>
</li>
<li><strong>B3:</strong> 1.597<br>
</li>
<li><strong>B4:</strong> 4.2594</li>
</ul>
</div><div class="column" style="width:60%;">
<p><strong>Plot of fitted values</strong></p>
<ul>
<li><strong>C1:</strong> the standard deviation of the distances from all the individual toy types lines to the black line<br>
</li>
<li><strong>C2:</strong> where the black line cuts the y axis<br>
</li>
<li><strong>C3:</strong> the slope of the black line<br>
</li>
<li><strong>C4:</strong> the standard deviation of the distances from all the individual observations to the line for the toy type to which it belongs.</li>
</ul>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-9" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')">
Solution
</button>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<ul>
<li>A1 = B2 = C1</li>
<li>A2 = B3 = C4</li>
<li>A3 = B4 = C2</li>
<li>A4 = B1 = C3</li>
</ul>
</div>
<p class="solution-end">
</p>
</section>
<section id="cross-sectional-new" class="level1">
<h1>Cross Sectional: NEW</h1>
<p>employee / department example</p>
<p>q1 = give code to fit fe, ri, rs models and add them to the plot run it one by one and see how the plot changes</p>
<p>q2 = mapping question</p>
<br>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="repeated-measures-audio-interference-in-executive-functioning" class="level1">
<h1>Repeated Measures: Audio Interference in Executive Functioning</h1>
<div class="frame">
<p><strong>Data: Audio interference in executive functioning</strong></p>
<p>This data is from a simulated study that aims to investigate the following research question:</p>
<blockquote class="blockquote">
<p>How do different types of audio interfere with executive functioning, and does this interference differ depending upon whether or not noise-cancelling headphones are used?</p>
</blockquote>
<p>30 healthy volunteers each completed the Symbol Digit Modalities Test (SDMT) - a commonly used test to assess processing speed and motor speed - a total of 15 times. During the tests, participants listened to either no audio (5 tests), white noise (5 tests) or classical music (5 tests). Half the participants listened via active-noise-cancelling headphones, and the other half listened via speakers in the room. Unfortunately, lots of the tests were not administered correctly, and so not every participant has the full 15 trials worth of data.</p>
<p>The data is available at <a href="https://uoepsy.github.io/data/efsdmt.csv">https://uoepsy.github.io/data/efsdmt.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="fptnpbqagc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#fptnpbqagc table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#fptnpbqagc thead, #fptnpbqagc tbody, #fptnpbqagc tfoot, #fptnpbqagc tr, #fptnpbqagc td, #fptnpbqagc th {
  border-style: none;
}

#fptnpbqagc p {
  margin: 0;
  padding: 0;
}

#fptnpbqagc .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#fptnpbqagc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#fptnpbqagc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#fptnpbqagc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#fptnpbqagc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fptnpbqagc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fptnpbqagc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fptnpbqagc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#fptnpbqagc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#fptnpbqagc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#fptnpbqagc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#fptnpbqagc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#fptnpbqagc .gt_spanner_row {
  border-bottom-style: hidden;
}

#fptnpbqagc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#fptnpbqagc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#fptnpbqagc .gt_from_md > :first-child {
  margin-top: 0;
}

#fptnpbqagc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#fptnpbqagc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#fptnpbqagc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#fptnpbqagc .gt_row_group_first td {
  border-top-width: 2px;
}

#fptnpbqagc .gt_row_group_first th {
  border-top-width: 2px;
}

#fptnpbqagc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#fptnpbqagc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#fptnpbqagc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fptnpbqagc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#fptnpbqagc .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#fptnpbqagc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#fptnpbqagc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fptnpbqagc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fptnpbqagc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fptnpbqagc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fptnpbqagc .gt_left {
  text-align: left;
}

#fptnpbqagc .gt_center {
  text-align: center;
}

#fptnpbqagc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#fptnpbqagc .gt_font_normal {
  font-weight: normal;
}

#fptnpbqagc .gt_font_bold {
  font-weight: bold;
}

#fptnpbqagc .gt_font_italic {
  font-style: italic;
}

#fptnpbqagc .gt_super {
  font-size: 65%;
}

#fptnpbqagc .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#fptnpbqagc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#fptnpbqagc .gt_indent_1 {
  text-indent: 5px;
}

#fptnpbqagc .gt_indent_2 {
  text-indent: 10px;
}

#fptnpbqagc .gt_indent_3 {
  text-indent: 15px;
}

#fptnpbqagc .gt_indent_4 {
  text-indent: 20px;
}

#fptnpbqagc .gt_indent_5 {
  text-indent: 25px;
}

#fptnpbqagc .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#fptnpbqagc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="variable">variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="description">description</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="variable" class="gt_row gt_left">PID</td>
<td headers="description" class="gt_row gt_left">Participant ID</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">audio</td>
<td headers="description" class="gt_row gt_left">Audio heard during the test ('no_audio', 'white_noise','music')</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">headphones</td>
<td headers="description" class="gt_row gt_left">Whether the participant listened via speakers in the room or via noise cancelling headphones</td></tr>
    <tr><td headers="variable" class="gt_row gt_left">SDMT</td>
<td headers="description" class="gt_row gt_left">Symbol Digit Modalities Test (SDMT) score</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>How many participants are there in the data?<br>
How many have complete data (15 trials)?<br>
What is the average number of trials that participants completed? What is the minimum?<br>
Does every participant have <em>some</em> data for each type of audio?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Functions like <code>table()</code> and <code>count()</code> will likely be useful here.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-10" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')">
1 - read in the data
</button>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>efdat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/efsdmt.csv"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(efdat)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  PID    audio       headphones      SDMT
  &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 PPT_15 no_audio    speakers          37
2 PPT_22 no_audio    anc_headphones    55
3 PPT_21 no_audio    anc_headphones    40
4 PPT_20 no_audio    anc_headphones    36
5 PPT_20 no_audio    anc_headphones    30
6 PPT_05 white_noise speakers          30</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-11" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-11', 'sol-start-11')">
2 - how many ppts?
</button>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>For a quick “how many?”, functions like <code>n_distinct()</code> can be handy:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">n_distinct</span>(efdat<span class="sc">$</span>PID)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30</code></pre>
</div>
</div>
<p>Which is essentially the same as asking:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(efdat<span class="sc">$</span>PID) <span class="sc">|&gt;</span> <span class="fu">length</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-12" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')">
3 - how many observations per ppt?
</button>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<p>Here are the counts of trials for each participant.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>efdat <span class="sc">|&gt;</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(PID)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 2
  PID        n
  &lt;chr&gt;  &lt;int&gt;
1 PPT_01    13
2 PPT_02    12
3 PPT_03    10
4 PPT_04    10
5 PPT_05    10
# ℹ 25 more rows</code></pre>
</div>
</div>
<p>We can pass that to something like <code>summary()</code> to get a quick descriptive of the <code>n</code> column, and so we can see that no participant completed all 15 trials (max is 14). Everyone completed at least 10, and the median was 12.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>efdat <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(PID) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     PID                  n     
 Length:30          Min.   :10  
 Class :character   1st Qu.:11  
 Mode  :character   Median :12  
                    Mean   :12  
                    3rd Qu.:13  
                    Max.   :14  </code></pre>
</div>
</div>
<p>We could also do this easily with things like:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(efdat<span class="sc">$</span>PID) <span class="sc">|&gt;</span> <span class="fu">median</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-13" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-13', 'sol-start-13')">
4 - how many observations for each audio type per ppt?
</button>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<p>For this kind of thing I would typically default to using <code>table()</code> for smaller datasets, to see how many datapoints are in each combination of <code>PID</code> and <code>audio</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(efdat<span class="sc">$</span>PID, efdat<span class="sc">$</span>audio)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
         music no_audio white_noise
  PPT_01     4        5           4
  PPT_02     5        4           3
  PPT_03     3        2           5
  PPT_04     3        4           3
  PPT_05     5        2           3
  PPT_06     4        4           5
  PPT_07     4        3           4
  PPT_08     4        4           5
  PPT_09     5        4           5
  PPT_10     4        5           4
  PPT_11     4        4           4
  PPT_12     4        5           5
  PPT_13     4        4           3
  PPT_14     3        5           4
  PPT_15     4        5           4
  PPT_16     4        4           3
  PPT_17     5        4           5
  PPT_18     5        3           3
  PPT_19     3        5           3
  PPT_20     4        4           5
  PPT_21     3        5           4
  PPT_22     4        4           3
  PPT_23     3        3           4
  PPT_24     4        5           5
  PPT_25     4        4           5
  PPT_26     5        4           5
  PPT_27     5        2           4
  PPT_28     4        4           4
  PPT_29     4        4           4
  PPT_30     2        5           3</code></pre>
</div>
</div>
<p>From the above, we can see that everyone has data from <span class="math inline">\(\geq 2\)</span> trials for a given audio type.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(efdat<span class="sc">$</span>PID, efdat<span class="sc">$</span>audio) <span class="sc">|&gt;</span> <span class="fu">min</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
a tidyverse way:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When tables get too big, we can do the same thing with <code>count()</code>, but we need to make sure that we are working with factors, in order to summarise all possible combinations of groups (even empty ones)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>efdat <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PID =</span> <span class="fu">factor</span>(PID),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">audio =</span> <span class="fu">factor</span>(audio)) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the .drop=FALSE means "keep empty groups"</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(PID,audio,<span class="at">.drop=</span><span class="cn">FALSE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      PID             audio          n    
 PPT_01 : 3   music      :30   Min.   :2  
 PPT_02 : 3   no_audio   :30   1st Qu.:4  
 PPT_03 : 3   white_noise:30   Median :4  
 PPT_04 : 3                    Mean   :4  
 PPT_05 : 3                    3rd Qu.:5  
 PPT_06 : 3                    Max.   :5  
 (Other):72                               </code></pre>
</div>
</div>
<p>There are plenty of other ways (e.g., you could use combinations of <code>group_by()</code>, <code>summarise()</code>), so just pick one that makes sense to you.</p>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Consider the following questions about the study:</p>
<ul>
<li>What is our outcome of interest?<br>
</li>
<li>What variables are we seeking to investigate in terms of their impact on the outcome?<br>
</li>
<li>What are the units of observations?<br>
</li>
<li>Are the observations clustered/grouped? In what way?<br>
</li>
<li>What varies <em>within</em> these clusters?<br>
</li>
<li>What varies <em>between</em> these clusters?</li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-14" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-14', 'sol-start-14')">
Solution
</button>
</div>
<div id="sol-body-14" class="solution-body" style="display: none;">
<ul>
<li>What is our outcome of interest?
<ul>
<li><strong>SDMT scores</strong><br>
</li>
</ul></li>
<li>What variables are we seeking to investigate in terms of their impact on the outcome?
<ul>
<li><strong>audio type</strong> and the interaction <strong>audio type <span class="math inline">\(\times\)</span> wearing headphones</strong></li>
</ul></li>
<li>What are the units of observations?
<ul>
<li><strong>individual trials</strong><br>
</li>
</ul></li>
<li>What are the groups/clusters?
<ul>
<li><strong>participants</strong><br>
</li>
</ul></li>
<li>What varies <em>within</em> these clusters?
<ul>
<li><strong>the type of audio</strong><br>
</li>
</ul></li>
<li>What varies <em>between</em> these clusters?
<ul>
<li><strong>whether they listen via headphones or speakers</strong></li>
</ul></li>
</ul>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Calculate the ICC, using the <code>ICCbare()</code> function from the <strong>ICC</strong> package.</p>
<p>How much of the variation in SDMT scores is attributable to participant level differences?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>See <a href="01a_clustered.html#icc---quantifying-clustering-in-an-outcome-variable" target="_blank">1A #icc</a>, or look up the help documentation for <code>?ICCbare()</code>.</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-15" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-15', 'sol-start-15')">
Solution
</button>
</div>
<div id="sol-body-15" class="solution-body" style="display: none;">
<p>44% of the variance in SDMT scores is attributable to participant level differences.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ICC)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ICCbare</span>(<span class="at">x =</span> PID, <span class="at">y =</span> SDMT, <span class="at">data =</span> efdat)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4363587</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>The multilevel model that has only an intercept (and the grouping structure) specified is sometimes referred to as the “null model” (or “intercept only model”).<br>
Because there are no predictors in the fixed effects there is just a single value (the intercept). All of the variance in the outcome gets modelled in the random effects part, and is partitioned into either ‘variance between groups’ or ‘residual variance’. This means we can just use those estimates to calculate the ICC.</p>
<p>For our executive functioning study, fit the null model use the output to calculate the ICC.<br>
Compare it to the answer from the previous question (it should be pretty close!)</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/nullmod.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The formula for the ICC is:<br>
<span class="math display">\[
ICC = \frac{\sigma^2_{b}}{\sigma^2_{b} + \sigma^2_e} = \frac{\text{between-group variance}}{\text{between-group variance}+\text{within-group variance}}
\]</span></p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-16" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-16', 'sol-start-16')">
Solution
</button>
</div>
<div id="sol-body-16" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>nullmod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(SDMT <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> PID), <span class="at">data =</span> efdat)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nullmod)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: SDMT ~ 1 + (1 | PID)
   Data: efdat

REML criterion at convergence: 2664.6

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.58680 -0.68262  0.03241  0.65701  2.26736 

Random effects:
 Groups   Name        Variance Std.Dev.
 PID      (Intercept) 62.02    7.875   
 Residual             79.82    8.934   
Number of obs: 360, groups:  PID, 30

Fixed effects:
            Estimate Std. Error t value
(Intercept)   34.789      1.514   22.98</code></pre>
</div>
</div>
<p><span class="math inline">\(\frac{62.02}{62.02+79.82} = 0.44\)</span>, or 44% of the variance in SDMT scores is explained by participant differences.</p>
<p>This matches (closely enough) with the <code>ICCbare()</code> function from the previous question!</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>Make factors and set the reference levels of the <code>audio</code> and <code>headphones</code> variables to “no audio” and “speakers” respectively.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Can’t remember about setting factors and reference levels? Check back to USMR materials!</p>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-17" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-17', 'sol-start-17')">
Solution
</button>
</div>
<div id="sol-body-17" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>efdat <span class="ot">&lt;-</span> efdat <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">audio =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(audio), <span class="st">"no_audio"</span>),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">headphones =</span> <span class="fu">fct_relevel</span>(<span class="fu">factor</span>(headphones), <span class="st">"speakers"</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Fit a multilevel model to address the aims of the study (copied below)</p>
<blockquote class="blockquote">
<p>How do different types of audio interfere with executive functioning, and does this interference differ depending upon whether or not noise-cancelling headphones are used?</p>
</blockquote>
<p>Specifying the model may feel like a lot, but try splitting it into three parts:</p>
<p><span class="math display">\[
\text{lmer(}\overbrace{\text{outcome }\sim\text{ fixed effects}}^1\, + \, (1 + \underbrace{\text{slopes}}_3\, |\, \overbrace{\text{grouping structure}}^2 )
\]</span></p>
<ol type="1">
<li>Just like the <code>lm()</code>s we have used in USMR, think about what we want to <em>test</em>. This should provide the outcome and the structure of our fixed effects.<br>
</li>
<li>Think about how the observations are clustered/grouped. This should tell us how to specify the grouping structure in the random effects.<br>
</li>
<li>Think about which slopes (i.e.&nbsp;which terms in our fixed effects) could feasibly vary between the clusters. This provides you with what to put in as random slopes.</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-18" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-18', 'sol-start-18')">
1 - fixed effects
</button>
</div>
<div id="sol-body-18" class="solution-body" style="display: none;">
<p>The question<br>
&nbsp;&nbsp;&nbsp; “<em>How do different types of audio interfere with executive functioning</em>” means we are interested in the effects of audio type (<code>audio</code>) on executive functioning (<code>SDMT</code> scores), so we will want:</p>
<pre><code>lmer(SDMT ~ audio ...</code></pre>
<p>However, the research aim also asks<br>
&nbsp;&nbsp;&nbsp; “<em>… and does this interference differ depending upon whether or not noise-cancelling headphones are used?</em>”<br>
which suggests that we are interested in the interaction <code>SDMT ~ audio * headphones</code></p>
<pre><code>lmer(SDMT ~ audio * headphones + ...   </code></pre>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-19" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-19', 'sol-start-19')">
2 - hierarchical data structure
</button>
</div>
<div id="sol-body-19" class="solution-body" style="display: none;">
<p>There are lots of ways that our data is grouped.<br>
We have:</p>
<ul>
<li>3 different groups of audio type (no_audio, white_noise, music)</li>
<li>2 groups of listening condition (speakers, anc_headphones)</li>
<li>30 groups of participants (“PPT_01”, “PPT_02”, “PPT_03”, …)</li>
</ul>
<p>The effects of audio type and headphones are both things we actually want to <em>test</em> - these variables are in our fixed effects. The levels of audio and headphones are not just a random sample from a wider population of levels - they’re a specific set of things we want to compare SDMT scores between.</p>
<p>Compare this with the participants - we don’t care about if there is a difference in SDMT scores between e.g., “PPT_03” and “PPT_28”. The participants themselves are just a sample of people that we have taken from a wider population. This makes thinking of “by-participant random effects” a sensible approach - we model differences between participants as a normal distribution of deviations around some average:</p>
<pre><code>lmer(SDMT ~ audio * headphones + (1 + ... | PID)  </code></pre>
<p>The minimum that we can include is the random intercept. What <code>(1|PID)</code> specifies is that “participants vary in their SDMT scores”. This makes sense - we would expect some participants to have higher executive functioning (and so will tend to score high on the SDMT), and others to have lower functioning (and so tend to score lower).</p>
</div>
<p class="solution-end">
</p>
<div class="solution-begin">
<button id="sol-start-20" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-20', 'sol-start-20')">
3 - random slopes
</button>
</div>
<div id="sol-body-20" class="solution-body" style="display: none;">
<p>We can also include a random by-participant effect of <code>audio</code>.<br>
<code>audio|PID</code> specifies that the effect of audio type on SDMT varies by participant. This seems feasible - music might be very distracting (and interfere a lot with the test) for some participants, but have a negligible effect for others.</p>
<pre><code>lmer(SDMT ~ audio * headphones + 
              (1 + audio | PID), data = efdat)</code></pre>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why can’t we have <code>(headphones|PID)</code>?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Why can we fit <code>(1 + audio | PID)</code> but not <code>(1 + headphones | PID)</code>, or both <code>(1 + audio + headphones | PID)</code> or <code>(1 + audio * headphones | PID)</code>?</p>
<p>Remember that <code>y ~ ... + (x | g)</code> is saying “the slope of y~x varies by g”.<br>
Such a sentence only makes sense if each “the slope of y~x” is defined for every (or most) groups.</p>
<p>For the <code>headphones</code> predictor, every participant is <em>either</em> in the “speakers” condition <em>or</em> the “anc_headphones” condition.<br>
This means that “the effect of headphones on SDMT” <em>doesn’t exist</em> for any single participant! This means it makes no sense to try and think of the effect as ‘varying by participant’.</p>
<p>Compare this to the <code>audio</code> predictor, for the effect <em>does</em> exist for a single given participant, therefore it is possible to think of it as being different for different participants (e.g.&nbsp;PPT_30’s performance improves with white noise, but PPT_16’s performance does not).</p>
<p>The plots below may help to cement this idea:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-39-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 14
</div>
<div class="question-body">
<p>We now have a model, but we don’t have any p-values or confidence intervals or anything - i.e.&nbsp;we have no inferential criteria on which to draw conclusions. There are a whole load of different methods available for drawing inferences from multilevel models, which means it can be a bit of a never-ending rabbit hole. For now, we’ll just use the ‘quick and easy’ approach provided by the <strong>lmerTest</strong> package seen in the lectures.</p>
<p>Using the <strong>lmerTest</strong> package, re-fit your model, and you should now get some p-values!</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hints
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If you use <code>library(lmerTest)</code> to load the package, then <em>every single</em> model you fit will show p-values calculated with the Satterthwaite method.<br>
Personally, I would rather this is not the case, so I often opt to fit specific models with these p-values without ever loading the package:<br>
<code>modp &lt;- lmerTest::lmer(y ~ 1 + x + ....</code></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
optional: a model comparison
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If we want to go down the model comparison route, we just need to isolate the relevant part(s) of the model that we are interested in.</p>
<p>Remember, as we saw in USMR, model comparison is sometimes a useful way of testing a <em>set</em> of coefficients. For instance, in this example the interaction involves estimating <em>two</em> terms: <code>audiomusic:headphonesanc_headphones</code> and <code>audiowhite_noise:headphonesanc_headphones</code>.</p>
<p>To test the interaction as a whole, we can create a model without the interaction, and then compare it. The <code>SATmodcomp()</code> function from the <strong>pbkrtest</strong> package provides a way of conducting an F test with the same Satterthwaite method of approximating the degrees of freedom:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>sdmt_mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(SDMT <span class="sc">~</span> audio <span class="sc">*</span> headphones <span class="sc">+</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>              (<span class="dv">1</span> <span class="sc">+</span> audio <span class="sc">|</span> PID), <span class="at">data =</span> efdat)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>sdmt_res <span class="ot">&lt;-</span> <span class="fu">lmer</span>(SDMT <span class="sc">~</span> audio <span class="sc">+</span> headphones <span class="sc">+</span> </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                   (<span class="dv">1</span> <span class="sc">+</span> audio <span class="sc">|</span> PID), <span class="at">data =</span> efdat)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pbkrtest)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">SATmodcomp</span>(<span class="at">largeModel =</span> sdmt_mod, <span class="at">smallModel =</span> sdmt_res)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>large : SDMT ~ audio * headphones + (1 + audio | PID)
small (restriction matrix) : 
                             
 0 0 0 0 0.8936904 -0.4486841
 0 0 0 0 0.4486841  0.8936904
     statistic    ndf    ddf   p.value    
[1,]    11.051  2.000 26.909 0.0003136 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-21" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-21', 'sol-start-21')">
Solution
</button>
</div>
<div id="sol-body-21" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>sdmt_mod <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(SDMT <span class="sc">~</span> audio <span class="sc">*</span> headphones <span class="sc">+</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>              (<span class="dv">1</span> <span class="sc">+</span> audio <span class="sc">|</span> PID), <span class="at">data =</span> efdat)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sdmt_mod)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: SDMT ~ audio * headphones + (1 + audio | PID)
   Data: efdat

REML criterion at convergence: 2376.2

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.34520 -0.62861  0.05762  0.60807  2.21250 

Random effects:
 Groups   Name             Variance Std.Dev. Corr       
 PID      (Intercept)      51.17    7.153               
          audiomusic       13.69    3.700     0.03      
          audiowhite_noise 15.22    3.901    -0.25 -0.16
 Residual                  31.49    5.612               
Number of obs: 360, groups:  PID, 30

Fixed effects:
                                          Estimate Std. Error       df t value
(Intercept)                               33.25799    1.98897 28.22065  16.721
audiomusic                                -8.01731    1.41149 27.58766  -5.680
audiowhite_noise                          -0.03044    1.44502 26.32588  -0.021
headphonesanc_headphones                   6.85313    2.81170 28.19226   2.437
audiomusic:headphonesanc_headphones       -3.58748    2.00129 27.94011  -1.793
audiowhite_noise:headphonesanc_headphones  8.02458    2.04498 26.46166   3.924
                                          Pr(&gt;|t|)    
(Intercept)                               3.54e-16 ***
audiomusic                                4.58e-06 ***
audiowhite_noise                          0.983354    
headphonesanc_headphones                  0.021355 *  
audiomusic:headphonesanc_headphones       0.083875 .  
audiowhite_noise:headphonesanc_headphones 0.000556 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) audmsc adwht_ hdphn_ adms:_
audiomusic  -0.174                            
audiowht_ns -0.352  0.192                     
hdphnsnc_hd -0.707  0.123  0.249              
admsc:hdph_  0.123 -0.705 -0.135 -0.173       
adwht_ns:h_  0.249 -0.136 -0.707 -0.351  0.191</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 15
</div>
<div class="question-body">
<p>We’ve already seen in the example with the toys (above) that we can visualise the fitted values (model predictions) using things like <code>augment()</code> from the <strong>broom.mixed</strong> package. But these were plotting all the cluster-specific values (i.e.&nbsp;our random effects), and what we are really interested in are the estimates of (and uncertainty around) our fixed effects.</p>
<p>Using tools like the <strong>effects</strong> package can provide us with the values of the outcome across levels of a specific fixed predictor (holding other predictors at their mean).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-22" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-22', 'sol-start-22')">
Solution
</button>
</div>
<div id="sol-body-22" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">effect</span>(<span class="at">term =</span> <span class="st">"audio*headphones"</span>, <span class="at">mod =</span> sdmt_mod) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>audio,<span class="at">y=</span>fit,</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper,</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">col=</span>headphones))<span class="sc">+</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="at">size=</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">1</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02ex_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 16
</div>
<div class="question-body">
<p>Now we have some p-values and a plot, try to create a short write-up of the analysis and results.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<button id="sol-start-23" class="jk-circle-right solution-icon clickable" onclick="toggle_visibility('sol-body-23', 'sol-start-23')">
Solution
</button>
</div>
<div id="sol-body-23" class="solution-body" style="display: none;">
<div class="int">
<p>SDMT scores were modelled using linear mixed effects regression, with fixed effects of audio-type (no audio/white noise/music, treatment coded with no audio as the reference level), audio delivery (speakers/ANC-headphones, treatment coded with speakers as the reference level) and their interaction. Participant-level random intercepts and random slopes of audio-type were also included. The model was fitted using the <strong>lme4</strong> package in R, and estimated with restricted estimation maximum likelihood (REML). Denominator degrees of freedom for all tests were approximated using the Satterthwaite method.</p>
<p>Inclusion of the interaction between headphones and audio-type was found to improve model fit (<span class="math inline">\(F(2, 26.9) = 11.05, p &lt; .001\)</span>), suggesting that the interference of different types of audio on executive functioning is dependent upon whether the audio is presented through ANC-headphones or through speakers.<br>
Participants not wearing headphones and presented with no audio scored on average 33.26 on the SDMT. Listening to music via speakers was associated with lower scores (<span class="math inline">\(b = -8.02, t(27.59)=-5.68, p &lt;0.001\)</span>) compared to no audio. White noise played via speakers was not associated with a difference in performance on the SDMT compared to no audio.</p>
<p>Without any audio playing, wearing ANC-headphones was associated with higher SDMT scores compared to no headphones (<span class="math inline">\(b = 6.85, t(28.19)=2.44, p =0.021\)</span>). This difference between headphones and speakers was also evident when listening to white-noise (<span class="math inline">\(b = 8.02, t(26.46)=3.92, p &lt;0.001\)</span>). The apparent detrimental influence of music was not found to differ depending on whether headphones were worn (<span class="math inline">\(b = -3.59, p =0.084\)</span>).</p>
<p>These results suggest that while music appears to interfere with executive functioning (resulting in lower SDMT scores) regardless of whether it is heard through headphones or speakers, listening to white noise may actually improve executive functioning, but only when presented via headphones. Furthermore, there appears to be benefits for executive functioning from wearing ANC-headphones even when not-listening to audio, perhaps due to the noise cancellation. The pattern of findings are displayed in <a href="#fig-efplot">Figure&nbsp;1</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-efplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="02ex_files/figure-html/fig-efplot-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Interaction between the type (no audio/white noise/music) and the delivery (speakers/ANC headphones) on executive functioning task (SDMT)</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<br>
<div class="divider div-transparent div-dot">

</div>
</section>
<section id="longitudinal-dominance-in-great-apes" class="level1">
<h1>Longitudinal: Dominance in Great Apes</h1>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Image sources:<br>http://tophatsasquatch.com/2012-tmnt-classics-action-figures/<br>https://www.dezeen.com/2016/02/01/barbie-dolls-fashionista-collection-mattel-new-body-types/<br>https://www.wish.com/product/5da9bc544ab36314cfa7f70c<br>https://www.worldwideshoppingmall.co.uk/toys/jumbo-farm-animals.asp<br>https://www.overstock.com/Sports-Toys/NJ-Croce-Scooby-Doo-5pc.-Bendable-Figure-Set-with-Scooby-Doo-Shaggy-Daphne-Velma-and-Fred/28534567/product.html<br>https://tvtropes.org/pmwiki/pmwiki.php/Toys/Furby<br>https://www.fun.com/toy-story-4-figure-4-pack.html<br>https://www.johnlewis.com/lego-minifigures-71027-series-20-pack/p5079461<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© Copyright 2019-2024 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>