---
title: "3-level multilevel model equations"
code-fold: true
self-contained: true
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---

10 schools, 20 children in each school, each child completed observed 5 times throughout the year.  
interested in how level of routine (child routine questionnaire CRQ), family income, and amount of school funding influence the level of aggressive behaviour (aggressive behaviour scale ABS)

It varies in textbooks whether the specification of levels is $i$>$j$>$k$ or $i$<$j$<$k$.  
In complex multilevel equations, it becomes confusing, so either way, we need to be clear about what each index refers to. 

$$
\begin{align}
i &= \textrm{Schools}\\
j &= \textrm{Children}\\
k &= \textrm{observations}
\end{align}
$$

The outcome, aggressive behaviour score, occurs at the observation level $ABS_{ijk}$.  
Level of routine occurs at the observation level $CRQ_{ijk}$.  
Family income occurs at the child level $Fincome_{ij}$.  
School funding occurs at the school level $SFunding_i$.  

## a single level regression 
If we just ignore all of the clustering:
$$
ABS = \beta_0 + \beta_1(CRQ) + \beta_2(Fincome) + \beta_3(SFunding) + \varepsilon
$$

```
lm(ABS ~ CRQ + Fincome + SFunding)
```

## adding random intercepts by-school and by-children

$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0ij} + \beta_1(CRQ_{ijk}) + \beta_2(Fincome_{ijk}) + \beta_3(SFunding_ijk) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0ij} = \gamma_{00i} +\zeta_{0ij} \\
\textrm{Level 3:} & \\
&\gamma_{00i} = \pi_{000} + u_{00i}
\end{align}
$$
```
lmer(ABS ~ CRQ + Fincome + SFunding + (1 | School / Child))
```
Which is the same as:
```
lmer(ABS ~ CRQ + Fincome + SFunding + 
           (1 | School) +
           (1 | School:Child)
)
```

#### moving predictors to their relevant level:  

We can also move the relevant effects to the corresponding level at which they exist. 
While we're at it, we can change the symbol to match the other effects at each level:
$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0ij} + \beta_{1}(CRQ_{ijk}) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0ij} = \gamma_{00i} + \gamma_{010}(Fincome_{ij}) +\zeta_{0ij} \\
\textrm{Level 3:} & \\
&\gamma_{00i}= \pi_{000} + \pi_{001}(SFunding_i) + u_{00i}
\end{align}
$$
  
## adding random slopes of CRQ by child

$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0ij} + \beta_{1jk}(CRQ_{ijk}) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0ij} = \gamma_{00i} + \gamma_{010}(Fincome_{ij}) +\zeta_{0ij} \\
&\beta_{1ij} = \gamma_{100} +\zeta_{1ij} \\
\textrm{Level 3:} & \\
&\gamma_{00i}= \pi_{000} + \pi_{001}(SFunding_i) + u_{00i}
\end{align}
$$
```
lmer(ABS ~ CRQ + Fincome + SFunding + 
           (1 | School) +
           (1 + CRQ | School:Child)
)
```


## adding a random slope of CRQ by school

$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0ij} + \beta_{1ij}(CRQ_{ijk}) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0ij} = \gamma_{00i} + \gamma_{010}(Fincome_{ij}) +\zeta_{0ij} \\
&\beta_{1ij} = \gamma_{10i} +\zeta_{1ij} \\
\textrm{Level 3:} & \\
&\gamma_{00i}= \pi_{000} + \pi_{001}(SFunding_i) + u_{00i}\\
&\gamma_{10i} = \pi_{100} + u_{10i} 
\end{align}
$$
```
lmer(ABS ~ CRQ + Fincome + SFunding + 
           (1 + CRQ + Fincome | School) +
           (1 + CRQ | School:Child)
)
```

### adding a random slope of family income by school  

$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0ij} + \beta_{1ij}(CRQ_{ijk}) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0ij} = \gamma_{00i} + \gamma_{01i}(Fincome_{ij}) +\zeta_{0ij} \\
&\beta_{1ij} = \gamma_{10i} +\zeta_{1ij} \\
\textrm{Level 3:} & \\
&\gamma_{00i}= \pi_{000} + \pi_{001}(SFunding_i) + u_{00i}\\
&\gamma_{10i} = \pi_{100} + u_{10i} \\
& \gamma_{01i} = \pi_{010} + u_{01i}
\end{align}
$$


## collapsing to mixed equation  

$$
\begin{align}
ABS_{ijk}= &(\pi_{000} + u_{00i} + \zeta_{0ij}) + & \\
& (\pi_{100} + u_{10i} + \zeta_{1ij})(CRQ_{ijk}) + &\\
&(\pi_{010} + u_{01i})(Fincome_{ij}) + &\\
&\pi_{001}(SFunding_i) + &\\
& \varepsilon_{ijk}& \\
\end{align}
$$

