---
title: "DAPR3 2026/27 group report (Cranium Collective)"
author: "B000001, B000002, B000003, B000004, B000005"
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2:
    toc: false
---

<!-- VERY IMPORTANT:

(1) In the "title" line above, write your actual group name!

(2) In the "author" line above, write your actual exam numbers!

(3) Leave everything else in the header above the way it is.

(4) Before you change ANYTHING in this document, make sure you can knit it to PDF.
It's lots easier to troubleshoot now than minutes before the deadline. -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# load all your libraries here
library(tidyverse)
library(kableExtra)
```

# Results

<!-- Set the scene (so the reader knows what you're talking about). -->

[...]


<!-- Describe and show the sample data (so that the reader knows how generalisable your analysis might be). -->

[...]


<!-- Visualise and summarise data patterns that address the RQ (so the reader knows the basic pattern of what you found). -->

[...]

See Figure \@ref(fig:starwars-heights).

```{r starwars-heights, fig.cap = 'Relative heights of several Star Wars characters. Darth Vader is taller than everyone else.', fig.width = 6, fig.height = 2}
starwars |>
  head() |>
  ggplot(aes(x = height, y = name)) +
  geom_col() +
  labs(
    y = '',
    x = 'Height (in cm)'
  )
```

<!-- Introduce your statistical analysis (so the reader can interpret the numbers you will report). -->

[...]


<!-- Report the results of your analysis (so the reader knows exactly what you found). -->

[...]

See Table \@ref(tab:starwars-eyes).

```{r starwars-eyes}
starwars |>
  head() |>
  select(name, eye_color) |>
  kable(
    caption = "Eye colours of several Star Wars characters. In the knitted output, this table might not appear exactly where you put it in the Rmd file, and that's fine. Don't stress about where exactly it appears, as long as it appears somewhere.", 
    booktabs = T
  )
```

# (APPENDIX) Appendix {-}  
<!-- ^ this line is invisible in the PDF. It changes the section numbering to letters for the appendix -->

<!-- You can include as many appendices as you feel you need. -->
<!-- Appendices do not count toward your page total. -->

# Appendix: [...]

[...]

# Appendix: [...]

[...]

