<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - Assumptions, Diagnostics, and Random Effect Structures</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-left')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-left')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR3</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-multi-level-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Multi Level Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-multi-level-models">    
        <li>
    <a class="dropdown-item" href="./01_regressionrefresh.html">
 <span class="dropdown-text">1: Linear Regression | Clustered Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_intromlm.html">
 <span class="dropdown-text">2: Multilevel Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_assumptranef.html">
 <span class="dropdown-text">3: Assumptions, Diagnostics &amp; Random Effect Structures</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_centerglmer.html">
 <span class="dropdown-text">4: Centering in MLM | Logistic</span></a>
  </li>  
        <li class="dropdown-header">5: Recap</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dimension-reduction--sem" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dimension reduction &amp; SEM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dimension-reduction--sem">    
        <li class="dropdown-header">7: Path Analysis</li>
        <li class="dropdown-header">8: Path Mediation</li>
        <li class="dropdown-header">9: Dimension Reduction</li>
        <li class="dropdown-header">10: EFA: Part 1</li>
        <li class="dropdown-header">11: EFA: Part 2</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercises-assumptions-diagnostics" id="toc-exercises-assumptions-diagnostics" class="nav-link active" data-scroll-target="#exercises-assumptions-diagnostics">Exercises: Assumptions &amp; Diagnostics</a></li>
  <li><a href="#random-effect-structures" id="toc-random-effect-structures" class="nav-link" data-scroll-target="#random-effect-structures">Random Effect Structures</a></li>
  <li><a href="#convergence-issues-and-what-to-do" id="toc-convergence-issues-and-what-to-do" class="nav-link" data-scroll-target="#convergence-issues-and-what-to-do">Convergence Issues and What To Do</a>
  <ul class="collapse">
  <li><a href="#singular-fits" id="toc-singular-fits" class="nav-link" data-scroll-target="#singular-fits">Singular fits</a></li>
  <li><a href="#convergence-warnings" id="toc-convergence-warnings" class="nav-link" data-scroll-target="#convergence-warnings">Convergence warnings</a></li>
  </ul></li>
  <li><a href="#exercises-random-effect-structures" id="toc-exercises-random-effect-structures" class="nav-link" data-scroll-target="#exercises-random-effect-structures">Exercises: Random Effect Structures</a>
  <ul class="collapse">
  <li><a href="#crossed-ranefs" id="toc-crossed-ranefs" class="nav-link" data-scroll-target="#crossed-ranefs">Crossed Ranefs</a></li>
  <li><a href="#nested-random-effects" id="toc-nested-random-effects" class="nav-link" data-scroll-target="#nested-random-effects">Nested Random Effects</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assumptions, Diagnostics, and Random Effect Structures</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="lo">
<p><strong>Preliminaries</strong></p>
<ol type="1">
<li>Create a new RMarkdown document or R script (whichever you like) for this week.</li>
</ol>
</div>
<section id="exercises-assumptions-diagnostics" class="level1">
<h1>Exercises: Assumptions &amp; Diagnostics</h1>
<p>For these next set of exercises we will return to our study from Week 1, in which researchers want to study the relationship between time spent outdoors and mental wellbeing, across all of Scotland. Data is collected from 20 of the Local Authority Areas and is accessible at <a href="https://uoepsy.github.io/data/LAAwellbeing.csv">https://uoepsy.github.io/data/LAAwellbeing.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="nlituqwkjn" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#nlituqwkjn .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#nlituqwkjn .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nlituqwkjn .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nlituqwkjn .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nlituqwkjn .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nlituqwkjn .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nlituqwkjn .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nlituqwkjn .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nlituqwkjn .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nlituqwkjn .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nlituqwkjn .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nlituqwkjn .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#nlituqwkjn .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nlituqwkjn .gt_from_md > :first-child {
  margin-top: 0;
}

#nlituqwkjn .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nlituqwkjn .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nlituqwkjn .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#nlituqwkjn .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#nlituqwkjn .gt_row_group_first td {
  border-top-width: 2px;
}

#nlituqwkjn .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlituqwkjn .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#nlituqwkjn .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#nlituqwkjn .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nlituqwkjn .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlituqwkjn .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nlituqwkjn .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nlituqwkjn .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nlituqwkjn .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nlituqwkjn .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlituqwkjn .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nlituqwkjn .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlituqwkjn .gt_left {
  text-align: left;
}

#nlituqwkjn .gt_center {
  text-align: center;
}

#nlituqwkjn .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nlituqwkjn .gt_font_normal {
  font-weight: normal;
}

#nlituqwkjn .gt_font_bold {
  font-weight: bold;
}

#nlituqwkjn .gt_font_italic {
  font-style: italic;
}

#nlituqwkjn .gt_super {
  font-size: 65%;
}

#nlituqwkjn .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#nlituqwkjn .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#nlituqwkjn .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#nlituqwkjn .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#nlituqwkjn .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#nlituqwkjn .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">variable</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">description</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">ppt</td>
<td class="gt_row gt_left">Participant ID</td></tr>
    <tr><td class="gt_row gt_left">name</td>
<td class="gt_row gt_left">Participant Name</td></tr>
    <tr><td class="gt_row gt_left">laa</td>
<td class="gt_row gt_left">Local Authority Area</td></tr>
    <tr><td class="gt_row gt_left">outdoor_time</td>
<td class="gt_row gt_left">Self report estimated number of hours per week spent outdoors</td></tr>
    <tr><td class="gt_row gt_left">wellbeing</td>
<td class="gt_row gt_left">Warwick-Edinburgh Mental Wellbeing Scale (WEMWBS), a self-report measure of mental health and well-being. The scale is scored by summing responses to each item, with items answered on a 1 to 5 Likert scale. The minimum scale score is 14 and the maximum is 70.</td></tr>
    <tr><td class="gt_row gt_left">density</td>
<td class="gt_row gt_left">LAA Population Density (people per square km)</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>The code below will read in the data and fit the model with by-LAA random intercepts and slopes of outdoor time.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>scotmw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/LAAwellbeing.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>rs_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(wellbeing <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> outdoor_time <span class="sc">|</span> laa), <span class="at">data =</span> scotmw)</span></code></pre></div>
</div>
<ol type="1">
<li>Plot the residuals vs fitted model, and assess the extend to which the assumption holds that the residuals are zero mean.</li>
<li>Construct a scale-location plot. This is where the square-root of the absolute value of the standardised residuals is plotted against the fitted values, and allows you to more easily assess the assumption of constant variance.</li>
</ol>
<ul>
<li>Optional: can you create the same plot using ggplot, starting with the <code>augment()</code> function from the <strong>broom.mixed</strong> package?</li>
</ul>
<div class="hints">
<p><strong>Hint:</strong> <code>plot(model)</code> will give you this plot, but you might want to play with the <code>type = c(......)</code> argument to get the smoothing line</p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-1" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-1', 'sol-start-1')"> Solution </span>
</div>
<div id="sol-body-1" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rs_model, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>As we can see, the mean value of the residuals is quite close to zero, right the way across the fitted values. This is good.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rs_model,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">form =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.))) <span class="sc">~</span> <span class="fu">fitted</span>(.),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>In this plot we can see that the variance of the residuals is fairly constant across the fitted values. There is a slight dip at the lower end. We can see this in the previous plot too - all the points at the LHS of the plot are slightly more tightly grouped around the line. This is not enough to worry me, personally.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(rs_model) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sqrtr =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(.resid))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>.fitted, <span class="at">y=</span>sqrtr)) <span class="sc">+</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Examine the normality of both the level 1 and level 2 residuals.</p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>Use <code>hist()</code> if you like, or <code>qqnorm(residuals)</code> followed by <code>qqline(residuals)</code></li>
<li>Extracting the level 2 residuals (the random effects) can be difficult. <code>ranef(model)</code> will get you some of the way.</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-2" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"> Solution </span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p><strong>Level 1</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(rs_model))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(rs_model))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(rs_model))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Level 2</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">1</span>], <span class="at">main =</span> <span class="st">"Random intercept"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">1</span>])</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">2</span>], <span class="at">main =</span> <span class="st">"Random slope"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>laa[, <span class="dv">2</span>])</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The normality of the residuals at both levels looks pretty decent here. This is especially good given that we only actually have 20 clusters (the LAAs). We have quite a small sample at this level.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<ol type="1">
<li>Which person in the dataset has the greatest influence on our model?<br>
</li>
<li>For which person is the model fit the worst (i.e., who has the highest residual?)</li>
<li>Which <em>LAA</em> has the greatest influence on our model?</li>
</ol>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>as well as <code>hlm_influence()</code> in the <strong>HLMdiag</strong> package there is another nice function, <code>hlm_augment()</code></li>
<li>we can often end up in confusion because the <span class="math inline">\(i^{th}\)</span> observation inputted to our model (and therefore the <span class="math inline">\(i^{th}\)</span> observation of <code>hlm_influence()</code> output) <strong>might not be</strong> the <span class="math inline">\(i^{th}\)</span> observation in our original dataset - there may be missing data! (Luckily, we have no missing data in this dataset).</li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-3" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"> Solution </span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HLMdiag)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>l1_inf <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(rs_model,<span class="at">level=</span><span class="dv">1</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(l1_inf<span class="sc">$</span>cooksd, <span class="at">cutoff=</span><span class="st">"internal"</span>)<span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,.<span class="dv">15</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Greatest influence:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(cooksd))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 132 × 15
      id wellbeing outdoo…¹ laa   .resid .fitted .ls.r…² .ls.f…³ .mar.…⁴ .mar.…⁵
   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1    74        35       33 Scot…  -5.15    40.2  -3.73     38.7  -10.3     45.3
 2   129        60        5 City…   8.89    51.1   6.43     53.6   20.7     39.3
 3   109        31        8 Inve…  -9.22    40.2  -3.03     34.0   -8.94    39.9
 4    59        32        7 Scot…  -6.43    38.4  -7.45     39.5   -7.73    39.7
 5    31        35        7 Moray  -3.44    38.4   0.198    34.8   -4.73    39.7
 6    90        70       34 Na h…  -3.16    73.2  -1.19     71.2   24.5     45.5
 7    87        54       29 High…  -5.33    59.3  -5.66     59.7    9.55    44.4
 8    62        26       21 Midl…  -4.77    30.8   0.214    25.8  -16.7     42.7
 9    67        37        7 East…   4.58    32.4   4.62     32.4   -2.73    39.7
10    64        46       18 City… -10.5     56.5 -10.1      56.1    3.91    42.1
# … with 122 more rows, 5 more variables: cooksd &lt;dbl&gt;, mdffits &lt;dbl&gt;,
#   covtrace &lt;dbl&gt;, covratio &lt;dbl&gt;, leverage.overall &lt;dbl&gt;, and abbreviated
#   variable names ¹​outdoor_time, ²​.ls.resid, ³​.ls.fitted, ⁴​.mar.resid,
#   ⁵​.mar.fitted
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>scotmw[<span class="dv">74</span>, ]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  ppt   name                 laa              outdoor_time wellbeing density
  &lt;chr&gt; &lt;chr&gt;                &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 ID46  Groundskeeper Willie Scottish Borders           33        35      29</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/intro/willie.jpg" class="img-fluid figure-img" width="100"></p>
</figure>
</div>
</div>
</div>
<p>Highest residual:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(.resid)))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 132 × 15
      id wellbeing outdoo…¹ laa   .resid .fitted .ls.r…² .ls.f…³ .mar.…⁴ .mar.…⁵
   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1    64        46       18 City… -10.5     56.5  -10.1     56.1    3.91    42.1
 2   107        22       12 East… -10.3     32.3  -10.1     32.1  -18.8     40.8
 3    72        22       24 West… -10.0     32.0   -9.24    31.2  -21.4     43.4
 4   109        31        8 Inve…  -9.22    40.2   -3.03    34.0   -8.94    39.9
 5   130        22       16 West…  -8.98    31.0   -8.61    30.6  -19.7     41.7
 6   129        60        5 City…   8.89    51.1    6.43    53.6   20.7     39.3
 7    93        65       18 City…   8.51    56.5    8.90    56.1   22.9     42.1
 8    85        47       15 City…  -8.25    55.2   -8.52    55.5    5.56    41.4
 9     7        38       13 Pert…  -7.84    45.8   -5.28    43.3   -3.01    41.0
10   121        31       16 Dumf…  -7.78    38.8   -7.70    38.7  -10.7     41.7
# … with 122 more rows, 5 more variables: cooksd &lt;dbl&gt;, mdffits &lt;dbl&gt;,
#   covtrace &lt;dbl&gt;, covratio &lt;dbl&gt;, leverage.overall &lt;dbl&gt;, and abbreviated
#   variable names ¹​outdoor_time, ²​.ls.resid, ³​.ls.fitted, ⁴​.mar.resid,
#   ⁵​.mar.fitted
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>scotmw[<span class="dv">64</span>, ]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  ppt   name            laa               outdoor_time wellbeing density
  &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 ID37  Nicola Sturgeon City of Edinburgh           18        46    1958</code></pre>
</div>
</div>
<p>Most influential LAA:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="st">"laa"</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(cooksd))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 10
   laa          .rane…¹ .ranef…² .ls.i…³ .ls.o…⁴  cooksd mdffits covtr…⁵ covra…⁶
   &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 Midlothian    -1.76  -0.486     8.75  -1.26   0.143   0.136    0.104     1.11
 2 Na h-Eilean…  14.1    0.399    21.4    0.0553 0.142   0.136    0.112     1.11
 3 Glasgow City -10.9   -0.464    -9.45  -0.593  0.101   0.0957   0.130     1.13
 4 City of Edi…  10.8    0.199    16.2   -0.144  0.0973  0.0917   0.114     1.12
 5 Stirling       6.51  -0.0758   13.3   -0.500  0.0877  0.0821   0.121     1.12
 6 Shetland Is…   4.73   0.389     3.69   0.424  0.0637  0.0600   0.118     1.12
 7 Angus         -4.86   0.0959   -6.82   0.265  0.0623  0.0584   0.117     1.12
 8 West Lothian  -3.13  -0.344     4.13  -0.725  0.0548  0.0519   0.101     1.10
 9 Falkirk       -7.45  -0.157   -12.3   -0.0360 0.0424  0.0407   0.100     1.10
10 Inverclyde    -1.30   0.197   -14.5    1.17   0.0405  0.0397   0.0735    1.07
11 Highland       6.73   0.281     8.95   0.155  0.0377  0.0358   0.125     1.13
12 West Dunbar…  -6.41  -0.267    -4.87  -0.395  0.0340  0.0323   0.0686    1.07
13 Moray         -2.22   0.133    -5.81   0.267  0.0336  0.0319   0.106     1.11
14 Perth and K…   1.49   0.257   -20.4    1.76   0.0334  0.0328   0.0650    1.07
15 East Ayrshi…  -5.67  -0.233    -3.63  -0.391  0.0263  0.0250   0.105     1.11
16 Orkney Isla…   0.179  0.155    -0.816  0.212  0.0169  0.0160   0.108     1.11
17 Scottish Bo…  -0.264 -0.148     3.28  -0.367  0.0155  0.0145   0.130     1.13
18 Dumfries an…  -2.69  -0.0120   -7.27   0.261  0.00836 0.00811  0.0728    1.07
19 Argyll and …   1.65  -0.00518   4.67  -0.187  0.00429 0.00402  0.124     1.13
20 East Renfre…   0.502  0.0849    1.40   0.0247 0.00393 0.00371  0.119     1.12
# … with 1 more variable: leverage.overall &lt;dbl&gt;, and abbreviated variable
#   names ¹​.ranef.intercept, ²​.ranef.outdoor_time, ³​.ls.intercept,
#   ⁴​.ls.outdoor_time, ⁵​covtrace, ⁶​covratio
# ℹ Use `colnames()` to see all variable names</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<ol type="1">
<li>Looking at the random effects, which LAA shows the least improvement in wellbeing as outdoor time increases, and which shows the greatest improvement?<br>
</li>
<li>What is the estimated wellbeing for people from City of Edinburgh with zero hours of outdoor time per week, and what is their associated increases in wellbeing for every hour per week increase in outdoor time?</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-4" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"> Solution </span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>It looks like the residents of Midlothian have the least improvement, and the Western Isles (Na h-Eileanan Siar) show the most increases of wellbeing with outdoor time. We can see this from the LAA-random slopes of outdoor time:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(rs_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$laa
                      (Intercept) outdoor_time
Angus                  -4.8568066  0.095850303
Argyll and Bute         1.6488121 -0.005181049
City of Edinburgh      10.8163125  0.199034174
Dumfries and Galloway  -2.6893688 -0.012005965
East Ayrshire          -5.6749200 -0.232750990
East Renfrewshire       0.5024800  0.084907037
Falkirk                -7.4525578 -0.156694328
Glasgow City          -10.9101439 -0.464232183
Highland                6.7315989  0.280992008
Inverclyde             -1.2966048  0.197142062
Midlothian             -1.7585791 -0.485961786
Moray                  -2.2165380  0.133392034
Na h-Eileanan Siar     14.0595006  0.399493656
Orkney Islands          0.1789928  0.154590585
Perth and Kinross       1.4894924  0.256689754
Scottish Borders       -0.2638474 -0.148174460
Shetland Islands        4.7262680  0.388873631
Stirling                6.5060959 -0.075781592
West Dunbartonshire    -6.4127140 -0.266515096
West Lothian           -3.1274727 -0.343667797

with conditional variances for "laa" </code></pre>
</div>
</div>
<p>We can get the cluster-specific coefficients either by adding the <code>fixef()</code> and <code>ranef()</code> together, or using <code>coef()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(rs_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$laa
                      (Intercept) outdoor_time
Angus                    33.36700   0.31050188
Argyll and Bute          39.87261   0.20947052
City of Edinburgh        49.04011   0.41368575
Dumfries and Galloway    35.53443   0.20264561
East Ayrshire            32.54888  -0.01809942
East Renfrewshire        38.72628   0.29955861
Falkirk                  30.77124   0.05795725
Glasgow City             27.31366  -0.24958061
Highland                 44.95540   0.49564358
Inverclyde               36.92720   0.41179364
Midlothian               36.46522  -0.27131021
Moray                    36.00726   0.34804361
Na h-Eileanan Siar       52.28330   0.61414523
Orkney Islands           38.40280   0.36924216
Perth and Kinross        39.71329   0.47134133
Scottish Borders         37.95995   0.06647711
Shetland Islands         42.95007   0.60352520
Stirling                 44.72990   0.13886998
West Dunbartonshire      31.81109  -0.05186352
West Lothian             35.09633  -0.12901622

attr(,"class")
[1] "coef.mer"</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(rs_model)<span class="sc">$</span>laa[<span class="st">"City of Edinburgh"</span>,]</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept) outdoor_time
City of Edinburgh    49.04011    0.4136857</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="random-effect-structures" class="level1">
<h1>Random Effect Structures</h1>
<p>Random effect structures can get pretty complicated quite quickly. Very often it is not the random effects part that is of specific interest to us, but we wish to estimate random effects in order to more accurately partition up the variance in our outcome variable and provide better estimates of fixed effects.</p>
<p>It is a fine balance between fitting the most sophisticated model structure that we possibly can, and fitting a model that converges without too much simplification. Typically for many research designs, the following steps will keep you mostly on track to finding the maximal model:</p>
<p><code>lmer(outcome ~ fixed effects + (random effects | grouping structure))</code></p>
<ol type="1">
<li><p>Specify the <code>outcome ~ fixed effects</code> bit first.</p>
<ul>
<li>The outcome variable should be clear: it is the variable we are wishing to explain/predict.</li>
<li>The fixed effects are the things we want to use to explain/predict variation in the outcome variable. These will often be the things that are of specific inferential interest, and other covariates. Just like the simple linear model.</li>
</ul></li>
<li><p>If there is a grouping structure to your data, and those groups (preferably n&gt;5) are perceived as a random sample of a wider population (the specific groups aren’t interesting to you), then consider fitting them in the random effects part <code>(1 | grouping)</code>.</p></li>
<li><p>If any of the things in the fixed effects vary within the groups, it might be possible to also include them as random effects.</p>
<ul>
<li>as a general rule, don’t specify random effects that are not also specified as fixed effects (an exception could be specifically for model comparison, to isolate the contribution of the fixed effect).<br>
</li>
<li>For things that do not vary within the groups, it rarely makes sense to include them as random effects. For instance if we had a model with <code>lmer(score ~ genetic_status + (1 + genetic_status | participant))</code> then we would be trying to model a process where “the effect of genetic_status on scores is different for each participant”. But if you consider an individual participant, their genetic status never changes. For participant <span class="math inline">\(i\)</span>, what is “the effect of genetic status on score”? It’s undefined. This is because genetic status only varies <em>between</em> participants.</li>
</ul></li>
</ol>
<!-- 

<div class="optional-begin"><span id='opt-start-5' class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-5', 'opt-start-5')"> <span class="olab">An example</span></span></div><div class="optional-body" id = "opt-body-5" style="display: none;">

 -->
<!-- Suppose we were also interested in the association between population density and wellbeing. Our data contains information on the population density for each LAA. Note that for all people in our data that are from the same LAA, they will have the same value in the `density` variable, because this is measured at the LAA level, not the person-level:   -->
<!-- ```{r} -->
<!-- scotmw %>%  -->
<!--   select(laa, density) -->
<!-- ``` -->
<!-- It doesn't really make sense to have random effects of density by LAA (the `density | laa` bit), because the association `wellbeing ~ density` is the same for _every_ person in that LAA. To say that "each LAA has a different effect of population density on wellbeing" is tricky, because we "effect of density on wellbeing" isn't really defined for an individual LAA.  -->
<!-- ```{r} -->
<!-- #| error: true -->
<!-- #| message: true -->
<!-- model_dens <- lmer(wellbeing ~ 1 + outdoor_time + density + -->
<!--                    (1 + outdoor_time + density | laa), data = scotmw) -->
<!-- ``` -->
<!-- The resulting model gives a singular fit, and we can see how this impacts the model estimates in the random effects. The random effect of `density | laa` is much smaller (explaining less variance), and is very highly correlated to the random intercept `1 | laa`, because it doesn't really contain a great deal more information (if you think about the `laa` and `density` columns of the dataset, there is a one-to-one mapping between them). Including the `density | laa` random effect here is not supported by the data.   -->
<!-- ```{r} -->
<!-- VarCorr(model_dens) -->
<!-- ``` -->
<!-- 

</div><p class="optional-end"></p>

 -->
<div class="rtip">
<p><strong>Random Effects in lme4</strong></p>
<p>Below are a selection of different formulas for specifying different random effect structures, taken from the <a href="https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf">lme4 vignette</a>. This might look like a lot, but over time and repeated use of multilevel models you will get used to reading these in a similar way to getting used to reading the formula structure of <code>y ~ x1 + x2</code> in all our linear models. <br></p>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 41%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Formula</th>
<th style="text-align: right;">Alternative</th>
<th style="text-align: right;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(\text{(1 | g)}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\text{1 + (1 | g)}\)</span></td>
<td style="text-align: right;">Random intercept with fixed mean</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(\text{(1 | g1/g2)}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\text{(1 | g1) + (1 | g1:g2)}\)</span></td>
<td style="text-align: right;">Intercept varying among <span class="math inline">\(g1\)</span> and <span class="math inline">\(g2\)</span> within <span class="math inline">\(g1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(\text{(1 | g1) + (1 | g2)}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\text{1 + (1 | g1) + (1 | g2)}\)</span></td>
<td style="text-align: right;">Intercept varying among <span class="math inline">\(g1\)</span> and <span class="math inline">\(g2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(\text{x + (x | g)}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\text{1 + x + (1 + x | g)}\)</span></td>
<td style="text-align: right;">Correlated random intercept and slope</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(\text{x + (x || g)}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\text{1 + x + (x | g) + (0 + x | g)}\)</span></td>
<td style="text-align: right;">Uncorrelated random intercept and slope</td>
</tr>
</tbody>
</table>
<p><strong>Table 1:</strong> Examples of the right-hand-sides of mixed effects model formulas. <span class="math inline">\(g\)</span>, <span class="math inline">\(g1\)</span>, <span class="math inline">\(g2\)</span> are grouping factors, <span class="math inline">\(x\)</span> is a predictor variable.</p>
</div>
</section>
<section id="convergence-issues-and-what-to-do" class="level1">
<h1>Convergence Issues and What To Do</h1>
<section id="singular-fits" class="level2">
<h2 class="anchored" data-anchor-id="singular-fits">Singular fits</h2>
<p>You may have noticed that some of our models over the last few weeks have been giving a warning: <code>boundary (singular) fit: see ?isSingular</code>.<br>
Up to now, we’ve been largely ignoring these warnings. However, this week we’re going to look at how to deal with this issue.</p>
<p style="color:red">
boundary (singular) fit: see ?isSingular
</p>
<p>The warning is telling us that our model has resulted in a ‘singular fit’. Singular fits often indicate that the model is ‘overfitted’ - that is, the random effects structure which we have specified is too complex to be supported by the data.</p>
<p>Perhaps the most intuitive advice would be remove the most complex part of the random effects structure (i.e.&nbsp;random slopes). This leads to a simpler model that is not over-fitted. In other words, start simplying from the top (where the most complexity is) to the bottom (where the lowest complexity is). Additionally, when variance estimates are very low for a specific random effect term, this indicates that the model is not estimating this parameter to differ much between the levels of your grouping variable. It might, in some experimental designs, be perfectly acceptable to remove this or simply include it as a fixed effect.</p>
<p>A key point here is that when fitting a mixed model, we should think about how the data are generated. Asking yourself questions such as “do we have good reason to assume subjects might vary over time, or to assume that they will have different starting points (i.e., different intercepts)?” can help you in specifying your random effect structure</p>
<p>You can read in depth about what this means by reading the help documentation for <code>?isSingular</code>. For our purposes, a relevant section is copied below:</p>
<p><em>… intercept-only models, or 2-dimensional random effects such as intercept + slope models, singularity is relatively easy to detect because it leads to random-effect variance estimates of (nearly) zero, or estimates of correlations that are (almost) exactly -1 or 1.</em></p>
</section>
<section id="convergence-warnings" class="level2">
<h2 class="anchored" data-anchor-id="convergence-warnings">Convergence warnings</h2>
<p>Issues of non-convergence can be caused by many things. If you’re model doesn’t converge, it does <em>not necessarily</em> mean the fit is incorrect, however it is <strong>is cause for concern</strong>, and should be addressed, else you may end up reporting inferences which do not hold.</p>
<p>There are lots of different things which you could do which <em>might</em> help your model to converge. A select few are detailed below:</p>
<ul>
<li><p>double-check the model specification and the data</p></li>
<li><p>adjust stopping (convergence) tolerances for the nonlinear optimizer, using the optCtrl argument to [g]lmerControl. (see <code>?convergence</code> for convergence controls).</p>
<ul>
<li>What is “tolerance”? Remember that our optimizer is the the method by which the computer finds the best fitting model, by iteratively assessing and trying to maximise the likelihood (or minimise the loss).</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-tolerance" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/tolerance.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Figure 1: An optimizer will stop after a certain number of iterations, or when it meets a tolerance threshold</figcaption><p></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>center and scale continuous predictor variables (e.g.&nbsp;with <code>scale</code>)</p></li>
<li><p>Change the optimization method (for example, here we change it to <code>bobyqa</code>): <code>lmer(..., control = lmerControl(optimizer="bobyqa"))</code><br>
<code>glmer(..., control = glmerControl(optimizer="bobyqa"))</code></p></li>
<li><p>Increase the number of optimization steps: <code>lmer(..., control = lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=50000))</code><br>
<code>glmer(..., control = glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=50000))</code></p></li>
<li><p>Use <code>allFit()</code> to try the fit with all available optimizers. This will of course be slow, but is considered ‘the gold standard’; <em>“if all optimizers converge to values that are practically equivalent, then we would consider the convergence warnings to be false positives.”</em></p></li>
<li><p>Consider simplifying your model, for example by removing random effects with the smallest variance (but be careful to not simplify more than necessary, and ensure that your write up details these changes)</p></li>
</ul>
</section>
</section>
<section id="exercises-random-effect-structures" class="level1">
<h1>Exercises: Random Effect Structures</h1>
<section id="crossed-ranefs" class="level2">
<h2 class="anchored" data-anchor-id="crossed-ranefs">Crossed Ranefs</h2>
<div class="frame">
<p><strong>Data: Test-enhanced learning</strong></p>
<p>An experiment was run to conceptually replicate “test-enhanced learning” (Roediger &amp; Karpicke, 2006): two groups of 25 participants were presented with material to learn. One group studied the material twice (<code>StudyStudy</code>), the other group studied the material once then did a test (<code>StudyTest</code>). Recall was tested immediately (one minute) after the learning session and one week later. The recall tests were composed of 175 items identified by a keyword (<code>Test_word</code>). One of the researchers’ questions concerned how test-enhanced learning influences time-to-recall.</p>
<p>The critical (replication) prediction is that the <code>StudyStudy</code> group should perform somewhat better on the immediate recall test, but the <code>StudyTest</code> group will retain the material better and thus perform better on the 1-week follow-up test.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> variable </th>
   <th style="text-align:left;"> description </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Subject_ID </td>
   <td style="text-align:left;"> Unique Participant Identifier </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Group </td>
   <td style="text-align:left;"> Group denoting whether the participant studied the material twice (StudyStudy), or studied it once then did a test (StudyTest) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Delay </td>
   <td style="text-align:left;"> Time of recall test ('min' = Immediate, 'week' = One week later) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Test_word </td>
   <td style="text-align:left;"> Word being recalled (175 different test words) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Correct </td>
   <td style="text-align:left;"> Whether or not the word was correctly recalled </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Rtime </td>
   <td style="text-align:left;"> Time to recall word (milliseconds) </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The following code loads the data into your R environment by creating a variable called <code>tel</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://uoepsy.github.io/data/testenhancedlearning.RData"</span>))</span></code></pre></div>
</div>
</div>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Load and plot the data.<br>
For this week, we’ll use Reaction Time as our proxy for the test performance, so you’ll probably want that variable on the y-axis.</p>
<p>Does it look like the effect was replicated?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-6" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"> Solution </span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://uoepsy.github.io/data/testenhancedlearning.RData"</span>))</span></code></pre></div>
</div>
<p>You can make use of <code>stat_summary()</code>!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tel, <span class="fu">aes</span>(Delay, Rtime, <span class="at">col=</span>Group)) <span class="sc">+</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data=</span>mean_se, <span class="at">geom=</span><span class="st">"pointrange"</span>)<span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code></pre></div>
</div>
<p>It’s more work, but some people might rather calculate the numbers and then plot them directly. It does just the same thing:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>tel <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Delay, Group) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(Rtime),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">sd</span>(Rtime)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>())</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x=</span>Delay, <span class="at">col =</span> Group)) <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">y=</span>mean, <span class="at">ymin=</span>mean<span class="sc">-</span>se, <span class="at">ymax=</span>mean<span class="sc">+</span>se))<span class="sc">+</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Response Time (ms)"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>That looks like test-enhanced learning to me!</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<blockquote class="blockquote">
<p>The critical (replication) prediction is that the <code>StudyStudy</code> group should perform somewhat better on the immediate recall test, but the <code>StudyTest</code> group will retain the material better and thus perform better on the 1-week follow-up test.</p>
</blockquote>
<p>Test the critical hypothesis using a multi-level model.<br>
<strong>Try</strong> to fit the maximally complex random effect structure that is supported by the experimental design.</p>
<p><strong>NOTE: Your model probably won’t converge. We’ll deal with that in the next question</strong></p>
<div class="hints">
<p><strong>Hints:</strong></p>
<ul>
<li>We can expect variability across subjects (some people are better at learning than others) <strong>and</strong> across items (some of the recall items are harder than others). How should this be represented in the random effects?</li>
<li><em>If a model takes ages to fit, you might want to cancel it by pressing the escape key. It is normal for complex models to take time, but for the purposes of this task, give up after a couple of minutes, and try simplifying your model.</em></li>
</ul>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-7" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"> Solution </span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>We know that we are interested in the <code>Rtime ~ Delay * Group</code> interaction, because we want to see how people perform at one week vs one minute (the <code>Delay</code> variable) and whether this is different between those in each condition (the <code>Group</code> variable, specifying whether participants are in the ‘StudyStudy’ condition or the ‘StudyTest’ condition).</p>
<p>We want to include Subject random effects <em>and</em> Item random effects, and these groupings are crossed, so we’re going to have <code>(1 + ??? | Subject_ID) + (1 + ??? | Test_word)</code>. Each subject is only in one group, so we can only have <code>(1 + Delay | Subject_ID)</code>, but the Test_word items are seen by subjects in both groups, and at both timepoints, so we can have <code>(1 + Delay * Group | Test_word)</code>.</p>
<p>This one will probably take a little bit of time:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Rtime <span class="sc">~</span> Delay <span class="sc">*</span> Group <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">|</span> Subject_ID) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">*</span> Group <span class="sc">|</span> Test_word),</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tel, <span class="at">control=</span><span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">"bobyqa"</span>))</span></code></pre></div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Often, models with maximal random effect structures will not converge, or will obtain a singular fit. One suggested approach here is to simplify the model until you achieve convergence (<a href="https://doi.org/10.1016/j.jml.2012.11.001">Barr et al., 2013</a>).</p>
<p>Incrementally simplify your model from the previous question until you obtain a model that converges and is not a singular fit.</p>
<div class="hints">
<p><strong>Hint:</strong> you can look at the variance estimates and correlations easily by using the <code>VarCorr()</code> function. What jumps out?</p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-8" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-8', 'sol-start-8')"> Solution </span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>There are very high correlations with the by-item random effects of the interaction Delay:Group. We might expect that because it’s an interaction term, but it is quite a complex bit of the model, so let’s remove it:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups     Name                     Std.Dev. Corr                
 Test_word  (Intercept)               17.8642                     
            Delayweek                 13.2793 -0.251              
            GroupStudyTest            18.0270 -0.797 -0.385       
            Delayweek:GroupStudyTest  13.1273  0.972 -0.016 -0.917
 Subject_ID (Intercept)               40.5201                     
            Delayweek                  7.4486 -0.038              
 Residual                            240.3113                     </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Rtime <span class="sc">~</span> Delay<span class="sc">*</span>Group <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">|</span> Subject_ID) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">+</span> Group <span class="sc">|</span> Test_word),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tel, <span class="at">control=</span><span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">"bobyqa"</span>))</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m1)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups     Name           Std.Dev. Corr         
 Test_word  (Intercept)     14.5561              
            Delayweek       14.6914  0.152       
            GroupStudyTest  12.3210 -0.612 -0.875
 Subject_ID (Intercept)     40.5190              
            Delayweek        7.4365 -0.038       
 Residual                  240.3436              </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(m1)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>We still have a singular fit here, and we still have quite high<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> correlations between by-testword random effects. Thinking about the study, if we are going to remove <strong>one</strong> of the by-testword random effects (<code>Delay</code> or <code>Group</code>), which one do we consider to be more theoretically justified? Is the effect of Delay likely to vary by test-words? More so than the effect of group is likely to vary by test-words? Quite possibly - there’s no obvious reason for <em>certain</em> words to be more memorable for people in one group vs another. But there is reason for words to vary in the effect that delay of one week has - how familiar a word is will likely influence the amount to which a week’s delay has on recall.</p>
<p>Let’s remove the by-testword random effect of group.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Rtime <span class="sc">~</span> Delay<span class="sc">*</span>Group <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">|</span> Subject_ID) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">|</span> Test_word),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tel, <span class="at">control=</span><span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">"bobyqa"</span>))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(m2)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m2)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups     Name        Std.Dev. Corr  
 Test_word  (Intercept)  11.6972       
            Delayweek    13.5689 -0.236
 Subject_ID (Intercept)  40.5156       
            Delayweek     7.4001 -0.037
 Residual               240.4432       </code></pre>
</div>
</div>
<p>Hooray, the model converged!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Rtime ~ Delay * Group + (1 + Delay | Subject_ID) + (1 + Delay |  
    Test_word)
   Data: tel
Control: lmerControl(optimizer = "bobyqa")

REML criterion at convergence: 241671.3

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.8200 -0.6685 -0.0096  0.6760  4.0783 

Random effects:
 Groups     Name        Variance Std.Dev. Corr 
 Test_word  (Intercept)   136.82  11.70        
            Delayweek     184.12  13.57   -0.24
 Subject_ID (Intercept)  1641.52  40.52        
            Delayweek      54.76   7.40   -0.04
 Residual               57812.93 240.44        
Number of obs: 17498, groups:  Test_word, 175; Subject_ID, 50

Fixed effects:
                         Estimate Std. Error t value
(Intercept)               744.047      8.925  83.363
Delayweek                  26.766      5.448   4.913
GroupStudyTest            -18.032     12.560  -1.436
Delayweek:GroupStudyTest  -17.647      7.566  -2.332

Correlation of Fixed Effects:
            (Intr) Delywk GrpStT
Delayweek   -0.285              
GropStdyTst -0.704  0.200       
Dlywk:GrpST  0.202 -0.694 -0.288</code></pre>
</div>
</div>
<p>Let’s quickly visualise the interaction. Remember, lower reaction times are better here. It looks like we have replicated the hypothesised effect:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m2, <span class="at">type=</span><span class="st">"int"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
</section>
<section id="nested-random-effects" class="level2">
<h2 class="anchored" data-anchor-id="nested-random-effects">Nested Random Effects</h2>
<div class="frame">
<p><strong>Data: Naming</strong></p>
<p>74 children from 10 schools were administered the full Boston Naming Test (BNT-60) on a yearly basis for 5 years to examine development of word retrieval. Five of the schools taught lessons in a bilingual setting with English as one of the languages, and the remaining five schools taught in monolingual English.</p>
<p>The data is available at <a href="https://uoepsy.github.io/data/bntmono.csv">https://uoepsy.github.io/data/bntmono.csv</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 18%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">variable</th>
<th style="text-align: center;">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">child_id</td>
<td style="text-align: center;">unique child identifier</td>
</tr>
<tr class="even">
<td style="text-align: center;">school_id</td>
<td style="text-align: center;">unique school identifier</td>
</tr>
<tr class="odd">
<td style="text-align: center;">BNT60</td>
<td style="text-align: center;">score on the Boston Naming Test-60. Scores range from 0 to 60</td>
</tr>
<tr class="even">
<td style="text-align: center;">schoolyear</td>
<td style="text-align: center;">Year of school</td>
</tr>
<tr class="odd">
<td style="text-align: center;">mlhome</td>
<td style="text-align: center;">Mono/Bi-lingual School. 0 = Bilingual, 1 = Monolingual</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Let’s start by thinking about our clustering - we’d like to know how much of the variance in BNT60 scores is due to the clustering of data within children, who are themselves within schools. One easy way of assessing this is to fit an <em>intercept only</em> model, which has the appropriate random effect structure.</p>
<p>Using the model below, calculate the proportion of variance attributable to the clustering of data within children within schools.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>bnt_null <span class="ot">&lt;-</span> <span class="fu">lmer</span>(BNT60 <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span>  (<span class="dv">1</span> <span class="sc">|</span> school_id<span class="sc">/</span>child_id), <span class="at">data =</span> bnt)</span></code></pre></div>
</div>
<div class="hints">
<p><strong>Hint:</strong> the random intercept variances are the building blocks here. There are no predictors in this model, so all the variance in the outcome gets attributed to either school-level nesting, child-level nesting, or else is lumped into the residual.</p>
</div>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-9" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-9', 'sol-start-9')"> Solution </span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p>As we can see from <code>summary(bnt_null)</code>, the random intercept variances are 36.52 for child-level, 28.76 for school-level, and the residual variance is 99.11.</p>
<p>So the nesting of data within children within schools accounts for <span class="math inline">\(\frac{36.52 + 28.76}{36.52 + 28.76 + 99.11} = 0.397\)</span> of the variance in the outcome BNT60.</p>
<p>We can calculate this directly using the model estimates if we want, but sometimes doing it by hand is more straightforward.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(bnt_null)) <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(grp, vcov) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">prop_var =</span> vcov <span class="sc">/</span> <span class="fu">sum</span>(vcov),</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">prop_var2 =</span> <span class="fu">cumsum</span>(prop_var)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 grp     vcov  prop_var prop_var2
1 child_id:school_id 36.52302 0.2221657 0.2221657
2          school_id 28.76157 0.1749536 0.3971194
3           Residual 99.11079 0.6028806 1.0000000</code></pre>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Fit a model examining the interaction between the effects of school year and mono/bilingual teaching on word retrieval, with random intercepts only for children and schools.</p>
<div class="hints">
<p><strong>Hint:</strong> make sure your variables are of the right type first - e.g.&nbsp;numeric, factor etc</p>
</div>
<p>Examine the fit and consider your model assumptions, and assess what might be done to improve the model in order to make better statistical inferences.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-10" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-10', 'sol-start-10')"> Solution </span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>This is a quick way to make a set of variables factors:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>bnt <span class="ot">&lt;-</span> bnt <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(mlhome, school_id, child_id), factor))</span></code></pre></div>
</div>
<p>And now let’s fit our model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>bntm0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(BNT60 <span class="sc">~</span> schoolyear <span class="sc">*</span> mlhome <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> school_id<span class="sc">/</span>child_id), <span class="at">data =</span> bnt)</span></code></pre></div>
</div>
<p>Residuals don’t look zero mean:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bntm0, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>It looks a little like, compared to our model (black lines below) the children’s scores (coloured lines) are more closely clustered together when they start school, and then they are more spread out by the end of the study. The fact that we’re fitting the same slope for each child is restricting us here, so we should try fitting random effects of schoolyear.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(bntm0) <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>schoolyear, <span class="at">col=</span>child_id)) <span class="sc">+</span> </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> BNT60))<span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">y =</span> BNT60))<span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted), <span class="at">col=</span><span class="st">"black"</span>, <span class="at">alpha=</span>.<span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">col=</span><span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>school_id)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>bntm1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(BNT60 <span class="sc">~</span> schoolyear <span class="sc">*</span> mlhome <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> schoolyear <span class="sc">|</span> school_id<span class="sc">/</span>child_id), <span class="at">data =</span> bnt)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bntm1, <span class="at">type=</span><span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Much better!</p>
<p>Let’s do some quick diagnostic checks for influence:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>inf1 <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(bntm1, <span class="at">level=</span><span class="dv">1</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(inf1<span class="sc">$</span>cooksd, <span class="at">cutoff =</span> <span class="st">"internal"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>If you check in the help for <code>dotplot_diag()</code>, it tells you that</p>
<ol type="a">
<li>we can add an index for the labels, and</li>
<li>the coordinates (x,y) are flipped. We’re telling R to change the limits of the y axis, but actually it is the x axis. This is just because we want to see the label for that point out to the right.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>infchild <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(bntm1, <span class="at">level=</span><span class="st">"child_id:school_id"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(infchild<span class="sc">$</span>cooksd, <span class="at">cutoff =</span> <span class="st">"internal"</span>, <span class="at">index =</span> infchild<span class="sc">$</span><span class="st">`</span><span class="at">child_id:school_id</span><span class="st">`</span>) <span class="sc">+</span> </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">05</span>))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>And then we can examine the effects to the fixed effects and our standard errors when we remove this child:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>del94 <span class="ot">&lt;-</span> <span class="fu">case_delete</span>(bntm1, <span class="at">level=</span><span class="st">"child_id:school_id"</span>, <span class="at">delete =</span> <span class="st">"ID94:SC9"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(del94<span class="sc">$</span>fixef.original, del94<span class="sc">$</span>fixef.delete)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        [,1]       [,2]
(Intercept)         6.265626  6.2627962
schoolyear          6.371168  6.3639335
mlhome1             0.138711 -0.3052998
schoolyear:mlhome1 -2.603763 -2.3701181</code></pre>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-11" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">Optional: Case deletion influence on standard errors</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p>We can examine the influence that deleting a case has on the standard errors. The standard errors are the square-root of the diagonal of the model-implied variance-covariance matrix:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>( </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">diag</span>(del94<span class="sc">$</span>vcov.original)),</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">diag</span>(del94<span class="sc">$</span>vcov.delete))</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        [,1]      [,2]
(Intercept)        1.0413285 0.9557645
schoolyear         0.7719321 0.6717837
mlhome1            1.4683927 1.3525492
schoolyear:mlhome1 1.0875897 0.9498207</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>infschool <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(bntm1, <span class="at">level=</span><span class="st">"school_id"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(infschool<span class="sc">$</span>cooksd, <span class="at">cutoff =</span> <span class="st">"internal"</span>, <span class="at">index =</span> infschool<span class="sc">$</span>school_id)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Using a method of your choosing, conduct inferences (i.e.&nbsp;obtain p-values or confidence intervals) from your final model and write up the results.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-12" class="fa fa-hand-o-right solution-icon clickable" onclick="toggle_visibility('sol-body-12', 'sol-start-12')"> Solution </span>
</div>
<div class="solution-body" id="sol-body-12" style="display: none;">


<p>We’ll use case-based bootstrapping for a demonstration, but other methods would be appropriate here. We have a large sample of children (74), each with 5 observations. However, we only have 10 schools. A standard likelihood ratio test using <code>anova(model1, model2)</code> might not be preferable here.</p>
<p>This took quite a while to run:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmeresampler)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>bntm1BS <span class="ot">&lt;-</span> <span class="fu">bootstrap</span>(bntm1, <span class="at">.f=</span>fixef, <span class="at">type =</span> <span class="st">"case"</span>, <span class="at">B =</span> <span class="dv">2000</span>, <span class="at">resample =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>,<span class="cn">TRUE</span>,<span class="cn">FALSE</span>))</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(bntm1BS, <span class="at">type =</span> <span class="st">"perc"</span>)</span></code></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  term               estimate lower upper type  level
  &lt;chr&gt;                 &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
1 (Intercept)           6.27   5.43  7.12 perc   0.95
2 schoolyear            6.37   5.72  7.02 perc   0.95
3 mlhome1               0.139 -1.12  1.40 perc   0.95
4 schoolyear:mlhome1   -2.60  -3.51 -1.59 perc   0.95</code></pre>
</div>
</div>
<div class="int">
<p>Multilevel level linear regression was used to investigate childrens’ development of word retrieval over 5 years of school, and whether development was dependent upon the school teaching classes monolingually or bilingually. Initial evaluation of the intercept-only model indicated that the clustering of multiple observations from children within schools accounted for 39.7% of the variance in scores on the Boston Naming Task (BNT60, range 0 to 60). BNT60 scores were modelled with fixed effects of school year (1-5) and monolingual teaching (monolingual vs bilingual, treatment coded with monolingual as the reference level). Random intercepts and slopes of school year were included for schools and for children nested within schools. The model was fitting with maximum likelihood estimation using the default optimiser from the <strong>lme4</strong> package (Bates et al., 2015).<br>
95% Confidence for fixed effect estimates were constructed by case-based bootstrapping with 2000 bootstraps in which children, (but neither observations within children nor the schools within which children were nested) were resampled. Results indicated that children’s scores on the BNT60 increased over the 5 years in which they were studied, with children from bilingual schools increasing in scores by 6.37 ([5.72 – 7.02]) every school year. There was a significant interaction between mono/bilingual schools and changes over the school year, with children from monolingual schools increasing -2.6 ([-3.51 – -1.59]) less than those from bilingual schools for every additional year of school. Full model results can be found in Table 1.</p>
</div>
<p>Table 1</p>
::: {.cell layout-align=“center”}

<table>
<tbody><tr>

<th class="thead firsttablerow firsttablecol col1">
&nbsp;
</th>

<th colspan="2" class="thead firsttablerow">
BNT 60
</th>
</tr>
<tr>

<td class="depvarhead firsttablerow firsttablecol col1">
Predictors
</td>

<td class="depvarhead firsttablerow col2">
Estimates
</td>

<td class="depvarhead firsttablerow col3">
95% CI<br>bootstrap
</td>
</tr>
<tr>

<td class="tdata firsttablecol col1">
Intercept
</td>
<td class="tdata centeralign modelcolumn1 col2">
6.27
</td>
<td class="tdata centeralign modelcolumn1 col3">
5.43&nbsp;–&nbsp;7.12
</td>
</tr>
<tr>

<td class="tdata firsttablecol col1">
School Year
</td>
<td class="tdata centeralign modelcolumn1 col2">
6.37
</td>
<td class="tdata centeralign modelcolumn1 col3">
4.85&nbsp;–&nbsp;7.89
</td>
</tr>
<tr>

<td class="tdata firsttablecol col1">
MonolingualSchool [1]
</td>
<td class="tdata centeralign modelcolumn1 col2">
0.14
</td>
<td class="tdata centeralign modelcolumn1 col3">
-2.75&nbsp;–&nbsp;3.03
</td>
</tr>
<tr>

<td class="tdata firsttablecol col1">
School<br>Year:MonolingualSchool<br>[1]
</td>
<td class="tdata centeralign modelcolumn1 col2">
-2.60
</td>
<td class="tdata centeralign modelcolumn1 col3">
-4.74&nbsp;–&nbsp;-0.46
</td>
</tr>
<tr>
<td colspan="3" class="randomparts">
Random Effects
</td>
</tr>
<tr>
<td class="tdata leftalign summary">
σ<sup>2</sup>
</td>
<td class="tdata summary summarydata" colspan="2">
8.64
</td>
</tr>
<tr>
<td class="tdata leftalign summary">
τ<sub>00</sub> <sub>child_id:school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
1.77
</td>
</tr><tr>
<td class="tdata leftalign summary">
τ<sub>00</sub> <sub>school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
3.83
</td>
</tr><tr>
<td class="tdata leftalign summary">
τ<sub>11</sub> <sub>child_id:school_id.schoolyear</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
6.83
</td>
</tr><tr>
<td class="tdata leftalign summary">
τ<sub>11</sub> <sub>school_id.schoolyear</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
1.89
</td>
</tr><tr>
<td class="tdata leftalign summary">
ρ<sub>01</sub> <sub>child_id:school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
-0.42
</td>
</tr><tr>
<td class="tdata leftalign summary">
ρ<sub>01</sub> <sub>school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
-0.39
</td>
</tr><tr>
<td class="tdata leftalign summary">
ICC
</td>
<td class="tdata summary summarydata" colspan="2">
0.91
</td>
</tr><tr>
<td class="tdata leftalign summary">
N <sub>child_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
74
</td>
</tr><tr>
<td class="tdata leftalign summary">
N <sub>school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
10
</td>
</tr><tr>
<td class="tdata leftalign summary firstsumrow">
Observations
</td>
<td class="tdata summary summarydata firstsumrow" colspan="2">
370
</td>
</tr>
<tr>
<td class="tdata leftalign summary">
Marginal R<sup>2</sup> / Conditional R<sup>2</sup>
</td>
<td class="tdata summary summarydata" colspan="2">
0.420 / 0.947
</td>
</tr>

</tbody></table>
<p>:::</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">effect</span>(<span class="st">"schoolyear:mlhome"</span>,bntm1)) <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x=</span>schoolyear,<span class="at">y=</span>fit,<span class="at">col=</span>mlhome))<span class="sc">+</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper))<span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="cn">NULL</span>,<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Bilingual"</span>,<span class="st">"Monolingual"</span>),<span class="at">values=</span><span class="fu">c</span>(<span class="st">"tomato1"</span>,<span class="st">"navyblue"</span>))<span class="sc">+</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"- School Year -"</span>, <span class="at">y=</span><span class="st">"BNT-60"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>It’s always going to be debateable about what is ‘too high’ because in certain situations you might expect correlations close to 1. It’s best to think through whether it is a feasible value given the study itself<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>