<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - Recap of multilevel models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-left')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-left')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

<link href="site_libs/panelset-0.2.6/panelset.css" rel="stylesheet">
<script src="site_libs/panelset-0.2.6/panelset.js"></script>
<script src="site_libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.24/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR3</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-multi-level-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Multi Level Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-multi-level-models">    
        <li>
    <a class="dropdown-item" href="./01_regressionrefresh.html">
 <span class="dropdown-text">1: Linear Regression | Clustered Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_intromlm.html">
 <span class="dropdown-text">2: Multilevel Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_assumptranef.html">
 <span class="dropdown-text">3: Assumptions, Diagnostics &amp; Random Effect Structures</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_centerglmer.html">
 <span class="dropdown-text">4: Centering in MLM | Logistic</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_recap.html">
 <span class="dropdown-text">5: Recap</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dimension-reduction--sem" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dimension reduction &amp; SEM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dimension-reduction--sem">    
        <li class="dropdown-header">7: Path Analysis</li>
        <li class="dropdown-header">8: Path Mediation</li>
        <li class="dropdown-header">9: Dimension Reduction</li>
        <li class="dropdown-header">10: EFA: Part 1</li>
        <li class="dropdown-header">11: EFA: Part 2</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#school-example" id="toc-school-example" class="nav-link active" data-scroll-target="#school-example">School Example</a>
  <ul class="collapse">
  <li><a href="#school-2020" id="toc-school-2020" class="nav-link" data-scroll-target="#school-2020">School 2020</a></li>
  <li><a href="#random-intercept-and-slopes" id="toc-random-intercept-and-slopes" class="nav-link" data-scroll-target="#random-intercept-and-slopes">Random intercept and slopes</a></li>
  </ul></li>
  <li><a href="#flashcards-lm-to-lmer" id="toc-flashcards-lm-to-lmer" class="nav-link" data-scroll-target="#flashcards-lm-to-lmer">Flashcards: <code>lm</code> to <code>lmer</code></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Recap of multilevel models</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="lo">
<p><strong>No specific exercises this week</strong></p>
<p>This week, there aren’t any exercises, but there is a small recap reading of multilevel models, followed by some ‘flashcard’ type boxes to help you test your understanding of some of the key concepts.</p>
<p>Please use the lab sessions to go over exercises from previous weeks, as we all as asking any questions about the content below.</p>
</div>
<section id="school-example" class="level1">
<h1>School Example</h1>
<blockquote class="blockquote">
<p>Do children scores in maths improve more in school 2020 vs school 2040?</p>
</blockquote>
<p>Consider the following data, representing longitudinal measurements on 10 students from an urban public primary school. The outcome of interest is mathematics achievement. The data were collected at the end of first grade and annually thereafter up to sixth grade, but not all students have six observations. The variable year has been mean-centred to have mean 0 so that results will have as baseline the average.</p>
<p><br></p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<div id="htmlwidget-44520a097087406fde74" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-44520a097087406fde74">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186"],["2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2020","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040","2040"],["273026452","273026452","273026452","273030991","273030991","273030991","273030991","273030991","273059461","273059461","273059461","273059461","273059461","278058841","278058841","278058841","278058841","278058841","292017571","292017571","292017571","292020281","292020281","292020281","292020281","292020281","292020281","292020361","292020361","292020361","292020361","292020361","292020361","292025081","292025081","292025081","292025081","292025081","292026211","292026211","292026211","292026211","292026211","292027291","292027291","292027291","292027291","292027291","292027531","292027531","292027531","292027531","292027531","292028181","292028181","292028181","292028181","292028181","292028931","292028931","292028931","292028931","292028931","292029071","292029071","292029071","292029071","292029071","292029901","292029901","292029901","292029901","292029901","292033851","292033851","292033851","292033851","292033851","295341521","295341521","295341521","295341521","295341521","295341521","298046562","298046562","298046562","301853741","301853741","301853741","307407931","307407931","307407931","307694141","307694141","307694141","307694141","253404261","253404261","253404261","253404261","253404261","253404261","253413681","253413681","253413681","270199271","270199271","270199271","285939962","285939962","285939962","288699161","288699161","288699161","288699161","288699161","289970511","289970511","289970511","289970511","289970511","292772811","292772811","292772811","293550291","293550291","293550291","293550291","299680041","299680041","299680041","299680041","299680041","303652591","303652591","303652591","303652591","303652591","303653561","303653561","303653561","303654611","303654611","303654611","303654611","303654611","303658951","303658951","303658951","303660691","303660691","303660691","303660691","303662391","303662391","303662391","303662391","303662391","303662391","303663601","303663601","303663601","303663601","303663601","303663601","303668751","303668751","303668751","303668751","303668751","303671891","303671891","303671891","303671891","303671891","303672001","303672001","303672001","303672861","303672861","303672861","303673321","303673321","303673321","303673321"],[0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,-2.5,-1.5,-0.5,0.5,1.5,2.5,-2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-2.5,-1.5,-0.5,0.5,1.5,2.5,0.5,1.5,2.5,-1.5,-0.5,0.5,-1.5,-0.5,0.5,-1.5,-0.5,0.5,1.5,-2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,-1.5,0.5,1.5,-0.5,0.5,1.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,-1.5,-0.5,0.5,1.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-2.5,-1.5,-0.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,-1.5,-0.5,0.5,1.5,-2.5,-1.5,-0.5,0.5,1.5,2.5,-2.5,-1.5,-0.5,0.5,1.5,2.5,-1.5,-0.5,0.5,1.5,2.5,-2.5,-1.5,-0.5,0.5,1.5,-1.5,-0.5,0.5,-1.5,-0.5,0.5,-1.5,0.5,1.5,2.5],[1.14600002765656,1.13399994373322,2.29999995231628,-1.30299997329712,0.439000010490417,2.4300000667572,2.25399994850159,3.87299990653992,-1.38399994373322,0.337999999523163,1.14600002765656,1.83899998664856,3.0550000667572,-0.732999980449677,1.04299998283386,2.14000010490417,2.81399989128113,3.54399991035461,-0.732999980449677,0.148000001907349,2.78999996185303,-3.06800007820129,-1.12999999523163,-0.921000003814697,0.462999999523163,0.0209999997168779,2.03500008583069,-2.73200011253357,-2.09699988365173,-0.987999975681305,0.226999998092651,0.402999997138977,1.62300002574921,-1.83000004291534,-0.785000026226044,0.716000020503998,1.20200002193451,3.0550000667572,-1.54100000858307,-0.273000001907349,-0.522000014781952,0.458999991416931,2.09899997711182,-1.75999999046326,-0.921000003814697,0.851999998092651,1.74800002574921,2.59999990463257,-1.83000004291534,-0.500999987125397,0.114000000059605,1.66100001335144,2.16400003433228,-2.3510000705719,-1.50499999523163,-0.725000023841858,0.0209999997168779,1.51400005817413,-1.21800005435944,-0.273000001907349,0.462999999523163,0.573000013828278,1.73599994182587,-1.96599996089935,-0.574000000953674,0.226999998092651,1.74800002574921,2.23099994659424,-2.71799993515015,-1.37800002098083,-0.623000025749207,0.810999989509583,1.97300004959106,-2.96000003814697,-1.25,-0.725000023841858,0.128000006079674,1.51400005817413,-2.73200011253357,-1.89800000190735,-0.921000003814697,0.587000012397766,1.57799994945526,2.29999995231628,0.00300000002607703,0.573000013828278,1.14800000190735,-0.732999980449677,-0.644999980926514,1.14600002765656,-0.732999980449677,-0.112000003457069,1.14600002765656,-2.47399997711182,-1.50499999523163,-0.623000025749207,-0.349999994039536,-2.18799996376038,-1.54100000858307,-0.351000010967255,1.30900001525879,1.4210000038147,2.68199992179871,-3.39499998092651,-3.23200011253357,-2.05299997329712,-1.98699998855591,-0.418999999761581,-0.244000002741814,-0.785000026226044,0.587000012397766,1.4210000038147,-2.16199994087219,0.24099999666214,0.226999998092651,1.27300000190735,3.0550000667572,-1.83000004291534,-1.18499994277954,0.851999998092651,0.573000013828278,1.73599994182587,-3.14400005340576,-2.09699988365173,-0.316000014543533,-2.09699988365173,-1.31400001049042,0.00300000002607703,0.181999996304512,-1.53799998760223,-0.941999971866608,-0.522000014781952,0.632000029087067,1.7940000295639,-1.89800000190735,-0.716000020503998,0.716000020503998,1.06599998474121,2.37100005149841,-3.23200011253357,-2.18799996376038,-1.46399998664856,-1.98699998855591,-1.61600005626678,-1.66499996185303,-0.349999994039536,1.04700005054474,-1.77199995517731,-0.194000005722046,1.67799997329712,-2.18799996376038,-1.567999958992,-1.23599994182587,-0.244000002741814,-3.39499998092651,-2.47399997711182,-1.96599996089935,-0.927999973297119,0.181999996304512,0.797999978065491,-3.23200011253357,-2.53500008583069,-0.785000026226044,0.342999994754791,0.573000013828278,1.30200004577637,-1.27600002288818,0.337999999523163,0.851999998092651,0.128000006079674,2.29999995231628,-3.23200011253357,-2.22499990463257,-0.987999975681305,-1.23599994182587,0.0209999997168779,-1.12999999523163,-0.426999986171722,0.995000004768372,-2.37700009346008,-0.426999986171722,0.995000004768372,-2.37700009346008,-1.23599994182587,-0.725000023841858,0.649999976158142]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>schoolid<\/th>\n      <th>childid<\/th>\n      <th>year<\/th>\n      <th>math<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"columnDefs":[{"targets":4,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \",\", \".\", null);\n  }"},{"className":"dt-right","targets":[3,4]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":["options.columnDefs.0.render"],"jsHooks":[]}</script>
</div>
</div>
<p>How many students in each school?</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>schoolid
2020 2040  Sum 
  21   21   42 </code></pre>
</div>
</div>
<p>We have 42 students, 21 in school with id 2020 and 21 in school with id 2040:</p>
<p>The number of observations per child are as follows.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>childid)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
253404261 253413681 270199271 273026452 273030991 273059461 278058841 285939962 
        6         3         3         3         5         5         5         3 
288699161 289970511 292017571 292020281 292020361 292025081 292026211 292027291 
        5         5         3         6         6         5         5         5 
292027531 292028181 292028931 292029071 292029901 292033851 292772811 293550291 
        5         5         5         5         5         5         3         4 
295341521 298046562 299680041 301853741 303652591 303653561 303654611 303658951 
        6         3         5         3         5         3         5         3 
303660691 303662391 303663601 303668751 303671891 303672001 303672861 303673321 
        4         6         6         5         5         3         3         4 
307407931 307694141 
        3         4 </code></pre>
</div>
</div>
<p>We can see that for some children we have fewer than the 6 observations: some have 3, 4, or 5.</p>
<section id="school-2020" class="level2">
<h2 class="anchored" data-anchor-id="school-2020">School 2020</h2>
<p>Let’s start by considering only the children in school 2020. The mathematics achievement over time is shown, for each student, in the plot below:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data2020 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(schoolid <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data2020, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> math)) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> childid, <span class="at">labeller =</span> label_both) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year (mean centred)"</span>, <span class="at">y =</span> <span class="st">"Maths achievement score"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Clearly, the measurements of mathematics achievement related to each student are <em>grouped data</em> as they refer to the same entity.</p>
<p>If we were to ignore this grouping and consider all children as one single population, we would obtain misleading results.The observations for the same student are clearly correlated. Some students consistently have a much better performance than other students, perhaps due to underlying numerical skills.</p>
<p>A fundamental assumption of linear regression models is that the residuals, and hence the data too, should be uncorrelated. In this example this is not the case.</p>
<p>The following plot considers all data as a single population</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data2020, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> math)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year (mean centred)"</span>, <span class="at">y =</span> <span class="st">"Maths achievement score"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>This is a simple linear regression model for the mathematics measurement of individual <span class="math inline">\(i\)</span> on occasion <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[
\text{math}_{ij} = \beta_0 + \beta_1 \ \text{year}_{ij} + \epsilon_{ij}
\]</span></p>
<p>where the subscript <span class="math inline">\(ij\)</span> denotes the <span class="math inline">\(j\)</span>th measurement from child <span class="math inline">\(i\)</span>.</p>
<p>Let’s fit this in R</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(math <span class="sc">~</span> year, <span class="at">data =</span> data2020)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m0)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = math ~ year, data = data2020)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6478 -0.6264 -0.1101  0.4543  2.4529 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.14323    0.08493  -1.687    0.095 .  
year         0.96072    0.05662  16.968   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8126 on 95 degrees of freedom
Multiple R-squared:  0.7519,    Adjusted R-squared:  0.7493 
F-statistic: 287.9 on 1 and 95 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The intercept and slope of this model can be visually represented as:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="random-intercept-and-slopes" class="level2">
<h2 class="anchored" data-anchor-id="random-intercept-and-slopes">Random intercept and slopes</h2>
<p>In reality, we see that each student has their own line, with a different intercept and slope. In other words, they all have different values of maths achievement when year = 0 and they also differ in their learning rate.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data2020, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> math, <span class="at">color =</span> childid)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year (mean centred)"</span>, <span class="at">y =</span> <span class="st">"Maths achievement score"</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'bottom'</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Let’s now write a model where each student has their own intercept and slope:</p>
<p><span class="math display">\[
\begin{aligned}
\text{math}_{ij}
&amp;= \beta_{0i} + \beta_{1i} \ \text{year}_{ij} + \epsilon_{ij} \\
&amp;= (\text{intercept for child } i) + (\text{slope for child } i) \ \text{year}_{ij} + \epsilon_{ij} \\
&amp;= (\gamma_{00} + \zeta_{0i}) + (\gamma_{10} + \zeta_{1i}) \ \text{year}_{ij} + \epsilon_{ij}
\end{aligned}
\]</span></p>
<p>where</p>
<ul>
<li><p><span class="math inline">\(\beta_{0i}\)</span> is the intercept of the line for child <span class="math inline">\(i\)</span></p></li>
<li><p><span class="math inline">\(\beta_{1i}\)</span> is the slope of the line for child <span class="math inline">\(i\)</span></p></li>
<li><p><span class="math inline">\(\epsilon_{ij}\)</span> are the deviations of each child’s measurement <span class="math inline">\(\text{math}_{ij}\)</span> from the line of child <span class="math inline">\(i\)</span></p></li>
</ul>
<p><br></p>
<p>We can think each child-specific intercept (respectively, slope) as being made up of two components: an “overall” intercept <span class="math inline">\(\gamma_{00}\)</span> (slope <span class="math inline">\(\gamma_{10}\)</span>) and a child-specific deviation from the overall intercept <span class="math inline">\(\zeta_{0i}\)</span> (slope <span class="math inline">\(\zeta_{1i}\)</span>):</p>
<ul>
<li><p><span class="math inline">\(\beta_{0i} = \gamma_{00} + \zeta_{0i} = \text{(overall intercept) + (deviation for child }i)\)</span></p></li>
<li><p><span class="math inline">\(\beta_{1i} = \gamma_{10} + \zeta_{1i} = \text{(overall slope) + (deviation for child }i)\)</span></p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/un_lmm.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="statbox">
<p><strong>FACT</strong></p>
<p><strong>Deviations from the mean average to zero (and sum to zero too!)</strong></p>
<p>As you know, deviations from the mean average to 0.</p>
<p>This holds for the errors <span class="math inline">\(\epsilon_{ij}\)</span>, as well as the deviations <span class="math inline">\(\zeta_{0i}\)</span> from the overall intercept, and the deviations <span class="math inline">\(\zeta_{1i}\)</span> from the overall slope.</p>
<p>Think of data <span class="math inline">\(y_1, ..., y_n\)</span> and their mean <span class="math inline">\(\bar y\)</span>. The average of the deviations from the mean is</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\sum_i (y_i - \bar y)}{n}
= \frac{\sum_i y_i }{n} - \frac{\sum_i \bar y}{n}
= \bar y - \frac{n * \bar y}{n}
= \bar y - \bar y
= 0
\end{aligned}
\]</span></p>
</div>
<p><br></p>
<p>The child-specific deviations <span class="math inline">\(\zeta_{0i}\)</span> from the overall intercept are normally distributed with mean <span class="math inline">\(0\)</span> and variance <span class="math inline">\(\sigma_0^2\)</span>. Similarly, the deviations <span class="math inline">\(\zeta_{1i}\)</span> of the slope for child <span class="math inline">\(i\)</span> from the overall slope come from a normal distribution with mean <span class="math inline">\(0\)</span> and variance <span class="math inline">\(\sigma_1^2\)</span>. The correlation between random intercepts and slopes is <span class="math inline">\(\rho = \text{Cor}(\zeta_{0i}, \zeta_{1i}) = \frac{\sigma_{01}}{\sigma_0 \sigma_1}\)</span>:</p>
<p><span class="math display">\[
\begin{bmatrix} \zeta_{0i} \\ \zeta_{1i} \end{bmatrix}
\sim N
\left(
    \begin{bmatrix} 0 \\ 0 \end{bmatrix},
    \begin{bmatrix}
        \sigma_0^2 &amp; \rho \sigma_0 \sigma_1 \\
        \rho \sigma_0 \sigma_1 &amp; \sigma_1^2
    \end{bmatrix}
\right)
\]</span></p>
<p>The random errors, independently from the random effects, are distributed</p>
<p><span class="math display">\[
\epsilon_{ij} \sim N(0, \sigma_\epsilon^2)
\]</span></p>
<p>This is fitted using <code>lmer()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(math <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> year <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> year <span class="sc">|</span> childid), <span class="at">data =</span> data2020)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: math ~ 1 + year + (1 + year | childid)
   Data: data2020

REML criterion at convergence: 166.6

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.3119 -0.6125 -0.0726  0.6002  2.4197 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 childid  (Intercept) 0.50065  0.7076       
          year        0.01131  0.1063   0.82
 Residual             0.16345  0.4043       
Number of obs: 97, groups:  childid, 21

Fixed effects:
            Estimate Std. Error t value
(Intercept)  -0.1091     0.1605   -0.68
year          0.9940     0.0381   26.09

Correlation of Fixed Effects:
     (Intr)
year 0.433 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">

</div>
<p>The summary of the <code>lmer</code> output returns estimated values for</p>
<p>Fixed effects:</p>
<ul>
<li><span class="math inline">\(\widehat \gamma_{00} = -0.109\)</span></li>
<li><span class="math inline">\(\widehat \gamma_{10} = 0.994\)</span></li>
</ul>
<p>Variability of random effects:</p>
<ul>
<li><span class="math inline">\(\widehat \sigma_{0} = 0.708\)</span></li>
<li><span class="math inline">\(\widehat \sigma_{1} = 0.106\)</span></li>
</ul>
<p>Correlation of random effects:</p>
<ul>
<li><span class="math inline">\(\widehat \rho = 0.816\)</span></li>
</ul>
<p>Residuals:</p>
<ul>
<li><span class="math inline">\(\widehat \sigma_\epsilon = 0.404\)</span></li>
</ul>
<p>Remember: - The child-specific deviations <span class="math inline">\(\zeta_{0i}\)</span> from the overall intercept are <strong>normally distributed</strong> with mean <span class="math inline">\(0\)</span> and variance <span class="math inline">\(\sigma_0^2\)</span>. - Similarly, the deviations <span class="math inline">\(\zeta_{1i}\)</span> of the slope for child <span class="math inline">\(i\)</span> from the overall slope come from a <strong>normal distribution</strong> with mean <span class="math inline">\(0\)</span> and variance <span class="math inline">\(\sigma_1^2\)</span>.</p>
<p>We can check that our random effects look :</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(m1)<span class="sc">$</span>childid[, <span class="dv">1</span>], <span class="at">main =</span> <span class="st">"Random intercept"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(m1)<span class="sc">$</span>childid[, <span class="dv">1</span>])</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">ranef</span>(m1)<span class="sc">$</span>childid[, <span class="dv">2</span>], <span class="at">main =</span> <span class="st">"Random slope"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">ranef</span>(m1)<span class="sc">$</span>childid[, <span class="dv">2</span>])</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:95.0%"></p>
</figure>
</div>
</div>
</div>
<p>Check normality and independence of errors:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(m1), <span class="at">id=</span><span class="fl">0.05</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(m1), <span class="at">id=</span><span class="fl">0.05</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:95.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">form =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.))) <span class="sc">~</span> <span class="fu">fitted</span>(.),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" style="width:95.0%"></p>
</figure>
</div>
</div>
</div>
<p>Visually inspect the correlation between the random intercept and slopes:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">ranef</span>(m1)<span class="sc">$</span>childid,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>, <span class="at">y =</span> year)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">'gray'</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<!-- HIDE??? -->
<!-- ## Schools 2020 and 2040 -->
<!-- Consider now the case where you want a fixed effect for the two schools, to compare the average mathematics achievement among those 2 particular schools. This would take the form of a fixed effect: -->
<!-- ```{r} -->
<!-- m2 <- lmer(math ~ 1 + year + schoolid + (1 + year | childid), data = data) -->
<!-- summary(m2) -->
<!-- ``` -->
<!-- Check normality of random effects: -->
<!-- ```{r, fig.width=8, fig.height = 4, out.width = '95%'} -->
<!-- par(mfrow = c(1,2)) -->
<!-- qqnorm(ranef(m2)$childid[, 1], main = "Random intercept") -->
<!-- qqline(ranef(m2)$childid[, 1]) -->
<!-- qqnorm(ranef(m2)$childid[, 2], main = "Random slope") -->
<!-- qqline(ranef(m2)$childid[, 2]) -->
<!-- ``` -->
<!-- Check normality and independence of errors: -->
<!-- ```{r, fig.width=8, fig.height = 4, out.width = '95%'} -->
<!-- par(mfrow = c(1,2)) -->
<!-- qqnorm(resid(m2), main = "Residuals") -->
<!-- qqline(resid(m2)) -->
<!-- plot(fitted(m2), resid(m2), ylab = "Residuals", xlab = "Fitted values") -->
<!-- abline(h=0) -->
<!-- ``` -->
<!-- Visually inspect the correlation between the random intercept and slopes: -->
<!-- ```{r} -->
<!-- ggplot(ranef(m2)$childid, -->
<!--        aes(x = `(Intercept)`, y = year)) + -->
<!--     geom_smooth(method = lm, se = FALSE,  -->
<!--                 color = 'gray', size = 0.5) + -->
<!--     geom_point() -->
<!-- ``` -->
<!-- We see from `summary` and the plot above, that the correlation between the random intercept and slope is equal to 1. -->
<!-- We also notice the following message: -->
<!-- ``` -->
<!-- Model failed to converge with max|grad| = 0.00288304 (tol = 0.002, component 1) -->
<!-- ``` -->
<!-- It basically is saying that the gradient stopping criterion at the termination was not smaller than the specified threshold of 0.002.  -->
<!-- We can try uncorrelating the random intercept and slope, i.e. setting $\rho = 0$ by either using `||`:  -->
<!-- ```{r} -->
<!-- m2a <- lmer(math ~ 1 + year + schoolid + (1 + year || childid), data = data) -->
<!-- summary(m2a) -->
<!-- ``` -->
<!-- or: -->
<!-- ```{r} -->
<!-- m2b <- lmer(math ~ 1 + year + schoolid +(1 | childid) + (0 + year | childid), data = data) -->
<!-- summary(m2b) -->
<!-- ``` -->
<!-- The two above will return the same results. -->
<!-- Check normality of random effects: -->
<!-- ```{r, fig.width=8, fig.height = 4, out.width = '95%'} -->
<!-- par(mfrow = c(1,2)) -->
<!-- qqnorm(ranef(m2a)$childid[, 1], main = "Random intercept") -->
<!-- qqline(ranef(m2a)$childid[, 1]) -->
<!-- qqnorm(ranef(m2a)$childid[, 2], main = "Random slope") -->
<!-- qqline(ranef(m2a)$childid[, 2]) -->
<!-- ``` -->
<!-- Check normality and independence of errors: -->
<!-- ```{r, fig.width=8, fig.height = 4, out.width = '95%'} -->
<!-- par(mfrow = c(1,2)) -->
<!-- qqnorm(resid(m2a), main = "Residuals") -->
<!-- qqline(resid(m2a)) -->
<!-- plot(fitted(m2a), resid(m2a), ylab = "Residuals", xlab = "Fitted values") -->
<!-- abline(h=0) -->
<!-- ``` -->
<!-- Visually inspect the correlation between the random intercept and slopes: -->
<!-- ```{r} -->
<!-- ggplot(ranef(m2a)$childid, -->
<!--        aes(x = `(Intercept)`, y = year)) + -->
<!--     geom_smooth(method = lm, se = FALSE,  -->
<!--                 color = 'gray', size = 0.5) + -->
<!--     geom_point() -->
<!-- ``` -->
</section>
</section>
<section id="flashcards-lm-to-lmer" class="level1">
<h1>Flashcards: <code>lm</code> to <code>lmer</code></h1>
<div class="cell" data-layout-align="center">

</div>
<p>In a simple linear regression, there is only considered to be one source of random variability: any variability left unexplained by a set of predictors (which are modelled as fixed estimates) is captured in the model residuals.</p>
<p>Multi-level (or ‘mixed-effects’) approaches involve modelling more than one source of random variability - as well as variance resulting from taking a random sample of observations, we can identify random variability across different groups of observations. For example, if we are studying a patient population in a hospital, we would expect there to be variability across the our sample of patients, but also across the doctors who treat them.</p>
<p>We can account for this variability by allowing the outcome to be lower/higher for each group (a random intercept) and by allowing the estimated effect of a predictor vary across groups (random slopes).</p>
<div class="blue">
<p>Before you expand each of the boxes below, think about how comfortable you feel with each concept.<br>
This content is very cumulative, which means often going back to try to isolate the place which we need to focus efforts in learning.</p>
</div>
<div class="optional-begin">
<span id="opt-start-1" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> <span class="olab">Simple Linear Regression</span></span>
</div>
<div id="opt-body-1" class="optional-body" style="display: none;">
<div class="frame">
<p><strong>Formula:</strong></p>
<ul>
<li><span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \epsilon_i\)</span></li>
</ul>
<p><strong>R command:</strong></p>
<ul>
<li><code>lm(outcome ~ predictor, data = dataframe)</code></li>
</ul>
<p><em>Note:</em> this is the same as <code>lm(outcome ~ 1 + predictor, data = dataframe)</code>. The <code>1 +</code> is always there unless we specify otherwise (e.g., by using <code>0 +</code>).</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-2" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-2', 'opt-start-2')"> <span class="olab">Clustered (multi-level) data</span></span>
</div>
<div id="opt-body-2" class="optional-body" style="display: none;">
<p>When our data is clustered (or ‘grouped’) such that datapoints are no longer independent, but belong to some grouping such as that of multiple observations from the same subject, we have multiple sources of random variability. A simple regression does not capture this.</p>
<p>If we separate out our data to show an individual plot for each subject, we can see how the fitted regression line from <code>lm()</code> is assumed to be the same for each subject.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-3" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-3', 'opt-start-3')"> <span class="olab">Random intercepts</span></span>
</div>
<div id="opt-body-3" class="optional-body" style="display: none;">
<p>By including a random-intercept term, we are letting our model estimate random variability around an average parameter (represented by the fixed effects) for the clusters.</p>
<div class="frame">
<p><strong>Formula:</strong><br>
Level 1:</p>
<ul>
<li><span class="math inline">\(y_{ij} = \beta_{0i} + \beta_{1i} x_{ij} + \epsilon_{ij}\)</span></li>
</ul>
<p>Level 2:</p>
<ul>
<li><span class="math inline">\(\beta_{0i} = \gamma_{00} + \zeta_{0i}\)</span></li>
</ul>
<p>Where the expected values of <span class="math inline">\(\zeta_{0}\)</span>, and <span class="math inline">\(\epsilon\)</span> are 0, and their variances are <span class="math inline">\(\sigma_{0}^2\)</span> and <span class="math inline">\(\sigma_\epsilon^2\)</span> respectively. We will further assume that these are normally distributed.</p>
<p>We can now see that the intercept estimate <span class="math inline">\(\beta_{0i}\)</span> for a particular group <span class="math inline">\(i\)</span> is represented by the combination of a mean estimate for the parameter (<span class="math inline">\(\gamma_{00}\)</span>) and a random effect for that group (<span class="math inline">\(\zeta_{0i}\)</span>).</p>
<p><strong>R command:</strong></p>
<ul>
<li><code>lmer(outcome ~ predictor + (1 | grouping), data = dataframe)</code></li>
</ul>
</div>
<p>Notice how the fitted line of the random intercept model has an adjustment for each subject.<br>
Each subject’s line has been moved up or down accordingly.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-4" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-4', 'opt-start-4')"> <span class="olab">Shrinkage</span></span>
</div>
<div id="opt-body-4" class="optional-body" style="display: none;">
<p>If you think about it, we might have done a similar thing with the tools we already had at our disposal, by using <code>lm(y~x+subject)</code>. This would give us a coefficient for the difference between each subject and the reference level intercept, or we could extend this to <code>lm(y~x*subject)</code> to give us an adjustment to the slope for each subject.</p>
<p>However, the estimate of these models will be slightly different:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Why?</strong> One of the benefits of multi-level models is that our cluster-level estimates are shrunk towards the average depending on a) the level of across-cluster variation and b) the number of datapoints in clusters.</p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-5" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-5', 'opt-start-5')"> <span class="olab">Random slopes</span></span>
</div>
<div id="opt-body-5" class="optional-body" style="display: none;">
<div class="frame">
<p><strong>Formula:</strong><br>
Level 1:</p>
<ul>
<li><span class="math inline">\(y_{ij} = \beta_{0i} + \beta_{1i} x_{ij} + \epsilon_{ij}\)</span></li>
</ul>
<p>Level 2:</p>
<ul>
<li><span class="math inline">\(\beta_{0i} = \gamma_{00} + \zeta_{0i}\)</span><br>
</li>
<li><span class="math inline">\(\beta_{1i} = \gamma_{10} + \zeta_{1i}\)</span></li>
</ul>
<p>Where the expected values of <span class="math inline">\(\zeta_0\)</span>, <span class="math inline">\(\zeta_1\)</span>, and <span class="math inline">\(\epsilon\)</span> are 0, and their variances are <span class="math inline">\(\sigma_{0}^2\)</span>, <span class="math inline">\(\sigma_{1}^2\)</span>, <span class="math inline">\(\sigma_\epsilon^2\)</span> respectively. We will further assume that these are normally distributed.</p>
<p>As with the intercept <span class="math inline">\(\beta_{0i}\)</span>, the slope of the predictor <span class="math inline">\(\beta_{1i}\)</span> is now modelled by a mean <span class="math inline">\(\gamma_{10}\)</span> and a random effect for each group (<span class="math inline">\(\zeta_{1i}\)</span>).</p>
<p><strong>R command:</strong></p>
<ul>
<li><code>lmer(outcome ~ predictor + (1 + predictor | grouping), data = dataframe)</code></li>
</ul>
<p><em>Note:</em> this is the same as <code>lmer(outcome ~ predictor + (predictor | grouping), data = dataframe)</code> . Like in the fixed-effects part, the <code>1 +</code> is assumed in the random-effects part.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<!-- 

<div class="optional-begin"><span id='opt-start-6' class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-6', 'opt-start-6')"> <span class="olab">Polynomials!</span></span></div><div class="optional-body" id = "opt-body-6" style="display: none;">

 -->
<!-- Sometimes, data have a clear non-linear pattern, such as a curvilinear trend. In such case, it is reasonable to try modelling the outcome _not_ as a linear function of the variable, but as a curvilinear function of it. -->
<!-- The following plots show data (as black dots) where the outcome $y$ has a nonlinear and decreasing dependence on $x$. That is, as $x$ varies from 1 to 10, the outcome $y$ decreases in a non-linear fashion. -->
<!-- Superimposed to the same data, you can see a linear fit (red line) and a cubic fit (blue). -->
<!-- ```{r echo=FALSE, out.widt='100%', fig.heigth = 4, fig.width = 8} -->
<!-- set.seed(5) -->
<!-- u = seq(1, 10, by = 0.5) -->
<!-- v = -(0.2 * u)^3 + rnorm(length(u), sd = 0.2) -->
<!-- pm1 = lm(v ~ u) -->
<!-- pm2 = lm(v ~ 1 + u + I(u^2) + I(u^3)) -->
<!-- par(mfrow = c(1,2)) -->
<!-- plot(u, v, pch = 16, frame.plot = FALSE, xlab = 'x', ylab = 'y') -->
<!-- curve(cbind(1, x) %*% coef(pm1), col = 'red', add = TRUE) -->
<!-- plot(u, v, pch = 16, frame.plot = FALSE, xlab = 'x', ylab = 'y') -->
<!-- curve(cbind(1, x, x^2, x^3) %*% coef(pm2), col = 'dodgerblue', add = TRUE) -->
<!-- ``` -->
<!-- The residuals corresponding to each fit are: -->
<!-- ```{r echo=FALSE, out.widt='100%', fig.heigth = 4, fig.width = 8} -->
<!-- par(mfrow = c(1,2)) -->
<!-- plot(fitted(pm1), resid(pm1), col = 'red', pch = 16, frame.plot = FALSE) -->
<!-- abline(h = 0, col = 'darkgray', xlab = 'Fitted', y = 'Residuals') -->
<!-- plot(fitted(pm2), resid(pm2), col = 'dodgerblue', pch = 16, frame.plot = FALSE) -->
<!-- abline(h = 0, col = 'darkgray', xlab = 'Fitted', y = 'Residuals') -->
<!-- ``` -->
<!-- Clearly, a linear fit doesn't capture the real trend in the data, and any leftover systematic pattern that the model doesn't explicity account for always ends up in the residuals as the red points show. -->
<!-- On the other hand, once we account for the nonlinear trend, that systematic pattern in the residuals disappears. -->
<!-- The secret is to use instead of $x$ as a predictor, the corresponding polynomial up to a specific order: -->
<!-- $$ -->
<!-- y = \beta_0 + \beta_1 x + \beta_2 x^2 + \beta_3 x^3 + \epsilon -->
<!-- $$ -->
<!-- Consider the following example data. You can add polynomials up to order 3, for example, of a predictor "time" by saying: -->
<!-- ```{r echo=FALSE} -->
<!-- df <- tibble(subject = 1, reaction = rexp(5, 3), time = 1:5) -->
<!-- df -->
<!-- ``` -->
<!-- ```{r} -->
<!-- source("https://uoepsy.github.io/msmr/functions/code_poly.R") -->
<!-- code_poly(df, predictor = 'time', poly.order = 3, draw.poly = FALSE) -->
<!-- ``` -->
<!-- and use those terms when specifying your linear model, for example: -->
<!-- ``` -->
<!-- lmer(reaction ~ poly1 + poly2 + poly3 + (1 | subject)) -->
<!-- ``` -->
<!-- 

</div><p class="optional-end"></p>

 -->
<div class="optional-begin">
<span id="opt-start-7" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-7', 'opt-start-7')"> <span class="olab">Fixed effects</span></span>
</div>
<div id="opt-body-7" class="optional-body" style="display: none;">
<p>The plot below show the fitted values for each subject from the random slopes model <code>lmer(outcome ~ predictor + (1 + predictor | grouping), data = dataframe)</code></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>The thick green line shows the fixed intercept and slope around which the groups all vary randomly.</p>
<p>The <em>fixed effects</em> are the parameters that define the thick green line, and we can extract them using the <code>fixef()</code> function:</p>
<p>These are the overall intercept and slope.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(random_slopes_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          x1 
405.7897675  -0.6722654 </code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-8" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-8', 'opt-start-8')"> <span class="olab">Random effects</span></span>
</div>
<div id="opt-body-8" class="optional-body" style="display: none;">
<p>The plots below show the fitted values for each subject from each model that we have gone through in these expandable boxes (simple linear regression, random intercept, and random intercept &amp; slope):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>In the random-intercept model (center panel), the differences from each of the subjects’ intercepts to the fixed intercept (thick green line) have mean 0 and standard deviation <span class="math inline">\(\sigma_0\)</span>. The standard deviation (and variance, which is <span class="math inline">\(\sigma_0^2\)</span>) is what we see in the random effects part of our model summary (or using the <code>VarCorr()</code> function).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/varcors.PNG" class="img-fluid figure-img" width="400"></p>
</figure>
</div>
</div>
</div>
<p>In the random-slope model (right panel), the same is true for the differences from each subjects’ slope to the fixed slope. We can extract the deviations for each group from the fixed effect estimates using the <code>ranef()</code> function.</p>
<p>These are the deviations from the overall intercept (<span class="math inline">\(\widehat \gamma_{00} = 405.79\)</span>) and slope (<span class="math inline">\(\widehat \gamma_{10} = -0.672\)</span>) for each subject <span class="math inline">\(i\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(random_slopes_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$subject
        (Intercept)          x1
sub_308   31.327291 -1.43995253
sub_309  -28.832219  0.41839420
sub_310    2.711822  0.05993766
sub_330   59.398971  0.38526670
sub_331   74.958481  0.17391602
sub_332   91.086535 -0.23461836
sub_333   97.852988 -0.19057838
sub_334  -54.185688 -0.55846794
sub_335  -16.902018  0.92071637
sub_337   52.217859 -1.16602280
sub_349  -67.760246 -0.68438960
sub_350   -5.821271 -1.23788002
sub_351   61.198823  0.05499816
sub_352   -7.905596 -0.66495059
sub_369  -47.636645 -0.46810258
sub_370  -33.121093 -1.11001234
sub_371   77.576205 -0.20402571
sub_372  -36.389281 -0.45829505
sub_373 -197.579562  1.79897904
sub_374  -52.195357  4.60508775

with conditional variances for "subject" </code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-9" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-9', 'opt-start-9')"> <span class="olab">Group-level coefficients</span></span>
</div>
<div id="opt-body-9" class="optional-body" style="display: none;">
<p>We can also see the actual intercept and slope for each subject <span class="math inline">\(i\)</span> directly, using the <code>coef()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(random_slopes_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$subject
        (Intercept)         x1
sub_308    437.1171 -2.1122179
sub_309    376.9575 -0.2538712
sub_310    408.5016 -0.6123277
sub_330    465.1887 -0.2869987
sub_331    480.7482 -0.4983494
sub_332    496.8763 -0.9068837
sub_333    503.6428 -0.8628438
sub_334    351.6041 -1.2307333
sub_335    388.8877  0.2484510
sub_337    458.0076 -1.8382882
sub_349    338.0295 -1.3566550
sub_350    399.9685 -1.9101454
sub_351    466.9886 -0.6172672
sub_352    397.8842 -1.3372160
sub_369    358.1531 -1.1403680
sub_370    372.6687 -1.7822777
sub_371    483.3660 -0.8762911
sub_372    369.4005 -1.1305604
sub_373    208.2102  1.1267137
sub_374    353.5944  3.9328224

attr(,"class")
[1] "coef.mer"</code></pre>
</div>
</div>
<p>Notice that the above are the fixed effects + random effects estimates, i.e.&nbsp;the overall intercept and slope + deviations for each subject.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(random_intercept_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$subject
        (Intercept)         x1
sub_308    384.0955 -0.9135829
sub_309    406.5426 -0.9135829
sub_310    421.8658 -0.9135829
sub_330    492.0476 -0.9135829
sub_331    498.0868 -0.9135829
sub_332    496.0130 -0.9135829
sub_333    504.6193 -0.9135829
sub_334    338.5855 -0.9135829
sub_335    440.3964 -0.9135829
sub_337    416.7346 -0.9135829
sub_349    319.6674 -0.9135829
sub_350    356.3696 -0.9135829
sub_351    479.2943 -0.9135829
sub_352    379.5162 -0.9135829
sub_369    349.0152 -0.9135829
sub_370    335.0869 -0.9135829
sub_371    484.0427 -0.9135829
sub_372    360.5322 -0.9135829
sub_373    293.6168 -0.9135829
sub_374    511.3440 -0.9135829

attr(,"class")
[1] "coef.mer"</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-10" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-10', 'opt-start-10')"> <span class="olab">Visualising Model Fitted values</span></span>
</div>
<div id="opt-body-10" class="optional-body" style="display: none;">
<p>The model fitted (or “model predicted”) values can be obtained using <code>predict()</code> (returning just the values) or <code>broom.mixed::augment()</code> (returning the values attached to the data that is inputted to the model).</p>
<p>To plot, them, we would typically like to plot the fitted values for each group (e.g.&nbsp;subject)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(random_slopes_model) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(.,<span class="fu">aes</span>(<span class="at">x=</span>x1, <span class="at">y=</span>.fitted, <span class="at">group=</span>subject))<span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-11" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-11', 'opt-start-11')"> <span class="olab">Visualising Fixed Effects</span></span>
</div>
<div id="opt-body-11" class="optional-body" style="display: none;">
<p>If we want to plot the fixed effects from our model, we have to do something else. Packages like <strong>sjPlot</strong> make it incredibly easy (but sometimes <em>too</em> easy), so a nice option is to use the <strong>effects</strong> package to construct a dataframe of the linear prediction accross the values of a predictor, plus standard errors and confidence intervals. We can then pass this to <code>ggplot()</code>, giving us all the control over the aesthetics.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ef <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">effect</span>(<span class="at">term=</span><span class="st">"x1"</span>,<span class="at">mod=</span>random_slopes_model))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ef, <span class="fu">aes</span>(<span class="at">x=</span>x1,<span class="at">y=</span>fit, <span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper))<span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span>.<span class="dv">3</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-12" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-12', 'opt-start-12')"> <span class="olab">Plotting random effects</span></span>
</div>
<div id="opt-body-12" class="optional-body" style="display: none;">
<p>The quick and easy way to plot your random effects is to use the <code>dotplot.ranef.mer()</code> function in <code>lme4</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>randoms <span class="ot">&lt;-</span> <span class="fu">ranef</span>(random_slopes_model, <span class="at">condVar=</span><span class="cn">TRUE</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot.ranef.mer</span>(randoms)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$subject</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-13" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-13', 'opt-start-13')"> <span class="olab">Completely optional - extracting them for plotting in ggplot</span></span>
</div>
<div id="opt-body-13" class="optional-body" style="display: none;">
<p>Sometimes, however, we might want to have a bit more control over our plotting, we can extract the estimates and correlations for each subject:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#we can get the random effects:</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#(note that we use $subject because there might be other groupings, and the ranef() function will give us a list, with one element for each grouping variable)</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>randoms <span class="ot">&lt;-</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ranef</span>(random_slopes_model)<span class="sc">$</span>subject <span class="sc">%&gt;%</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">subject =</span> <span class="fu">row.names</span>(.)) <span class="sc">%&gt;%</span>  <span class="co"># the subject IDs are stored in the rownames, so lets add them as a variable</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">names_to=</span><span class="st">"term"</span>,<span class="at">values_to=</span><span class="st">"estimate"</span>) <span class="co"># finally, let's reshape it for plotting</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co">#and the same for the standard errors (from the arm package):</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>randoms_se <span class="ot">&lt;-</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  arm<span class="sc">::</span><span class="fu">se.ranef</span>(random_slopes_model)<span class="sc">$</span>subject <span class="sc">%&gt;%</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">subject =</span> <span class="fu">row.names</span>(.)) <span class="sc">%&gt;%</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">names_to=</span><span class="st">"term"</span>,<span class="at">values_to=</span><span class="st">"se"</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="co"># join them together:</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>ranefs_plotting <span class="ot">&lt;-</span> <span class="fu">left_join</span>(randoms, randoms_se)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="co"># it's easier for plotting if we</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ranefs_plotting, <span class="fu">aes</span>(<span class="at">y=</span>subject, <span class="at">x=</span>estimate))<span class="sc">+</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin=</span>estimate<span class="dv">-2</span><span class="sc">*</span>se, <span class="at">xmax=</span>estimate<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>se))<span class="sc">+</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>term, <span class="at">scales=</span><span class="st">"free_x"</span>)</span></code></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_recap_long_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-14" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-14', 'opt-start-14')"> <span class="olab">Nested and Crossed structures</span></span>
</div>
<div id="opt-body-14" class="optional-body" style="display: none;">
<p>The same principle we have seen for one level of clustering can be extended to clustering at different levels (for instance, observations are clustered within subjects, which are in turn clustered within groups).</p>
<p>Consider the example where we have observations for each student in every class within a number of schools:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/structure_id.png" class="img-fluid figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
<p><strong>Question:</strong> Is “Class 1” in “School 1” the same as “Class 1” in “School 2”?</p>
<p>No.<br>
The classes in one school are distinct from the classes in another <strong>even though they are named the same</strong>.</p>
<p>The classes-within-schools example is a good case of <strong>nested random effects</strong> - one factor level (one group in a grouping varible) appears <em>only within</em> a particular level of another grouping variable.</p>
<p>In R, we can specify this using:</p>
<p><code>(1 | school) + (1 | class:school)</code></p>
<p>or, more succinctly:</p>
<p><code>(1 | school/class)</code></p>
<p>Consider another example, where we administer the same set of tasks at multiple time-points for every participant.</p>
<p><strong>Question:</strong> Are tasks nested within participants?</p>
<p>No.<br>
Tasks are seen by multiple participants (and participants see multiple tasks).</p>
<p>We could visualise this as the below:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/structure_crossed.png" class="img-fluid figure-img" width="400"></p>
</figure>
</div>
</div>
</div>
<p>In the sense that these are not nested, they are <strong>crossed</strong> random effects.</p>
<p>In R, we can specify this using:</p>
<p><code>(1 | subject) + (1 | task)</code></p>
<div class="blue">
<p><strong>Nested vs Crossed</strong></p>
<p><em>Nested:</em> Each group belongs uniquely to a higher-level group.</p>
<p><em>Crossed:</em> Not-nested.</p>
</div>
<p>Note that in the schools and classes example, had we changed data such that the classes had unique IDs (e.g., see below), then the structures <code>(1 | school) + (1 | class)</code> and <code>(1 | school/class)</code> would give the same results.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/structure_nested.png" class="img-fluid figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-15" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-15', 'opt-start-15')"> <span class="olab">Inference for Multilevel Models</span></span>
</div>
<div id="opt-body-15" class="optional-body" style="display: none;">
<div class="imp">
<p>This is a copy from what we saw in Week 2, but it is important, so here it is again!<br>
The majority of the examples you have seen have been using likelihood ratio tests (using <code>anova(model1, model2)</code>) or using an approximation for the denominator degrees of freedom (the <strong>lmerTest</strong> package). But there are many other options, as detailed below (and this list is not remotely exhaustive).</p>
</div>
<div class="frame">
<p><strong>For these examples… </strong></p>
<p>For the following examples, we’re going to return to our dataset of various toys, and we are going to be concerned with whether practice (the <code>hrs_week</code> variable) is associated with changes in reading ages (<code>R_AGE</code> variable).<br>
To accommodate for the clustered nature of the data, we are going to fit a model with both intercepts and slopes varying by toy-type.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>toys_read <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/toyexample.csv"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">|</span> toy_type), <span class="at">data =</span> toys_read)</span></code></pre></div>
</div>
</div>
<div class="optional-begin">
<span id="opt-start-16" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-16', 'opt-start-16')"> <span class="olab">Use a normal approximation</span></span>
</div>
<div id="opt-body-16" class="optional-body" style="display: none;">
<p>Remember that the <span class="math inline">\(t\)</span> distribution starts to look more and more like the <span class="math inline">\(z\)</span> (“normal”) distribution when degrees of freedom increase? We could just assume we have infinite degrees of freedom in our test statistics, and pretend that the <span class="math inline">\(t\)</span>-values we get are actually <span class="math inline">\(z\)</span>-values. This is “anti-conservative” inasmuch as it is not a very cautious approach, and we are likely to have a higher false positive rate (e.g.&nbsp;more chance of saying “there <strong>is</strong> an effect!” when there actually isn’t.)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">summary</span>(full_model)<span class="sc">$</span>coefficients)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>coefs<span class="sc">$</span>p.z <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(coefs[,<span class="dv">3</span>])))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>coefs</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error  t value          p.z
(Intercept) 1.755943  0.9610348 1.827138 0.0676790647
hrs_week    1.143508  0.2956875 3.867286 0.0001100533</code></pre>
</div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-17" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-17', 'opt-start-17')"> <span class="olab">Satterthwaite df approximation</span></span>
</div>
<div id="opt-body-17" class="optional-body" style="display: none;">
<p>There have been a couple of methods proposed to estimate the degrees of freedom in order to provide a better approximation to the null distribution of our tests. The way the Satterthwaite method has been implemented in R will just add a column for p-values to your <code>summary(model)</code> output).</p>
<p>Load the <strong>lmerTest</strong> package, refit the model, and voila!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">|</span> toy_type), <span class="at">data =</span> toys_read)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_model)<span class="sc">$</span>coefficients</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error       df  t value    Pr(&gt;|t|)
(Intercept) 1.755943  0.9610348 16.19251 1.827138 0.086168780
hrs_week    1.143508  0.2956875 17.51503 3.867286 0.001178702</code></pre>
</div>
</div>
<div class="int">
<p><strong>Reporting</strong></p>
<p>To account for the extra uncertainty brought by the inclusion of random effects in the model, the degrees of freedom in the coefficients tests have been corrected via Satterthwaite’s method.<br>
…<br>
…<br>
Weekly hours of reading practice was associated increased reading age (<span class="math inline">\(\beta = 1.14,\ SE = 0.30,\ t(17.52^*) = 3.87,\ p = .001\)</span>).</p>
</div>
<p><strong>Note:</strong> if you have the <strong>lmerTest</strong> package loaded, then all the models you fit with <code>lmer()</code> will show p-values! If you want to stop this, then you will have to detach/unload the package, and refit the model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(<span class="st">"package:lmerTest"</span>, <span class="at">unload=</span><span class="cn">TRUE</span>)</span></code></pre></div>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-18" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-18', 'opt-start-18')"> <span class="olab">Kenward Rogers df approximations</span></span>
</div>
<div id="opt-body-18" class="optional-body" style="display: none;">
<p>The Kenward-Rogers approach is slightly more conservative than the Satterthwaite method, and has been implemented for model comparison between a full model and a restricted model (a model without the parameter of interest), using the KR adjustment for the denominator degrees of freedom in the <span class="math inline">\(F\)</span>-test.<br>
For this, models must be fitted with REML, <strong>not</strong> ML. The function <code>KRmodcomp()</code> will take care of this and re-fit them for you.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pbkrtest)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>restricted_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">|</span> toy_type), <span class="at">data =</span> toys_read)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">|</span> toy_type), <span class="at">data =</span> toys_read)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">KRmodcomp</span>(full_model, restricted_model)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>large : R_AGE ~ hrs_week + (1 + hrs_week | toy_type)
small : R_AGE ~ 1 + (1 + hrs_week | toy_type)
        stat    ndf    ddf F.scaling  p.value   
Ftest 14.637  1.000 17.738         1 0.001266 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p><strong>Reporting</strong></p>
<p>To account for the extra uncertainty brought by the inclusion of random effects in the model, the denominator degrees of freedom in have been corrected via Kenward-Rogers’ method.<br>
…<br>
…<br>
Inclusion of weekly hours of reading practice as a predictor was associated with an improvement in model fit (<span class="math inline">\(F(1,17.74^*) = 14.64,\ p = .001\)</span>).</p>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-19" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-19', 'opt-start-19')"> <span class="olab">Likelihood Ratio Test (LRT)</span></span>
</div>
<div id="opt-body-19" class="optional-body" style="display: none;">
<p>Conduct a model comparison between your model and a restricted model (a model without the parameter of interest), evaluating the change in log-likelihood.</p>
<div class="statbox">
<p><strong>Likelihood</strong></p>
<p>“likelihood” is a function that associates to a parameter the probability (or probability density) of observing the given sample data.<br>
In simpler terms, the likelihood is the probability of the model given that we have this data.</p>
<p>The intuition behind likelihood:</p>
<ol type="1">
<li>I toss a coin 10 time and observed 8 Heads.<br>
</li>
<li>We can think of a ‘model’ of the process that governs the coin’s behaviour in terms of just one number: a parameter that indicates the probability of the coin landing on heads.<br>
I have two models:</li>
</ol>
<ul>
<li>Model 1: The coin will land on heads 20% of the time. <span class="math inline">\(P(Heads)=0.2\)</span><br>
</li>
<li>Model 2: The coin will land on heads 70% of the time. <span class="math inline">\(P(Heads)=0.7\)</span><br>
</li>
</ul>
<ol start="3" type="1">
<li>Given the data I observe (see 1, above), we can (hopefully) intuit that Model 2 is more likely than Model 1.</li>
</ol>
<p>For a (slightly) more detailed explanation, see <a href="lvp.html">here</a>.</p>
</div>
<p>This method assumes that the ratio of two likelihoods will (as sample size increases) become closer to being <span class="math inline">\(\chi^2\)</span> distributed, and so may be unreliable for small samples.</p>
<p>Models must be fitted with ML, <strong>not</strong> REML. The function <code>anova()</code> will re-fit them for you.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>restricted_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">|</span> toy_type), <span class="at">data =</span> toys_read)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">|</span> toy_type), <span class="at">data =</span> toys_read)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(restricted_model, full_model, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>refitting model(s) with ML (instead of REML)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: toys_read
Models:
restricted_model: R_AGE ~ 1 + (1 + hrs_week | toy_type)
full_model: R_AGE ~ hrs_week + (1 + hrs_week | toy_type)
                 npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
restricted_model    5 660.32 674.73 -325.16   650.32                         
full_model          6 650.51 667.80 -319.25   638.51 11.813  1   0.000588 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="int">
<p><strong>Reporting</strong></p>
<p>A likelihood ratio test indicated that the inclusion of weekly hours of reading practice as a predictor was associated with an improvement in model fit (<span class="math inline">\(\chi^2(1) = 11.81, p &lt; .001\)</span>).</p>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-20" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-20', 'opt-start-20')"> <span class="olab">Optional: Parametric Bootstrap LRT</span></span>
</div>
<div id="opt-body-20" class="optional-body" style="display: none;">
<p>There are also various “bootstrapping” methods which it is worth looking into. Think back to USMR when we first learned about hypothesis testing. Remember that we did lots of simulating data, so that we can compare what we actually observe with what we would expect if the null hypothesis were true? By doing this, we were essentially <em>creating</em> a null distribution, so that our calculating a p-value can become an issue of summarising data (e.g.&nbsp;calculate the proportion of our simulated null distribution that is more extreme than our observed statistic)</p>
<p>Instead of assuming that the likelihood ratio test statistics are <span class="math inline">\(\chi^2\)</span>-distributed, we can bootstrap this test instead. This approach simulates data from the simpler model, fits both the simple model and the complex model and evaluates the change in log-likelihood. By doing this over and over again, we build a distribution of what changes in log-likelihood we would be likely to see if the more complex model is not any better. In this way it actually constructs a distribution reflecting our null hypothesis, against which we can then compare our actual observed effect</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pbkrtest)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(full_model, restricted_model, <span class="at">nsim=</span><span class="dv">1000</span>)</span></code></pre></div>
</div>
<div class="int">
<p><strong>Reporting</strong></p>
<p>A parametric bootstrap likelihood ratio test (R = 1000) indicated that the inclusion of weekly hours of reading practice as a predictor was associated with an improvement in model fit (<span class="math inline">\(LRT = 11.79, p = .004\)</span>).</p>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-21" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-21', 'opt-start-21')"> <span class="olab">Parametric Bootstrap Confidence Intervals</span></span>
</div>
<div id="opt-body-21" class="optional-body" style="display: none;">
<p>Much the same as above, but with just one model we simulate data many times and refit the model, so that we get an empirical distribution that we can use to construct confidence intervals for our effects.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(full_model, <span class="at">method=</span><span class="st">"boot"</span>)  </span></code></pre></div>
</div>
<div class="int">
<p><strong>Reporting</strong></p>
<p>95% Confidence Intervals were obtained via parametric bootstrapping with 1000 iterations.<br>
…<br>
…<br>
Weekly hours of reading practice was associated increased reading age (<span class="math inline">\(\beta = 1.14,\ 95%\ CI\ [0.58 -- 1.73]\)</span>).</p>
</div>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
<span id="opt-start-22" class="fa fa-hand-o-right optional-icon clickable" onclick="toggle_visibility('opt-body-22', 'opt-start-22')"> <span class="olab">Case-based Bootstrap Confidence Intervals</span></span>
</div>
<div id="opt-body-22" class="optional-body" style="display: none;">
<p>It’s worth noting that there are many different types of bootstrapping that we can conduct. Different methods of bootstrapping vary with respect to the assumptions we will have to make when using them for drawing inferences. For instance, the parametric bootstrap discussed above assumes that explanatory variables are fixed and that model specification and the distributions such as <span class="math inline">\(\zeta_i \sim N(0,\sigma_{\zeta})\)</span> and <span class="math inline">\(\varepsilon_i \sim N(0,\sigma_{\varepsilon})\)</span> are correct.<br>
An alternative is to generate a distribution by <strong>resampling with replacement</strong> from our data, fitting our model to the resample, and then repeating this over and over. This doesn’t have to rely on assumptions about the shape of the distributions of <span class="math inline">\(\zeta_i\)</span> and <span class="math inline">\(\varepsilon_i\)</span> - we just need to ensure that we correctly specify the hierarchical dependency of data. It does, however, require the decision of at which levels to resample.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">|</span> toy_type), <span class="at">data =</span> toys_read)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmeresampler)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>fullmod_bs <span class="ot">&lt;-</span> </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bootstrap</span>(full_model, <span class="co"># this is the model</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.f =</span> fixef, <span class="co"># we want the fixef from each bootstrap</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">type =</span> <span class="st">"case"</span>, <span class="co"># case based bootstrap</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">B=</span><span class="dv">2000</span>, <span class="co"># do 2000 bootstraps</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">resample =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">TRUE</span>) <span class="co"># resample both toy_types and individual toys</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fullmod_bs, <span class="at">type =</span> <span class="st">"perc"</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  term        estimate  lower upper type  level
  &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
1 (Intercept)     1.76 -1.35   3.65 perc   0.95
2 hrs_week        1.14  0.633  2.03 perc   0.95</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">

</div>
<div class="int">
<p><strong>Reporting</strong></p>
<p>95% Confidence Intervals were obtained via case-based bootstrapping (resampling both toy types and individual toys) with 2000 iterations.<br>
…<br>
…<br>
Weekly hours of reading practice was associated increased reading age (<span class="math inline">\(\beta\)</span> = 1.1435083, 95% CI [0.6326681 – 2.0317448]).</p>
</div>
</div>
<p class="optional-end">
</p>
<div class="frame">
<p>If you want more information (not required reading for this course), then Julian Faraway has a page <a href="https://people.bath.ac.uk/jjf23/mixchange/index.html">here</a> with links to some worked examples, and Ben Bolker has a wealth of information on his <a href="http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#why-doesnt-lme4-display-denominator-degrees-of-freedomp-values-what-other-options-do-i-have">GLMM FAQ pages</a>.</p>
</div>
</div>
<p class="optional-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>