<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - Analysis Example: Cross-sectional multi-level</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-left')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-left')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR3</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-multi-level-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Multi Level Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-multi-level-models">    
        <li>
    <a class="dropdown-item" href="./01_regressionrefresh.html">
 <span class="dropdown-text">1: Linear Regression | Clustered Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_intromlm.html">
 <span class="dropdown-text">2: Multilevel Models</span></a>
  </li>  
        <li class="dropdown-header">3: Assumptions, Diagnostics &amp; Random Effect Structures</li>
        <li class="dropdown-header">4: Centering in MLM | Logistic</li>
        <li class="dropdown-header">5: Recap</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dimension-reduction--sem" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dimension reduction &amp; SEM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dimension-reduction--sem">    
        <li class="dropdown-header">7: Path Analysis</li>
        <li class="dropdown-header">8: Path Mediation</li>
        <li class="dropdown-header">9: Dimension Reduction</li>
        <li class="dropdown-header">10: EFA: Part 1</li>
        <li class="dropdown-header">11: EFA: Part 2</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">Data Wrangling</a></li>
  <li><a href="#descriptives" id="toc-descriptives" class="nav-link" data-scroll-target="#descriptives">Descriptives</a></li>
  <li><a href="#visualisations" id="toc-visualisations" class="nav-link" data-scroll-target="#visualisations">Visualisations</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#equations" id="toc-equations" class="nav-link" data-scroll-target="#equations">Equations</a></li>
  <li><a href="#fitting-the-models" id="toc-fitting-the-models" class="nav-link" data-scroll-target="#fitting-the-models">Fitting the models</a></li>
  </ul></li>
  <li><a href="#check-model" id="toc-check-model" class="nav-link" data-scroll-target="#check-model">Check model</a></li>
  <li><a href="#visualise-model" id="toc-visualise-model" class="nav-link" data-scroll-target="#visualise-model">Visualise model</a></li>
  <li><a href="#interpret-model" id="toc-interpret-model" class="nav-link" data-scroll-target="#interpret-model">Interpret model</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis Example: Cross-sectional multi-level</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="frame">
<p>Each of these pages provides an analysis run through for a different type of design. Each document is structured in the same way:</p>
<ul>
<li>First the data and research context is introduced. For the purpose of these tutorials, we will only use examples where the data can be shared - either because it is from an open access publication, or because it is unpublished or simulated.</li>
<li>Second, we go through any tidying of the data that is required, before creating some brief descriptives and visualizations of the raw data.</li>
<li>Then, we conduct an analysis. Where possible, we translate the research questions into formal equations prior to fitting the models in <strong>lme4</strong>. Model comparisons are conducted, along with checks of distributional assumptions on our model residuals.</li>
<li>Finally, we visualize and interpret our analysis.</li>
</ul>
<p>Please note that there will be only minimal explanation of the steps undertaken here, as these pages are intended as example analyses rather than additional labs readings. Please also be aware that there are many decisions to be made throughout conducting analyses, and it may be the case that you disagree with some of the choices we make here. As always with these things, it is how we justify our choices that is important. We warmly welcome any feedback and suggestions to improve these examples: please email <a href="mailto:ug.ppls.stats@ed.ac.uk">ug.ppls.stats@ed.ac.uk</a>.</p>
</div>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>OK, in this example we are keeping with Tom’s home territory of organisational psychology. This data set was provided by Dr.&nbsp;David Hughes, from Manchester Business School. It is a subset of a larger data set that has been published on.</p>
<ul>
<li>OrgID: organisation ID</li>
<li>Sex: 0= female, 1=male</li>
<li>Mot: self-rated motivation</li>
<li>Perf: boss rated performance</li>
<li>PubPri: 0= public, 1=private</li>
<li>Region: geographical location, 1=Wales, 2=England, 3=Scotland</li>
<li>Size: number of employees 1= &lt;20, 2=21-50, 3=50-100, 4=100-250, 5=251-500, 6=500-1,000, 7=1,000+</li>
</ul>
<p>Here we are going to be looking at predicting employee performance from self-motivation, and investigating whether this effect is consistent across organisation. We will also look at whether the fact an organisation is public or private accounts for variation in model intercepts and slopes.</p>
</section>
<section id="data-wrangling" class="level1">
<h1>Data Wrangling</h1>
<p>This data set is available at <a href="https://uoepsy.github.io/data/MLM_Org.csv">https://uoepsy.github.io/data/MLM_Org.csv</a>.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>perform <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/MLM_Org.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>perform <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(OrgID <span class="sc">==</span> <span class="st">"Org1"</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 7
   OrgID Sex      Mot Perform PubPri Region   Size
   &lt;chr&gt; &lt;chr&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;dbl&gt;
 1 Org1  female     3      58 public England     3
 2 Org1  female     7      59 public England     3
 3 Org1  male       4      60 public England     3
 4 Org1  male       1      48 public England     3
 5 Org1  female     4      59 public England     3
 6 Org1  male       4      50 public England     3
 7 Org1  female     1      43 public England     3
 8 Org1  female     2      48 public England     3
 9 Org1  male       5      65 public England     3
10 Org1  male       2      41 public England     3
11 Org1  female     2      50 public England     3
12 Org1  female     2      64 public England     3</code></pre>
</div>
</div>
<p>Here we can see the first 10 employees in <code>Org1</code>. Look here at the values that are constant across the organisation, and those that vary by person.</p>
</section>
<section id="descriptives" class="level1">
<h1>Descriptives</h1>
<p>Given our data structure, it likely makes most sense for us to look at the averages across organisations.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>summarytab <span class="ot">&lt;-</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  perform <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(OrgID) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n_distinct</span>(Perform),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean.Perf =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Perform, <span class="at">na.rm=</span>T),<span class="dv">2</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD.Perf =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Perform, <span class="at">na.rm=</span>T),<span class="dv">2</span>),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean.Motiv =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Mot, <span class="at">na.rm=</span>T),<span class="dv">2</span>),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD.Motiv =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Mot, <span class="at">na.rm=</span>T),<span class="dv">2</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(summarytab) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="st">"striped"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> OrgID </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> Mean.Perf </th>
   <th style="text-align:right;"> SD.Perf </th>
   <th style="text-align:right;"> Mean.Motiv </th>
   <th style="text-align:right;"> SD.Motiv </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Org1 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 53.75 </td>
   <td style="text-align:right;"> 8.07 </td>
   <td style="text-align:right;"> 3.08 </td>
   <td style="text-align:right;"> 1.78 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org10 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 48.35 </td>
   <td style="text-align:right;"> 10.96 </td>
   <td style="text-align:right;"> 2.00 </td>
   <td style="text-align:right;"> 1.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org11 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 43.55 </td>
   <td style="text-align:right;"> 10.01 </td>
   <td style="text-align:right;"> 1.64 </td>
   <td style="text-align:right;"> 1.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org12 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 49.86 </td>
   <td style="text-align:right;"> 8.44 </td>
   <td style="text-align:right;"> 0.86 </td>
   <td style="text-align:right;"> 0.77 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org13 </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 46.40 </td>
   <td style="text-align:right;"> 4.32 </td>
   <td style="text-align:right;"> 1.15 </td>
   <td style="text-align:right;"> 0.81 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org14 </td>
   <td style="text-align:right;"> 13 </td>
   <td style="text-align:right;"> 56.38 </td>
   <td style="text-align:right;"> 9.35 </td>
   <td style="text-align:right;"> 2.62 </td>
   <td style="text-align:right;"> 1.75 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org15 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 55.70 </td>
   <td style="text-align:right;"> 9.53 </td>
   <td style="text-align:right;"> 1.83 </td>
   <td style="text-align:right;"> 1.23 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org16 </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 51.05 </td>
   <td style="text-align:right;"> 10.27 </td>
   <td style="text-align:right;"> 2.75 </td>
   <td style="text-align:right;"> 1.71 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org17 </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 40.95 </td>
   <td style="text-align:right;"> 6.36 </td>
   <td style="text-align:right;"> 1.63 </td>
   <td style="text-align:right;"> 1.07 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org18 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 62.82 </td>
   <td style="text-align:right;"> 5.68 </td>
   <td style="text-align:right;"> 3.30 </td>
   <td style="text-align:right;"> 1.72 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org19 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 49.67 </td>
   <td style="text-align:right;"> 10.34 </td>
   <td style="text-align:right;"> 2.10 </td>
   <td style="text-align:right;"> 1.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org2 </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 57.38 </td>
   <td style="text-align:right;"> 9.98 </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:right;"> 1.04 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org20 </td>
   <td style="text-align:right;"> 14 </td>
   <td style="text-align:right;"> 46.33 </td>
   <td style="text-align:right;"> 9.55 </td>
   <td style="text-align:right;"> 1.33 </td>
   <td style="text-align:right;"> 0.91 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org21 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 51.33 </td>
   <td style="text-align:right;"> 9.99 </td>
   <td style="text-align:right;"> 1.63 </td>
   <td style="text-align:right;"> 1.08 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org22 </td>
   <td style="text-align:right;"> 14 </td>
   <td style="text-align:right;"> 47.85 </td>
   <td style="text-align:right;"> 11.30 </td>
   <td style="text-align:right;"> 1.60 </td>
   <td style="text-align:right;"> 1.43 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org23 </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 54.93 </td>
   <td style="text-align:right;"> 12.47 </td>
   <td style="text-align:right;"> 2.00 </td>
   <td style="text-align:right;"> 1.75 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org3 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 56.60 </td>
   <td style="text-align:right;"> 11.84 </td>
   <td style="text-align:right;"> 2.20 </td>
   <td style="text-align:right;"> 1.64 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org4 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 48.46 </td>
   <td style="text-align:right;"> 8.62 </td>
   <td style="text-align:right;"> 1.50 </td>
   <td style="text-align:right;"> 0.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org5 </td>
   <td style="text-align:right;"> 17 </td>
   <td style="text-align:right;"> 45.74 </td>
   <td style="text-align:right;"> 7.53 </td>
   <td style="text-align:right;"> 1.39 </td>
   <td style="text-align:right;"> 1.12 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org6 </td>
   <td style="text-align:right;"> 14 </td>
   <td style="text-align:right;"> 53.94 </td>
   <td style="text-align:right;"> 7.30 </td>
   <td style="text-align:right;"> 1.76 </td>
   <td style="text-align:right;"> 1.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org7 </td>
   <td style="text-align:right;"> 16 </td>
   <td style="text-align:right;"> 50.09 </td>
   <td style="text-align:right;"> 9.14 </td>
   <td style="text-align:right;"> 1.50 </td>
   <td style="text-align:right;"> 1.01 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org8 </td>
   <td style="text-align:right;"> 15 </td>
   <td style="text-align:right;"> 42.15 </td>
   <td style="text-align:right;"> 8.32 </td>
   <td style="text-align:right;"> 2.35 </td>
   <td style="text-align:right;"> 1.31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Org9 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 53.25 </td>
   <td style="text-align:right;"> 11.52 </td>
   <td style="text-align:right;"> 1.83 </td>
   <td style="text-align:right;"> 1.13 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Note the different numbers of employees we have across organisation. Clearly this will mean the information provided by each organisation will vary.</p>
</section>
<section id="visualisations" class="level1">
<h1>Visualisations</h1>
<p>Next, we can visualize the relationship between motivation and performance within each organisation.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>perform <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Mot, <span class="at">y=</span>Perform, <span class="at">group =</span> OrgID)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha=</span> .<span class="dv">75</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Motivation"</span>, <span class="at">y=</span><span class="st">"Performance"</span>) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>OrgID)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_04_cross_sectional_multilevel_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What we see here is A LOT of variability. Not only do the intercepts change, so does the steepness and direction of the slopes.</p>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="equations" class="level2">
<h2 class="anchored" data-anchor-id="equations">Equations</h2>
<p>Our model will take the structure specified below. However, we may also want to discuss whether public/private moderates the <em>within</em> effect of motivation, or the <em>between</em> effect of motivation, in which case we would need to separate out the group mean motivation and the group-mean centered motivation.</p>
<p><span class="math display">\[
\begin{align}
\operatorname{Perform}_{ij} &amp;= \beta_{0i} + \beta_{1i}(\operatorname{Motivation}_j) + \varepsilon_{ij}\\
\beta_{0i} &amp;= \gamma_{00} + \zeta_{0i} \\
\beta_{1i} &amp;= \gamma_{10} + \gamma_{11}(\operatorname{isPrivate}_i) + \zeta_{0i} \\
&amp; \text{for OrgID i = 1,} \dots \text{,I}
\end{align}
\]</span></p>
</section>
<section id="fitting-the-models" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-models">Fitting the models</h2>
<p>As we have in many of our examples, let’s run an empty model, and look at the ICC for the grouping variable organisation.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Empty model</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Perform <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">|</span> OrgID),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> perform)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m0)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Perform ~ 1 + (1 | OrgID)
   Data: perform

REML criterion at convergence: 3560

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.69138 -0.71156 -0.03565  0.73487  2.68864 

Random effects:
 Groups   Name        Variance Std.Dev.
 OrgID    (Intercept) 25.05    5.005   
 Residual             80.34    8.964   
Number of obs: 487, groups:  OrgID, 23

Fixed effects:
            Estimate Std. Error t value
(Intercept)   50.613      1.134   44.64</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ICC</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>varM0 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(m0))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>varM0</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       grp        var1 var2     vcov    sdcor
1    OrgID (Intercept) &lt;NA&gt; 25.05319 5.005316
2 Residual        &lt;NA&gt; &lt;NA&gt; 80.34482 8.963527</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>((varM0[<span class="dv">1</span>,<span class="dv">4</span>]<span class="sc">/</span><span class="fu">sum</span>(varM0[,<span class="dv">4</span>]))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23.77</code></pre>
</div>
</div>
<p>So, around 24% of the variance in our data is at the grouping level, meaning around 76% is at the person level. So clearly we have scope here for explanatory variables of both types.</p>
<p>To begin, we add motivation as a fixed effect:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fixed effect for motivation</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Perform <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Mot <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">|</span> OrgID),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> perform)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Perform ~ 1 + Mot + (1 | OrgID)
   Data: perform

REML criterion at convergence: 3493

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.6341 -0.6969 -0.0137  0.6438  3.2444 

Random effects:
 Groups   Name        Variance Std.Dev.
 OrgID    (Intercept) 20.30    4.506   
 Residual             70.25    8.381   
Number of obs: 487, groups:  OrgID, 23

Fixed effects:
            Estimate Std. Error t value
(Intercept)   46.035      1.159  39.731
Mot            2.453      0.288   8.517

Correlation of Fixed Effects:
    (Intr)
Mot -0.464</code></pre>
</div>
</div>
<p>From this, we can calculate the reduction in the residual variance, or the PRV:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PRV - how much residual variance does motivation account for</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>m1_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(m1)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>varM1 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(m1_sum<span class="sc">$</span>varcor)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>varM1</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       grp        var1 var2     vcov    sdcor
1    OrgID (Intercept) &lt;NA&gt; 20.30283 4.505866
2 Residual        &lt;NA&gt; &lt;NA&gt; 70.24540 8.381253</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(((varM0[<span class="dv">2</span>,<span class="dv">4</span>]<span class="sc">-</span>varM1[<span class="dv">2</span>,<span class="dv">4</span>])<span class="sc">/</span>varM0[<span class="dv">2</span>,<span class="dv">4</span>])<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.57</code></pre>
</div>
</div>
<p>Not bad, so there is a 12.5% reduction in level 1 residual variance from the inclusion of motivation. The coefficient is positive, which is what we would hope to see, motivated employees have better performance.</p>
<p>We will do all of our model comparisons in one go at the end of our model building, so let’s continue. Next, is a random slope (as evidenced by our plots above) for motivation.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Random slope</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Perform <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Mot <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Mot <span class="sc">|</span> OrgID),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> perform)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Perform ~ 1 + Mot + (1 + Mot | OrgID)
   Data: perform

REML criterion at convergence: 3393.7

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.27286 -0.69631 -0.00381  0.66058  2.82123 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 OrgID    (Intercept) 62.10    7.881         
          Mot         18.06    4.250    -0.84
 Residual             50.88    7.133         
Number of obs: 487, groups:  OrgID, 23

Fixed effects:
            Estimate Std. Error t value
(Intercept)  46.0257     1.7571  26.195
Mot           2.0031     0.9351   2.142

Correlation of Fixed Effects:
    (Intr)
Mot -0.834</code></pre>
</div>
</div>
<p>And now we can look to compare the set of models before adding the predictors:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0, m1, m2)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: perform
Models:
m0: Perform ~ 1 + (1 | OrgID)
m1: Perform ~ 1 + Mot + (1 | OrgID)
m2: Perform ~ 1 + Mot + (1 + Mot | OrgID)
   npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
m0    3 3568.1 3580.7 -1781.0   3562.1                         
m1    4 3502.2 3518.9 -1747.1   3494.2 67.894  1  &lt; 2.2e-16 ***
m2    6 3409.1 3434.2 -1698.5   3397.1 97.087  2  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>In each case, adding the additional parameters has improved our model, so we will keep them all.</p>
<p>Our big interest here is in whether organisations being public or private changes the relationship of motivation to performance. For this, we will want to include the cross level interaction between <code>Mot</code> and <code>PubPri</code>.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Perform <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Mot <span class="sc">+</span> PubPri <span class="sc">+</span> Mot<span class="sc">*</span>PubPri <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Mot <span class="sc">|</span> OrgID),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> perform)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Perform ~ 1 + Mot + PubPri + Mot * PubPri + (1 + Mot | OrgID)
   Data: perform

REML criterion at convergence: 3384.4

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.29012 -0.69613 -0.02848  0.65620  2.76816 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 OrgID    (Intercept) 63.44    7.965         
          Mot         18.62    4.315    -0.86
 Residual             50.91    7.135         
Number of obs: 487, groups:  OrgID, 23

Fixed effects:
                 Estimate Std. Error t value
(Intercept)       45.2718     2.1765  20.800
Mot                1.7909     1.1737   1.526
PubPripublic       2.4448     3.7569   0.651
Mot:PubPripublic   0.5623     1.9904   0.283

Correlation of Fixed Effects:
            (Intr) Mot    PbPrpb
Mot         -0.853              
PubPripublc -0.579  0.494       
Mt:PbPrpblc  0.503 -0.590 -0.848</code></pre>
</div>
</div>
<p>The <em>t</em>-values here are pretty small. This doesn’t look like the added effects have contributed much to our model.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model comparison</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2,m3)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: perform
Models:
m2: Perform ~ 1 + Mot + (1 + Mot | OrgID)
m3: Perform ~ 1 + Mot + PubPri + Mot * PubPri + (1 + Mot | OrgID)
   npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
m2    6 3409.1 3434.2 -1698.5   3397.1                     
m3    8 3410.1 3443.6 -1697.1   3394.1 2.9908  2     0.2242</code></pre>
</div>
</div>
<p>And indeed our model comparison suggests not. But wait a minute, we forgot about something….</p>
<p>…we need to center our predictors.</p>
<p>Let’s create variables which are the group mean motivation, and the group-mean centered motivation.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>perform <span class="ot">&lt;-</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  perform <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(OrgID) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mot_m =</span> <span class="fu">mean</span>(Mot, <span class="at">na.rm=</span>T),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mot_c =</span> Mot <span class="sc">-</span> <span class="fu">mean</span>(Mot, <span class="at">na.rm=</span>T)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> ungroup</span></code></pre></div>
</details>
</div>
<p>And re-run the models:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Perform <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Mot_m <span class="sc">+</span> Mot_c <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Mot_c <span class="sc">|</span> OrgID),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> perform)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Perform <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Mot_m <span class="sc">+</span> Mot_c <span class="sc">+</span> PubPri <span class="sc">+</span> Mot_c<span class="sc">*</span>PubPri <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Mot_c <span class="sc">|</span> OrgID),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> perform)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m4,m5)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: perform
Models:
m4: Perform ~ 1 + Mot_m + Mot_c + (1 + Mot_c | OrgID)
m5: Perform ~ 1 + Mot_m + Mot_c + PubPri + Mot_c * PubPri + (1 + Mot_c | OrgID)
   npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
m4    7 3413.8 3443.2 -1699.9   3399.8                     
m5    9 3414.6 3452.3 -1698.3   3396.6 3.1947  2     0.2024</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: Perform ~ 1 + Mot_m + Mot_c + PubPri + Mot_c * PubPri + (1 +  
    Mot_c | OrgID)
   Data: perform

REML criterion at convergence: 3383.8

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.38702 -0.70580 -0.02145  0.64741  2.79873 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 OrgID    (Intercept) 19.96    4.467         
          Mot_c       18.62    4.315    -0.09
 Residual             51.01    7.142         
Number of obs: 487, groups:  OrgID, 23

Fixed effects:
                   Estimate Std. Error t value
(Intercept)         45.2647     3.2271  14.027
Mot_m                2.1373     1.8199   1.174
Mot_c                1.7695     1.1752   1.506
PubPripublic         4.1109     2.4320   1.690
Mot_c:PubPripublic   0.6012     1.9967   0.301

Correlation of Fixed Effects:
            (Intr) Mot_m  Mot_c  PbPrpb
Mot_m       -0.925                     
Mot_c       -0.028 -0.001              
PubPripublc  0.269 -0.497  0.039       
Mt_c:PbPrpb  0.020 -0.003 -0.589 -0.064</code></pre>
</div>
</div>
<p>What do you notice about the results? Spend a little bit of time comparing the effects (fixed and random) and see the changes that result from centering a variable. Remember that our interpretation of the conditional main effects is the effect of a predictor on the outcome when the interacting variable = 0. Zero for Mot_c is average motivation, and zero for PubPri is public sector. So for every unit increase in motivation within a public centre organisation, performance increases by 1.77 units.</p>
</section>
</section>
<section id="check-model" class="level1">
<h1>Check model</h1>
<p>I might be a little concerned about homoscedasticity here. The variance is a bit narrower at the tail ends:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m5, <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.)))<span class="sc">~</span><span class="fu">fitted</span>(.), <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_04_cross_sectional_multilevel_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqmath</span>(m5)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_04_cross_sectional_multilevel_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot.ranef.mer</span>(<span class="fu">ranef</span>(m5))</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$OrgID</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_04_cross_sectional_multilevel_files/figure-html/unnamed-chunk-17-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(robustlmm)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>m5r <span class="ot">&lt;-</span> <span class="fu">rlmer</span>(Perform <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Mot_m <span class="sc">+</span> Mot_c <span class="sc">+</span> PubPri <span class="sc">+</span> Mot_c<span class="sc">*</span>PubPri <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Mot_c <span class="sc">|</span> OrgID),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> perform)</span></code></pre></div>
</details>
</div>
</section>
<section id="visualise-model" class="level1">
<h1>Visualise model</h1>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m5, <span class="at">type=</span><span class="st">"pred"</span>,<span class="at">terms=</span><span class="fu">c</span>(<span class="st">"Mot_m"</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_04_cross_sectional_multilevel_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m5, <span class="at">type=</span><span class="st">"pred"</span>, <span class="at">terms=</span><span class="fu">c</span>(<span class="st">"Mot_c"</span>,<span class="st">"PubPri"</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_04_cross_sectional_multilevel_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpret-model" class="level1">
<h1>Interpret model</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>