<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - Analysis Example 3: Many trials</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-left')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-left')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR3</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-multi-level-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Multi Level Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-multi-level-models">    
        <li>
    <a class="dropdown-item" href="./01_regressionrefresh.html">
 <span class="dropdown-text">1: Linear Regression | Clustered Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02_intromlm.html">
 <span class="dropdown-text">2: Multilevel Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03_assumptranef.html">
 <span class="dropdown-text">3: Assumptions, Diagnostics &amp; Random Effect Structures</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04_centerglmer.html">
 <span class="dropdown-text">4: Centering in MLM | Logistic</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05_recap.html">
 <span class="dropdown-text">5: Recap</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dimension-reduction--sem" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dimension reduction &amp; SEM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dimension-reduction--sem">    
        <li class="dropdown-header">7: Path Analysis</li>
        <li class="dropdown-header">8: Path Mediation</li>
        <li class="dropdown-header">9: Dimension Reduction</li>
        <li class="dropdown-header">10: EFA: Part 1</li>
        <li class="dropdown-header">11: EFA: Part 2</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">Data Wrangling</a></li>
  <li><a href="#descriptives" id="toc-descriptives" class="nav-link" data-scroll-target="#descriptives">Descriptives</a></li>
  <li><a href="#visualizations" id="toc-visualizations" class="nav-link" data-scroll-target="#visualizations">Visualizations</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#equations" id="toc-equations" class="nav-link" data-scroll-target="#equations">Equations</a></li>
  <li><a href="#fitting-the-models" id="toc-fitting-the-models" class="nav-link" data-scroll-target="#fitting-the-models">Fitting the models</a></li>
  <li><a href="#check-models" id="toc-check-models" class="nav-link" data-scroll-target="#check-models">Check model(s)</a></li>
  </ul></li>
  <li><a href="#visualise-models" id="toc-visualise-models" class="nav-link" data-scroll-target="#visualise-models">Visualise model(s)</a></li>
  <li><a href="#interpret-models" id="toc-interpret-models" class="nav-link" data-scroll-target="#interpret-models">Interpret model(s)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis Example 3: Many trials</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="frame">
<p>Each of these pages provides an analysis run through for a different type of design. Each document is structured in the same way:</p>
<ul>
<li>First the data and research context is introduced. For the purpose of these tutorials, we will only use examples where the data can be shared - either because it is from an open access publication, or because it is unpublished or simulated.</li>
<li>Second, we go through any tidying of the data that is required, before creating some brief descriptives and visualizations of the raw data.</li>
<li>Then, we conduct an analysis. Where possible, we translate the research questions into formal equations prior to fitting the models in <strong>lme4</strong>. Model comparisons are conducted, along with checks of distributional assumptions on our model residuals.</li>
<li>Finally, we visualize and interpret our analysis.</li>
</ul>
<p>Please note that there will be only minimal explanation of the steps undertaken here, as these pages are intended as example analyses rather than additional labs readings. Please also be aware that there are many decisions to be made throughout conducting analyses, and it may be the case that you disagree with some of the choices we make here. As always with these things, it is how we justify our choices that is important. We warmly welcome any feedback and suggestions to improve these examples: please email <a href="mailto:ug.ppls.stats@ed.ac.uk">ug.ppls.stats@ed.ac.uk</a>.</p>
</div>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>This data comes from an undergraduate dissertation student. She ran an experiment looking at the way people’s perception of the size of models influences the price they are willing to pay for products. Participants saw a series of pictures of a number of items of clothing. The images had been manipulated so that (a) all pictures were of the same model, and (b) the size of the model differed from a 6 to 16. In total participants saw 54 images. During the study, each picture was presented to participants with a sliding scale from 0 to 100 underneath. Participants simply had to drag the cursor to the appropriate point on the slide to indicate how much they would pay for the garment.</p>
<p>This data was collected using Qualtrics. The resultant output was a wide format data set where each participant (n=120) is a row and each item (n=54) is a column. Along with each of these questions were a series of demographic variables, and two short survey measures assessing participants attitude to thinness.</p>
<p>The main ideas we were interested in looking at were whether:</p>
<ol type="i">
<li>participants would pay more for garments on thinner models</li>
<li>participants would pay more for items when the model size matched their actual size</li>
<li>participants would pay more for items when the model size matched their ideal size</li>
<li>the extent to which participants idealize thin figures would moderate (ii)</li>
</ol>
</section>
<section id="data-wrangling" class="level1">
<h1>Data Wrangling</h1>
<p>Unlike some of our examples, there was some fairly serious data cleaning needed with this data set. So let’s work through it.</p>
<p>The data is available at <a href="https://uoepsy.github.io/data/data_HA.csv">https://uoepsy.github.io/data/data_HA.csv</a></p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://uoepsy.github.io/data/data_HA.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 116
  Respons…¹ Gender   Age Dress…² Top_1…³ Botto…⁴ Dress…⁵ Botto…⁶ Top_6…⁷ Dress…⁸
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 P_ID1001       1    22      45      24      30      30      20      17      15
2 P_ID1002       1    20      30      19       9      52       0       5      16
3 P_ID1003       1    21      30      12       4      18      20       8      12
4 P_ID1004       1    21      39      30      30      45      25      20      25
5 P_ID1005       1    23      10       5      15       7      15       5      20
6 P_ID1006       1    43      40      30      45      60      35      25      30
# … with 106 more variables: Dress_12...11 &lt;dbl&gt;, Bottom_12...12 &lt;dbl&gt;,
#   Top_10...13 &lt;dbl&gt;, Top_8...14 &lt;dbl&gt;, Bottom_6...15 &lt;dbl&gt;,
#   Bottom_8...16 &lt;dbl&gt;, Dress_14...17 &lt;dbl&gt;, Top_16...18 &lt;dbl&gt;,
#   Bottom_6...19 &lt;dbl&gt;, Bottom_14...20 &lt;dbl&gt;, Top_8...21 &lt;dbl&gt;,
#   Dress_8...22 &lt;dbl&gt;, Top_12...23 &lt;dbl&gt;, Top_14...24 &lt;dbl&gt;,
#   Dress_16...25 &lt;dbl&gt;, Top_10...26 &lt;dbl&gt;, Top_14...27 &lt;dbl&gt;,
#   Dress_8...28 &lt;dbl&gt;, Dress_16...29 &lt;dbl&gt;, Bottom_12...30 &lt;dbl&gt;, …
# ℹ Use `colnames()` to see all variable names</code></pre>
</div>
</div>
<p>First things first, let’s use a handy package to change all our variable names to a nice easy “snake_case”:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">clean_names</span>(df)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 116
  respons…¹ gender   age dress…² top_1…³ botto…⁴ dress…⁵ botto…⁶ top_6_9 dress…⁷
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 P_ID1001       1    22      45      24      30      30      20      17      15
2 P_ID1002       1    20      30      19       9      52       0       5      16
3 P_ID1003       1    21      30      12       4      18      20       8      12
4 P_ID1004       1    21      39      30      30      45      25      20      25
5 P_ID1005       1    23      10       5      15       7      15       5      20
6 P_ID1006       1    43      40      30      45      60      35      25      30
# … with 106 more variables: dress_12_11 &lt;dbl&gt;, bottom_12_12 &lt;dbl&gt;,
#   top_10_13 &lt;dbl&gt;, top_8_14 &lt;dbl&gt;, bottom_6_15 &lt;dbl&gt;, bottom_8_16 &lt;dbl&gt;,
#   dress_14_17 &lt;dbl&gt;, top_16_18 &lt;dbl&gt;, bottom_6_19 &lt;dbl&gt;, bottom_14_20 &lt;dbl&gt;,
#   top_8_21 &lt;dbl&gt;, dress_8_22 &lt;dbl&gt;, top_12_23 &lt;dbl&gt;, top_14_24 &lt;dbl&gt;,
#   dress_16_25 &lt;dbl&gt;, top_10_26 &lt;dbl&gt;, top_14_27 &lt;dbl&gt;, dress_8_28 &lt;dbl&gt;,
#   dress_16_29 &lt;dbl&gt;, bottom_12_30 &lt;dbl&gt;, dress_6_31 &lt;dbl&gt;,
#   bottom_14_32 &lt;dbl&gt;, bottom_8_33 &lt;dbl&gt;, top_16_34 &lt;dbl&gt;, …
# ℹ Use `colnames()` to see all variable names</code></pre>
</div>
</div>
<p>Our next job is to cut out a few variables that we will not work with in this example. These are a set of questions asking about clothing preferences. They all end in <code>p</code> and appear at the end of the data set.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">ends_with</span>(<span class="st">"p"</span>))</span></code></pre></div>
</details>
</div>
<p>Now we want to create scores for the two surveys scored using Likert-type scales. We’re going to take the means of these scales as our scores:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TI score</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  df1 <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"_tii"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowMeans</span>(., <span class="at">na.rm=</span>T) <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(df1, <span class="at">tii_score =</span> .)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># MA score</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  df1 <span class="sc">%&gt;%</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"_mo"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowMeans</span>(., <span class="at">na.rm=</span>T) <span class="sc">%&gt;%</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(df1, <span class="at">ma_score =</span> .)</span></code></pre></div>
</details>
</div>
<p>Next, we need to make some changes to the coding of current and ideal size</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  df1 <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">c.size =</span> <span class="fu">recode</span>(current_size, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">16</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">i.size =</span> <span class="fu">recode</span>(ideal_size,  <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">16</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
</div>
<p>Always sensible to check our changes:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(current_size, ideal_size, c.size, i.size)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 120 × 4
   current_size ideal_size c.size i.size
          &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1            3          2     10      8
 2            1          1      6      6
 3            2          1      8      6
 4            2          1      8      6
 5            3          2     10      8
 6            4          3     12     10
 7            3          2     10      8
 8            2          2      8      8
 9            5          3     14     10
10            3          2     10      8
# … with 110 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>Excellent, that has worked.</p>
<p>Our next step (and this one is not strictly necessary) is that we are going to aggregate over the different types of top, bottoms and dresses. We could treat each individual garment of clothing as exactly that, but in this instance it was decided that this was not of interest, and to simplify the models, we would create scores for each broad category by size.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  df1 <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">top_S6 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"top_6"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">top_S8 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"top_8"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">top_S10 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"top_10"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">top_S12 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"top_12"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">top_S14 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"top_14"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">top_S16 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"top_16"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">bottom_S6 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"bottom_6"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">bottom_S8 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"bottom_8"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">bottom_S10 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"bottom_10"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">bottom_S12 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"bottom_12"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">bottom_S14 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"bottom_14"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">bottom_S16 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"bottom_16"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">dress_S6 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"dress_6"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">dress_S8 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"dress_8"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">dress_S10 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"dress_10"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">dress_S12 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"dress_12"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">dress_S14 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"dress_14"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">dress_S16 =</span> <span class="fu">rowMeans</span>(.[<span class="fu">names</span>(df1)[<span class="fu">grepl</span>(<span class="st">"dress_16"</span>,<span class="fu">names</span>(df1))]]),</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>         )</span></code></pre></div>
</details>
</div>
<p>At this point, our next big step is to make the data long. But I am also going to make this a little more manageable by trimming out the variables we do not need. We want ID and age, gender is constant (all female sample), so we do not need this, and then we want the variables we have just created.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  df1 <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(response_id, age, <span class="dv">99</span><span class="sc">:</span><span class="dv">120</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>df2</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 120 × 24
   response_id   age tii_s…¹ ma_sc…² c.size i.size top_S6 top_S8 top_S10 top_S12
   &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 P_ID1001       22    2.63    1.78     10      8  20.7    16.3    21.7   20   
 2 P_ID1002       20    3       2.44      6      6   7.67   12.3    10     17.3 
 3 P_ID1003       21    2.6     1.78      8      6  16.7    10.3     9     11.7 
 4 P_ID1004       21    2.27    1.78      8      6  23.3    20      18.3   23.3 
 5 P_ID1005       23    2.87    2.56     10      8   6.33   10.7    11      8.33
 6 P_ID1006       43    2.73    2.22     12     10  28.3    25      41.7   30   
 7 P_ID1007       55    2.93    1.89     10      8  23.3    28.3    23.3   23.3 
 8 P_ID1008       20    3.03    2.11      8      8  21.3    20.7    19     23   
 9 P_ID1009       48    2.7     2.89     14     10  45.7    20.3    26.7   57   
10 P_ID1010       21    2.37    2        10      8  15.3    16.7    18.3   13.3 
# … with 110 more rows, 14 more variables: top_S14 &lt;dbl&gt;, top_S16 &lt;dbl&gt;,
#   bottom_S6 &lt;dbl&gt;, bottom_S8 &lt;dbl&gt;, bottom_S10 &lt;dbl&gt;, bottom_S12 &lt;dbl&gt;,
#   bottom_S14 &lt;dbl&gt;, bottom_S16 &lt;dbl&gt;, dress_S6 &lt;dbl&gt;, dress_S8 &lt;dbl&gt;,
#   dress_S10 &lt;dbl&gt;, dress_S12 &lt;dbl&gt;, dress_S14 &lt;dbl&gt;, dress_S16 &lt;dbl&gt;, and
#   abbreviated variable names ¹​tii_score, ²​ma_score
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
</div>
<p>OK, now we need to get the data from wide to long format.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df_long <span class="ot">&lt;-</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  df2 <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(top_S6<span class="sc">:</span>dress_S16, <span class="at">names_to =</span> <span class="st">"garment"</span>,<span class="at">values_to =</span> <span class="st">"price"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>df_long</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,160 × 8
   response_id   age tii_score ma_score c.size i.size garment    price
   &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
 1 P_ID1001       22      2.63     1.78     10      8 top_S6      20.7
 2 P_ID1001       22      2.63     1.78     10      8 top_S8      16.3
 3 P_ID1001       22      2.63     1.78     10      8 top_S10     21.7
 4 P_ID1001       22      2.63     1.78     10      8 top_S12     20  
 5 P_ID1001       22      2.63     1.78     10      8 top_S14     15.3
 6 P_ID1001       22      2.63     1.78     10      8 top_S16     17  
 7 P_ID1001       22      2.63     1.78     10      8 bottom_S6   21.7
 8 P_ID1001       22      2.63     1.78     10      8 bottom_S8   18  
 9 P_ID1001       22      2.63     1.78     10      8 bottom_S10  30  
10 P_ID1001       22      2.63     1.78     10      8 bottom_S12  20  
# … with 2,150 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>This looks good, but we now need to have variables that code for size and item type.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df_analysis <span class="ot">&lt;-</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  df_long <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(garment, <span class="fu">c</span>(<span class="st">"item"</span>, <span class="st">"size"</span>), <span class="st">"_S"</span>)</span></code></pre></div>
</details>
</div>
<p>And check….</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df_analysis</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,160 × 9
   response_id   age tii_score ma_score c.size i.size item   size  price
   &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;dbl&gt;
 1 P_ID1001       22      2.63     1.78     10      8 top    6      20.7
 2 P_ID1001       22      2.63     1.78     10      8 top    8      16.3
 3 P_ID1001       22      2.63     1.78     10      8 top    10     21.7
 4 P_ID1001       22      2.63     1.78     10      8 top    12     20  
 5 P_ID1001       22      2.63     1.78     10      8 top    14     15.3
 6 P_ID1001       22      2.63     1.78     10      8 top    16     17  
 7 P_ID1001       22      2.63     1.78     10      8 bottom 6      21.7
 8 P_ID1001       22      2.63     1.78     10      8 bottom 8      18  
 9 P_ID1001       22      2.63     1.78     10      8 bottom 10     30  
10 P_ID1001       22      2.63     1.78     10      8 bottom 12     20  
# … with 2,150 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>Finally, our last couple of steps. First, we want to calculate a couple of binary variables that code whether a give item being rated matches a participants actual or ideal size; second, we need to make our item variable a factor, and third, let’s standardize our scale scores for idealization of thinness.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df_analysis <span class="ot">&lt;-</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  df_analysis <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">c.match =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(c.size <span class="sc">==</span> size, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">i.match =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(i.size <span class="sc">==</span> size, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sizefactor =</span> <span class="fu">factor</span>(size, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"6"</span>,<span class="st">"8"</span>,<span class="st">"10"</span>,<span class="st">"12"</span>,<span class="st">"14"</span>,<span class="st">"16"</span>)),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fu">scale</span>(<span class="fu">as.numeric</span>(<span class="fu">as.character</span>(size))),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">item =</span> <span class="fu">as.factor</span>(item),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> response_id,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">tii_scorez =</span> <span class="fu">scale</span>(tii_score),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">ma_scorez =</span> <span class="fu">scale</span>(ma_score)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>df_analysis[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span><span class="sc">:</span><span class="dv">11</span>)]</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,160 × 8
   response_id c.size i.size item   size[,1] price c.match i.match
   &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt; &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;   &lt;fct&gt;  
 1 P_ID1001        10      8 top      -1.46   20.7 0       0      
 2 P_ID1001        10      8 top      -0.878  16.3 0       1      
 3 P_ID1001        10      8 top      -0.293  21.7 1       0      
 4 P_ID1001        10      8 top       0.293  20   0       0      
 5 P_ID1001        10      8 top       0.878  15.3 0       0      
 6 P_ID1001        10      8 top       1.46   17   0       0      
 7 P_ID1001        10      8 bottom   -1.46   21.7 0       0      
 8 P_ID1001        10      8 bottom   -0.878  18   0       1      
 9 P_ID1001        10      8 bottom   -0.293  30   1       0      
10 P_ID1001        10      8 bottom    0.293  20   0       0      
# … with 2,150 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<div class="imp">
<p>There’s a debate to be had about whether we should consider our <code>size</code> variable to be numeric or a factor. It could be argued that the sizes of clothing are distinct categories, and that the scale might not be regular (e.g.&nbsp;size 10 is not the same amount bigger than size 8 as size 8 is from size 6). On the other hand, clothing sizes can also be considered points on an underlying latent continuous variable, which might lead you to want to treat it as numeric. Personally, I would want to know exactly how the participants were presented with the sizes - if they were shown the images and the size of the garment was made explicit for each item, then I would be inclined to consider them distinct categories. However, if participants were not explicitly aware of the size of each item, and it was only the size of the model they saw that varied in their size, I am tempted to treat it numerically.</p>
</div>
</section>
<section id="descriptives" class="level1">
<h1>Descriptives</h1>
<p>Let’s look at the average price paid by item type and size:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_analysis <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(size, item) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">price =</span> <span class="fu">mean</span>(price, <span class="at">na.rm=</span>T)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(item)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 3
# Groups:   size [6]
   size[,1] item   price
      &lt;dbl&gt; &lt;fct&gt;  &lt;dbl&gt;
 1   -1.46  bottom  26.1
 2   -0.878 bottom  25.7
 3   -0.293 bottom  23.7
 4    0.293 bottom  24.0
 5    0.878 bottom  24.1
 6    1.46  bottom  22.5
 7   -1.46  dress   28.2
 8   -0.878 dress   27.3
 9   -0.293 dress   26.2
10    0.293 dress   27.3
11    0.878 dress   25.8
12    1.46  dress   26.5
13   -1.46  top     18.6
14   -0.878 top     18.1
15   -0.293 top     20.0
16    0.293 top     19.1
17    0.878 top     19.2
18    1.46  top     19.3</code></pre>
</div>
</div>
<p>This looks a lot like we are seeing difference, averaged across all participants, in the price they would pay for different types of garment, but not a lot of difference by size.</p>
<p>We can also calculate the ICC’s</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span><span class="sc">|</span>id) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>item),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_analysis)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>ICC <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(m0))</span></code></pre></div>
</details>
</div>
<p>For participant:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>((ICC[<span class="dv">1</span>,<span class="dv">4</span>]<span class="sc">/</span><span class="fu">sum</span>(ICC[,<span class="dv">4</span>]))<span class="sc">*</span><span class="dv">100</span>, <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53.99</code></pre>
</div>
</div>
<p>And item:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>((ICC[<span class="dv">2</span>,<span class="dv">4</span>]<span class="sc">/</span><span class="fu">sum</span>(ICC[,<span class="dv">4</span>]))<span class="sc">*</span><span class="dv">100</span>, <span class="dv">2</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.36</code></pre>
</div>
</div>
<p>So we can see we have a lot of between person variation, and some between item variation in our data. This suggests that there is potential value in our level 2 predictors concerning both the items and between person characteristics.</p>
</section>
<section id="visualizations" class="level1">
<h1>Visualizations</h1>
<p>There are too many ways to visualize this data! Here are just a few:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_analysis, <span class="fu">aes</span>(<span class="at">x=</span>c.size, <span class="at">y=</span>price,<span class="at">col=</span>sizefactor))<span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>)<span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"path"</span>)<span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>item)<span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"actual size"</span>,<span class="at">y=</span><span class="st">"price would pay"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_analysis, <span class="fu">aes</span>(<span class="at">x=</span>i.size, <span class="at">y=</span>price,<span class="at">col=</span>sizefactor))<span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>)<span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"path"</span>)<span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>item)<span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"ideal size"</span>,<span class="at">y=</span><span class="st">"price would pay"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Remember, however, that we had some research questions to consider!</p>
<ol type="i">
<li>participants would pay more for garments on thinner models</li>
</ol>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_analysis, <span class="fu">aes</span>(<span class="at">x=</span>sizefactor, <span class="at">y=</span>price))<span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>()<span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"item size"</span>,<span class="at">y=</span><span class="st">"price would pay"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="i">
<li>participants would pay more for items when the model size matched their actual size</li>
</ol>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_analysis, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">factor</span>(c.match), <span class="at">y=</span>price))<span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>()<span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"item size matches actual size"</span>,<span class="at">y=</span><span class="st">"price would pay"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="i">
<li>participants would pay more for items when the model size matched their ideal size</li>
</ol>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_analysis, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">factor</span>(i.match), <span class="at">y=</span>price))<span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>()<span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"item size matches ideal size"</span>,<span class="at">y=</span><span class="st">"price would pay"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="i">
<li>the extent to which participants idealize thin figures would moderate (ii)</li>
</ol>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_analysis, <span class="fu">aes</span>(<span class="at">x=</span>tii_scorez, <span class="at">y=</span>price))<span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>,<span class="fu">aes</span>(<span class="at">group=</span>id))<span class="sc">+</span> <span class="co"># want a mean per participant, rather than each individual point</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>c.match)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"thinness idealization score"</span>,<span class="at">y=</span><span class="st">"price would pay"</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$x
[1] "thinness idealization score"

$y
[1] "price would pay"

attr(,"class")
[1] "labels"</code></pre>
</div>
</div>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="equations" class="level2">
<h2 class="anchored" data-anchor-id="equations">Equations</h2>
<div class="imp">
<p>Why <code>item</code> as a fixed effect and not by-item random intercepts (e.g.<code>(1 | item)</code>)? It is debatable how you decide to treat item here. It could be argued that the different item types (dress/top/bottom, etc) represent a sample from some broader population of garment types, and as such should be modeled as random effects (especially given that we are not interested in specific parameter estimates for differences between item types).</p>
<p>However, we only have 3 different types of item, and it is important to remember that having <code>(1|item)</code> will involve estimating variance components based on these. Variance estimates will be less stable with such a small number of groups. There’s no hard rule to follow here about “how many groups is enough” (some people suggest 5 or 6 at least), but personally I would be inclined to use item as a fixed effect.</p>
<p>We should also consider the possibility that certain items should be less desirable to purchase when in a smaller/bigger size. It may be that size differences are more salient, or more influential on our outcome variable, for certain types of item over others. This would involve adding the interaction between size and item type</p>
</div>
$$
<span class="math display">\[\begin{aligned}
  \operatorname{price}_{i[j]}  =&amp; \beta_{0i} +
  \beta_{1i}(\operatorname{item-size}_j) +
  \beta_{1}(\operatorname{item-type}_j) + \\
  &amp; \beta_{2}(\operatorname{item-size}_j \times \operatorname{item-type}_j) + \\
  &amp; \beta_{3i}(\operatorname{matches-actual-size}_j) + \\
  &amp; \beta_{4}(\operatorname{matches-ideal-size}_j) + \varepsilon_{i[j]}\\
  \qquad \\
  
  \beta_{0i} &amp;= \gamma_{00} + \gamma_{01}(\operatorname{thin-idealisation-score}_i) + \zeta_{0i} \\
  \beta_{1i} &amp;= \gamma_{10} + \zeta_{1i}\\
  \beta_{3i} &amp;= \gamma_{30} + \gamma_{31}(\operatorname{thin-idealisation-score}_i)\\
  &amp; \text{for participant i = 1, } \dots \text{, I} \\
\end{aligned}\]</span>
<p>$$</p>
</section>
<section id="fitting-the-models" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-models">Fitting the models</h2>
<p>We’re going to want to do lots of model comparisons, and for those we need all our models to be fitted on the same data. We’re going to use these variables:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df_analysis <span class="ot">&lt;-</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  df_analysis <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(size),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(item),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(c.match),</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(i.match),</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(tii_scorez),</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(id),</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(price)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
</details>
</div>
<p>First, the effect of size. We’re going to treat size as a numeric variable here, in part because it makes our models less complex. It also allows us to model by-participant random effects of size (you can think of this as modeling participants as varying in the amount to which size influences the amount that they are prepared to pay).</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> item <span class="sc">+</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span><span class="sc">+</span>size<span class="sc">|</span>id),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_analysis)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> item <span class="sc">+</span> size <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> size<span class="sc">|</span>id),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_analysis)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: price ~ 1 + item + size + (1 + size | id)
   Data: df_analysis

REML criterion at convergence: 14045.7

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.5003 -0.5885 -0.0396  0.5259  5.1435 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 id       (Intercept) 62.130   7.882         
          size         2.371   1.540    -0.07
 Residual             33.570   5.794         
Number of obs: 2130, groups:  id, 120

Fixed effects:
            Estimate Std. Error t value
(Intercept)  24.3845     0.7517  32.439
itemdress     2.6468     0.3081   8.590
itemtop      -5.3352     0.3073 -17.360
size         -0.4893     0.1887  -2.593

Correlation of Fixed Effects:
          (Intr) itmdrs itemtp
itemdress -0.204              
itemtop   -0.205  0.500       
size      -0.051  0.000  0.001</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0, m1)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: df_analysis
Models:
m0: price ~ 1 + item + (1 + size | id)
m1: price ~ 1 + item + size + (1 + size | id)
   npar   AIC   BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)  
m0    7 14065 14104 -7025.3    14051                       
m1    8 14060 14105 -7022.0    14044 6.6082  1    0.01015 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The interaction between size and item:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span>  item <span class="sc">*</span> size <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span><span class="sc">+</span>size<span class="sc">|</span>id),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_analysis)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: price ~ 1 + item * size + (1 + size | id)
   Data: df_analysis

REML criterion at convergence: 14026.4

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.5043 -0.5804 -0.0377  0.5095  5.1433 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 id       (Intercept) 62.135   7.883         
          size         2.392   1.547    -0.07
 Residual             33.240   5.765         
Number of obs: 2130, groups:  id, 120

Fixed effects:
               Estimate Std. Error t value
(Intercept)     24.3870     0.7514  32.454
itemdress        2.6449     0.3066   8.626
itemtop         -5.3370     0.3058 -17.451
size            -1.1062     0.2587  -4.277
itemdress:size   0.4740     0.3071   1.543
itemtop:size     1.3689     0.3058   4.477

Correlation of Fixed Effects:
            (Intr) itmdrs itemtp size   itmdr:
itemdress   -0.203                            
itemtop     -0.204  0.500                     
size        -0.038  0.002  0.002              
itemdrss:sz  0.001 -0.003 -0.002 -0.591       
itemtop:siz  0.001 -0.002 -0.002 -0.594  0.500</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1,m2)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: df_analysis
Models:
m1: price ~ 1 + item + size + (1 + size | id)
m2: price ~ 1 + item * size + (1 + size | id)
   npar   AIC   BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)    
m1    8 14060 14105 -7022.0    14044                         
m2   10 14043 14100 -7011.7    14023 20.613  2  3.341e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>What about the effect of item size matching your current size:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span>  item <span class="sc">*</span> size <span class="sc">+</span> c.match <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span><span class="sc">+</span>size<span class="sc">|</span>id),</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_analysis)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: price ~ 1 + item * size + c.match + (1 + size | id)
   Data: df_analysis

REML criterion at convergence: 14023.1

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.4754 -0.5995 -0.0312  0.5075  5.1647 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 id       (Intercept) 62.145   7.883         
          size         2.317   1.522    -0.08
 Residual             33.233   5.765         
Number of obs: 2130, groups:  id, 120

Fixed effects:
               Estimate Std. Error t value
(Intercept)     24.2782     0.7537  32.214
itemdress        2.6431     0.3066   8.621
itemtop         -5.3374     0.3058 -17.454
size            -1.0747     0.2580  -4.166
c.match1         0.6620     0.3494   1.895
itemdress:size   0.4736     0.3071   1.542
itemtop:size     1.3689     0.3058   4.477

Correlation of Fixed Effects:
            (Intr) itmdrs itemtp size   c.mtc1 itmdr:
itemdress   -0.202                                   
itemtop     -0.203  0.500                            
size        -0.048  0.002  0.002                     
c.match1    -0.076 -0.003 -0.001  0.064              
itemdrss:sz  0.001 -0.003 -0.002 -0.592  0.000       
itemtop:siz  0.001 -0.002 -0.002 -0.595  0.000  0.500</code></pre>
</div>
</div>
<p>Compare models for current size match:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2,m3)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: df_analysis
Models:
m2: price ~ 1 + item * size + (1 + size | id)
m3: price ~ 1 + item * size + c.match + (1 + size | id)
   npar   AIC   BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)  
m2   10 14043 14100 -7011.7    14023                       
m3   11 14042 14104 -7009.9    14020 3.5856  1    0.05828 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Or your ideal size:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> item <span class="sc">*</span> size <span class="sc">+</span> c.match <span class="sc">+</span> i.match <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span><span class="sc">+</span>size<span class="sc">|</span>id),</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_analysis)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: price ~ 1 + item * size + c.match + i.match + (1 + size | id)
   Data: df_analysis

REML criterion at convergence: 14021.9

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.4705 -0.5911 -0.0355  0.5049  5.1828 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 id       (Intercept) 62.171   7.885         
          size         2.281   1.510    -0.08
 Residual             33.244   5.766         
Number of obs: 2130, groups:  id, 120

Fixed effects:
               Estimate Std. Error t value
(Intercept)     24.2167     0.7556  32.050
itemdress        2.6439     0.3066   8.622
itemtop         -5.3369     0.3058 -17.450
size            -1.0264     0.2606  -3.938
c.match1         0.5972     0.3539   1.688
i.match1         0.4308     0.3650   1.180
itemdress:size   0.4736     0.3071   1.542
itemtop:size     1.3685     0.3058   4.475

Correlation of Fixed Effects:
            (Intr) itmdrs itemtp size   c.mtc1 i.mtc1 itmdr:
itemdress   -0.202                                          
itemtop     -0.203  0.500                                   
size        -0.058  0.002  0.002                            
c.match1    -0.064 -0.003 -0.001  0.038                     
i.match1    -0.069  0.002  0.001  0.156 -0.160              
itemdrss:sz  0.001 -0.003 -0.002 -0.586 -0.001  0.000       
itemtop:siz  0.001 -0.002 -0.002 -0.589  0.000 -0.001  0.500
optimizer (nloptwrap) convergence code: 0 (OK)
Model failed to converge with max|grad| = 0.00383895 (tol = 0.002, component 1)</code></pre>
</div>
</div>
<p>Compare models for ideal size match:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m3,m4)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: df_analysis
Models:
m3: price ~ 1 + item * size + c.match + (1 + size | id)
m4: price ~ 1 + item * size + c.match + i.match + (1 + size | id)
   npar   AIC   BIC  logLik deviance Chisq Df Pr(&gt;Chisq)
m3   11 14042 14104 -7009.9    14020                    
m4   12 14042 14110 -7009.2    14018 1.399  1     0.2369</code></pre>
</div>
</div>
<p>Fixed effects for thin ideals:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> item <span class="sc">*</span> size <span class="sc">+</span> c.match <span class="sc">+</span> i.match <span class="sc">+</span> tii_scorez <span class="sc">+</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span><span class="sc">+</span>size<span class="sc">|</span>id),</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_analysis)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: price ~ 1 + item * size + c.match + i.match + tii_scorez + (1 +  
    size | id)
   Data: df_analysis

REML criterion at convergence: 14020.7

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.4719 -0.5907 -0.0357  0.5059  5.1829 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 id       (Intercept) 62.695   7.918         
          size         2.279   1.510    -0.08
 Residual             33.245   5.766         
Number of obs: 2130, groups:  id, 120

Fixed effects:
               Estimate Std. Error t value
(Intercept)    24.21667    0.75848  31.928
itemdress       2.64389    0.30664   8.622
itemtop        -5.33684    0.30584 -17.450
size           -1.02641    0.26060  -3.939
c.match1        0.59704    0.35388   1.687
i.match1        0.43085    0.36497   1.181
tii_scorez     -0.07229    0.73246  -0.099
itemdress:size  0.47367    0.30714   1.542
itemtop:size    1.36846    0.30582   4.475

Correlation of Fixed Effects:
            (Intr) itmdrs itemtp size   c.mtc1 i.mtc1 t_scrz itmdr:
itemdress   -0.201                                                 
itemtop     -0.202  0.500                                          
size        -0.058  0.002  0.002                                   
c.match1    -0.064 -0.003 -0.001  0.038                            
i.match1    -0.068  0.002  0.001  0.156 -0.160                     
tii_scorez   0.000  0.000 -0.001  0.001  0.003 -0.001              
itemdrss:sz  0.001 -0.003 -0.002 -0.587 -0.001  0.000  0.000       
itemtop:siz  0.001 -0.002 -0.002 -0.589  0.000 -0.001  0.000  0.500</code></pre>
</div>
</div>
<p>Compare models for thin ideal:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m4,m5)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: df_analysis
Models:
m4: price ~ 1 + item * size + c.match + i.match + (1 + size | id)
m5: price ~ 1 + item * size + c.match + i.match + tii_scorez + (1 + size | id)
   npar   AIC   BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
m4   12 14042 14110 -7009.2    14018                     
m5   13 14044 14118 -7009.2    14018 0.0099  1     0.9208</code></pre>
</div>
</div>
<p>Do they interact?</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>m6 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(price <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> item <span class="sc">*</span> size <span class="sc">+</span> c.match <span class="sc">+</span> i.match <span class="sc">+</span> tii_scorez <span class="sc">+</span> c.match<span class="sc">*</span>tii_scorez <span class="sc">+</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span><span class="sc">+</span>size<span class="sc">|</span>id),</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df_analysis)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m6)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: price ~ 1 + item * size + c.match + i.match + tii_scorez + c.match *  
    tii_scorez + (1 + size | id)
   Data: df_analysis

REML criterion at convergence: 14019.8

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.4672 -0.5966 -0.0323  0.5021  5.1910 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 id       (Intercept) 62.679   7.917         
          size         2.281   1.510    -0.08
 Residual             33.243   5.766         
Number of obs: 2130, groups:  id, 120

Fixed effects:
                    Estimate Std. Error t value
(Intercept)         24.20683    0.75845  31.916
itemdress            2.64336    0.30663   8.621
itemtop             -5.33608    0.30584 -17.448
size                -1.02537    0.26062  -3.934
c.match1             0.56650    0.35506   1.595
i.match1             0.51739    0.37448   1.382
tii_scorez          -0.01563    0.73458  -0.021
itemdress:size       0.47423    0.30713   1.544
itemtop:size         1.36867    0.30581   4.476
c.match1:tii_scorez -0.37423    0.36191  -1.034

Correlation of Fixed Effects:
            (Intr) itmdrs itemtp size   c.mtc1 i.mtc1 t_scrz itmdr: itmtp:
itemdress   -0.201                                                        
itemtop     -0.202  0.500                                                 
size        -0.056  0.002  0.002                                          
c.match1    -0.063 -0.003 -0.001  0.037                                   
i.match1    -0.070  0.002  0.002  0.153 -0.173                            
tii_scorez  -0.001  0.000  0.000  0.001 -0.003  0.016                     
itemdrss:sz  0.001 -0.003 -0.002 -0.586 -0.001  0.001  0.000              
itemtop:siz  0.001 -0.002 -0.002 -0.589  0.000 -0.001  0.000  0.500       
c.mtch1:t_s  0.013  0.002 -0.002 -0.004  0.082 -0.224 -0.076 -0.002 -0.001</code></pre>
</div>
</div>
<p>And let’s just compare all at once, just for fun:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0,m1,m2,m3,m4,m5,m6)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: df_analysis
Models:
m0: price ~ 1 + item + (1 + size | id)
m1: price ~ 1 + item + size + (1 + size | id)
m2: price ~ 1 + item * size + (1 + size | id)
m3: price ~ 1 + item * size + c.match + (1 + size | id)
m4: price ~ 1 + item * size + c.match + i.match + (1 + size | id)
m5: price ~ 1 + item * size + c.match + i.match + tii_scorez + (1 + size | id)
m6: price ~ 1 + item * size + c.match + i.match + tii_scorez + c.match * tii_scorez + (1 + size | id)
   npar   AIC   BIC  logLik deviance   Chisq Df Pr(&gt;Chisq)    
m0    7 14065 14104 -7025.3    14051                          
m1    8 14060 14105 -7022.0    14044  6.6082  1    0.01015 *  
m2   10 14043 14100 -7011.7    14023 20.6131  2  3.341e-05 ***
m3   11 14042 14104 -7009.9    14020  3.5856  1    0.05828 .  
m4   12 14042 14110 -7009.2    14018  1.3990  1    0.23690    
m5   13 14044 14118 -7009.2    14018  0.0099  1    0.92076    
m6   14 14045 14125 -7008.7    14017  1.0720  1    0.30048    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="check-models" class="level2">
<h2 class="anchored" data-anchor-id="check-models">Check model(s)</h2>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(m1, <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.)))<span class="sc">~</span><span class="fu">fitted</span>(.), <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>)),</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(m2, <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.)))<span class="sc">~</span><span class="fu">fitted</span>(.), <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>)),</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(m3, <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.)))<span class="sc">~</span><span class="fu">fitted</span>(.), <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>)),</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(m4, <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.)))<span class="sc">~</span><span class="fu">fitted</span>(.), <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>)),</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(m5, <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.)))<span class="sc">~</span><span class="fu">fitted</span>(.), <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>)),</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(m6, <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.)))<span class="sc">~</span><span class="fu">fitted</span>(.), <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>)),</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncol=</span><span class="dv">3</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqmath</span>(m1),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqmath</span>(m2),</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqmath</span>(m3),</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqmath</span>(m4),</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqmath</span>(m5),</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qqmath</span>(m6),</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncol=</span><span class="dv">3</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-35-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I might be a little concerned about our assumptions here. The QQplots look a little off in the tails, however, the histograms of residuals make it look okay:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For peace of mind, we could re-do the model comparisons with parametric bootstrapped model comparison for more reliable conclusions. This <em>will</em> assume that the model specified distribution of residuals (<span class="math inline">\(\varepsilon \sim N(0, \sigma_\varepsilon)\)</span>) holds in the population</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pbkrtest)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(m1, m0)</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>           stat df    p.value
LRT    6.605558  1 0.01016610
PBtest 6.605558 NA 0.01098901</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(m2, m1)</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>           stat df      p.value
LRT    20.61468  2 3.338708e-05
PBtest 20.61468 NA 9.990010e-04</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(m3, m2)</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>           stat df    p.value
LRT    3.585967  1 0.05826951
PBtest 3.585967 NA 0.07092907</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(m4, m3)</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>           stat df   p.value
LRT    1.399085  1 0.2368768
PBtest 1.399085 NA 0.2317682</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(m5, m4)</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>             stat df   p.value
LRT    0.00153228  1 0.9687753
PBtest 0.00153228 NA 0.9670330</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(m6, m5)</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>           stat df   p.value
LRT    1.072739  1 0.3003275
PBtest 1.072739 NA 0.2857143</code></pre>
</div>
</div>
</section>
</section>
<section id="visualise-models" class="level1">
<h1>Visualise model(s)</h1>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_model</span>(m6)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot.ranef.mer</span>(<span class="fu">ranef</span>(m6))</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$id</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m6, <span class="at">type =</span> <span class="st">"pred"</span>)<span class="sc">$</span>size</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m6, <span class="at">type =</span> <span class="st">"pred"</span>)<span class="sc">$</span>c.match</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-52-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m6, <span class="at">type =</span> <span class="st">"pred"</span>)<span class="sc">$</span>i.match</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-52-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m6, <span class="at">type =</span> <span class="st">"pred"</span>, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"c.match"</span>,<span class="st">"tii_scorez [-1,0,1]"</span>)) <span class="sc">+</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_path</span>()</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_03_many_trials_files/figure-html/unnamed-chunk-52-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpret-models" class="level1">
<h1>Interpret model(s)</h1>
<div class="int">
<p>The amount that participants indicated they would pay for a garment was modeled using multi-level linear regression models, with by-participant random intercepts and effects of garment size. After adjusting for effects on our outcome due to the garment-type (dress/top/bottom), inclusion of garment size as a fixed predictor was found to improve model fit (Parametric Bootstrap Likelihood Ratio = 6.61, p = 0.011). The effect of garment-size was found to differ between garment-types (inclusion of interaction term LRT 20.61, p &lt;.001). After controlling for garment-type, -size and their interaction, neither the garments’ matching participants’ actual or ideal size, nor the extent to which participants idealized thin figures were found to predict the price they would pay, and the predicted interaction between actual-size matching and idealization of thin figures was not evidenced. Results of the full model are shown in Table 1.</p>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(m6, <span class="at">show.p =</span> F, <span class="at">title=</span><span class="st">"Table 1: Model results. Please note that 95% CIs are not bootstrapped"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">

<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">Table 1: Model results. Please note that 95% CIs are not bootstrapped</caption>
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">&nbsp;</th>
<th colspan="2" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">price</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">CI</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">24.21</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">22.72&nbsp;–&nbsp;25.69</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">item [dress]</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">2.64</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">2.04&nbsp;–&nbsp;3.24</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">item [top]</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-5.34</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-5.94&nbsp;–&nbsp;-4.74</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">size</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.03</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.54&nbsp;–&nbsp;-0.51</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">c match [1]</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.57</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.13&nbsp;–&nbsp;1.26</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">i match [1]</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.52</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.22&nbsp;–&nbsp;1.25</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">tii scorez</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.02</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.46&nbsp;–&nbsp;1.42</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">item [dress] * size</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.47</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.13&nbsp;–&nbsp;1.08</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">item [top] * size</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">1.37</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.77&nbsp;–&nbsp;1.97</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">c match [1] * tii scorez</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-0.37</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">-1.08&nbsp;–&nbsp;0.34</td>
</tr>
<tr>
<td colspan="3" style="font-weight:bold; text-align:left; padding-top:.8em;">Random Effects</td>
</tr>

<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">σ<sup>2</sup></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">33.24</td>
</tr>

<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">τ<sub>00</sub> <sub>id</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">62.68</td>

</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">τ<sub>11</sub> <sub>id.size</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">2.28</td>

</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ρ<sub>01</sub> <sub>id</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">-0.08</td>

</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ICC</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">0.66</td>

</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">N <sub>id</sub></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">120</td>
</tr><tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="2">2130</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="2">0.106 / 0.697</td>
</tr>

</tbody></table>

</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>