<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DAPR3 - Analysis Example: Intervention</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-hand-o-right')) {
    f.classList.add('fa-hand-o-left')
    f.classList.remove('fa-hand-o-right')
} else {
    f.classList.add('fa-hand-o-right')
    f.classList.remove('fa-hand-o-left')
}
}
</script>

<script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR3</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-multi-level-models" role="button" data-bs-toggle="dropdown" aria-expanded="false">Multi Level Models</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-multi-level-models">    
        <li>
    <a class="dropdown-item" href="./01_regressionrefresh.html">
 <span class="dropdown-text">1: Linear Regression | Clustered Data</span></a>
  </li>  
        <li class="dropdown-header">2: Multilevel Models</li>
        <li class="dropdown-header">3: Assumptions, Diagnostics &amp; Random Effect Structures</li>
        <li class="dropdown-header">4: Centering in MLM | Logistic</li>
        <li class="dropdown-header">5: Recap</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dimension-reduction--sem" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dimension reduction &amp; SEM</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dimension-reduction--sem">    
        <li class="dropdown-header">7: Path Analysis</li>
        <li class="dropdown-header">8: Path Mediation</li>
        <li class="dropdown-header">9: Dimension Reduction</li>
        <li class="dropdown-header">10: EFA: Part 1</li>
        <li class="dropdown-header">11: EFA: Part 2</li>
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">Data Wrangling</a></li>
  <li><a href="#descriptives" id="toc-descriptives" class="nav-link" data-scroll-target="#descriptives">Descriptives</a></li>
  <li><a href="#visualizations" id="toc-visualizations" class="nav-link" data-scroll-target="#visualizations">Visualizations</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#equations" id="toc-equations" class="nav-link" data-scroll-target="#equations">Equations</a></li>
  <li><a href="#fitting-the-models" id="toc-fitting-the-models" class="nav-link" data-scroll-target="#fitting-the-models">Fitting the models</a></li>
  <li><a href="#check-model" id="toc-check-model" class="nav-link" data-scroll-target="#check-model">Check Model</a></li>
  </ul></li>
  <li><a href="#visualise-model" id="toc-visualise-model" class="nav-link" data-scroll-target="#visualise-model">Visualise Model</a></li>
  <li><a href="#interpret-model" id="toc-interpret-model" class="nav-link" data-scroll-target="#interpret-model">Interpret model</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis Example: Intervention</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="frame">
<p>Each of these pages provides an analysis run through for a different type of design. Each document is structured in the same way:</p>
<ul>
<li>First the data and research context is introduced. For the purpose of these tutorials, we will only use examples where the data can be shared - either because it is from an open access publication, or because it is unpublished or simulated.</li>
<li>Second, we go through any tidying of the data that is required, before creating some brief descriptives and visualizations of the raw data.</li>
<li>Then, we conduct an analysis. Where possible, we translate the research questions into formal equations prior to fitting the models in <strong>lme4</strong>. Model comparisons are conducted, along with checks of distributional assumptions on our model residuals.</li>
<li>Finally, we visualize and interpret our analysis.</li>
</ul>
<p>Please note that there will be only minimal explanation of the steps undertaken here, as these pages are intended as example analyses rather than additional labs readings. Please also be aware that there are many decisions to be made throughout conducting analyses, and it may be the case that you disagree with some of the choices we make here. As always with these things, it is how we justify our choices that is important. We warmly welcome any feedback and suggestions to improve these examples: please email <a href="mailto:ug.ppls.stats@ed.ac.uk">ug.ppls.stats@ed.ac.uk</a>.</p>
</div>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>Intervention studies are where the researchers <em>intervenes</em> (e.g.&nbsp;through administration of a drug or treatment) as part of the study</p>
<p>The data used for this worked example are simulated to represent data from 50 participants, each measured at 3 different time-points (pre, during, and post) on a measure of stress. Half of the participants are in the control group, and half are in the treatment group (e.g.&nbsp;half received some cognitive behavioural therapy (CBT), half did not).</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">983</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>simMIX <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ppt =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">paste</span>(<span class="st">"ID"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>, <span class="at">sep=</span><span class="st">""</span>),<span class="at">each=</span><span class="dv">3</span>)),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ppt_int =</span> <span class="fu">rep</span>(<span class="fu">rnorm</span>(<span class="dv">50</span>,<span class="dv">0</span>,<span class="dv">15</span>), <span class="at">each=</span><span class="dv">3</span>), </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">stress =</span> <span class="fu">round</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">75</span>,<span class="fu">c</span>(<span class="dv">50</span>,<span class="dv">45</span>,<span class="dv">42</span>),<span class="at">sd=</span><span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">5</span>)),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">rnorm</span>(<span class="dv">75</span>,<span class="fu">c</span>(<span class="dv">55</span>,<span class="dv">30</span>,<span class="dv">20</span>),<span class="at">sd=</span><span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">10</span>, <span class="dv">5</span>))) <span class="sc">+</span> ppt_int,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="fu">as_factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Pre"</span>, <span class="st">"During"</span>, <span class="st">"Post"</span>), <span class="dv">50</span>)),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">as_factor</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Control"</span>, <span class="dv">75</span>), <span class="fu">rep</span>(<span class="st">"Treatment"</span>, <span class="dv">75</span>)))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>ppt_int)</span></code></pre></div>
</details>
</div>
</section>
<section id="data-wrangling" class="level1">
<h1>Data Wrangling</h1>
<p>Because we simulated our data, it is already nice and tidy. Each observation is a row, and we have variable indicating participant identifier (the <code>ppt</code> variable).</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simMIX)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      ppt          stress           time          group   
 ID1    :  3   Min.   :-13.00   Pre   :50   Control  :75  
 ID10   :  3   1st Qu.: 29.00   During:50   Treatment:75  
 ID11   :  3   Median : 43.00   Post  :50                 
 ID12   :  3   Mean   : 42.22                             
 ID13   :  3   3rd Qu.: 55.75                             
 ID14   :  3   Max.   : 90.00                             
 (Other):132                                              </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(<span class="fu">head</span>(simMIX), <span class="fu">tail</span>(simMIX))</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
   ppt   stress time   group    
   &lt;fct&gt;  &lt;dbl&gt; &lt;fct&gt;  &lt;fct&gt;    
 1 ID1       65 Pre    Control  
 2 ID1       81 During Control  
 3 ID1       55 Post   Control  
 4 ID2       62 Pre    Control  
 5 ID2       57 During Control  
 6 ID2       67 Post   Control  
 7 ID49      58 Pre    Treatment
 8 ID49      34 During Treatment
 9 ID49      25 Post   Treatment
10 ID50      35 Pre    Treatment
11 ID50      21 During Treatment
12 ID50       0 Post   Treatment</code></pre>
</div>
</div>
</section>
<section id="descriptives" class="level1">
<h1>Descriptives</h1>
<p>We now have two factors of interest, scores over <code>Time</code> and by <code>Group</code>. So we do our descriptive statistics by multiple grouping factors.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sumMIX <span class="ot">&lt;-</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  simMIX <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(time, group) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n_distinct</span>(ppt),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean =</span> <span class="fu">round</span>(<span class="fu">mean</span>(stress, <span class="at">na.rm=</span>T),<span class="dv">2</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(stress, <span class="at">na.rm=</span>T),<span class="dv">2</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(sumMIX) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="st">"striped"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> time </th>
   <th style="text-align:left;"> group </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> Mean </th>
   <th style="text-align:right;"> SD </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Pre </td>
   <td style="text-align:left;"> Control </td>
   <td style="text-align:right;"> 25 </td>
   <td style="text-align:right;"> 52.84 </td>
   <td style="text-align:right;"> 14.60 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Pre </td>
   <td style="text-align:left;"> Treatment </td>
   <td style="text-align:right;"> 25 </td>
   <td style="text-align:right;"> 54.76 </td>
   <td style="text-align:right;"> 16.78 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> During </td>
   <td style="text-align:left;"> Control </td>
   <td style="text-align:right;"> 25 </td>
   <td style="text-align:right;"> 49.64 </td>
   <td style="text-align:right;"> 13.23 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> During </td>
   <td style="text-align:left;"> Treatment </td>
   <td style="text-align:right;"> 25 </td>
   <td style="text-align:right;"> 30.44 </td>
   <td style="text-align:right;"> 15.49 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Post </td>
   <td style="text-align:left;"> Control </td>
   <td style="text-align:right;"> 25 </td>
   <td style="text-align:right;"> 46.08 </td>
   <td style="text-align:right;"> 14.24 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Post </td>
   <td style="text-align:left;"> Treatment </td>
   <td style="text-align:right;"> 25 </td>
   <td style="text-align:right;"> 19.56 </td>
   <td style="text-align:right;"> 15.99 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="visualizations" class="level1">
<h1>Visualizations</h1>
<p>We can use a violin plot to visualize our data.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>simMIX <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>time, <span class="at">y=</span>stress, <span class="at">color=</span>group, <span class="at">fill=</span>group))  <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> .<span class="dv">25</span>) <span class="sc">+</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_dotplot</span>(<span class="at">binaxis=</span><span class="st">'y'</span>, <span class="at">stackdir=</span><span class="st">'center'</span>, <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="dv">1</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">dotsize =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Time"</span>, <span class="at">y =</span> <span class="st">"Stress Score"</span>, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"Stress over Time by Treat Vs Control"</span>, <span class="at">color=</span><span class="st">"Condition"</span>, <span class="at">fill=</span><span class="st">"Condition"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is useful to note that the violin plot contains much of the same information that a more traditional boxplot would have, but provides more information on the actual distribution with groups as it draws on density plots.</p>
<p>What we can see here is that over time, the control group shows little change, but the treatment group shows distinct declines.<br>
We can also consider line plots with separate facets for each condition:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>simMIX <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>time, <span class="at">y=</span>stress, <span class="at">col=</span>group))  <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">3</span>, <span class="at">alpha=</span>.<span class="dv">4</span>)<span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group=</span>ppt), <span class="at">alpha=</span>.<span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"pointrange"</span>, <span class="at">col=</span><span class="st">"black"</span>)<span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>group)<span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Time"</span>, <span class="at">y =</span> <span class="st">"Stress Score"</span>, </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title=</span><span class="st">"Stress over Time by Treat Vs Control"</span>, <span class="at">color=</span><span class="st">"Condition"</span>, <span class="at">fill=</span><span class="st">"Condition"</span>)<span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="equations" class="level2">
<h2 class="anchored" data-anchor-id="equations">Equations</h2>
<p><span class="math display">\[
\begin{aligned}
  \operatorname{stress}_{i[j]}  &amp;= \beta_{0i} + \beta_{1i}(\operatorname{timeDuring}_j) + \beta_{2i}(\operatorname{timePost}_j) + \varepsilon_{i[j]} \\
  \beta_{0i} &amp;= \gamma_{00} + \gamma_{01}(\operatorname{groupTreatment}_i) + \zeta_{0i} \\
  \beta_{1i} &amp;= \gamma_{10} + \gamma_{11}(\operatorname{groupTreatment}_i) \\
  \beta_{2i} &amp;= \gamma_{20} + \gamma_{21}(\operatorname{groupTreatment}_i) \\
  &amp; \text{for ppt i = 1,} \dots \text{, I}
\end{aligned}
\]</span></p>
</section>
<section id="fitting-the-models" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-models">Fitting the models</h2>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code></pre></div>
</details>
</div>
<p>Base model:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(stress <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">|</span> ppt), <span class="at">data =</span> simMIX)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m0)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: stress ~ 1 + (1 | ppt)
   Data: simMIX

REML criterion at convergence: 1286.7

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.02099 -0.49670  0.01511  0.49445  1.96548 

Random effects:
 Groups   Name        Variance Std.Dev.
 ppt      (Intercept) 179.7    13.40   
 Residual             209.7    14.48   
Number of obs: 150, groups:  ppt, 50

Fixed effects:
            Estimate Std. Error t value
(Intercept)   42.220      2.234    18.9</code></pre>
</div>
</div>
<p>Main effects:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(stress <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> time <span class="sc">+</span> group <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">|</span> ppt), <span class="at">data =</span> simMIX)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: stress ~ 1 + time + group + (1 | ppt)
   Data: simMIX

REML criterion at convergence: 1185.9

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.69666 -0.62649  0.01574  0.59245  1.92387 

Random effects:
 Groups   Name        Variance Std.Dev.
 ppt      (Intercept) 166.57   12.91   
 Residual              98.01    9.90   
Number of obs: 150, groups:  ppt, 50

Fixed effects:
               Estimate Std. Error t value
(Intercept)      61.100      3.046  20.061
timeDuring      -13.760      1.980  -6.950
timePost        -20.980      1.980 -10.596
groupTreatment  -14.600      3.992  -3.657

Correlation of Fixed Effects:
            (Intr) tmDrng timPst
timeDuring  -0.325              
timePost    -0.325  0.500       
groupTrtmnt -0.655  0.000  0.000</code></pre>
</div>
</div>
<p>Interaction:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(stress <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> time <span class="sc">+</span> group <span class="sc">+</span> time<span class="sc">*</span>group <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">|</span> ppt), <span class="at">data =</span> simMIX)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: stress ~ 1 + time + group + time * group + (1 | ppt)
   Data: simMIX

REML criterion at convergence: 1096.5

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.83946 -0.53326 -0.05639  0.53766  2.31546 

Random effects:
 Groups   Name        Variance Std.Dev.
 ppt      (Intercept) 184.82   13.595  
 Residual              43.26    6.577  
Number of obs: 150, groups:  ppt, 50

Fixed effects:
                          Estimate Std. Error t value
(Intercept)                 52.840      3.020  17.494
timeDuring                  -3.200      1.860  -1.720
timePost                    -6.760      1.860  -3.634
groupTreatment               1.920      4.272   0.449
timeDuring:groupTreatment  -21.120      2.631  -8.028
timePost:groupTreatment    -28.440      2.631 -10.810

Correlation of Fixed Effects:
            (Intr) tmDrng timPst grpTrt tmDr:T
timeDuring  -0.308                            
timePost    -0.308  0.500                     
groupTrtmnt -0.707  0.218  0.218              
tmDrng:grpT  0.218 -0.707 -0.354 -0.308       
tmPst:grpTr  0.218 -0.354 -0.707 -0.308  0.500</code></pre>
</div>
</div>
<div class="frame">
<p><strong>Comparison with <code>aov()</code></strong></p>
<p>As we did with the simple repeated measures, we can also compare the sums of squares breakdown for the LMM (<code>m2</code>) by calling <code>anova()</code> on the <code>lmer()</code> model.</p>
<p>First with <code>aov()</code>:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(stress <span class="sc">~</span> time <span class="sc">+</span> group <span class="sc">+</span> time<span class="sc">*</span>group <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">Error</span>(ppt), <span class="at">data =</span> simMIX)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: ppt
          Df Sum Sq Mean Sq F value   Pr(&gt;F)    
group      1   7993    7993   13.37 0.000633 ***
Residuals 48  28691     598                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
           Df Sum Sq Mean Sq F value Pr(&gt;F)    
time        2  11360    5680  131.31 &lt;2e-16 ***
time:group  2   5452    2726   63.01 &lt;2e-16 ***
Residuals  96   4153      43                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>And then summarise:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m2)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table
           npar  Sum Sq Mean Sq F value
time          2 11360.4  5680.2 131.305
group         1   578.5   578.5  13.373
time:group    2  5452.0  2726.0  63.014</code></pre>
</div>
</div>
</div>
<p>For ease, lets compare all models with a parametric bootstrap likelihood ratio test:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pbkrtest)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(m1, m0)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">PBmodcomp</span>(m2, m1)</span></code></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Bootstrap test; time: 44.99 sec; samples: 1000; extremes: 0;
large : stress ~ 1 + time + group + (1 | ppt)
stress ~ 1 + (1 | ppt)
         stat df   p.value    
LRT    90.348  3 &lt; 2.2e-16 ***
PBtest 90.348     0.000999 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Bootstrap test; time: 46.25 sec; samples: 1000; extremes: 0;
large : stress ~ 1 + time + group + time * group + (1 | ppt)
stress ~ 1 + time + group + (1 | ppt)
         stat df   p.value    
LRT    83.853  2 &lt; 2.2e-16 ***
PBtest 83.853     0.000999 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>And extract some bootstrap 95% CIs</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m2,<span class="at">method=</span><span class="st">"boot"</span>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                               2.5 %      97.5 %
.sig01                     11.063915  16.8989137
.sigma                      5.570576   7.3318954
(Intercept)                46.958215  58.9035049
timeDuring                 -6.598935  -0.1161317
timePost                  -10.473009  -3.1302747
groupTreatment             -7.001190  10.0517531
timeDuring:groupTreatment -26.395306 -16.1101659
timePost:groupTreatment   -33.665532 -23.2588741</code></pre>
</div>
</div>
</section>
<section id="check-model" class="level2">
<h2 class="anchored" data-anchor-id="check-model">Check Model</h2>
<p>The residuals look reasonably normally distributed, and there seems to be fairly constant variance across the linear predictor. We might be a little concerned about the potential tails of the plot below, at which residuals don’t appear to have a mean of zero</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m2, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"p"</span>,<span class="st">"smooth"</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m2, <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.)))<span class="sc">~</span><span class="fu">fitted</span>(.))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqmath</span>(m2)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/unnamed-chunk-16-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Random effects are (roughly) normally distributed:</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>rans <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">ranef</span>(m2)<span class="sc">$</span>ppt)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rans, <span class="fu">aes</span>(<span class="at">sample =</span> <span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"random intercept"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="visualise-model" class="level1">
<h1>Visualise Model</h1>
<div class="cell" data-layout-align="center">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m2, <span class="at">type=</span><span class="st">"int"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m2, <span class="at">type=</span><span class="st">"re"</span>) <span class="co"># an alternative: dotplot.ranef.mer(ranef(m1))</span></span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpret-model" class="level1">
<h1>Interpret model</h1>
<div class="cell" data-layout-align="center">

</div>
<div class="int">
<p>Stress at each study time-point (pre-, during- and post-intervention) was modeled using linear mixed effects models, with by-participant random intercepts, and the incremental addition of time, condition (control vs treatment) and their interaction. An interaction between time and condition improved model fit over the model without the interaction (Parametric bootstrap LRT 83.85, p &lt; .001), suggesting that patterns of change over time in stress levels differed for the treatment group from the control group.<br>
Result show that for the control group, stress did not show clear change between time-points 1 and 2 (-3.2, 95% CI [-6.92 – 0.32]), but by time-point 3 had reduced relative to time-point 1 by -6.76 [-10.58 – -3.3] points. Prior to the intervention (time-point 1), the treatment group did not appear to differ from the control group with respect to their level of stress, but showed an <em>additional</em> -21.12 [-26.75 – -15.63] point change by time-point 2 and -28.44 [-33.75 – -23.23] points by the end of the study (time-point 3). This pattern of results is shown in Figure 1.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="example_02_intervention_files/figure-html/res-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Stress levels over time for control and treatment groups, with bootstrap prediction intervals (R = 2000)</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>