project:
  render: 
    - "*.qmd"
    - "!*liver.qmd"
    - "!todo/*"
  output-dir: ../../docs/2425/lectures

subtitle: "Data Analysis for Psychology in R 3"
author: "Dr John Martindale"
institute:
  - "Psychology, PPLS"
  - "University of Edinburgh"
format:
  revealjs:
    theme: [default, _theme/mystyle.scss]
    css: img/css/wizard.css
    width: 1294
    height: 1000
    transition: fade
    slide-number: true
    preview-links: auto
    include-after-body: _theme/clean_title_page.html
    callout-appearance: simple
    code-line-numbers: false
    code-overflow: wrap
    code-annotations: hover
    code-copy: hover
    classoption: fleqn
    chalkboard: true
revealjs-plugins:
  - attribution
filters: 
  - "_theme/inverse_part.lua"
  - line-highlight
highlight-style: breeze
title-slide-attributes:
  data-background-color: "#88B04B"
  data-background-image: img/logo.svg
  data-background-size: 25%
  data-background-position: 2% 2%
execute:
  warning: false
  echo: true
  message: false
  fig-format: svg
include-in-header: _theme/highlighter.js
