---
title: "Analysis Example 5: Longitudinal Growth Model"
output:
  html_document:
    code_folding: show
    theme: flatly
    toc: yes
    toc_depth: 3
    toc_float: yes
    css: assets/style-labs.css
---
```{r setup, include=F}
knitr::opts_chunk$set(message = F, warning = F, fig.align = 'center')
```

:::frame

Each of these pages provides an analysis run through for a different type of design. Each document is structured in the same way:  

  - First the data is introduced. For the purpose of these tutorials, I will only use examples where the data can be shared - either because it is from an open access publication, or because it is unpublished or simulated. 
  - Second, the structure of the data is discussed so that we can more easily see what data structure the design creates, and how this aligns to the variables in the data.
  - Third, we translate the research questions into formal equations, and then `lmer()` code. 
  - Finally, we will follow those through for our example data.

:::

# Overview

# Data Wrangling

# Descriptives

# Visualisations

# Analysis
## Equations

## Fitting the models

# Check model

# Visualise model

# Interpret Model