---
title: "Resources"
output:
  html_document:
    theme: flatly
    toc: yes
    toc_depth: 3
    toc_float: yes
    css: assets/style-labs.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Visualisations, Blogposts, Tutorials  

---

Michael Clark: Mixed Models with R tutorial: https://m-clark.github.io/mixed-models-with-R/  

---

Tristan Mahr: Shrinkage in Mixed Models Blogpost: https://www.tjmahr.com/plotting-partial-pooling-in-mixed-effects-models/  

---

A really lovely visualisation by Michael Freeman: http://mfviz.com/hierarchical-models/  

---

Some handy datasets if you want some data to play with: https://multilevel-analysis.sites.uu.nl/datasets/ 

---

Lisa DeBruine created the excellent [faux](https://cran.r-project.org/web/packages/faux/index.html) package which you can use to simulate some mixed factorial design data. You can find a tutorial here: https://debruine.github.io/faux/articles/sim_mixed.html  
<br><br>

## Papers   

---

Hoffman, L., & Walters, R. W. (in press). Catching up on multilevel modeling. Forthcoming in Annual Review of Psychology (73).  

+ preprint available at https://psyarxiv.com/j8x9k 

---

Meteyard, L., & Davies, R. A. (2020). Best practice guidance for linear mixed-effects models in psychological science. Journal of Memory and Language, 112, 104092.

+ Access via institutional login: at https://doi.org/10.1016/j.jml.2020.104092 

---
    
McNeish D, Stapleton LM, Silverman RD. On the unnecessary ubiquity of hierarchical linear modeling. Psychol Methods. 2017 Mar;22(1):114-140. doi: 10.1037/met0000078. Epub 2016 May 5. PMID: 27149401. 

+ available on [researchgate](https://www.researchgate.net/publication/292091130_On_the_Unnecessary_Ubiquity_of_Hierarchical_Linear_Modeling)

---

Sander Greenland, Principles of multilevel modelling, International Journal of Epidemiology, Volume 29, Issue 1, April 2000, Pages 158–167, https://doi.org/10.1093/ije/29.1.158

+ OpenAccess: https://academic.oup.com/ije/article/29/1/158/666823 

---

Bell, A., Fairbrother, M. & Jones, K. Fixed and random effects models: making an informed choice. Qual Quant 53, 1051–1074 (2019). https://doi.org/10.1007/s11135-018-0802-x

+ OpenAccess: https://link.springer.com/article/10.1007%2Fs11135-018-0802-x

---
    
Bell, A., Jones, K. & Fairbrother, M. Understanding and misunderstanding group mean centering: a commentary on Kelley et al.’s dangerous practice. Qual Quant 52, 2031–2036 (2018). https://doi.org/10.1007/s11135-017-0593-5

+ OpenAccess: https://link.springer.com/article/10.1007%2Fs11135-017-0593-5

---