{
  "hash": "8565d5a9b042946dcb5c0e2046da0595",
  "result": {
    "markdown": "---\ntitle: \"4. Random Effect Structures | Logistic MLM\"\nparams: \n    SHOW_SOLS: TRUE\n    TOGGLE: TRUE\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n### Nested and Crossed structures\n\nThe same principle we have seen for one level of clustering can be extended to clustering at different levels (for instance, observations are clustered within subjects, which are in turn clustered within groups). \n\nConsider the example where we have observations for each student in every class within a number of schools:  \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/structure_nestednew.png){fig-align='center' width=1200px}\n:::\n:::\n\n\n**Question:** Is \"Class 1\" in \"School 1\" the same as \"Class 1\" in \"School 2\"?  \n  \nNo.  \nThe classes in one school are distinct from the classes in another **even though they are named the same**.  \n  \nThe classes-within-schools example is a good case of **nested random effects** - one factor level (one group in a grouping varible) appears *only within* a particular level of another grouping variable.  \n  \nIn R, we can specify this using:  \n  \n`(1 | school) + (1 | class:school)`  \n  \nor, more succinctly:  \n  \n`(1 | school/class)`  \n\nConsider another example, where we administer the same set of tasks for every participant.  \n  \n**Question:** Are tasks nested within participants?  \n  \nNo.  \nTasks are seen by multiple participants (and participants see multiple tasks).  \n  \nWe could visualise this as the below:  \n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/structure_crossednew.png){fig-align='center' width=400px}\n:::\n:::\n\n\nIn the sense that these are not nested, they are **crossed** random effects.  \n  \nIn R, we can specify this using:  \n\n`(1 | subject) + (1 | task)`  \n\n:::blue\n**Nested vs Crossed**  \n\n*Nested:* Each group belongs uniquely to a higher-level group.   \n\n*Crossed:* Not-nested. \n\n:::\n\nNote that in the schools and classes example, had we changed data such that the classes had unique IDs (e.g., see below), then the structures `(1 | school) + (1 | class)` and `(1 | school/class)` would give the same results.  \n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/structure_nestedlabnew.png){fig-align='center' width=1200px}\n:::\n:::\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n### Random Effects in lme4  \n\nBelow are a selection of different formulas for specifying different random effect structures, taken from the [lme4 vignette](https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf). This might look like a lot, but over time and repeated use of multilevel models you will get used to reading these in a similar way to getting used to reading the formula structure of `y ~ x1 + x2` in all our linear models. \n<br>\n\n|  Formula|  Alternative|  Meaning|\n|--------:|------------:|--------:|\n|  $\\text{(1 | g)}$|  $\\text{1 + (1 | g)}$|  Random intercept with fixed mean|\n|  $\\text{(1 | g1/g2)}$|  $\\text{(1 | g1) + (1 | g1:g2)}$|  Intercept varying among $g1$, and $g2$ within $g1$|\n|  $\\text{(1 | g1) + (1 | g2)}$|  $\\text{1 + (1 | g1) + (1 | g2)}$|  Intercept varying among $g1$ and $g2$|\n|  $\\text{x + (x | g)}$|  $\\text{1 + x + (1 + x | g)}$|  Correlated random intercept and slope|\n|  $\\text{x + (x || g)}$|  $\\text{1 + x + (1 | g) + (0 + x | g)}$|  Uncorrelated random intercept and slope|\n  \n**Table 1:** Examples of the right-hand-sides of mixed effects model formulas. $g$, $g1$, $g2$ are grouping factors, $x$ is a predictor variable.\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n### Singular fits\n\nYou may have noticed that some of our models over the last few weeks have been giving a warning: `boundary (singular) fit: see ?isSingular`.   \nUp to now, we've been largely ignoring these warnings. However, this week we're going to look at how to deal with this issue.\n\n<p style=\"color:red\">boundary (singular) fit: see ?isSingular</p>\n\nThe warning is telling us that our model has resulted in a 'singular fit'. Singular fits often indicate that the model is 'overfitted' - that is, the random effects structure which we have specified is too complex to be supported by the data.  \n\nPerhaps the most intuitive advice would be remove the most complex part of the random effects structure (i.e. random slopes). This leads to a simpler model that is not over-fitted. In other words, start simplifying from the top (where the most complexity is) to the bottom (where the lowest complexity is).\nAdditionally, when variance estimates are very low for a specific random effect term, this indicates that the model is not estimating this parameter to differ much between the levels of your grouping variable. It might, in some experimental designs, be perfectly acceptable to remove this or simply include it as a fixed effect.\n\nA key point here is that when fitting a mixed model, we should think about how the data are generated. Asking yourself questions such as \"do we have good reason to assume subjects might vary over time, or to assume that they will have different starting points (i.e., different intercepts)?\" can help you in specifying your random effect structure\n\nYou can read in depth about what this means by reading the help documentation for `?isSingular`. For our purposes, a relevant section is copied below:  \n\n*... intercept-only models, or 2-dimensional random effects such as intercept + slope models, singularity is relatively easy to detect because it leads to random-effect variance estimates of (nearly) zero, or estimates of correlations that are (almost) exactly -1 or 1.*\n\n:::\n::: {.callout-note collapse=\"true\"}\n### Convergence warnings  \n\nIssues of non-convergence can be caused by many things. If you're model doesn't converge, it does *not necessarily* mean the fit is incorrect, however it is **is cause for concern**, and should be addressed, else you may end up reporting inferences which do not hold.\n\nThere are lots of different things which you could do which *might* help your model to converge. A select few are detailed below:  \n\n- double-check the model specification and the data  \n\n- adjust stopping (convergence) tolerances for the nonlinear optimizer, using the optCtrl argument to [g]lmerControl. (see `?convergence` for convergence controls). \n    - What is \"tolerance\"? Remember that our optimizer is the the method by which the computer finds the best fitting model, by iteratively assessing and trying to maximise the likelihood (or minimise the loss). \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![An optimizer will stop after a certain number of iterations, or when it meets a tolerance threshold](images/tolerance.png){#fig-tolerance fig-align='center' width=80%}\n:::\n:::\n\n\n- center and scale continuous predictor variables (e.g. with `scale`)  \n\n- Change the optimization method (for example, here we change it to `bobyqa`):\n    `lmer(..., control = lmerControl(optimizer=\"bobyqa\"))`  \n    `glmer(..., control = glmerControl(optimizer=\"bobyqa\"))`  \n\n- Increase the number of optimization steps:\n    `lmer(..., control = lmerControl(optimizer=\"bobyqa\", optCtrl=list(maxfun=50000))`  \n    `glmer(..., control = glmerControl(optimizer=\"bobyqa\", optCtrl=list(maxfun=50000))`  \n\n- Use `allFit()` to try the fit with all available optimizers. This will of course be slow, but is considered 'the gold standard'; *\"if all optimizers converge to values that are practically equivalent, then we would consider the convergence warnings to be false positives.\"*  \n\n- Consider simplifying your model, for example by removing random effects with the smallest variance (but be careful to not simplify more than necessary, and ensure that your write up details these changes)\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n### Model Building\n\nRandom effect structures can get pretty complicated quite quickly. Very often it is not the random effects part that is of specific interest to us, but we wish to estimate random effects in order to more accurately partition up the variance in our outcome variable and provide better estimates of fixed effects.  \n\nIt is a fine balance between fitting the most sophisticated model structure that we possibly can, and fitting a model that converges without too much simplification. Typically for many research designs, the following steps will keep you mostly on track to finding the maximal model:  \n\n`lmer(outcome ~ fixed effects + (random effects | grouping structure))`  \n\n1. Specify the `outcome ~ fixed effects` bit first. \n    - The outcome variable should be clear: it is the variable we are wishing to explain/predict. \n    - The fixed effects are the things we want to use to explain/predict variation in the outcome variable. These will often be the things that are of specific inferential interest, and other covariates. Just like the simple linear model.  \n    \n2. If there is a grouping structure to your data, and those groups (preferably n>7 or 8) are perceived as a random sample of a wider population (the specific groups aren't interesting to you), then consider including random intercepts (and possibly random slopes of predictors) for those groups `(1 | grouping)`.  \n\n3. If there are multiple different grouping structures, is one nested within another? (If so, we can specify this as `(1 | high_level_grouping / low_level_grouping)`.  If the grouping structures are not nested, we specify them as crossed: `(1 | grouping1) + (1 | grouping2)`.  \n\n\n4. If any of the things in the fixed effects vary within the groups, it might be possible to also include them as random effects.  \n    - as a general rule, don't specify random effects that are not also specified as fixed effects (an exception could be specifically for model comparison, to isolate the contribution of the fixed effect).  \n    - For things that do not vary within the groups, it rarely makes sense to include them as random effects. For instance if we had a model with `lmer(score ~ genetic_status + (1 + genetic_status | patient))` then we would be trying to model a process where \"the effect of genetic_status on scores is different for each patient\". But if you consider an individual patient, their genetic status never changes. For patient $i$, what is \"the effect of genetic status on score\"? It's undefined. This is because genetic status only varies _between_ patients.\n    - Sometimes, things will vary within one grouping, but not within another. E.g. with patients nested within hospitals `(1 | hospital/patient)`, genetic_status varies _between_ patients, but _within_ hospitals. Therefore we could theoretically fit a random effect of `genetic_status | hospital`, but __not__ one for `genetic_status | patient`.  \n    We can include these while preserving the nested structure of the data by separating out the groupings: `(1 + genetic_status | hospital) + (1 | patient:hospital)`.  \n\n5. A common approach to fitting multilevel models is to fit the most complex model _that the study design allows_. This means including random effects for everything that makes _theoretical_ sense to be included. Because this \"maximal model\" will often not converge, we then simplify our random effect structure to obtain a convergent model.  \nCandidate random effect terms for removal are:\n  - overly complex terms (e.g. `(1 + x1 * x2 | group)` could be simplified to `(1 + x1 + x2 | group)`).  \n  - those with little variance\n  - those with near perfect correlation (we can alternatively remove just the correlation)\n\n6. Obtain final model, and proceed to checking assumptions, checking influence, plotting, and eventually writing up.  \n\n<!-- \n\n<div class=\"optional-begin\"><button id='opt-start-1' class=\"jk-circle-right optional-icon clickable\" onclick=\"toggle_visibility('opt-body-1', 'opt-start-1')\"> An example </button></div><div class=\"optional-body\" id = \"opt-body-1\" style=\"display: none;\">\n\n -->\n<!-- Suppose we were also interested in the association between population density and wellbeing. Our data contains information on the population density for each LAA. Note that for all people in our data that are from the same LAA, they will have the same value in the `density` variable, because this is measured at the LAA level, not the person-level:   -->\n<!-- ```{r} -->\n<!-- scotmw %>%  -->\n<!--   select(laa, density) -->\n<!-- ``` -->\n\n<!-- It doesn't really make sense to have random effects of density by LAA (the `density | laa` bit), because the association `wellbeing ~ density` is the same for _every_ person in that LAA. To say that \"each LAA has a different effect of population density on wellbeing\" is tricky, because we \"effect of density on wellbeing\" isn't really defined for an individual LAA.  -->\n<!-- ```{r} -->\n<!-- #| error: true -->\n<!-- #| message: true -->\n<!-- model_dens <- lmer(wellbeing ~ 1 + outdoor_time + density + -->\n<!--                    (1 + outdoor_time + density | laa), data = scotmw) -->\n<!-- ``` -->\n<!-- The resulting model gives a singular fit, and we can see how this impacts the model estimates in the random effects. The random effect of `density | laa` is much smaller (explaining less variance), and is very highly correlated to the random intercept `1 | laa`, because it doesn't really contain a great deal more information (if you think about the `laa` and `density` columns of the dataset, there is a one-to-one mapping between them). Including the `density | laa` random effect here is not supported by the data.   -->\n<!-- ```{r} -->\n<!-- VarCorr(model_dens) -->\n<!-- ``` -->\n<!-- \n\n</div><p class=\"optional-end\"></p>\n\n -->\n\n:::\n\n<br>\n<div class=\"divider div-transparent div-dot\"></div>\n\n\n\n\n# Exercises: Crossed Ranefs\n\n:::frame\n__Data: Test-enhanced learning__  \n\nAn experiment was run to conceptually replicate \"test-enhanced learning\" (Roediger & Karpicke, 2006): two groups of 25 participants were presented with material to learn. One group studied the material twice (`StudyStudy`), the other group studied the material once then did a test (`StudyTest`). Recall was tested immediately (one minute) after the learning session and one week later. The recall tests were composed of 175 items identified by a keyword (`Test_word`). \n\nThe researchers are interested in how test-enhanced learning influences time-to-recall. The critical (replication) prediction is that the `StudyTest` group will retain the material better (lower reaction times) on the 1-week follow-up test compared to the `StudyStudy` group.  \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> variable </th>\n   <th style=\"text-align:left;\"> description </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Subject_ID </td>\n   <td style=\"text-align:left;\"> Unique Participant Identifier </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Group </td>\n   <td style=\"text-align:left;\"> Group denoting whether the participant studied the material twice (StudyStudy), or studied it once then did a test (StudyTest) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Delay </td>\n   <td style=\"text-align:left;\"> Time of recall test ('min' = Immediate, 'week' = One week later) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Test_word </td>\n   <td style=\"text-align:left;\"> Word being recalled (175 different test words) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Rtime </td>\n   <td style=\"text-align:left;\"> Time to respond (milliseconds) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nThe following code loads the data into your R environment by creating a variable called `tel`:\n```{}\nload(url(\"https://uoepsy.github.io/data/RTtestlearning.RData\"))\n```\n\n:::\n\n\n\n\n<div class='question-begin'>Question 1</div><div class='question-body'>\n\n\nLoad and plot the data.  \n\nFor this week, we'll use Reaction Time as our proxy for the test performance, so you'll probably want that variable on the y-axis.  \n\nDoes it look like the effect was replicated?\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\nOur outcome variable is reaction time, so we'll want to plot that on the y axis.  \n\nAs described in the data summary, this is a replication, and the prediction is that the `StudyTest` group will retain the material better (have lower reaction times) on the 1-week follow-up test compared to the `StudyStudy` group.  \n\nSo we want to show the reaction times for each group, at each test (`min` or `week` delay). Do we want to show _all_ the datapoints, or maybe just the average for each group at each test (in which case, does `stat_summary()` help?).  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-2' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-2', 'sol-start-2')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-2\" style=\"display: none;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nload(url(\"https://uoepsy.github.io/data/RTtestlearning.RData\"))\n```\n:::\n\nYou can make use of `stat_summary()`! \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(telrt, aes(Delay, Rtime, col=Group)) + \n  stat_summary(fun.data=mean_se, geom=\"pointrange\")+\n  theme_light()\n```\n:::\n\nIt's more work, but some people might rather calculate the numbers and then plot them directly. It does just the same thing: \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntelrt %>% \n  group_by(Delay, Group) %>%\n  summarise(\n    mean = mean(Rtime),\n    se = sd(Rtime)/sqrt(n())\n  ) %>%\n  ggplot(., aes(x=Delay, col = Group)) +\n  geom_pointrange(aes(y=mean, ymin=mean-se, ymax=mean+se))+\n  theme_light() +\n  labs(y = \"Response Time (ms)\")\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=80%}\n:::\n:::\n\n  \nThat looks like test-enhanced learning to me!  \n\n\n</div><p class=\"solution-end\"></p>\n\n \n\n\n\n<div class='question-begin'>Question 2</div><div class='question-body'>\n\n\n> The critical (replication) prediction is that the `StudyStudy` group should perform somewhat better on the immediate recall test, but the `StudyTest` group will retain the material better and thus perform better on the 1-week follow-up test.  \n\nTest the critical hypothesis using a multi-level model.  \n**Try** to fit the maximally complex random effect structure that is supported by the experimental design.  \n\n__NOTE: Your model probably won't converge. We'll deal with that in the next question__  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- We can expect variability across subjects (some people are better at learning than others) __and__ across items (some of the recall items are harder than others). How should this be represented in the random effects?\n- _If a model takes ages to fit, you might want to cancel it by pressing the escape key. It is normal for complex models to take time, but for the purposes of this task, give up after a couple of minutes, and try simplifying your model._  \n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-3' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-3', 'sol-start-3')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-3\" style=\"display: none;\">\n\n\nWe know that we are interested in the `Rtime ~ Delay * Group` interaction, because we want to see how people perform at one week vs one minute (the `Delay` variable) and whether this is different between those in each condition (the `Group` variable, specifying whether participants are in the 'StudyStudy' condition or the 'StudyTest' condition).  \n\nWe want to include Subject random effects _and_ Item random effects, and these groupings are crossed, so we're going to have `(1 + ??? | Subject_ID) + (1 + ??? | Test_word)`.  Each subject is only in one group, so we can only have `(1 + Delay | Subject_ID)`, but the Test_word items are seen by subjects in both groups, and at both timepoints, so we can have `(1 + Delay * Group | Test_word)`.  \n\nThis one will probably take a little bit of time:  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm <- lmer(Rtime ~ Delay * Group +\n             (1 + Delay | Subject_ID) +\n             (1 + Delay * Group | Test_word),\n           data=telrt, control=lmerControl(optimizer = \"bobyqa\"))\n```\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n \n\n\n\n<div class='question-begin'>Question 3</div><div class='question-body'>\n\n\nOften, models with maximal random effect structures will not converge, or will obtain a singular fit. So we need to simplify the model until we achieve convergence ([Barr et al., 2013](https://doi.org/10.1016/j.jml.2012.11.001)).  \n\nIncrementally simplify your model from the previous question until you obtain a model that converges and is not a singular fit.  \n  \n::: {.callout-tip collapse=\"true\"}\n#### Hints  \nyou can look at the variance estimates and correlations easily by using the `VarCorr()` function. What jumps out?  \n\nThere's a bit of subjectivity here about which simplifications we can live with, so you might end up with a slightly different model from the solutions, and _that's okay_.  \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n \n\n\n<div class=\"solution-begin\"><button id='sol-start-4' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-4', 'sol-start-4')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-4\" style=\"display: none;\">\n\n\nThere are very high correlations with the by-item random effects of the interaction Delay:Group. We might expect that because it's an interaction term, but it is quite a complex bit of the model, so let's remove it:  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nVarCorr(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Groups     Name                     Std.Dev. Corr                \n Test_word  (Intercept)               17.8641                     \n            Delayweek                 13.2793 -0.251              \n            GroupStudyTest            18.0269 -0.797 -0.385       \n            Delayweek:GroupStudyTest  13.1273  0.972 -0.016 -0.917\n Subject_ID (Intercept)               40.5201                     \n            Delayweek                  7.4482 -0.038              \n Residual                            240.3113                     \n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1 <- lmer(Rtime ~ Delay*Group +\n             (1 + Delay | Subject_ID) +\n             (1 + Delay + Group | Test_word),\n           data=telrt, control=lmerControl(optimizer = \"bobyqa\"))\nVarCorr(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Groups     Name           Std.Dev. Corr         \n Test_word  (Intercept)      0.0000              \n            Delayweek       18.6861    NaN       \n            GroupStudyTest   8.3577    NaN -0.778\n Subject_ID (Intercept)     40.5125              \n            Delayweek        7.3661 -0.036       \n Residual                  240.5318              \n```\n:::\n\n```{.r .cell-code}\nisSingular(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\nWe still have a singular fit here, and we still have quite high^[It's always going to be debateable about what is 'too high' because in certain situations you might expect correlations close to 1. It's best to think through whether it is a feasible value given the study itself] correlations between by-testword random effects. Thinking about the study, if we are going to remove __one__ of the by-testword random effects (`Delay` or `Group`), which one do we consider to be more theoretically justified? Is the effect of Delay likely to vary by test-words? More so than the effect of group is likely to vary by test-words? Quite possibly - there's no obvious reason for _certain_ words to be more memorable for people in one group vs another. But there is reason for words to vary in the effect that delay of one week has - how familiar a word is will likely influence the amount to which a week's delay has on recall.   \n\nLet's remove the by-testword random effect of group. \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm2 <- lmer(Rtime ~ Delay*Group +\n             (1 + Delay | Subject_ID) +\n             (1 + Delay | Test_word),\n           data=telrt, control=lmerControl(optimizer = \"bobyqa\"))\nisSingular(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\nVarCorr(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Groups     Name        Std.Dev. Corr  \n Test_word  (Intercept)  11.6973       \n            Delayweek    13.5692 -0.236\n Subject_ID (Intercept)  40.5155       \n            Delayweek     7.4004 -0.037\n Residual               240.4432       \n```\n:::\n:::\n\nHooray, the model converged! \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: Rtime ~ Delay * Group + (1 + Delay | Subject_ID) + (1 + Delay |  \n    Test_word)\n   Data: telrt\nControl: lmerControl(optimizer = \"bobyqa\")\n\nREML criterion at convergence: 241671.3\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.8200 -0.6685 -0.0096  0.6760  4.0783 \n\nRandom effects:\n Groups     Name        Variance Std.Dev. Corr \n Test_word  (Intercept)   136.83  11.70        \n            Delayweek     184.12  13.57   -0.24\n Subject_ID (Intercept)  1641.51  40.52        \n            Delayweek      54.77   7.40   -0.04\n Residual               57812.93 240.44        \nNumber of obs: 17498, groups:  Test_word, 175; Subject_ID, 50\n\nFixed effects:\n                         Estimate Std. Error t value\n(Intercept)               744.047      8.925  83.363\nDelayweek                  26.766      5.448   4.913\nGroupStudyTest            -18.032     12.560  -1.436\nDelayweek:GroupStudyTest  -17.647      7.566  -2.332\n\nCorrelation of Fixed Effects:\n            (Intr) Delywk GrpStT\nDelayweek   -0.285              \nGropStdyTst -0.704  0.200       \nDlywk:GrpST  0.202 -0.694 -0.288\n```\n:::\n:::\n\n\nLet's quickly visualise the interaction. Remember, lower reaction times are better here. \nIt looks like we have replicated the hypothesised effect:  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sjPlot)\nplot_model(m2, type=\"int\")\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n \n<br>\n<div class=\"divider div-transparent div-dot\"></div>\n\n\n# Exercises: Nested Random Effects\n\n:::frame\n__Data: Naming__ \n\n74 children from 10 schools were administered the full Boston Naming Test (BNT-60) on a yearly basis for 5 years to examine development of word retrieval. Five of the schools taught lessons in a bilingual setting with English as one of the languages, and the remaining five schools taught in monolingual English.  \n\nThe data is available at [https://uoepsy.github.io/data/bntmono.csv](https://uoepsy.github.io/data/bntmono.csv).  \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n-------------------------------------------\n  variable            description          \n------------ ------------------------------\n  child_id      unique child identifier    \n\n school_id      unique school identifier   \n\n   BNT60       score on the Boston Naming  \n              Test-60. Scores range from 0 \n                         to 60             \n\n schoolyear          Year of school        \n\n   mlhome     Mono/Bi-lingual School. 0 =  \n               Bilingual, 1 = Monolingual  \n-------------------------------------------\n:::\n:::\n\n\n:::\n\n\n\n<div class='question-begin'>Question 4</div><div class='question-body'>\n\n\nLet's start by thinking about our clustering - we'd like to know how much of the variance in BNT60 scores is due to the clustering of data within children, who are themselves within schools. One easy way of assessing this is to fit an _intercept only_ model, which has the appropriate random effect structure.  \n\nUsing the model below, calculate the proportion of variance attributable to the clustering of data within children within schools.  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbnt_null <- lmer(BNT60 ~ 1 +  (1 | school_id/child_id), data = bnt)\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nthe random intercept variances are the building blocks here. There are no predictors in this model, so all the variance in the outcome gets attributed to either school-level nesting, child-level nesting, or else is lumped into the residual.   \n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-5' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-5', 'sol-start-5')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-5\" style=\"display: none;\">\n\n\nAs we can see from `summary(bnt_null)`, the random intercept variances are 36.52 for child-level, 28.76 for school-level, and the residual variance is 99.11.  \n\nSo the nesting of data within children within schools accounts for $\\frac{36.52 + 28.76}{36.52 + 28.76 + 99.11} = 0.397$ of the variance in the outcome BNT60.   \n\nWe can calculate this directly using the model estimates if we want, but sometimes doing it by hand is more straightforward.  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.data.frame(VarCorr(bnt_null)) %>%\n  select(grp, vcov) %>% \n  mutate(\n    prop_var = vcov / sum(vcov),\n    prop_var2 = cumsum(prop_var)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 grp     vcov  prop_var prop_var2\n1 child_id:school_id 36.52302 0.2221657 0.2221657\n2          school_id 28.76157 0.1749536 0.3971194\n3           Residual 99.11079 0.6028806 1.0000000\n```\n:::\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 5</div><div class='question-body'>\n\n\nFit a model examining the interaction between the effects of school year and mono/bilingual teaching on word retrieval (via BNT test), with random intercepts only for children and schools.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\nmake sure your variables are of the right type first - e.g. numeric, factor etc  \n:::\n  \n  \nExamine the fit and consider your model assumptions, and assess what might be done to improve the model in order to make better statistical inferences. \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-6' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-6', 'sol-start-6')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-6\" style=\"display: none;\">\n\n\nThis is a quick way to make a set of variables factors:  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbnt <- bnt %>% mutate(across(c(mlhome, school_id, child_id), factor))\n```\n:::\n\n\nAnd now let's fit our model: \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbntm0 <- lmer(BNT60 ~ schoolyear * mlhome + (1 | school_id/child_id), data = bnt)\n```\n:::\n\n\nResiduals don't look zero mean:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(bntm0, type=c(\"p\",\"smooth\"))\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\nIt looks a little like, compared to our model (black lines below) the children's scores (coloured lines) are more closely clustered together when they start school, and then they are more spread out by the end of the study. \nThe fact that we're fitting the same slope for each child is restricting us here, so we should try fitting random effects of schoolyear. \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(broom.mixed)\naugment(bntm0) %>%\n  ggplot(aes(x=schoolyear, col=child_id)) + \n  geom_point(aes(y = BNT60))+\n  geom_path(aes(y = BNT60))+\n  geom_path(aes(y = .fitted), col=\"black\", alpha=.3)+\n  guides(col=\"none\")+\n  facet_wrap(~school_id)\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=80%}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbntm1 <- lmer(BNT60 ~ schoolyear * mlhome + (1 + schoolyear | school_id/child_id), data = bnt)\nplot(bntm1, type=c(\"p\",\"smooth\"))\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=80%}\n:::\n:::\n\nMuch better!  \n\nLet's do some quick diagnostic checks for influence:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(HLMdiag)\ninf1 <- hlm_influence(bntm1, level=1)\ndotplot_diag(inf1$cooksd, cutoff = \"internal\")\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\nIf you check in the help for `dotplot_diag()`, it tells you that\n\na) we can add an index for the labels, and \nb) the coordinates (x,y) are flipped. We're telling R to change the limits of the y axis, but actually it is the x axis. This is just because we want to see the label for that point out to the right. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninfchild <- hlm_influence(bntm1, level=\"child_id:school_id\")\ndotplot_diag(infchild$cooksd, cutoff = \"internal\", index = infchild$`child_id:school_id`) + \n  scale_y_continuous(limits=c(0,.05))\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=80%}\n:::\n:::\n\nAnd then we can examine the effects to the fixed effects and our standard errors when we remove this child:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndel94 <- case_delete(bntm1, level=\"child_id:school_id\", delete = \"ID94:SC9\")\ncbind(del94$fixef.original, del94$fixef.delete)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        [,1]       [,2]\n(Intercept)         6.265626  6.2627962\nschoolyear          6.371168  6.3639335\nmlhome1             0.138711 -0.3052998\nschoolyear:mlhome1 -2.603763 -2.3701181\n```\n:::\n:::\n\n\n\n::: {.callout-note collapse=\"true\"}\n#### Optional: Case deletion influence on standard errors\n\nWe can examine the influence that deleting a case has on the standard errors.\nThe standard errors are the square-root of the diagonal of the model-implied variance-covariance matrix:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncbind( \n  sqrt(diag(del94$vcov.original)),\n  sqrt(diag(del94$vcov.delete))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        [,1]      [,2]\n(Intercept)        1.0413285 0.9557645\nschoolyear         0.7719321 0.6717837\nmlhome1            1.4683927 1.3525492\nschoolyear:mlhome1 1.0875897 0.9498207\n```\n:::\n:::\n\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninfschool <- hlm_influence(bntm1, level=\"school_id\")\ndotplot_diag(infschool$cooksd, cutoff = \"internal\", index = infschool$school_id)\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question 6</div><div class='question-body'>\n\n\nUsing a method of your choosing, conduct inferences (i.e. obtain p-values or confidence intervals) from your final model and write up the results. \n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-7' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-7', 'sol-start-7')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-7\" style=\"display: none;\">\n\n\nWe'll use case-based bootstrapping for a demonstration, but other methods would be appropriate here. We have a large sample of children (74), each with 5 observations. However, we only have 10 schools. A standard likelihood ratio test using `anova(model1, model2)` might not be preferable here.  \n\nThis took quite a while to run: \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lmeresampler)\nbntm1BS <- bootstrap(bntm1, .f=fixef, type = \"case\", B = 2000, resample = c(FALSE,TRUE,FALSE))\nconfint(bntm1BS, type = \"basic\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 6\n  term               estimate lower upper type  level\n  <chr>                 <dbl> <dbl> <dbl> <chr> <dbl>\n1 (Intercept)           6.27   5.41  7.10 basic  0.95\n2 schoolyear            6.37   5.72  7.02 basic  0.95\n3 mlhome1               0.139 -1.12  1.40 basic  0.95\n4 schoolyear:mlhome1   -2.60  -3.62 -1.70 basic  0.95\n```\n:::\n:::\n\n\n\n\n:::int\n\nMultilevel level linear regression was used to investigate childrens' development of word retrieval over 5 years of school, and whether development was dependent upon the school teaching classes monolingually or bilingually. \nInitial evaluation of the intercept-only model indicated that the clustering of multiple observations from children within schools accounted for 39.7% of the variance in scores on the Boston Naming Task (BNT60, range 0 to 60).\nBNT60 scores were modelled with fixed effects of school year (1-5) and monolingual teaching (bilingual vs monolingual, treatment coded with bilingual as the reference level). Random intercepts and slopes of school year were included for schools and for children nested within schools. The model was fitting with maximum likelihood estimation using the default optimiser from the **lme4** package (Bates et al., 2015).  \n95% Confidence for fixed effect estimates were constructed by case-based bootstrapping with 2000 bootstraps in which children, (but neither observations within children nor the schools within which children were nested) were resampled. \nResults indicated that children's scores on the BNT60 increased over the 5 years in which they were studied, with children from bilingual schools increasing in scores by 6.37 ([5.72 -- 7.02]) every school year. There was a significant interaction between mono/bilingual schools and changes over the school year, with children from monolingual schools increasing -2.6 ([-3.62 -- -1.7]) less than those from bilingual schools for every additional year of school. Full model results can be found in Table 1. \n\n:::\n\nTable 1\n\n::: {.cell layout-align=\"center\"}\n<table>\n<tr>\n<th class=\"thead firsttablerow firsttablecol col1\">&nbsp;</th>\n<th colspan=\"2\" class=\"thead firsttablerow\">BNT 60</th>\n</tr>\n<tr>\n<td class=\"depvarhead firsttablerow firsttablecol col1\">Predictors</td>\n<td class=\"depvarhead firsttablerow col2\">Estimates</td>\n<td class=\"depvarhead firsttablerow col3\">95% CI<br>bootstrap</td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">Intercept</td>\n<td class=\"tdata centeralign modelcolumn1 col2\">6.27</td>\n<td class=\"tdata centeralign modelcolumn1 col3\">5.43&nbsp;&ndash;&nbsp;7.12</td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">School Year</td>\n<td class=\"tdata centeralign modelcolumn1 col2\">6.37</td>\n<td class=\"tdata centeralign modelcolumn1 col3\">4.85&nbsp;&ndash;&nbsp;7.89</td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">MonolingualSchool [1]</td>\n<td class=\"tdata centeralign modelcolumn1 col2\">0.14</td>\n<td class=\"tdata centeralign modelcolumn1 col3\">&#45;2.75&nbsp;&ndash;&nbsp;3.03</td>\n</tr>\n<tr>\n<td class=\"tdata firsttablecol col1\">School<br>Year:MonolingualSchool<br>[1]</td>\n<td class=\"tdata centeralign modelcolumn1 col2\">&#45;2.60</td>\n<td class=\"tdata centeralign modelcolumn1 col3\">&#45;4.74&nbsp;&ndash;&nbsp;-0.46</td>\n</tr>\n<tr>\n<td colspan=\"3\" class=\"randomparts\">Random Effects</td>\n</tr>\n\n<tr>\n<td class=\"tdata leftalign summary\">&sigma;<sup>2</sup></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">8.64</td>\n</tr>\n\n<tr>\n<td class=\"tdata leftalign summary\">&tau;<sub>00</sub> <sub>child_id:school_id</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">1.77</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">&tau;<sub>00</sub> <sub>school_id</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">3.83</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">&tau;<sub>11</sub> <sub>child_id:school_id.schoolyear</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">6.83</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">&tau;<sub>11</sub> <sub>school_id.schoolyear</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">1.89</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">&rho;<sub>01</sub> <sub>child_id:school_id</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">-0.42</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">&rho;<sub>01</sub> <sub>school_id</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">-0.39</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">ICC</td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">0.91</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">N <sub>child_id</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">74</td>\n\n<tr>\n<td class=\"tdata leftalign summary\">N <sub>school_id</sub></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">10</td>\n<tr>\n<td class=\"tdata leftalign summary firstsumrow\">Observations</td>\n<td class=\"tdata summary summarydata firstsumrow\" colspan=\"2\">370</td>\n</tr>\n<tr>\n<td class=\"tdata leftalign summary\">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>\n<td class=\"tdata summary summarydata\" colspan=\"2\">0.420 / 0.947</td>\n</tr>\n\n</table>\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effects)\nas.data.frame(effect(\"schoolyear:mlhome\",bntm1)) %>%\n  ggplot(., aes(x=schoolyear,y=fit,col=mlhome))+\n  geom_pointrange(aes(ymin=lower,ymax=upper))+\n  scale_color_manual(NULL,labels=c(\"Bilingual\",\"Monolingual\"),values=c(\"tomato1\",\"navyblue\"))+\n  labs(x=\"- School Year -\", y=\"BNT-60\")\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n<br>\n<div class=\"divider div-transparent div-dot\"></div>\n\n\n# Optional Exercises: Logistic MLM\n\n:::frame\n**Don't forget to look back at other materials!** \n\nBack in DAPR2, we introduced logistic regression in semester 2, week 8. The lab contained some simulated data based on a hypothetical study [about inattentional blindness](https://uoepsy.github.io/dapr2/2122/labs/2_07_binary.html). \nThat content will provide a lot of the groundwork for this week, so we recommend revisiting it if you feel like it might be useful. \n:::\n\n\n::: {.callout-note collapse=\"true\"}\n#### From `lmer()` to `glmer()`\n\nRemember how we simply used `glm()` and could specify the `family = \"binomial\"` in order to fit a logistic regression? Well it's much the same thing for multi-level models! \n\n+ Gaussian model: `lmer(y ~ x1 + x2 + (1 | g), data = data)`  \n+ Binomial model: `glmer(y ~ x1 + x2 + (1 | g), data = data, family = binomial(link='logit'))`\n    + or just `glmer(y ~ x1 + x2 + (1 | g), data = data, family = \"binomial\")`\n    + or `glmer(y ~ x1 + x2 + (1 | g), data = data, family = binomial)`\n  \n:::\n\n\n<!-- \n\n<div class=\"optional-begin\"><button id='opt-start-8' class=\"jk-circle-right optional-icon clickable\" onclick=\"toggle_visibility('opt-body-8', 'opt-start-8')\"> Binary? Binomial? </button></div><div class=\"optional-body\" id = \"opt-body-8\" style=\"display: none;\">\n\n -->\n<!-- For binary regression, all the data in our outcome variable has to be a 0 or a 1.   -->\n<!-- For example, the `correct` variable below:   -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- tibble(participant = c(1,1,1),question=c(1,2,3),correct=c(1,0,1)) %>% rbind(rep(\"...\",3)) %>% -->\n<!--   gt::gt() -->\n<!-- ``` -->\n\n<!-- But we can re-express this information in a different way, when we know the total number of questions asked. -->\n<!-- ```{r} -->\n<!-- #| echo: false -->\n<!-- tibble(participant = c(1,2,3),questions_correct=c(2,1,3),questions_incorrect=c(1,2,0)) %>% rbind(rep(\"...\",3)) %>% gt::gt() -->\n<!-- ``` -->\n\n<!-- To model data when it is in this form, we can express our outcome as `cbind(questions_correct, questions_incorrect)` -->\n<!-- \n\n</div><p class=\"optional-end\"></p>\n\n -->\n\n:::frame\n__Data: Memory Recall & Finger Tapping__ \n\n> **Research Question:** After accounting for effects of sentence length, does the rhythmic tapping of fingers aid memory recall? \n\nResearchers recruited 40 participants. Each participant was tasked with studying and then recalling 10 randomly generated sentences between 1 and 14 words long. For 5 of these sentences, participants were asked to tap their fingers along with speaking the sentence in both the study period and in the recall period. For the remaining 5 sentences, participants were asked to sit still.  \nThe data are available at [https://uoepsy.github.io/data/memorytap.csv](https://uoepsy.github.io/data/memorytap.csv), and contains information on the length (in words) of each sentence, the condition (static vs tapping) under which it was studied and recalled, and whether the participant was correct in recalling it.  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"kdmnvuiydo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kdmnvuiydo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kdmnvuiydo thead, #kdmnvuiydo tbody, #kdmnvuiydo tfoot, #kdmnvuiydo tr, #kdmnvuiydo td, #kdmnvuiydo th {\n  border-style: none;\n}\n\n#kdmnvuiydo p {\n  margin: 0;\n  padding: 0;\n}\n\n#kdmnvuiydo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kdmnvuiydo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kdmnvuiydo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kdmnvuiydo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kdmnvuiydo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kdmnvuiydo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kdmnvuiydo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kdmnvuiydo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kdmnvuiydo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kdmnvuiydo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kdmnvuiydo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kdmnvuiydo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kdmnvuiydo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kdmnvuiydo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kdmnvuiydo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kdmnvuiydo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kdmnvuiydo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kdmnvuiydo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kdmnvuiydo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kdmnvuiydo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kdmnvuiydo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kdmnvuiydo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kdmnvuiydo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kdmnvuiydo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kdmnvuiydo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kdmnvuiydo .gt_left {\n  text-align: left;\n}\n\n#kdmnvuiydo .gt_center {\n  text-align: center;\n}\n\n#kdmnvuiydo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kdmnvuiydo .gt_font_normal {\n  font-weight: normal;\n}\n\n#kdmnvuiydo .gt_font_bold {\n  font-weight: bold;\n}\n\n#kdmnvuiydo .gt_font_italic {\n  font-style: italic;\n}\n\n#kdmnvuiydo .gt_super {\n  font-size: 65%;\n}\n\n#kdmnvuiydo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kdmnvuiydo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kdmnvuiydo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kdmnvuiydo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kdmnvuiydo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kdmnvuiydo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kdmnvuiydo .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ppt</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Identifier (n=40)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">slength</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of words in sentence</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">condition</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Condition under which sentence is studied and recalled ('static' = sitting still, 'tap' = tapping fingers along to sentence)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">correct</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether or not the sentence was correctly recalled</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n:::\n\n\n\n\n<div class='question-begin'>Question Optional</div><div class='question-body'>\n\n\n> **Research Question:** After accounting for effects of sentence length, does the rhythmic tapping of fingers aid memory recall? \n\nFit an appropriate model to answer the research question.  \n\n::: {.callout-tip collapse=\"true\"}\n#### Hints\n\n- our outcome is conceptually 'memory recall', and it's been measured by \"Whether or not a sentence was correctly recalled\". This is a binary variable.  \n- we have multiple observations for each _????_?  \nThis will define our `(  | ??? )` bit\n\n:::\n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-9' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-9', 'sol-start-9')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-9\" style=\"display: none;\">\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmemtap <- read_csv(\"https://uoepsy.github.io/data/memorytap.csv\")\n```\n:::\n\n\nWhen we fit the maximal model, note that we obtain a singular fit. The variance of the slength effect between participants is quite small relative to the others, and there is a correlation between it and the random intercepts. \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntapmod <- glmer(correct ~ 1 + slength + condition + \n                  (1 + slength + condition | ppt),\n      data = memtap,\n      family = binomial)\nisSingular(tapmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\nVarCorr(tapmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Groups Name         Std.Dev. Corr         \n ppt    (Intercept)  1.032849              \n        slength      0.070307 -1.000       \n        conditiontap 0.665626  0.590 -0.590\n```\n:::\n:::\n\nlet's remove the random effect of `slength | ppt`. \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntapmod2 <- glmer(correct ~ 1 + slength + condition + \n                  (1 + condition | ppt),\n      data = memtap,\n      family = binomial)\n```\n:::\n\nthe model now looks a bit better (not a singular fit):\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(tapmod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGeneralized linear mixed model fit by maximum likelihood (Laplace\n  Approximation) [glmerMod]\n Family: binomial  ( logit )\nFormula: correct ~ 1 + slength + condition + (1 + condition | ppt)\n   Data: memtap\n\n     AIC      BIC   logLik deviance df.resid \n   537.6    561.5   -262.8    525.6      394 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.8949 -0.8955  0.4483  0.7962  1.6862 \n\nRandom effects:\n Groups Name         Variance Std.Dev. Corr\n ppt    (Intercept)  0.2755   0.5249       \n        conditiontap 0.4207   0.6486   0.66\nNumber of obs: 400, groups:  ppt, 40\n\nFixed effects:\n             Estimate Std. Error z value Pr(>|z|)  \n(Intercept)   0.76140    0.37077   2.054   0.0400 *\nslength      -0.12086    0.04721  -2.560   0.0105 *\nconditiontap  0.50945    0.24317   2.095   0.0362 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) slngth\nslength     -0.890       \nconditiontp -0.154 -0.029\n```\n:::\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n#### From Log odds to odds ratios\n\n\nTake some time to remind yourself from DAPR2 of the [interpretation of logistic regression coefficients](https://uoepsy.github.io/dapr2/2223/lectures/dapR2_16_binarylogistic.html#37).  \n\nIn `family = binomial(link='logit')`, we are modelling the log-odds. \nWe can obtain estimates on this scale using:  \n\n- `fixef(model)`\n- `summary(model)$coefficients`\n- `tidy(model)` **from broom.mixed**  \n- (there are probably more ways, but I can't think of them right now!)\n\nWe can use `exp()`, to get these back into odds and odds ratios.  \n\n:::\n\n\n\n<div class='question-begin'>Question Optional</div><div class='question-body'>\n\n\nInterpret each of the fixed effect estimates from your model.  \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-10' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-10', 'sol-start-10')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-10\" style=\"display: none;\">\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixef(tapmod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n (Intercept)      slength conditiontap \n   0.7613976   -0.1208591    0.5094460 \n```\n:::\n\n```{.r .cell-code}\nexp(fixef(tapmod2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n (Intercept)      slength conditiontap \n   2.1412669    0.8861589    1.6643689 \n```\n:::\n:::\n\n\n- `(Intercept)`: For an sentence with zero words, when sitting statically, the odds of correctly recalling the sentence are 2.14. This is equivalent to a $\\frac{2.14}{1 + 2.14} = 0.6815287$ probability of getting it correct.  \n- `slength`: After accounting for differences due to tapping/not-tapping during study & recall, for every 1 word longer a sentence is, the odds of correctly recalling the sentence is decreased by 0.89. \n- `conditiontap`: After accounting for differences in recall due to sentence length, finger tapping during the study and recall of sentences was associated with 1.66 increased odds correct recall in comparison to sitting still. \n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n\n\n<div class='question-begin'>Question Optional</div><div class='question-body'>\n\n\nChecking the assumptions in non-gaussian models in general (i.e. those where we set the `family` to some other error distribution) can be a bit tricky, and this is especially true for multilevel models.  \n\nFor the logistic MLM, the standard assumptions of normality etc for our Level 1 residuals `residuals(model)` do not hold. However, it is still useful to quickly plot the residuals and check that $|residuals|\\leq 2$ (or $|residuals|\\leq 3$ if you're more relaxed). We don't need to worry too much about the pattern though. \n\nWhile we're more relaxed about Level 1 residuals, we _do_ still want our random effects `ranef(model)` to look fairly normally distributed. \n\n1. Plot the level 1 residuals and check whether any are greater than 3 in magnitude\n2. Plot the random effects (the level 2 residuals) and assess the normality. \n\n\n\n</div><p class=\"question-end\"></p>\n\n\n\n\n<div class=\"solution-begin\"><button id='sol-start-11' class=\"jk-circle-right solution-icon clickable\" onclick=\"toggle_visibility('sol-body-11', 'sol-start-11')\">  Solution </button></div><div class=\"solution-body\" id = \"sol-body-11\" style=\"display: none;\">\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(tapmod2)\n```\n\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-40-1.png){fig-align='center' width=80%}\n:::\n\n```{.r .cell-code}\nsum(abs(resid(tapmod2))>3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\nAll residuals are between -3 and 3.  \n\nThe random effects look _okay_ here. Not perfect, but bear in mind we have only 40 participants. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqqnorm(ranef(tapmod2)$ppt[, 1], main = \"Random intercept\")\nqqline(ranef(tapmod2)$ppt[, 1])\nqqnorm(ranef(tapmod2)$ppt[, 2], main = \"Random slope of condition\")\nqqline(ranef(tapmod2)$ppt[, 2])\nhist(ranef(tapmod2)$ppt[, 1])\nhist(ranef(tapmod2)$ppt[, 2])\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04_ranefglmer_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n\n</div><p class=\"solution-end\"></p>\n\n\n\n::: {.callout-caution collapse=\"true\"}\n#### for beyond DAPR3\n\n- The **HLMdiag** package doesn’t support diagnosing influential points/clusters for `glmer`, but there is a package called **influence.me** which might help:  [https://journal.r-project.org/archive/2012/RJ-2012-011/RJ-2012-011.pdf](https://journal.r-project.org/archive/2012/RJ-2012-011/RJ-2012-011.pdf){target=\"_blank\"}\n- There are packages which aim to create more interpretable residual plots for these models via simulation, such as the **DHARMa** package:  [https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html](https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html){target=\"_blank\"}\n\n:::\n\n\n<div class=\"divider div-transparent div-dot\"></div>\n\n\n# Practice Datasets Weeks 4 and 5\n\nBelow are various datasets on which you can try out your new-found modelling skills. Read the descriptions carefully, keeping in mind the explanation of how the data is collected and the research question that motivates the study design.  \n\n::: {.callout-note collapse=\"true\"}\n#### Practice 1: Music and Driving \n\nThese data are simulated to represent data from a fake experiment, in which participants were asked to drive around a route in a 30mph zone. Each participant completed the route 3 times (i.e. \"repeated measures\"), but each time they were listening to different audio (either speech, classical music or rap music). Their average speed across the route was recorded. \nThis is a fairly simple design, that we might use to ask **\"how is the type of audio being listened to associated with driving speeds?\"** \n\nThe data are available at [https://uoepsy.github.io/data/drivingmusicwithin.csv](https://uoepsy.github.io/data/drivingmusicwithin.csv).  \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ryoxnfmbuq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ryoxnfmbuq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ryoxnfmbuq thead, #ryoxnfmbuq tbody, #ryoxnfmbuq tfoot, #ryoxnfmbuq tr, #ryoxnfmbuq td, #ryoxnfmbuq th {\n  border-style: none;\n}\n\n#ryoxnfmbuq p {\n  margin: 0;\n  padding: 0;\n}\n\n#ryoxnfmbuq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ryoxnfmbuq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ryoxnfmbuq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ryoxnfmbuq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ryoxnfmbuq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ryoxnfmbuq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ryoxnfmbuq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ryoxnfmbuq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ryoxnfmbuq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ryoxnfmbuq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ryoxnfmbuq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ryoxnfmbuq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ryoxnfmbuq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ryoxnfmbuq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ryoxnfmbuq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ryoxnfmbuq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ryoxnfmbuq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ryoxnfmbuq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ryoxnfmbuq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ryoxnfmbuq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ryoxnfmbuq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ryoxnfmbuq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ryoxnfmbuq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ryoxnfmbuq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ryoxnfmbuq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ryoxnfmbuq .gt_left {\n  text-align: left;\n}\n\n#ryoxnfmbuq .gt_center {\n  text-align: center;\n}\n\n#ryoxnfmbuq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ryoxnfmbuq .gt_font_normal {\n  font-weight: normal;\n}\n\n#ryoxnfmbuq .gt_font_bold {\n  font-weight: bold;\n}\n\n#ryoxnfmbuq .gt_font_italic {\n  font-style: italic;\n}\n\n#ryoxnfmbuq .gt_super {\n  font-size: 65%;\n}\n\n#ryoxnfmbuq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ryoxnfmbuq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ryoxnfmbuq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ryoxnfmbuq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ryoxnfmbuq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ryoxnfmbuq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ryoxnfmbuq .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">pid</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Identifier</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">speed</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Avg Speed Driven on Route (mph)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">music</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Music listened to while driving (classical music / rap music / spoken word)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n#### Practice 2: CBT and Stress\n\nThese data are simulated to represent data from 50 participants, each measured at 3 different time-points (pre, during, and post) on a measure of stress. Participants were randomly allocated such that half received some cognitive behavioural therapy (CBT) treatment, and half did not. This study is interested in assessing **whether the two groups (control vs treatment) differ in how stress changes across the 3 time points**. \n\nThe data are available at [https://uoepsy.github.io/data/stressint.csv](https://uoepsy.github.io/data/stressint.csv).  \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"pouhevcyjj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pouhevcyjj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pouhevcyjj thead, #pouhevcyjj tbody, #pouhevcyjj tfoot, #pouhevcyjj tr, #pouhevcyjj td, #pouhevcyjj th {\n  border-style: none;\n}\n\n#pouhevcyjj p {\n  margin: 0;\n  padding: 0;\n}\n\n#pouhevcyjj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pouhevcyjj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pouhevcyjj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pouhevcyjj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pouhevcyjj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pouhevcyjj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pouhevcyjj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pouhevcyjj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pouhevcyjj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pouhevcyjj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pouhevcyjj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pouhevcyjj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pouhevcyjj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pouhevcyjj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pouhevcyjj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pouhevcyjj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pouhevcyjj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pouhevcyjj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pouhevcyjj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pouhevcyjj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pouhevcyjj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pouhevcyjj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pouhevcyjj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pouhevcyjj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pouhevcyjj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pouhevcyjj .gt_left {\n  text-align: left;\n}\n\n#pouhevcyjj .gt_center {\n  text-align: center;\n}\n\n#pouhevcyjj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pouhevcyjj .gt_font_normal {\n  font-weight: normal;\n}\n\n#pouhevcyjj .gt_font_bold {\n  font-weight: bold;\n}\n\n#pouhevcyjj .gt_font_italic {\n  font-style: italic;\n}\n\n#pouhevcyjj .gt_super {\n  font-size: 65%;\n}\n\n#pouhevcyjj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pouhevcyjj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pouhevcyjj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pouhevcyjj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pouhevcyjj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pouhevcyjj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pouhevcyjj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ppt</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Identifier</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">stress</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Stress (range 0 to 100)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">time</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Time (pre/post/during)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">group</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Whether participant is in the CBT group or control group</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n#### Practice 3: Erm.. I don't believe you\n\nThese data are simulated to represent data from 30 participants who took part in an experiment designed to investigate **whether fluency of speech influences how believable an utterance is perceived to be**.  \n\nEach participant listened to the same 20 statements, with 10 being presented in fluent speech, and 10 being presented with a disfluency (an \"erm, ...\"). Fluency of the statements was counterbalanced such that 15 participants heard statements 1 to 10 as fluent and 11 to 20 as disfluent, and the remaining 15 participants heard statements 1 to 10 as disfluent, and 11 to 20 as fluent. The order of the statements presented to each participant was random. Participants rated each statement on how believable it is on a scale of 0 to 100.  \n\nThe data are available at [https://uoepsy.github.io/data/erm_belief.csv](https://uoepsy.github.io/data/erm_belief.csv). \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"rzfqxxsdus\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rzfqxxsdus table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rzfqxxsdus thead, #rzfqxxsdus tbody, #rzfqxxsdus tfoot, #rzfqxxsdus tr, #rzfqxxsdus td, #rzfqxxsdus th {\n  border-style: none;\n}\n\n#rzfqxxsdus p {\n  margin: 0;\n  padding: 0;\n}\n\n#rzfqxxsdus .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rzfqxxsdus .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rzfqxxsdus .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rzfqxxsdus .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rzfqxxsdus .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rzfqxxsdus .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rzfqxxsdus .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rzfqxxsdus .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rzfqxxsdus .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rzfqxxsdus .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rzfqxxsdus .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rzfqxxsdus .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rzfqxxsdus .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rzfqxxsdus .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rzfqxxsdus .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rzfqxxsdus .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rzfqxxsdus .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rzfqxxsdus .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rzfqxxsdus .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rzfqxxsdus .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rzfqxxsdus .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rzfqxxsdus .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rzfqxxsdus .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rzfqxxsdus .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rzfqxxsdus .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rzfqxxsdus .gt_left {\n  text-align: left;\n}\n\n#rzfqxxsdus .gt_center {\n  text-align: center;\n}\n\n#rzfqxxsdus .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rzfqxxsdus .gt_font_normal {\n  font-weight: normal;\n}\n\n#rzfqxxsdus .gt_font_bold {\n  font-weight: bold;\n}\n\n#rzfqxxsdus .gt_font_italic {\n  font-style: italic;\n}\n\n#rzfqxxsdus .gt_super {\n  font-size: 65%;\n}\n\n#rzfqxxsdus .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rzfqxxsdus .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rzfqxxsdus .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rzfqxxsdus .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rzfqxxsdus .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rzfqxxsdus .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rzfqxxsdus .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">ppt</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Identifier</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">trial_n</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Trial number</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">sentence</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Statement identifier</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">condition</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Condition (fluent v disfluent)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">belief</td>\n<td headers=\"description\" class=\"gt_row gt_left\">belief rating (0-100)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">statement</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Statement</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n#### Practice 4: Cognitive Aging\n\nThese data are simulated to represent a large scale international study of cognitive aging, for which data from 17 research centers has been combined. The study team are interested in **whether different cognitive domains have different trajectories as people age**. Do all cognitive domains decline at the same rate? Do some decline more steeply, and some less? The literature suggests that scores on cognitive ability are predicted by educational attainment, so they would like to control for this.  \n\nEach of the 17 research centers recruited a minimum of 14 participants (Median = 21, Range 14-29) at age 45, and recorded their level of education (in years). Participants were then tested on 5 cognitive domains: processing speed, spatial visualisation, memory, reasoning, and vocabulary. Participants were contacted for follow-up on a further 9 occasions (resulting in 10 datapoints for each participant), and at every follow-up they were tested on the same 5 cognitive domains. Follow-ups were on average 3 years apart (Mean = 3, SD = 0.8). \n\nThe data are available at [https://uoepsy.github.io/data/cogdecline.csv](https://uoepsy.github.io/data/cogdecline.csv). \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"dhbngjkmoh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dhbngjkmoh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dhbngjkmoh thead, #dhbngjkmoh tbody, #dhbngjkmoh tfoot, #dhbngjkmoh tr, #dhbngjkmoh td, #dhbngjkmoh th {\n  border-style: none;\n}\n\n#dhbngjkmoh p {\n  margin: 0;\n  padding: 0;\n}\n\n#dhbngjkmoh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dhbngjkmoh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dhbngjkmoh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dhbngjkmoh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dhbngjkmoh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dhbngjkmoh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dhbngjkmoh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dhbngjkmoh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dhbngjkmoh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dhbngjkmoh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dhbngjkmoh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dhbngjkmoh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dhbngjkmoh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dhbngjkmoh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dhbngjkmoh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhbngjkmoh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dhbngjkmoh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dhbngjkmoh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dhbngjkmoh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhbngjkmoh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dhbngjkmoh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhbngjkmoh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dhbngjkmoh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhbngjkmoh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dhbngjkmoh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dhbngjkmoh .gt_left {\n  text-align: left;\n}\n\n#dhbngjkmoh .gt_center {\n  text-align: center;\n}\n\n#dhbngjkmoh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dhbngjkmoh .gt_font_normal {\n  font-weight: normal;\n}\n\n#dhbngjkmoh .gt_font_bold {\n  font-weight: bold;\n}\n\n#dhbngjkmoh .gt_font_italic {\n  font-style: italic;\n}\n\n#dhbngjkmoh .gt_super {\n  font-size: 65%;\n}\n\n#dhbngjkmoh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dhbngjkmoh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dhbngjkmoh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dhbngjkmoh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dhbngjkmoh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dhbngjkmoh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dhbngjkmoh .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"description\">description</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">cID</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Center ID</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">pptID</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Participant Identifier</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">educ</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Educational attainment (years of education)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Age at visit (years)</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">processing_speed</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Score on Processing Speed domain task</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">spatial_visualisation</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Score on Spatial Visualisation domain task</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">memory</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Score on Memory domain task</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">reasoning</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Score on Reasoning domain task</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_left\">vocabulary</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Score on Vocabulary domain task</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n\n\n\n<div class=\"tocify-extend-page\" data-unique=\"tocify-extend-page\" style=\"height: 0;\"></div>",
    "supporting": [
      "04_ranefglmer_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/panelset-0.2.6/panelset.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/panelset-0.2.6/panelset.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}