---
title: "TODO Assumptions for LMMs"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

## Why do models make assumptions?

We can think of a linear model as a way to describe [the process of how our data was generated](dgp.html).

Certain aspects of that process are hard-coded and cannot be changed.
Hard-coded aspects of a model's data generating process are called "assumptions".

For example, think back to the assumptions of linear models you learned in DAPR2 (see also the [DAPR2 assumptions flash cards](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions)):

- **Linearity of association:**
  - A linear model can **only** model associations between predictor and outcome in terms of a straight line. Within the basic linear model machinery, this cannot be changed, and we just have to accept it. That's what it means to be an "assumption".
    - If an association *doesn't* follow a straight line, then a linear model cannot accurately capture it.
    -  Think of `height ~ age`, for example. Height rises steeply when ages are small and then eventually tapers off (and may even start to decrease in old age!).
    - If we used a linear model to model `height ~ age`, then our model will give us the best straight line it can.
  - To be satisfied with a linear model of that data, **we have to assume that the best possible straight line is a good representation of the data.**
- **Independence of errors:**
  - A linear model can **only** model errors as residuals that are independent from one another. Within the basic linear model machinery, this cannot be changed.
    - One source of non-independence are data points that come from the same source (for example, multiple data points from the same person, or from the same test question—see [grouping variables](groupstruc.html)). 
  To take that non-independence into account, we must use [random effects](ranef.html).
  - To be satisfied with a linear model of our data, **we have to assume that independent residuals are a good representation of the data.**
- **Normality of errors:**
  - A linear model can **only** model errors as residuals that are normally distributed. Within the basic linear model machinery, this cannot be changed.
  - To be satisfied with a linear model of our data, **we have to assume that normally-distributed residuals are a good representation of the data.**
- **Equal variance of errors:**
  - A linear model can **only** model errors as residuals that have equal variance. Within the basic linear model machinery, this cannot be changed.
  - To be satisfied with a linear model of our data, **we have to assume that residuals with equal variance are a good representation of the data.**


## Assumptions in LMMs

### Assumptions about residuals

When we use LMMs, those four assumptions still hold, but at a slightly different level than with simple linear models.

Three of those four assumptions have to do with the errors, or the residuals, of the model: how far each observed data point is from the model's fitted line.

[TODO fig of points, fixef line, resids from line]

When we are modelling randomly-varying groups, we essentially ask our model to fit more lines: one fitted line for the fixed effects, and another fitted line for each group.

[TODO fig of points, fixef line, ranefs lines]

And we still have residuals in this data, but at a different level: now we are looking at how far each observed data point is from the model's fitted line **for the group that that data point belongs to**.
It's about *those* residuals that we are now making our assumptions: 

[TODO same fig of points, fixef line, ranefs lines, with resids from points to ranef lines]

- independence
- normality
- equal variance (for the whole dataset and for each level of the grouping variable)


### Assumptions about intercept and slope adjustments

To get the group-level lines:

- We take the fixed intercept (the `(Intercept)` coefficient) and add on adjustment value to produce the intercept for the group-level line (see [random intercepts](rdint.html)).
- If we have a random slope over the predictor, we *also* take the fixed slope for that predictor and add on an adjustment value to produce the slope for the group-level line (see [random slopes](rdslp.html)).

These adjustment values to intercept and slope come with their own assumptions.
**Specifically, we assume that the adjustments are normally distributed with a mean of zero.**

Let's visualise how that's working behind the scenes:

[TODO figs of different samples from normal distribs and how those adjustments impact the fixef line]


When we [include random effects in a model](ranef-formula.html), what we see in the model summary are the standard deviations of the normal distributions from which the group-level adjustments are (assumed to be) sampled.



## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO
