---
title: "Describing group-structured data"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

Descriptives of hierarchical data are sometimes a bit more difficult than when we don’t have any ‘levels’. Typically, what we are wanting to do is provide our readers with a picture of the characteristics of our sample. “Our sample” now refers to multiple levels, so we want to describe each of these. More often than not, one of these levels will be a bit more interesting to us as a population we are hoping to generalise to. In psychology we are usually interested in “people”, so if we have data that is multiple trials per participant, we would probably want to focus on describing the participants (the clusters) as the individual trials are something we exert control over as the experimenter. If each datapoint was a child and they were nested in schools, we would probably want to describe both the children and the schools that are in our sample.

The aim here is to provide a picture of our sample so that a reader can get a sense of how ‘transportable’ the findings are to different contexts. For instance, if participants in our study are all university students, then we want to be careful about thinking that the findings will apply in other populations (see e.g. “most people aren’t WEIRD”).

A checklist
what is the hierarchical data structure (how many levels, what is each level?)
Describe any data cleaning outlier/data removal prior to calculating descriptive statistics (these tend to be the impossible values - i.e. observations that you would never want in your data anyway)
sample sizes: how many at each level?
how many lower-level within each higher level unit? (if this varies, provide an average, and possibly a min and a max)
scales of measured variables
descriptive statistics of relevant variables that characterise your sample.
these should be computed at the level at which they were measured. For instance, if you have observations grouped by participant, mean(data$age) would give the average age of your observations (which isn’t meaningful, and would differ from the average age of your participants if you have a different number of observations for each participant).
How much of the variability in the outcome variable is attributable to the clustering? (i.e. ICC)


## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO
