---
title: "Grouping variables"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
library(tidyverse)
```


**Grouping variables are ordinal or categorical variables whose values appear more than once in a dataset.**
In other words, when multiple observations in a dataset are related to the same value of an ordinal or categorical variable, then you're dealing with grouping variables.

For example:

- The same child is observed at a few different times of day, so our data contains multiple observations from that child.
- The same experimental participant sees all conditions of an experiment, so our data contains multiple observations from that participant.
- The same experimental condition is seen by many participants, so our data contains multiple observations of that experimental condition.
- The same test question is seen by every student, so our data contains multiple observations from that test question.
- The same student sees many test questions, so our data contains multiple observations from that student.


To see how to identify grouping variables in a given dataset, see [Identifying grouping variables](identify-group.html){target="_blank"}.

## Why are grouping variables important?

In DAPR2, you learned that linear models make a number of assumptions ([revisit last year's DAPR2 flashcards here](https://uoepsy.github.io/dapr2/2425/labs/1_b4_reading.html#model-assumptions){target="_blank"}).

One of those assumptions was the **assumption of independence of errors.**
For this assumption to be met, every observation must be independent of every other observation.
But when (for example) our data contains multiple observations from the same child, those data points are **not independent, because they all come from the same child.**

In general, when our data contains grouping structures, the data points associated with each member of each group are not independent.
Our analysis will violate the assumption of independence of errors unless we include the grouping variables in our model.

Depending on the [data generating process](dgp.html){target="_blank"}, we model grouping variables either as [fixed effects](fixef.html){target="_blank"} or as [random effects](ranef.html){target="_blank"}.




## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO

