---
title: "Maximal model"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

The "maximal model" is the version of the model that **contains all possible random intercepts and random slopes that the data can support.**

A maximal model **does _not_ need to contain every possible fixed effect.**
The term "maximal model" refers only to the random effect structure, not the fixed effects.
(As always, fixed effects should be chosen based on your RQ.)

The process outlined in [Identify possible random effects](identify-ranef.html) walks through how to work out the maximal random effect structure, i.e., how to identify the maximal model.

If you try to fit the maximal model to your data, you might find that it fails to converge (see [Troubleshoot common issues](troubleshoot.html)).
If this is the case, you may need to [change the model's optimiser](optimiser.html) and/or [simplify](simplify.html) the random effect structure to a non-maximal version that does converge.


## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO
