---
title: "TODO Get p-values for LMMs"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```


## Statistical significance of LMM coefficients

tests/CIs of individual parameters	

Tests of individual parameters can be done by refitting with lmerTest::lmer(...) for the Satterthwaite (S) method

refer to https://uoepsy.github.io/lmm/03_inference.html?panelset_002=tests-of-single-parameters2&panelset_001=tests-of-single-parameters

focus on Satterthwaite.

rabbit hole: Kenward-Rogers?


## No significance testing for random effects

Tests of random effects are difficult because the null hypothesis (the random effect variance is zero) lies on a boundary (you can’t have a negative variance). Comparisons of models that differ only in their random effects can be done by comparing ratio of likelihoods when fitted with REML=TRUE (this has to be done manually), but these tests should be treated with caution.

We can obtain confidence intervals for our random effect variances using both the profile likelihood and the parametric boostrap methods discussed above.

As random effects are typically part of the experimental design, there is often little need to test their significance. In most cases, the maximal random effect structure can be conceptualised without reference to the data or any tests, and the inclusion/exclusion of specific random effects is more a matter of what simplifications are required for the model to converge. Inclusion/exclusion of parameters based on significance testing is rarely, if ever a sensible approach.



## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO
