---
title: "TODO Random effects"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

**"Random effects" is an umbrella term that covers both [random intercepts](rdint.html){target="_blank"} and [random slopes](rdslp.html){target="_blank"}.**

If we're modelling data which contains [grouping variables](groupstruc.html){target="_blank"} that contribute random variability to the data (see [Data generating process](dgp.html){target="_blank"}), then our model should include random effects.


worked example of moving from fixef line to ranef line

To get the group-level lines, we take the parameters of the fixed-effect line—the intercept and slope—and add on some adjustment value for each group to the intercept and slope (see [random effects](ranef.html)).

To get the group-level lines:

- We take the fixed intercept (the `(Intercept)` coefficient) and add on adjustment value to produce the intercept for the group-level line (see [random intercepts](rdint.html)).
- If we have a random slope over the predictor, we *also* take the fixed slope for that predictor and add on an adjustment value to produce the slope for the group-level line (see [random slopes](rdslp.html)).

These adjustment values to intercept and slope come with their own assumptions.
**Specifically, we assume that the adjustments are normally distributed with a mean of zero.**

Let's visualise how that's working behind the scenes:

[TODO figs of different samples from normal distribs and how those adjustments impact the fixef line]


When we [include random effects in a model](ranef-formula.html), what we see in the model summary are the standard deviations of the normal distributions from which the group-level adjustments are (assumed to be) sampled.



## Interpreting model-estimated random effects


- Interpret fixed effects first
- Ranefs only make sense relative to fixefs






## Extracting from fitted model

### Group-member-specific random effects


### Group-member-specific coefficients


### Variance components



::: {.callout-caution collapse="true"}
## Shrinkage

lorem ipsum

:::


::: {.callout-caution collapse="true"}
## Pooling

lorem ipsum

:::


## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO
