---
title: "Random intercepts"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

Random intercepts are

- the way the model adjusts the average ([fixed](fixef.html)) intercept to better match the data from each level of the [grouping variable(s)](groupstruc.html).
- one number per level of the grouping variable, which is added on to the fixed intercept to produce the group-specific intercept.
- also called "varying intercepts" or "intercept adjustments".
- represented by the `1` in the random effect `lme4` syntax: `(1 + p | g)`, where `g` is the grouping variable. If a model has only random intercepts by `g` and no [random slopes](rdslp.html) over `p`, the random effect term is `(1 | g)`.

To work out whether your model should contain random intercepts, see [Identify possible random effects](identify-ranef.html).


<!-- ::: {.callout-caution collapse="true"} -->
<!-- ### How to represent random intercepts mathematically -->

<!-- The basic mathematical representation of a simple linear model `y ~ x` is -->

<!-- $$y = \beta_0 + \beta_1 x + \epsilon$$ -->

<!-- Parameter glossary: -->

<!-- - $y$ represents the outcome variable -->
<!-- - $\beta_0$ represents the intercept -->
<!-- - $\beta_1$ represents the slope over predictor $x$ -->
<!-- - $x$ represents the predictor variable -->
<!-- - $\epsilon$ represents the residual error  -->

<!-- Adding a random intercept into the model `y ~ x + (1 | g)` is represented mathematically as -->

<!-- $$y_{i} = \beta_0 + u_i + \beta_1 x_{i} + \epsilon_{i}$$ -->

<!-- ::: -->



## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO
