---
title: "Simplify random effects"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

If a [maximal model](maxmodel.html) will not converge, even after you change the optimiser (see [Troubleshoot](troubleshoot.html)), then you will need to simplify the model's random effect structure.

Let's assume a maximal model with the formula `y ~ x * z + (1 + x * z | g)`.
This model is predicting `y` as a function of `x`, `z`, and their interaction, and it includes by-`g` adjustments to the intercept, to the slopes of `x` and `z`, and to the interaction.
It also estimates the correlations between all the by-`g` adjustments.

There is no single correct way to simplify the random effect structure.
But here's a guide to a sequence of simplifications you might make.
This sequence starts with the parameters that are generally least relevant for your research question (but if you really need a given parameter to address your research question, then definitely leave it in!).

Try to fit the model again after every step, and stop simplifying once it successfully converges without singularities.

- Remove the by-group adjustment to the interaction term: `y ~ x * z + (1 + x + z | g)`.
- Remove the correlations between by-group adjustments: `y ~ x * z + (1 + x + z || g)`.
- Remove one of the by-group slope adjustments (if one is a covariate, remove that one first): `y ~ x * z + (1 + x || g)`.
- Remove both of the by-group slope adjustments: `y ~ x * z + (1 | g)`.
- (Usually not a good idea, only do this if you have very low group-level variance) Remove the random effect entirely: `y ~ x * z`.


## Linked flash cards

### Outgoing links

- TODO


### Backlinks

- TODO
