---
title: "Prerequisites"
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
editor_options: 
  chunk_output_type: console
---



# Install/Update R & RStudio

Make sure you have installed **both** R and RStudio on your computer. You may have done this previously for DAPR2, in which case it is probably worth doing some updates. 

**Please make sure to read and follow the instructions below slowly and carefully!!**  
- For instructions on how to **install** R and RStudio, click [here](https://uoepsy.github.io/files/install-update-r.html#a--installing-r-and-rstudio){target="_blank"}
- For instructions on how to **update** R and RStudio, click [here](https://uoepsy.github.io/files/install-update-r.html#b--updating-r-and-rstudio){target="_blank"}



# Update Packages

It's worth keeping packages up to date, so it might be worth updating all your packages. 

Running this code will update all your packages. Just put it into the console (bottom left bit of RStudio):

```{r}
#| eval: false
options(pkgType = "binary")
update.packages(ask = FALSE)
```

# New packages!

Now it is probably worth installing a few of the packages that we will be using in DAPR3. There are a few that we will need. For each one, check whether you have it already installed, because there's not much point wasting time re-installing something you already have!  

+ __tidyverse__ : for organising data  
+ __lme4__ : for fitting generalised linear mixed effects models
+ __broom.mixed__ : tidying methods for mixed models
+ __effects__ : for tabulating and graphing effects in linear models
+ __lmerTest__: for quick p-values from mixed models
+ __parameters__: various inferential methods for mixed models
