---
title: "Tutors"
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
editor_options: 
  chunk_output_type: console
---


- In Week 1, start all labs with a quick:

"hello. almost all of you are well practiced at DAPR labs now. 
take a seat, say hello to your colleagues, open Rstudio, and get started on the exercises on Learn. 

work together with people on your table - explain stuff to one another, troubleshoot together etc. 

for any questions, we have lovely tutors wandering around, just grab one, or put your hand up etc, and they will be able to help. 

The groups for the report will not be set until week 3, so for now just sit with whoever you want"



## Tutor guidelines 


- try to do less: 
    - standing around chatting
    - using your phone
    - sitting with one student for too long
- try to do more: 
    - make sure every table gets an introduction to a tutor ("hello, i'm X, how are you getting on? etc")
    - make sure tables don't get ignored (even if no hands are going up)
    - if all is quiet, try **actively** asking a table 1) where they're up to in the exercises, 2) if they need any help etc. 



