---
title: "Identifying grouping structure"
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
editor_options: 
  chunk_output_type: console
---

<!-- render in RStudio/not production profile:   SHOW_SOLS: TRUE -->
<!-- render in terminal/with production profile: SHOW_SOLS: FALSE -->

```{r}
#| label: setup
#| include: false
source('assets/setup.R')
library(xaringanExtra)
library(tidyverse)
library(patchwork)
library(ggdist)
xaringanExtra::use_panelset()
qcounter <- function(){
  if(!exists("qcounter_i")){
    qcounter_i <<- 1
  }else{
    qcounter_i <<- qcounter_i + 1
  }
  qcounter_i
}
```

In this lab, you will start to build skills that you'll use again and again for the next five weeks (and really, for the rest of your data analysis career!).

This week is all about **practicing how to identify the grouping structure within a given dataset.**

In the ten questions below, you'll use the tools you saw during the lecture to figure out the grouping structure in ten different datasets.

:::{.callout-note}
### Get set up

- Create a new .Rmd file for this week's exercises.
- Save it somewhere you can find it again.
- Give it a clear name (for example, `dapr3_lab01.Rmd`).
- At the beginning of your file, load the packages you'll need this week:
  - `tidyverse`

:::


`r qbegin(qcounter())`

Read in the dataset located at [URL TODO].

- What group or groups does this dataset contain?
- How many levels does each group have?

`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`

dolor sit amet

`r solend()`




