---
title: 'Welcome to DAPR3'
output: 
  bookdown::html_document2:
    toc: false
---

Welcome to the Data Analysis for Psychology in R 3 (DAPR3) lab workbook. Using the menu above, you can find lab materials for each week. These include sets of exercises along with walkthrough readings in which we introduce some of the more important R code. It is strongly recommended that students have taken Data Analysis for Psychology in R 1 and 2  (DAPR1 & DAPR2).   
   
#### Solutions   
Solutions will be made available immediately below each exercise, in the week *after* they are set, so make sure to re-visit the labs to check your answers.  
  
#### Asking Questions  
We encourage you to use the various support options, details of which can be found on the [Course Learn Page.](https://www.learn.ed.ac.uk/webapps/blackboard/content/listContentEditable.jsp?content_id=_6062239_1&course_id=_88036_1)

#### Tips on googling statistics and R

Searching online for help with statistics and R can be both a help and a hindrance.  
If you have an error message in R, copy the error message into google. The results returned can sometimes just cause more confusion, but sometimes something might jump out at you and help you solve the problem. The same applies with searching the internet for help with statistics - search for "what is a p-value", and you'll find many many different articles and forum discussions etc. Some of them you will find too technical, but don't be scared - the vast majority of people work in statistics will find these too technical too. Some of them you might feel are too simple/not helpful. As a general guide, keep clicking around the search responses, and you may end up finding that someone, somewhere, has provided an explanation at the right level. If you find something during your search which you don't quite understand, feel free to link it in a post on the discussion forum!  

#### Feedback on labs

If you wish to make suggestions for improvements to these workbooks, please email [ug.ppls.stats@ed.ac.uk](mailto:ug.ppls.stats@ed.ac.uk) making sure to include the course name in the subject.