---
title: "optional rotations"
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
editor_options: 
  chunk_output_type: inline
---

```{r}
#| label: setup
#| include: false
source('assets/setup.R')
library(xaringanExtra)
library(tidyverse)
library(patchwork)
xaringanExtra::use_panelset()

```


The two plots below show an unrotated and a rotated solution to the same data:  

# No rotation 
```{r}
#| echo: false
#| label: fig-unrot
#| fig-cap: "unrotated solution"
library(rgl)
library(tidyverse)
library(psych)
set.seed(123)
df <- tibble(
  y1 = rnorm(100),
  y2 = rnorm(100, mean = y1),
  y3 = rnorm(100, mean = y1 + y2)
) |> mutate(across(everything(),~scale(.)[,1]))

pca_result <- principal(df, nfactors = 3, rotate = "none")
rotated_pca_result <- principal(df, nfactors = 3, rotate = "varimax")

pc1 <- pca_result$loadings[, 1]
pc2 <- pca_result$loadings[, 2]
pc3 <- pca_result$loadings[, 3]
pc1_rot <- rotated_pca_result$loadings[, 1]
pc2_rot <- rotated_pca_result$loadings[, 2]
pc3_rot <- rotated_pca_result$loadings[, 3]

scale_factor <- max(abs(range(df$y1)), abs(range(df$y2)), abs(range(df$y3)))
pc1_line <- rbind(pc1 * -scale_factor, pc1 * scale_factor)
pc2_line <- rbind(pc2 * -scale_factor, pc2 * scale_factor)
pc3_line <- rbind(pc3 * -scale_factor, pc3 * scale_factor)
pc1_rot_line <- rbind(pc1_rot * -scale_factor, pc1_rot * scale_factor)
pc2_rot_line <- rbind(pc2_rot * -scale_factor, pc2_rot * scale_factor)
pc3_rot_line <- rbind(pc3_rot * -scale_factor, pc3_rot * scale_factor)

plot3d(df$y1, df$y2, df$y3, col = "blue", size = 1, type = 's', xlab = "y1", ylab = "y2", zlab = "y3",
       xlim=c(-3,3),ylim=c(-3,3),zlim=c(-3,3))
segments3d(pc1_line, col = "red", lwd = 4)
segments3d(pc2_line, col = "green", lwd = 4)
segments3d(pc3_line, col = "purple", lwd = 4)
rglwidget()

```


# Rotation

```{r}
#| echo: false
#| label: fig-rot
#| fig-cap: "rotated solution"
plot3d(df$y1, df$y2, df$y3, col = "blue", size = 1, type = 's', xlab = "y1", ylab = "y2", zlab = "y3",
       xlim=c(-3,3),ylim=c(-3,3),zlim=c(-3,3))
segments3d(pc1_rot_line, col = "red", lwd = 4)
segments3d(pc2_rot_line, col = "green", lwd = 4)
segments3d(pc3_rot_line, col = "purple", lwd = 4)
rglwidget()
```