---
title: "3-level multilevel model equations"
link-citations: yes
code-fold: true
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
---

10 schools, 20 children in each school, each child completed observed 5 times throughout the year.  
interested in how level of routine (child routine questionnaire CRQ), family income, and amount of school funding influence the level of aggressive behaviour (aggressive behaviour scale ABS)

It varies in textbooks whether the specification of levels is $i$>$j$>$k$ or $i$<$j$<$k$.  
In complex multilevel equations, it becomes a little easier sometimes (for me) to use the latter.  
Either way, we need to be clear about what each index refers to. 

$$
\begin{align}
k &= \textrm{Schools}\\
j &= \textrm{Children}\\
i &= \textrm{observations}
\end{align}
$$

The outcome, aggressive behaviour score, occurs at the observation level $ABS_{ijk}$.  
Level of routine occurs at the observation level $CRQ_{ijk}$.  
Family income occurs at the child level $Income_{jk}$.  
School funding occurs at the school level $Funding_k$.  

:::frame

If we just ignore all of the clustering:
$$
ABS = \beta_0 + \beta_1(CRQ) + \beta_2(Income) + \beta_3(Funding) + \varepsilon
$$
:::

<br><br>

:::frame

If we put random intercepts for schools and children:
$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0jk} + \beta_1(CRQ_{ijk}) + \beta_2(Income_{jk}) + \beta_3(Funding_k) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0jk} = \gamma_{00k} +\zeta_{0jk} \\
\textrm{Level 3:} & \\
&\gamma_{00k} = \pi_{000} + u_{00k}
\end{align}
$$
:::

<br><br>

:::frame

We can also move the relevant effects to the corresponding level at which they exist. 
While we're at it, we can change the symbol to match the other effects at each level:
$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0jk} + \beta_{1}(CRQ_{ijk}) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0jk} = \gamma_{00k} + \gamma_{010}(Income_{jk}) +\zeta_{0jk} \\
\textrm{Level 3:} & \\
&\gamma_{00k}= \pi_{000} + \pi_{001}(Funding_k) + u_{00k}
\end{align}
$$

:::

<br><br>

:::frame

Adding in a random slope of routine for each child:
$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0jk} + \beta_{1jk}(CRQ_{ijk}) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0jk} = \gamma_{00k} + \gamma_{010}(Income_{jk}) +\zeta_{0jk} \\
&\beta_{1jk} = \gamma_{100} +\zeta_{1jk} \\
\textrm{Level 3:} & \\
&\gamma_{00k}= \pi_{000} + \pi_{001}(Funding_k) + u_{00k}
\end{align}
$$

Adding in a random slope of routine for each school:
$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0jk} + \beta_{1jk}(CRQ_{ijk}) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0jk} = \gamma_{00k} + \gamma_{010}(Income_{jk}) +\zeta_{0jk} \\
&\beta_{1jk} = \gamma_{10k} +\zeta_{1jk} \\
\textrm{Level 3:} & \\
&\gamma_{00k}= \pi_{000} + \pi_{001}(Funding_k) + u_{00k}\\
&\gamma_{10k} = \pi_{100} + u_{10k} 
\end{align}
$$

Adding in a random slope of income for each school:
$$
\begin{align}
\textrm{Level 1:} & \\
& ABS_{ijk} = \beta_{0jk} + \beta_{1jk}(CRQ_{ijk}) + \varepsilon_{ijk}\\
\textrm{Level 2:} & \\
&\beta_{0jk} = \gamma_{00k} + \gamma_{01k}(Income_{jk}) +\zeta_{0jk} \\
&\beta_{1jk} = \gamma_{10k} +\zeta_{1jk} \\
\textrm{Level 3:} & \\
&\gamma_{00k}= \pi_{000} + \pi_{001}(Funding_k) + u_{00k}\\
&\gamma_{10k} = \pi_{100} + u_{10k} \\
& \gamma_{01k} = \pi_{010} + u_{01k}
\end{align}
$$


:::

<br><br>

:::frame

collapsing it all back down in to a "mixed" equation:
$$
\begin{align}
ABS_{ijk}= &(\pi_{000} + u_{00k} + \zeta_{0jk}) + & \\
& (\pi_{100} + u_{10k} + \zeta_{1jk})(CRQ_{ijk}) + &\\
&(\pi_{010} + u_{01k})(Income_{jk}) + &\\
&\pi_{001}(Funding_k) + &\\
& \varepsilon_{ijk}& \\
\end{align}
$$
:::
