<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Assumptions, Diagnostics, and Random Effect Structures</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR3</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Multi Level Models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_regressionrefresh.html">1: Linear Regression | Clustered Data</a>
    </li>
    <li>
      <a href="02_intromlm.html">2: LM to MLM</a>
    </li>
    <li>
      <a href="03_assumptranef.html">3: Assumptions, Diagnostics</a>
    </li>
    <li>
      <a href="04_centerglmer.html">4: Centering | Logistic</a>
    </li>
    <li>
      <a href="05_examples.html">5: Recap</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Dimension reduction &amp; SEM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="07_path1.html">7: Path Analysis</a>
    </li>
    <li>
      <a href="08_path2.html">8: Path Mediation</a>
    </li>
    <li>
      <a href="09_pca.html">9: Dimension Reduction</a>
    </li>
    <li class="dropdown-header">10: EFA 1</li>
    <li class="dropdown-header">11: EFA 2</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Extra
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../resources.html">Useful Resources</a>
    </li>
    <li>
      <a href="../examples/example_01_repeated_measures.html">Example: Repeated Measures MLM</a>
    </li>
    <li>
      <a href="../examples/example_02_intervention.html">Example: Intervention Study</a>
    </li>
    <li>
      <a href="../examples/example_03_many_trials.html">Example: Many Trials</a>
    </li>
    <li>
      <a href="../examples/example_00_anova.html">Example: ANOVA (rpt measures &amp; mixed)</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Assumptions, Diagnostics, and Random Effect Structures</h1>

</div>


<div class="green">
<p><strong>Information about solutions</strong></p>
<p>Solutions for these exercises are available immediately below each question.<br />
We would like to emphasise that much evidence suggests that testing enhances learning, and we <strong>strongly</strong> encourage you to make a concerted attempt at answering each question <em>before</em> looking at the solutions. Immediately looking at the solutions and then copying the code into your work will lead to poorer learning.<br />
We would also like to note that there are always many different ways to achieve the same thing in R, and the solutions provided are simply <em>one</em> approach.</p>
</div>
<div class="lo">
<p><strong>Preliminaries</strong></p>
<ol style="list-style-type: decimal">
<li>Create a new RMarkdown document or R script (whichever you like) for this week.</li>
</ol>
</div>
<div id="assumptions" class="section level1">
<h1>Assumptions</h1>
<div id="toy-data" class="section level2">
<h2>Toy data</h2>
<div class="frame">
<div style="display:inline-block; width: 45%;vertical-align: middle;">
<p>Recall our toy example data in which we fitted a multilevel model to model how practice (in hours per week) influences the reading age of toy figurines which are grouped by toy-type (Playmobil, Powerrangers, Farm Animals etc).</p>
</div>
<div style="display:inline-block; width: 45%;vertical-align: middle;">
<p><img src="images/intro/toys.png" width="300px" style="display: block; margin: auto;" /></p>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>toys_read <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://uoepsy.github.io/data/toyexample.csv&quot;</span>)</span></code></pre></div>
</div>
<div class="question-begin">
Question A1
</div>
<div class="question-body">
<p>Run the code below to fit the model with by-toy-type random intercepts and slopes of practice.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>toys_read <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://uoepsy.github.io/data/toyexample.csv&quot;</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>rs_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(R_AGE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> hrs_week <span class="sc">|</span> toy_type), <span class="at">data =</span> toys_read)</span></code></pre></div>
<p>Plot the residuals vs fitted model, and assess the extend to which the assumption holds that the residuals are zero mean.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-38" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-38&#39;, &#39;sol-start-38&#39;)"> Solution </span>
</div>
<div id="sol-body-38" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rs_model, <span class="at">type=</span><span class="fu">c</span>(<span class="st">&quot;p&quot;</span>,<span class="st">&quot;smooth&quot;</span>))</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-4-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A2
</div>
<div class="question-body">
<p>Construct a scale-location plot. This is where the square-root of the absolute value of the standardised residuals is plotted against the fitted values, and allows you to more easily assess the assumption of constant variance.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-39" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-39&#39;, &#39;sol-start-39&#39;)"> Solution </span>
</div>
<div id="sol-body-39" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rs_model,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">form =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(<span class="fu">resid</span>(.))) <span class="sc">~</span> <span class="fu">fitted</span>(.),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="fu">c</span>(<span class="st">&quot;p&quot;</span>,<span class="st">&quot;smooth&quot;</span>))</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-5-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A3
</div>
<div class="question-body">
<p>Using the <code>augment()</code> function from the <strong>broom.mixed</strong> package, construct the same plot using ggplot.</p>
<p><em>(constructing plots like this manually is a really useful way to help understand <strong>what</strong> exactly is being plotted)</em></p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-40" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-40&#39;, &#39;sol-start-40&#39;)"> Solution </span>
</div>
<div id="sol-body-40" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(rs_model) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sqrtr =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(.resid))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>.fitted, <span class="at">y=</span>sqrtr)) <span class="sc">+</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-6-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question A4
</div>
<div class="question-body">
<p>Examine the normality of both the level 1 and level 2 residuals.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-41" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-41&#39;, &#39;sol-start-41&#39;)"> Solution </span>
</div>
<div id="sol-body-41" class="solution-body" style="display: none;">
<p><strong>Level 1</strong></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(rs_model))</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-7-1.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqmath</span>(rs_model, <span class="at">id=</span><span class="fl">0.05</span>)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-7-2.png" width="80%" style="display: block; margin: auto;" />
<strong>Level 2</strong></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqmath</span>(<span class="fu">ranef</span>(rs_model))</span></code></pre></div>
<pre><code>## $toy_type</code></pre>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-8-1.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>toy_type[,<span class="dv">1</span>])</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-8-2.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">ranef</span>(rs_model)<span class="sc">$</span>toy_type[,<span class="dv">2</span>])</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-8-3.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="diagnostics" class="section level1">
<h1>Diagnostics</h1>
<div class="question-begin">
Question B1
</div>
<div class="question-body">
<p>Which toy in the dataset has the greatest influence on our model?</p>
<p><strong>Hint:</strong> as well as <code>hlm_influence()</code> in the <strong>HLMdiag</strong> package there is another nice function, <code>hlm_augment()</code></p>
<div class="imp">
<p>We can often end up in confusion because the <span class="math inline">\(i^{th}\)</span> observation inputted to our model (and therefore the <span class="math inline">\(i^{th}\)</span> observation of <code>hlm_influence()</code> output) <strong>might not be</strong> the <span class="math inline">\(i^{th}\)</span> observation in our original dataset - there may be missing data!</p>
</div>
<p>(Luckily, we have no missing data in the Toy dataset).</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-42" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-42&#39;, &#39;sol-start-42&#39;)"> Solution </span>
</div>
<div id="sol-body-42" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HLMdiag)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>l1_inf <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(rs_model,<span class="at">level=</span><span class="dv">1</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(l1_inf<span class="sc">$</span>cooksd, <span class="at">cutoff=</span><span class="st">&quot;internal&quot;</span>)<span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,.<span class="dv">15</span>)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-9-1.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(cooksd))</span></code></pre></div>
<pre><code>## # A tibble: 132 × 15
##       id  R_AGE hrs_week toy_type .resid .fitted .ls.resid .ls.fitted .mar.resid
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1    81  2.91      6.28 SuperZi…  -3.24    6.15   -1.60        4.51      -6.03 
##  2    65 14.0       2.44 G.I.Joe    4.98    8.99    2.69       11.3        9.43 
##  3   115  0.735     1.70 Stretch…  -3.17    3.91   -0.182       0.917     -2.97 
##  4    46 11.6       5.70 Star Wa…  -2.68   14.3    -2.50       14.1        3.34 
##  5    55  1.47      2.77 SuperZi…  -2.11    3.58   -3.36        4.84      -3.45 
##  6   104  2.68      2.74 Rugrats   -1.79    4.47    0.0279      2.65      -2.21 
##  7    23  0.838     1.74 Playmob…  -1.55    2.39    0.585       0.253     -2.91 
##  8    30  5.33      2.99 Furby     -3.10    8.43   -2.72        8.04       0.156
##  9   130  3.79      2.73 Lego Mi…   2.54    1.25    1.94        1.85      -1.08 
## 10    36  3.16      2.99 My Litt…   1.87    1.29   -0.508       3.66      -2.02 
## # … with 122 more rows, and 6 more variables: .mar.fitted &lt;dbl&gt;, cooksd &lt;dbl&gt;,
## #   mdffits &lt;dbl&gt;, covtrace &lt;dbl&gt;, covratio &lt;dbl&gt;, leverage.overall &lt;dbl&gt;</code></pre>
<p>Greatest influence:</p>
<p><img src="images/ace.png" width="100px" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B2
</div>
<div class="question-body">
<p>For which toy is the model fit the worst (i.e., who has the highest residual?)</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-43" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-43&#39;, &#39;sol-start-43&#39;)"> Solution </span>
</div>
<div id="sol-body-43" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(.resid)))</span></code></pre></div>
<pre><code>## # A tibble: 132 × 15
##       id  R_AGE hrs_week toy_type .resid .fitted .ls.resid .ls.fitted .mar.resid
##    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1    93  7.78      4.28 G.I.Joe   -5.26  13.0       -4.62     12.4         1.13
##  2    65 14.0       2.44 G.I.Joe    4.98   8.99       2.69     11.3         9.43
##  3    56 -3.17      3.47 Lego Mi…  -4.59   1.42      -4.69      1.52       -8.89
##  4   102 -2.91      5.12 My Litt…  -4.56   1.64      -3.96      1.04      -10.5 
##  5    43 -2.99      3.96 Transfo…  -3.84   0.853     -3.79      0.800      -9.28
##  6    16  8.41      3.89 G.I.Joe   -3.76  12.2       -3.75     12.2         2.21
##  7    22  0.763     3.97 Sock Pu…  -3.70   4.46      -3.65      4.42       -5.54
##  8    62  4.31      3.61 Minecra…  -3.54   7.85      -2.53      6.84       -1.58
##  9   129  5.00      4.84 My Litt…   3.41   1.60       3.61      1.39       -2.29
## 10    14 16.4       4.26 G.I.Joe    3.39  13.0        3.99     12.4         9.76
## # … with 122 more rows, and 6 more variables: .mar.fitted &lt;dbl&gt;, cooksd &lt;dbl&gt;,
## #   mdffits &lt;dbl&gt;, covtrace &lt;dbl&gt;, covratio &lt;dbl&gt;, leverage.overall &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>toys_read[<span class="dv">93</span>, ]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   toy_type toy        hrs_week   age R_AGE
##   &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 G.I.Joe  Cold Front     4.28  7.35  7.78</code></pre>
<p><img src="images/coldfront.png" width="100px" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B3
</div>
<div class="question-body">
<p>Which <em>type</em> of toy has the greatest influence on our model?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-44" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-44&#39;, &#39;sol-start-44&#39;)"> Solution </span>
</div>
<div id="sol-body-44" class="solution-body" style="display: none;">
<p>Either this way:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hlm_augment</span>(rs_model, <span class="at">level=</span><span class="st">&quot;toy_type&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(cooksd))</span></code></pre></div>
<pre><code>## # A tibble: 20 × 10
##    toy_type  .ranef.intercept .ranef.hrs_week .ls.intercept .ls.hrs_week  cooksd
##    &lt;chr&gt;                &lt;dbl&gt;           &lt;dbl&gt;         &lt;dbl&gt;        &lt;dbl&gt;   &lt;dbl&gt;
##  1 G.I.Joe             1.86            1.06           9.29        -0.889 1.60e-1
##  2 Scooby D…           2.37            1.62           8.35         0.336 1.33e-1
##  3 Farm Ani…          -2.13           -1.73           0.314       -2.40  1.22e-1
##  4 My Littl…          -0.956          -0.979          6.82        -2.72  8.50e-2
##  5 Stretch …          -0.140           0.203         -4.65         1.47  8.09e-2
##  6 SuperZin…          -0.198          -0.412          4.57        -1.58  6.48e-2
##  7 Playmobil          -0.778          -0.336         -3.72         0.487 6.24e-2
##  8 Toy Story           0.970           0.890         -0.388        1.14  4.77e-2
##  9 Transfor…          -1.33           -1.03           1.44        -1.79  4.13e-2
## 10 Teenage …          -1.32           -0.912         -4.24        -0.510 3.96e-2
## 11 Lego Min…          -1.10           -0.925          2.55        -1.94  3.81e-2
## 12 Furby               0.894           0.791          0.235        0.948 3.29e-2
## 13 Star Wars           1.20            0.846          3.70         0.245 3.27e-2
## 14 Rugrats            -0.296          -0.0454        -3.46         0.545 2.68e-2
## 15 Polly Po…           0.715           0.662         -1.30         1.23  2.66e-2
## 16 Peppa Pig           0.174          -0.0388         4.04        -0.973 2.54e-2
## 17 Minecraft           0.393           0.433        -20.2          5.84  1.97e-2
## 18 Barbie              0.0856          0.165         -0.843        0.359 8.94e-3
## 19 Sock Pup…          -0.523          -0.331         -3.98         0.490 8.13e-3
## 20 Power Ra…           0.108           0.0754         1.44        -0.296 2.65e-4
## # … with 4 more variables: mdffits &lt;dbl&gt;, covtrace &lt;dbl&gt;, covratio &lt;dbl&gt;,
## #   leverage.overall &lt;dbl&gt;</code></pre>
<p>Or the plot. Note, the <strong>only</strong> reason we using the <code>cutoff = .15</code> is to make the labels appear.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>inftoytype <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(rs_model,<span class="at">level=</span><span class="st">&quot;toy_type&quot;</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(inftoytype<span class="sc">$</span>cooksd, <span class="at">index=</span>inftoytype<span class="sc">$</span>toy_type, <span class="at">cutoff=</span>.<span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,.<span class="dv">2</span>)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-15-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B4
</div>
<div class="question-body">
<p>Looking at the random effects, which toy type shows the least improvement in reading age as practice increases, and which shows the greatest improvement?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-45" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-45&#39;, &#39;sol-start-45&#39;)"> Solution </span>
</div>
<div id="sol-body-45" class="solution-body" style="display: none;">
<p>It looks like the Farm Animals have the least improvement, and Scooby Doo shows the most improvement</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(rs_model)</span></code></pre></div>
<pre><code>## $toy_type
##                              (Intercept)    hrs_week
## Barbie                         0.0855596  0.16463252
## Farm Animals                  -2.1303034 -1.72532126
## Furby                          0.8940478  0.79109745
## G.I.Joe                        1.8601170  1.05745304
## Lego Minifigures              -1.0963190 -0.92548279
## Minecraft                      0.3930185  0.43342754
## My Little Pony                -0.9557181 -0.97937536
## Peppa Pig                      0.1742980 -0.03882159
## Playmobil                     -0.7780752 -0.33556416
## Polly Pocket                   0.7147074  0.66199641
## Power Rangers                  0.1076182  0.07541960
## Rugrats                       -0.2959716 -0.04537848
## Scooby Doo                     2.3654608  1.61665908
## Sock Puppets                  -0.5225530 -0.33068125
## Star Wars                      1.2020393  0.84628213
## Stretch Armstrong             -0.1397913  0.20314258
## SuperZings                    -0.1976937 -0.41191503
## Teenage Mutant Ninja Turtles  -1.3163768 -0.91247162
## Toy Story                      0.9701905  0.88966357
## Transformers                  -1.3342550 -1.03476237
## 
## with conditional variances for &quot;toy_type&quot;</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question B5
</div>
<div class="question-body">
<p>What is the estimated reading age for sock puppets with zero hours of practice per week, and what is their estimated change in reading age for every hour per week increase in practice?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-46" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-46&#39;, &#39;sol-start-46&#39;)"> Solution </span>
</div>
<div id="sol-body-46" class="solution-body" style="display: none;">
<p>We can get these either by adding the <code>fixef()</code> and <code>ranef()</code> together, or:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(rs_model)</span></code></pre></div>
<pre><code>## $toy_type
##                              (Intercept)   hrs_week
## Barbie                         1.8415026  1.3081408
## Farm Animals                  -0.3743604 -0.5818130
## Furby                          2.6499908  1.9346058
## G.I.Joe                        3.6160599  2.2009613
## Lego Minifigures               0.6596239  0.2180255
## Minecraft                      2.1489614  1.5769358
## My Little Pony                 0.8002248  0.1641329
## Peppa Pig                      1.9302409  1.1046867
## Playmobil                      0.9778678  0.8079441
## Polly Pocket                   2.4706504  1.8055047
## Power Rangers                  1.8635611  1.2189279
## Rugrats                        1.4599714  1.0981298
## Scooby Doo                     4.1214037  2.7601674
## Sock Puppets                   1.2333900  0.8128271
## Star Wars                      2.9579822  1.9897904
## Stretch Armstrong              1.6161517  1.3466509
## SuperZings                     1.5582493  0.7315933
## Teenage Mutant Ninja Turtles   0.4395661  0.2310367
## Toy Story                      2.7261335  2.0331719
## Transformers                   0.4216880  0.1087459
## 
## attr(,&quot;class&quot;)
## [1] &quot;coef.mer&quot;</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(rs_model)<span class="sc">$</span>toy_type[<span class="st">&quot;Sock Puppets&quot;</span>,]</span></code></pre></div>
<pre><code>##              (Intercept)  hrs_week
## Sock Puppets     1.23339 0.8128271</code></pre>
<p><img src="images/sockpuppet.gif" width="100px" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
<div id="convergence-issues" class="section level1">
<h1>Convergence Issues</h1>
<div id="singular-fits" class="section level2">
<h2>Singular fits</h2>
<div class="statbox">
<p>You may have noticed that a lot of our models over the last few weeks have been giving a warning: <code>boundary (singular) fit: see ?isSingular</code>.<br />
Up to now, we’ve been largely ignoring these warnings. However, this week we’re going to look at how to deal with this issue.</p>
<p>The warning is telling us that our model has resulted in a ‘singular fit.’ Singular fits often indicate that the model is ‘overfitted’ - that is, the random effects structure which we have specified is too complex to be supported by the data.</p>
<p>Perhaps the most intuitive advice would be remove the most complex part of the random effects structure (i.e. random slopes). This leads to a simpler model that is not over-fitted. In other words, start simplying from the top (where the most complexity is) to the bottom (where the lowest complexity is).
Additionally, when variance estimates are very low for a specific random effect term, this indicates that the model is not estimating this parameter to differ much between the levels of your grouping variable. It might, in some experimental designs, be perfectly acceptable to remove this or simply include it as a fixed effect.</p>
<p>A key point here is that when fitting a mixed model, we should think about how the data are generated. Asking yourself questions such as “do we have good reason to assume subjects might vary over time, or to assume that they will have different starting points (i.e., different intercepts)?” can help you in specifying your random effect structure</p>
<p>You can read in depth about what this means by reading the help documentation for <code>?isSingular</code>. For our purposes, a relevant section is copied below:</p>
<p><em>… intercept-only models, or 2-dimensional random effects such as intercept + slope models, singularity is relatively easy to detect because it leads to random-effect variance estimates of (nearly) zero, or estimates of correlations that are (almost) exactly -1 or 1.</em></p>
</div>
</div>
<div id="convergence-warnings" class="section level2">
<h2>Convergence warnings</h2>
<div class="rtip">
<p>Issues of non-convergence can be caused by many things. If you’re model doesn’t converge, it does <em>not necessarily</em> mean the fit is incorrect, however it is <strong>is cause for concern</strong>, and should be addressed, else you may end up reporting inferences which do not hold.</p>
<p>There are lots of different things which you could do which <em>might</em> help your model to converge. A select few are detailed below:</p>
<ul>
<li><p>double-check the model specification and the data</p></li>
<li><p>adjust stopping (convergence) tolerances for the nonlinear optimizer, using the optCtrl argument to [g]lmerControl. (see <code>?convergence</code> for convergence controls).</p>
<ul>
<li>What is “tolerance?” Remember that our optimizer is the the method by which the computer finds the best fitting model, by iteratively assessing and trying to maximise the likelihood (or minimise the loss).
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-20"></span>
<img src="images/tolerance.png" alt="An optimizer will stop after a certain number of iterations, or when it meets a tolerance threshold" width="80%" />
<p class="caption">
Figure 1: An optimizer will stop after a certain number of iterations, or when it meets a tolerance threshold
</p>
</div></li>
</ul></li>
<li><p>center and scale continuous predictor variables (e.g. with <code>scale</code>)</p></li>
<li><p>Change the optimization method (for example, here we change it to <code>bobyqa</code>):
<code>lmer(..., control = lmerControl(optimizer="bobyqa"))</code><br />
<code>glmer(..., control = glmerControl(optimizer="bobyqa"))</code></p></li>
<li><p>Increase the number of optimization steps:
<code>lmer(..., control = lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=50000))</code><br />
<code>glmer(..., control = glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=50000))</code></p></li>
<li><p>Use <code>allFit()</code> to try the fit with all available optimizers. This will of course be slow, but is considered ‘the gold standard’; <em>“if all optimizers converge to values that are practically equivalent, then we would consider the convergence warnings to be false positives.”</em></p></li>
<li><p>Consider simplifying your model, for example by removing random effects with the smallest variance (but be careful to not simplify more than necessary, and ensure that your write up details these changes)</p></li>
</ul>
</div>
<div class="question-begin">
Question C1
</div>
<div class="question-body">
<p>Recall Questions C1-C6 in last week’s exercises, we used the <code>WeightMaintain3</code> dataset and fitted some models:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">&quot;https://uoepsy.github.io/data/WeightMaintain3.rda&quot;</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>m.base <span class="ot">&lt;-</span> <span class="fu">lmer</span>(WeightChange <span class="sc">~</span> Assessment <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Assessment <span class="sc">|</span> ID), <span class="at">data=</span>WeightMaintain3)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>m.int <span class="ot">&lt;-</span> <span class="fu">lmer</span>(WeightChange <span class="sc">~</span> Assessment <span class="sc">+</span> Condition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Assessment <span class="sc">|</span> ID), <span class="at">data=</span>WeightMaintain3)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>m.full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(WeightChange <span class="sc">~</span> Assessment <span class="sc">*</span> Condition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Assessment <span class="sc">|</span> ID), <span class="at">data=</span>WeightMaintain3)</span></code></pre></div>
<p>Many of these were singular fits, and we ignored them, e.g:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(m.base)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Think carefully about how you might simplify the random effect structure for these models, and pay close attention to the study design. What do we think the baseline weight change should be? Should it be the same for everyone? If so, might we want to remove the random intercept, which we can do by setting it to 0.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-47" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-47&#39;, &#39;sol-start-47&#39;)"> Solution </span>
</div>
<div id="sol-body-47" class="solution-body" style="display: none;">
<p>Think about what these models are fitting. Why (in this very specific research design) might it make sense to not model by-participant variation around the intercept?<br />
The “baseline” visit is the starting point for the study, and (based on the description we were given) it doesn’t make sense to think of participants’ weights as having changed by their baseline visit - changed since when? As baseline is at the very start of the weight maintenance, it makes sense that we wouldn’t have very much (if any) participant variation in change at this point.
Note that by removing the estimation of this parameter, our models now converge!</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>m.base <span class="ot">&lt;-</span> <span class="fu">lmer</span>(WeightChange <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Assessment <span class="sc">+</span> (<span class="dv">0</span> <span class="sc">+</span> Assessment <span class="sc">|</span> ID), <span class="at">data=</span>WeightMaintain3)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>m.int <span class="ot">&lt;-</span> <span class="fu">lmer</span>(WeightChange <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Assessment <span class="sc">+</span> Condition <span class="sc">+</span> (<span class="dv">0</span> <span class="sc">+</span> Assessment <span class="sc">|</span> ID), <span class="at">data=</span>WeightMaintain3)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>m.full <span class="ot">&lt;-</span> <span class="fu">lmer</span>(WeightChange <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Assessment <span class="sc">*</span> Condition <span class="sc">+</span> (<span class="dv">0</span> <span class="sc">+</span> Assessment <span class="sc">|</span> ID), <span class="at">data=</span>WeightMaintain3)</span></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(m.base)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="random-effects" class="section level1">
<h1>Random effects</h1>
<div class="statbox">
<p>When specifying a random effects model, think about the data you have and how they fit in the following table:</p>
<table>
<colgroup>
<col width="11%" />
<col width="37%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>Criterion:</th>
<th>Repetition: <br> <em>If the experiment were repeated:</em></th>
<th>Desired inference: <br> <em>The conclusions refer to:</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fixed effects</td>
<td>Same levels would be used</td>
<td>The levels used</td>
</tr>
<tr class="even">
<td>Random effects</td>
<td>Different levels would be used</td>
<td>A population from which the levels used are just a (random) sample</td>
</tr>
</tbody>
</table>
<p>For example, applying the criteria to the following questions:</p>
<ul>
<li><p>Do dogs learn faster with higher rewards?</p>
<p>FIXED: reward</p>
<p>RANDOM: dog</p></li>
<li><p>Do students read faster at higher temperatures?</p>
<p>FIXED: temperature</p>
<p>RANDOM: student</p></li>
<li><p>Does people speaking one language speak faster than another?</p>
<p>FIXED: the language</p>
<p>RANDOM: the people speaking that language</p></li>
</ul>
<p><br></p>
<p>Sometimes, after simplifying the model, you find that there isn’t much variability in a specific random effect and, if it still leads to singular fits or convergence warnings, it is common to just model that variable as a fixed effect.</p>
<p>Other times, you don’t have sufficient data or levels to estimate the random effect variance, and you are forced to model it as a fixed effect.
This is similar to trying to find the “best-fit” line passing through a single point… You can’t because you need two points!</p>
</div>
<div id="random-effects-in-lme4" class="section level2">
<h2>Random effects in lme4</h2>
<div class="rtip">
<p>Below are a selection of different formulas for specifying different random effect structures, taken from the <a href="https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf">lme4 vignette</a>. This might look like a lot, but over time and repeated use of multilevel models you will get used to reading these in a similar way to getting used to reading the formula structure of <code>y ~ x1 + x2</code> in all our linear models.
<br></p>
<table>
<colgroup>
<col width="29%" />
<col width="41%" />
<col width="29%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Formula</th>
<th align="right">Alternative</th>
<th align="right">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right"><span class="math inline">\(\text{(1 | g)}\)</span></td>
<td align="right"><span class="math inline">\(\text{1 + (1 | g)}\)</span></td>
<td align="right">Random intercept with fixed mean</td>
</tr>
<tr class="even">
<td align="right"><span class="math inline">\(\text{0 + offset(o) + (1 | g)}\)</span></td>
<td align="right"><span class="math inline">\(\text{-1 + offset(o) + (1 | g)}\)</span></td>
<td align="right">Random intercept with <em>a priori</em> means</td>
</tr>
<tr class="odd">
<td align="right"><span class="math inline">\(\text{(1 | g1/g2)}\)</span></td>
<td align="right"><span class="math inline">\(\text{(1 | g1) + (1 | g1:g2)}\)</span></td>
<td align="right">Intercept varying among <span class="math inline">\(g1\)</span> and <span class="math inline">\(g2\)</span> within <span class="math inline">\(g1\)</span></td>
</tr>
<tr class="even">
<td align="right"><span class="math inline">\(\text{(1 | g1) + (1 | g2)}\)</span></td>
<td align="right"><span class="math inline">\(\text{1 + (1 | g1) + (1 | g2)}\)</span></td>
<td align="right">Intercept varying among <span class="math inline">\(g1\)</span> and <span class="math inline">\(g2\)</span></td>
</tr>
<tr class="odd">
<td align="right"><span class="math inline">\(\text{x + (x | g)}\)</span></td>
<td align="right"><span class="math inline">\(\text{1 + x + (1 + x | g)}\)</span></td>
<td align="right">Correlated random intercept and slope</td>
</tr>
<tr class="even">
<td align="right"><span class="math inline">\(\text{x + (x || g)}\)</span></td>
<td align="right"><span class="math inline">\(\text{1 + x + (x | g) + (0 + x | g)}\)</span></td>
<td align="right">Uncorrelated random intercept and slope</td>
</tr>
</tbody>
</table>
<p><strong>Table 1:</strong> Examples of the right-hand-sides of mixed effects model formulas. <span class="math inline">\(g\)</span>, <span class="math inline">\(g1\)</span>, <span class="math inline">\(g2\)</span> are grouping factors, covariates and <em>a priori</em> known offsets are <span class="math inline">\(x\)</span> and <span class="math inline">\(o\)</span>.</p>
</div>
</div>
<div id="three-level-nesting" class="section level2">
<h2>Three-level nesting</h2>
<div class="frame">
<p><strong>Data: Treatment Effects</strong></p>
<p>Synthetic data from a RCT treatment study: 5 therapists randomly assigned participants to control or treatment group and monitored the participants’ performance over time. There was a baseline test, then 6 weeks of treatment, with test sessions every week (7 total sessions).</p>
<p>The following code will load in your R session an object already called <code>tx</code> with the data:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">&quot;https://uoepsy.github.io/msmr/data/tx.Rdata&quot;</span>))</span></code></pre></div>
You can see the head of the data below:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
group
</th>
<th style="text-align:center;">
session
</th>
<th style="text-align:center;">
therapist
</th>
<th style="text-align:center;">
Score
</th>
<th style="text-align:center;">
PID
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
control
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
A
</td>
<td style="text-align:center;">
0.56
</td>
<td style="text-align:center;">
A_control_15
</td>
</tr>
<tr>
<td style="text-align:center;">
control
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
B
</td>
<td style="text-align:center;">
0.61
</td>
<td style="text-align:center;">
B_control_15
</td>
</tr>
<tr>
<td style="text-align:center;">
control
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
C
</td>
<td style="text-align:center;">
0.54
</td>
<td style="text-align:center;">
C_control_15
</td>
</tr>
<tr>
<td style="text-align:center;">
control
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
D
</td>
<td style="text-align:center;">
0.45
</td>
<td style="text-align:center;">
D_control_15
</td>
</tr>
<tr>
<td style="text-align:center;">
control
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
E
</td>
<td style="text-align:center;">
0.59
</td>
<td style="text-align:center;">
E_control_15
</td>
</tr>
<tr>
<td style="text-align:center;">
control
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
A
</td>
<td style="text-align:center;">
0.56
</td>
<td style="text-align:center;">
A_control_21
</td>
</tr>
</tbody>
</table>
</div>
<div class="question-begin">
Question D1
</div>
<div class="question-body">
<p>Load and visualise the data. Does it look like the treatment had an effect on the performance score?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-48" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-48&#39;, &#39;sol-start-48&#39;)"> Solution </span>
</div>
<div id="sol-body-48" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tx, <span class="fu">aes</span>(session, Score, <span class="at">color=</span>group)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom=</span><span class="st">&quot;pointrange&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>() <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-27-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Just for fun, let’s add on the individual participant scores, and also make a plot for each therapist.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tx, <span class="fu">aes</span>(session, Score, <span class="at">color=</span>group)) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean_se, <span class="at">geom =</span> <span class="st">&quot;pointrange&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>() <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> PID), <span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> therapist)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-28-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question D2
</div>
<div class="question-body">
<p>Consider these questions when you’re designing your model(s) and use your answers to motivate your model design and interpretation of results:</p>
<ol style="list-style-type: lower-alpha">
<li>What are the levels of nesting? How should that be reflected in the random effect structure?</li>
<li>What is the shape of change over time? Do you need polynomials to model this shape? If yes, what order polynomials?</li>
</ol>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-49" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-49&#39;, &#39;sol-start-49&#39;)"> Solution </span>
</div>
<div id="sol-body-49" class="solution-body" style="display: none;">
<ol style="list-style-type: lower-alpha">
<li>There are repeated measures of participants (session). There are also repeated measures of therapists (each one treated many participants).</li>
<li>Looks like linear change, don’t need polynomials. Good to know that there is no difference at baseline, so no need for orthogonal time.</li>
</ol>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question D3
</div>
<div class="question-body">
<p>Test whether the treatment had an effect using mixed-effects modelling.</p>
<p>Try to fit the <strong>maximal</strong> model.<br />
Does it converge? Is it singular?</p>
<div class="optional-begin">
<span id="opt-start-50" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-50&#39;, &#39;opt-start-50&#39;)"> Hint: What <em>is</em> the maximal model?</span>
</div>
<div id="opt-body-50" class="optional-body" style="display: none;">
<p>There’s an interaction between session and group. Each participant has several sessions, so we want <code>(1 + session | PID)</code> and each therapist has several groups and sessions, so we want <code>(1 + ? * ? | ?)</code></p>
</div>
<p class="optional-end">
</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-51" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-51&#39;, &#39;sol-start-51&#39;)"> Solution </span>
</div>
<div id="sol-body-51" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># start with maximal model</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Score <span class="sc">~</span> session <span class="sc">*</span> group <span class="sc">+</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> session <span class="sc">|</span> PID) <span class="sc">+</span> </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> session <span class="sc">*</span> group <span class="sc">|</span> therapist),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tx)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(m1)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question D4
</div>
<div class="question-body">
<p>Try adjusting your model by removing random effects or correlations, examine the model again, and so on..</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-52" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-52&#39;, &#39;sol-start-52&#39;)"> Solution </span>
</div>
<div id="sol-body-52" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m1)</span></code></pre></div>
<pre><code>##  Groups    Name                 Std.Dev.  Corr                
##  PID       (Intercept)          0.1181433                     
##            session              0.0315954 -0.603              
##  therapist (Intercept)          0.0000000                     
##            session              0.0023525    NaN              
##            groupcontrol         0.0098621    NaN  1.000       
##            session:groupcontrol 0.0019791    NaN -1.000 -1.000
##  Residual                       0.0732691</code></pre>
<p>There’s a correlation of exactly -1 between the random intercepts and slopes for therapists, and the standard deviation estimate for <code>session|therapist</code> is pretty small. Let’s remove it.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Score <span class="sc">~</span> session <span class="sc">*</span> group <span class="sc">+</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> session <span class="sc">|</span> PID) <span class="sc">+</span> </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">|</span> therapist),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tx)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m2)</span></code></pre></div>
<pre><code>##  Groups    Name        Std.Dev. Corr  
##  PID       (Intercept) 0.118298       
##            session     0.031661 -0.602
##  therapist (Intercept) 0.000000       
##  Residual              0.073270</code></pre>
<p>It now looks like estimates for random intercepts for therapists is now 0. If we remove this, our model finally is non-singular:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Score <span class="sc">~</span> session <span class="sc">*</span> group <span class="sc">+</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> session <span class="sc">|</span> PID),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tx)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: Score ~ session * group + (1 + session | PID)
##    Data: tx
## 
## REML criterion at convergence: -1633.6
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.63301 -0.58620  0.01599  0.55405  2.88093 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  PID      (Intercept) 0.013994 0.11829       
##           session     0.001002 0.03166  -0.60
##  Residual             0.005368 0.07327       
## Number of obs: 945, groups:  PID, 135
## 
## Fixed effects:
##                       Estimate Std. Error t value
## (Intercept)           0.526849   0.015959  33.013
## session               0.033688   0.004130   8.156
## groupcontrol          0.018136   0.022999   0.789
## session:groupcontrol -0.020138   0.005952  -3.383
## 
## Correlation of Fixed Effects:
##             (Intr) sessin grpcnt
## session     -0.655              
## groupcontrl -0.694  0.454       
## sssn:grpcnt  0.454 -0.694 -0.655</code></pre>
<p>Lastly, it’s then a good idea to check that the parameter estimates and SE are not radically different across these models (they are virtually identical)</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                         Estimate  Std. Error    t value
## (Intercept)           0.52684907 0.015942928 33.0459425
## session               0.03368821 0.004255211  7.9169307
## groupcontrol          0.01813605 0.023395688  0.7751876
## session:groupcontrol -0.02013829 0.006007577 -3.3521487</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                         Estimate  Std. Error    t value
## (Intercept)           0.52684907 0.015959286 33.0120700
## session               0.03368821 0.004130318  8.1563229
## groupcontrol          0.01813605 0.022999779  0.7885314
## session:groupcontrol -0.02013829 0.005952422 -3.3832097</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                         Estimate  Std. Error    t value
## (Intercept)           0.52684907 0.015958981 33.0127011
## session               0.03368821 0.004130297  8.1563646
## groupcontrol          0.01813605 0.022999339  0.7885464
## session:groupcontrol -0.02013829 0.005952391 -3.3832270</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question D5: Optional
</div>
<div class="question-body">
<p>Try the code below to use the <code>allFit()</code> function to fit your final model with all the available optimizers.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<ul>
<li>You might need to install the <code>dfoptim</code> package to get one of the optimizers</li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>sumfits <span class="ot">&lt;-</span> <span class="fu">allFit</span>(yourmodel)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sumfits)</span></code></pre></div>
</div>
<p class="question-end">
</p>
</div>
<div id="crossed-random-effects" class="section level2">
<h2>Crossed random effects</h2>
<div class="frame">
<p><strong>Data: Test-enhanced learning</strong></p>
<p>An experiment was run to conceptually replicate “test-enhanced learning” (Roediger &amp; Karpicke, 2006): two groups of 25 participants were presented with material to learn. One group studied the material twice (<code>StudyStudy</code>), the other group studied the material once then did a test (<code>StudyTest</code>). Recall was tested immediately (one minute) after the learning session and one week later. The recall tests were composed of 175 items identified by a keyword (<code>Test_word</code>). One of the researchers’ questions concerned how test-enhanced learning influences time-to-recall.</p>
<p>The critical (replication) prediction is that the <code>StudyStudy</code> group should perform somewhat better on the immediate recall test, but the <code>StudyTest</code> group will retain the material better and thus perform better on the 1-week follow-up test.</p>
<p>The following code loads the data into your R environment by creating a variable called <code>tel</code>:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">&quot;https://uoepsy.github.io/data/testenhancedlearning.RData&quot;</span>))</span></code></pre></div>
The head of the dataset can be seen below:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Subject_ID
</th>
<th style="text-align:center;">
Group
</th>
<th style="text-align:center;">
Delay
</th>
<th style="text-align:center;">
Test_word
</th>
<th style="text-align:center;">
Correct
</th>
<th style="text-align:center;">
Rtime
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
StudyTest_L
</td>
<td style="text-align:center;">
StudyTest
</td>
<td style="text-align:center;">
min
</td>
<td style="text-align:center;">
van
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
456.81
</td>
</tr>
<tr>
<td style="text-align:center;">
StudyTest_L
</td>
<td style="text-align:center;">
StudyTest
</td>
<td style="text-align:center;">
week
</td>
<td style="text-align:center;">
dinosaur
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
888.13
</td>
</tr>
<tr>
<td style="text-align:center;">
StudyTest_L
</td>
<td style="text-align:center;">
StudyTest
</td>
<td style="text-align:center;">
min
</td>
<td style="text-align:center;">
typewriter
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
713.43
</td>
</tr>
<tr>
<td style="text-align:center;">
StudyTest_L
</td>
<td style="text-align:center;">
StudyTest
</td>
<td style="text-align:center;">
min
</td>
<td style="text-align:center;">
chimney
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
725.52
</td>
</tr>
<tr>
<td style="text-align:center;">
StudyTest_L
</td>
<td style="text-align:center;">
StudyTest
</td>
<td style="text-align:center;">
week
</td>
<td style="text-align:center;">
dog
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
472.69
</td>
</tr>
<tr>
<td style="text-align:center;">
StudyTest_L
</td>
<td style="text-align:center;">
StudyTest
</td>
<td style="text-align:center;">
min
</td>
<td style="text-align:center;">
turkey
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
574.30
</td>
</tr>
</tbody>
</table>
</div>
<div class="question-begin">
Question E1
</div>
<div class="question-body">
<p>Load and plot the data. Does it look like the effect was replicated?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-53" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-53&#39;, &#39;sol-start-53&#39;)"> Solution </span>
</div>
<div id="sol-body-53" class="solution-body" style="display: none;">
<p>You can make use of <code>stat_summary()</code> again!</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tel, <span class="fu">aes</span>(Delay, Rtime, <span class="at">col=</span>Group)) <span class="sc">+</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data=</span>mean_se, <span class="at">geom=</span><span class="st">&quot;pointrange&quot;</span>)<span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code></pre></div>
<p>It’s more work, but some people might rather calculate the numbers and then plot them directly. It does just the same thing:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>tel <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Delay, Group) <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(Rtime),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="fu">sd</span>(Rtime)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>())</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x=</span>Delay, <span class="at">col =</span> Group)) <span class="sc">+</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">y=</span>mean, <span class="at">ymin=</span>mean<span class="sc">-</span>se, <span class="at">ymax=</span>mean<span class="sc">+</span>se))<span class="sc">+</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Response Time (ms)&quot;</span>)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-39-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>That looks like test-enhanced learning to me!</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question E2
</div>
<div class="question-body">
<p>Test the critical hypothesis using a mixed-effects model. Fit the maximal random effect structure supported by the experimental design.</p>
<p>Some questions to consider:</p>
<ul>
<li><p>Item accuracy is a binary variable. What kind of model will you use?<br />
</p></li>
<li><p>We can expect variability across subjects (some people are better at learning than others) and across items (some of the recall items are harder than others). How should this be represented in the random effects?</p></li>
<li><p>If a model takes ages to fit, you might want to cancel it by pressing the escape key. It is normal for complex models to take time, but for the purposes of this task, give up after a couple of minutes, and try simplifying your model.</p></li>
</ul>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-54" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-54&#39;, &#39;sol-start-54&#39;)"> Solution </span>
</div>
<div id="sol-body-54" class="solution-body" style="display: none;">
<p>This one will probably take a little bit of time:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Rtime <span class="sc">~</span> Delay<span class="sc">*</span>Group <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">|</span> Subject_ID) <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">*</span> Group <span class="sc">|</span> Test_word),</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tel, <span class="at">control=</span><span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</span></code></pre></div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question E3
</div>
<div class="question-body">
<p>The model with maximal random effects will probably not converge, or will obtain a singular fit. Simplify the model until you achieve convergence.<br />
<br>
What we’re aiming to do here is to follow <a href="https://doi.org/10.1016/j.jml.2012.11.001">Barr et al.’s</a> advice of defining our maximal model and then removing only the terms to allow a non-singular fit.<br />
<br>
<strong>Note:</strong> This strategy - starting with the maximal random effects structure and removing terms until obtaining model convergence, is just <em>one</em> approach, and there are drawbacks (see <a href="https://doi.org/10.1016/j.jml.2017.01.001">Matuschek et al., 2017</a>). There is no consensus on what approach is best (see <code>?isSingular</code>).<br />
<br>
<br>
<em>Tip:</em> you can look at the variance estimates and correlations easily by using the <code>VarCorr()</code> function. What jumps out?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-55" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-55&#39;, &#39;sol-start-55&#39;)"> Solution </span>
</div>
<div id="sol-body-55" class="solution-body" style="display: none;">
<p>There’s a correlation of .999 for some of the random effects by-item!</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m)</span></code></pre></div>
<pre><code>##  Groups     Name                     Std.Dev. Corr                
##  Test_word  (Intercept)               40.956                      
##             Delayweek                 25.223  -0.823              
##             GroupStudyTest            25.429  -0.852  0.999       
##             Delayweek:GroupStudyTest  13.453   0.998 -0.786 -0.817
##  Subject_ID (Intercept)               48.177                      
##             Delayweek                 14.073  -0.536              
##  Residual                            297.325</code></pre>
<p>lets remove the interaction in the by-word random effects:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Rtime <span class="sc">~</span> Delay<span class="sc">*</span>Group <span class="sc">+</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">|</span> Subject_ID) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">+</span> Group <span class="sc">|</span> Test_word),</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tel, <span class="at">control=</span><span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m1)</span></code></pre></div>
<pre><code>##  Groups     Name           Std.Dev. Corr         
##  Test_word  (Intercept)     37.547               
##             Delayweek       20.416  -0.695       
##             GroupStudyTest  20.169  -0.738  0.998
##  Subject_ID (Intercept)     48.176               
##             Delayweek       14.068  -0.536       
##  Residual                  297.346</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(m1)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>We still have a singular fit here, and the correlation is just slightly different (0.998). Thinking about the study, if we are going to remove <strong>one</strong> of the by-testword random effects (<code>Delay</code> or <code>Group</code>), which one do we consider to be more theoretically justified? Is the effect of Delay likely to vary by test-words? More so than the effect of group is likely to vary by test-words? Quite possibly - there’s no obvious reason for <em>certain</em> words to be more memorable for people in one group vs another. But there is reason for words to vary in the effect that delay of one week has - how familiar a word is will likely influence the amount to which a week’s delay has on recall.</p>
<p>Let’s remove the by-testword random effect of group.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Rtime <span class="sc">~</span> Delay<span class="sc">*</span>Group <span class="sc">+</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">|</span> Subject_ID) <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>             (<span class="dv">1</span> <span class="sc">+</span> Delay <span class="sc">|</span> Test_word),</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>tel, <span class="at">control=</span><span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(m2)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m2)</span></code></pre></div>
<pre><code>##  Groups     Name        Std.Dev. Corr  
##  Test_word  (Intercept)  29.3486       
##             Delayweek     8.8058 -0.594
##  Subject_ID (Intercept)  48.1651       
##             Delayweek    13.9890 -0.537
##  Residual               297.6631</code></pre>
<p>Hooray, the model converged!</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: Rtime ~ Delay * Group + (1 + Delay | Subject_ID) + (1 + Delay |  
##     Test_word)
##    Data: tel
## Control: lmerControl(optimizer = &quot;bobyqa&quot;)
## 
## REML criterion at convergence: 249189.6
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.2904 -0.6785 -0.0012  0.6712  3.8854 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev. Corr 
##  Test_word  (Intercept)   861.34  29.349       
##             Delayweek      77.54   8.806  -0.59
##  Subject_ID (Intercept)  2319.87  48.165       
##             Delayweek     195.69  13.989  -0.54
##  Residual               88603.33 297.663       
## Number of obs: 17498, groups:  Test_word, 175; Subject_ID, 50
## 
## Fixed effects:
##                          Estimate Std. Error t value
## (Intercept)               885.762     10.862  81.548
## Delayweek                  31.162      6.985   4.462
## GroupStudyTest            -18.564     15.037  -1.235
## Delayweek:GroupStudyTest  -16.298      9.832  -1.658
## 
## Correlation of Fixed Effects:
##             (Intr) Delywk GrpStT
## Delayweek   -0.470              
## GropStdyTst -0.692  0.331       
## Dlywk:GrpST  0.325 -0.704 -0.470</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question E4
</div>
<div class="question-body">
<p>Load the <strong>effects</strong> package, and try running this code:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>ef <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">effect</span>(<span class="st">&quot;Delay:Group&quot;</span>, m2))</span></code></pre></div>
<p>What is <code>ef</code>? and how can you use it to plot the model-estimated condition means and variability?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-56" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-56&#39;, &#39;sol-start-56&#39;)"> Solution </span>
</div>
<div id="sol-body-56" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ef, <span class="fu">aes</span>(Delay, fit, <span class="at">color=</span>Group)) <span class="sc">+</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymax=</span>upper, <span class="at">ymin=</span>lower), <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.2</span>))<span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="co"># just for a change :)</span></span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-46-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question E5
</div>
<div class="question-body">
<p>Can we get a similar plot using <code>plot_model()</code> from the <strong>sjPlot</strong> package?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-57" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-57&#39;, &#39;sol-start-57&#39;)"> Solution </span>
</div>
<div id="sol-body-57" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m2, <span class="at">type=</span><span class="st">&quot;int&quot;</span>)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-47-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question E6
</div>
<div class="question-body">
<p>What should we do with this information? How can we apply test-enhanced learning to learning R and statistics?</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-58" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-58&#39;, &#39;sol-start-58&#39;)"> Solution </span>
</div>
<div id="sol-body-58" class="solution-body" style="display: none;">
<p>You’ll get the benefits of test-enhanced learning if you try yourself before looking at the solutions! If you don’t test yourself, you’re more likely to forget it in the long run.</p>
</div>
<p class="solution-end">
</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
</div>
<div id="less-guided-exercises" class="section level1">
<h1>Less-Guided Exercises</h1>
<div class="frame">
<p><strong>Data: Naming</strong></p>
<p>72 children from 10 schools were administered the full Boston Naming Test (BNT-60) on a yearly basis for 5 years to examine development of word retrieval. Five of the schools taught lessons in a bilingual setting with English as one of the languages, and the remaining five schools taught in monolingual English.</p>
<p>The data is available at <a href="https://uoepsy.github.io/data/bntmono.csv">https://uoepsy.github.io/data/bntmono.csv</a>.</p>
<table style="width:61%;">
<colgroup>
<col width="18%" />
<col width="43%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">variable</th>
<th align="center">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">child_id</td>
<td align="center">unique child identifier</td>
</tr>
<tr class="even">
<td align="center">school_id</td>
<td align="center">unique school identifier</td>
</tr>
<tr class="odd">
<td align="center">BNT60</td>
<td align="center">score on the Boston Naming
Test-60. Scores range from 0
to 60</td>
</tr>
<tr class="even">
<td align="center">schoolyear</td>
<td align="center">Year of school</td>
</tr>
<tr class="odd">
<td align="center">mlhome</td>
<td align="center">Mono/Bi-lingual School. 0 =
Bilingual, 1 = Monolingual</td>
</tr>
</tbody>
</table>
</div>
<div class="question-begin">
Question E7
</div>
<div class="question-body">
<p>Fit a model examining the interaction between the effects of school year and mono/bilingual teaching on word retrieval, with random intercepts only for children and schools.<br />
<strong>tip:</strong> make sure your variables are of the right type first - e.g. numeric, factor etc<br />
<br>
Examine the fit and consider your model assumptions, and assess what might be done to improve the model in order to make better statistical inferences.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-59" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-59&#39;, &#39;sol-start-59&#39;)"> Solution </span>
</div>
<div id="sol-body-59" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>bnt <span class="ot">&lt;-</span> bnt <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(mlhome, school_id, child_id), factor))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>bntm0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(BNT60 <span class="sc">~</span> schoolyear <span class="sc">*</span> mlhome <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> school_id<span class="sc">/</span>child_id), <span class="at">data =</span> bnt)</span></code></pre></div>
<p>Residuals don’t look zero mean:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bntm0, <span class="at">type=</span><span class="fu">c</span>(<span class="st">&quot;p&quot;</span>,<span class="st">&quot;smooth&quot;</span>))</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-50-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>It looks a little like, compared to our model (black lines below) the children’s scores (coloured lines) are more closely clustered together when they start school, and then they are more spread out by the end of the study.
The fact that we’re fitting the same slope for each child is restricting us here, so we should try fitting random effects of schoolyear.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(bntm0) <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>schoolyear, <span class="at">col=</span>child_id)) <span class="sc">+</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> BNT60))<span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">y =</span> BNT60))<span class="sc">+</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted), <span class="at">col=</span><span class="st">&quot;black&quot;</span>, <span class="at">alpha=</span>.<span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">col=</span><span class="st">&quot;none&quot;</span>)<span class="sc">+</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>school_id)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-51-1.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>bntm1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(BNT60 <span class="sc">~</span> schoolyear <span class="sc">*</span> mlhome <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> schoolyear <span class="sc">|</span> school_id<span class="sc">/</span>child_id), <span class="at">data =</span> bnt)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bntm1, <span class="at">type=</span><span class="fu">c</span>(<span class="st">&quot;p&quot;</span>,<span class="st">&quot;smooth&quot;</span>))</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-52-1.png" width="80%" style="display: block; margin: auto;" />
Much better!</p>
<p>Let’s do some quick diagnostic checks for influence:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>inf1 <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(bntm1, <span class="at">level=</span><span class="dv">1</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(inf1<span class="sc">$</span>cooksd, <span class="at">cutoff =</span> <span class="st">&quot;internal&quot;</span>)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-53-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>If you check in the help for <code>dotplot_diag()</code>, it tells you that</p>
<ol style="list-style-type: lower-alpha">
<li>we can add an index for the labels, and</li>
<li>the coordinates (x,y) are flipped. We’re telling R to change the limits of the y axis, but actually it is the x axis. This is just because we want to see the label for that point out to the right.</li>
</ol>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>infchild <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(bntm1, <span class="at">level=</span><span class="st">&quot;child_id:school_id&quot;</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(infchild<span class="sc">$</span>cooksd, <span class="at">cutoff =</span> <span class="st">&quot;internal&quot;</span>, <span class="at">index =</span> infchild<span class="sc">$</span><span class="st">`</span><span class="at">child_id:school_id</span><span class="st">`</span>) <span class="sc">+</span> </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">05</span>))</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-54-1.png" width="80%" style="display: block; margin: auto;" />
And then we can examine the effects to the fixed effects and our standard errors when we remove this child:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>del94 <span class="ot">&lt;-</span> <span class="fu">case_delete</span>(bntm1, <span class="at">level=</span><span class="st">&quot;child_id:school_id&quot;</span>, <span class="at">delete =</span> <span class="st">&quot;ID94:SC9&quot;</span>)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(del94<span class="sc">$</span>fixef.original, del94<span class="sc">$</span>fixef.delete)</span></code></pre></div>
<pre><code>##                         [,1]       [,2]
## (Intercept)         6.265626  6.2627962
## schoolyear          6.371168  6.3639335
## mlhome1             0.138711 -0.3052998
## schoolyear:mlhome1 -2.603763 -2.3701181</code></pre>
<div class="optional-begin">
<span id="opt-start-60" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-60&#39;, &#39;opt-start-60&#39;)"> Optional: Case deletion influence on standard errors</span>
</div>
<div id="opt-body-60" class="optional-body" style="display: none;">
<p>We can examine the influence that deleting a case has on the standard errors.
The standard errors are the square-root of the diagonal of the model-implied variance-covariance matrix:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>( </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">diag</span>(del94<span class="sc">$</span>vcov.original)),</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">diag</span>(del94<span class="sc">$</span>vcov.delete))</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##                         [,1]      [,2]
## (Intercept)        1.0413285 0.9557645
## schoolyear         0.7719321 0.6717837
## mlhome1            1.4683927 1.3525492
## schoolyear:mlhome1 1.0875897 0.9498207</code></pre>
</div>
<p class="optional-end">
</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>infschool <span class="ot">&lt;-</span> <span class="fu">hlm_influence</span>(bntm1, <span class="at">level=</span><span class="st">&quot;school_id&quot;</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot_diag</span>(infschool<span class="sc">$</span>cooksd, <span class="at">cutoff =</span> <span class="st">&quot;internal&quot;</span>, <span class="at">index =</span> infschool<span class="sc">$</span>school_id)</span></code></pre></div>
<p><img src="03_assumptranef_files/figure-html/unnamed-chunk-57-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question E8
</div>
<div class="question-body">
<p>Using a method of your choosing, conduct inferences from your model and write up the results.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-61" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-61&#39;, &#39;sol-start-61&#39;)"> Solution </span>
</div>
<div class="solution-body" id = "sol-body-61" style="display: none;">



<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>bnt_null <span class="ot">&lt;-</span> <span class="fu">lmer</span>(BNT60 <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span>  (<span class="dv">1</span> <span class="sc">|</span> school_id<span class="sc">/</span>child_id), <span class="at">data =</span> bnt)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(bnt_null)) <span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(grp, vcov) <span class="sc">%&gt;%</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">icc =</span> <span class="fu">cumsum</span>(vcov)<span class="sc">/</span><span class="fu">sum</span>(vcov)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>##                  grp     vcov       icc
## 1 child_id:school_id 36.52302  22.21657
## 2          school_id 28.76157  39.71194
## 3           Residual 99.11079 100.00000</code></pre>
<p>This took quite a while to run:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmeresampler)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>bntm1BS <span class="ot">&lt;-</span> <span class="fu">bootstrap</span>(bntm1, <span class="at">.f=</span>fixef, <span class="at">type =</span> <span class="st">&quot;case&quot;</span>, <span class="at">B =</span> <span class="dv">2000</span>, <span class="at">resample =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>,<span class="cn">TRUE</span>,<span class="cn">FALSE</span>))</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(bntm1BS, <span class="at">type =</span> <span class="st">&quot;perc&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 6
##   term               estimate lower upper type  level
##   &lt;chr&gt;                 &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
## 1 (Intercept)           6.27   5.43  7.12 perc   0.95
## 2 schoolyear            6.37   5.72  7.02 perc   0.95
## 3 mlhome1               0.139 -1.12  1.40 perc   0.95
## 4 schoolyear:mlhome1   -2.60  -3.51 -1.59 perc   0.95</code></pre>
<div class="int">
<p>Multilevel level linear regression was used to investigate childrens’ development of word retrieval over 5 years of school, and whether development was dependent upon the school teaching classes monolingually or bilingually.
Initial evaluation of the intercept-only model indicated that the clustering of multiple observations from children within schools accounted for 39.7% of the variance in scores on the Boston Naming Task (BNT60, range 0 to 60).
BNT60 scores were modelled with fixed effects of school year (1-5) and monolingual teaching (monolingual vs bilingual, treatment coded with monolingual as the reference level). Random intercepts and slopes of school year were included for schools and for children nested within schools. The model was fitting with maximum likelihood estimation using the default optimiser from the <strong>lme4</strong> package (Bates et al., 2015).<br />
95% Confidence for fixed effect estimates were constructed by case-based bootstrapping with 2000 bootstraps in which children, (but neither observations within children nor the schools within which children were nested) were resampled.
Results indicated that children’s scores on the BNT60 increased over the 5 years in which they were studied, with children from bilingual schools increasing in scores by 6.37 ([5.72 – 7.02]) every school year. There was a significant interaction between mono/bilingual schools and the changes over school year, with children from monolingual schools increasing -2.6 ([-3.51 – -1.59]) less than those from bilingual schools for every additional year of school. Full model results can be found in Table 1.</p>
</div>
Table 1
<table>
<tr>
<th class="thead firsttablerow firsttablecol col1">
 
</th>
<th colspan="2" class="thead firsttablerow">
BNT 60
</th>
</tr>
<tr>
<td class="depvarhead firsttablerow firsttablecol col1">
Predictors
</td>
<td class="depvarhead firsttablerow col2">
Estimates
</td>
<td class="depvarhead firsttablerow col3">
95% CI<br>bootstrap
</td>
</tr>
<tr>
<td class="tdata firsttablecol col1">
Intercept
</td>
<td class="tdata centeralign modelcolumn1 col2">
6.27
</td>
<td class="tdata centeralign modelcolumn1 col3">
5.43 – 7.12
</td>
</tr>
<tr>
<td class="tdata firsttablecol col1">
School Year
</td>
<td class="tdata centeralign modelcolumn1 col2">
6.37
</td>
<td class="tdata centeralign modelcolumn1 col3">
4.85 – 7.89
</td>
</tr>
<tr>
<td class="tdata firsttablecol col1">
MonolingualSchool [1]
</td>
<td class="tdata centeralign modelcolumn1 col2">
0.14
</td>
<td class="tdata centeralign modelcolumn1 col3">
-2.75 – 3.03
</td>
</tr>
<tr>
<td class="tdata firsttablecol col1">
School<br>Year:MonolingualSchool<br>[1]
</td>
<td class="tdata centeralign modelcolumn1 col2">
-2.60
</td>
<td class="tdata centeralign modelcolumn1 col3">
-4.74 – -0.46
</td>
</tr>
<tr>
<td colspan="3" class="randomparts">
Random Effects
</td>
</tr>
<tr>
<td class="tdata leftalign summary">
σ<sup>2</sup>
</td>
<td class="tdata summary summarydata" colspan="2">
8.64
</td>
<tr>
<td class="tdata leftalign summary">
τ<sub>00</sub> <sub>child_id:school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
1.77
</td>
<tr>
<td class="tdata leftalign summary">
τ<sub>00</sub> <sub>school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
3.83
</td>
<tr>
<td class="tdata leftalign summary">
τ<sub>11</sub> <sub>child_id:school_id.schoolyear</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
6.83
</td>
<tr>
<td class="tdata leftalign summary">
τ<sub>11</sub> <sub>school_id.schoolyear</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
1.89
</td>
<tr>
<td class="tdata leftalign summary">
ρ<sub>01</sub> <sub>child_id:school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
-0.42
</td>
<tr>
<td class="tdata leftalign summary">
ρ<sub>01</sub> <sub>school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
-0.39
</td>
<tr>
<td class="tdata leftalign summary">
ICC
</td>
<td class="tdata summary summarydata" colspan="2">
0.91
</td>
<tr>
<td class="tdata leftalign summary">
N <sub>child_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
74
</td>
<tr>
<td class="tdata leftalign summary">
N <sub>school_id</sub>
</td>
<td class="tdata summary summarydata" colspan="2">
10
</td>
<tr>
<td class="tdata leftalign summary firstsumrow">
Observations
</td>
<td class="tdata summary summarydata firstsumrow" colspan="2">
370
</td>
</tr>
<tr>
<td class="tdata leftalign summary">
Marginal R<sup>2</sup> / Conditional R<sup>2</sup>
</td>
<td class="tdata summary summarydata" colspan="2">
0.420 / 0.947
</td>
</tr>
</table>
</div>
<p class="solution-end">
</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>If you have an older version of <code>lme4</code>, then <code>allFit()</code> might not be directly available, and you will need to run the following: <code>source(system.file("utils", "allFit.R", package="lme4"))</code>.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
