<!DOCTYPE html>
<html lang="en"><head>
<script src="03-interp-maxmod_files/libs/clipboard/clipboard.min.js"></script>
<script src="03-interp-maxmod_files/libs/quarto-html/tabby.min.js"></script>
<script src="03-interp-maxmod_files/libs/quarto-html/popper.min.js"></script>
<script src="03-interp-maxmod_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="03-interp-maxmod_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="03-interp-maxmod_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="03-interp-maxmod_files/libs/quarto-html/quarto-syntax-highlighting-89ef1ee790bdc269b52a829279c5ce0e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.24">

  <meta name="author" content="Elizabeth Pankratz (elizabeth.pankratz@ed.ac.uk)">
  <title>Interpreting LMMs and   building maximal models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="03-interp-maxmod_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="03-interp-maxmod_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #1f1c1b;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #1f1c1b; } /* Normal */
    code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
    code span.an { color: #ca60ca; } /* Annotation */
    code span.at { color: #0057ae; } /* Attribute */
    code span.bn { color: #b08000; } /* BaseN */
    code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
    code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #924c9d; } /* Char */
    code span.cn { color: #aa5500; } /* Constant */
    code span.co { color: #898887; } /* Comment */
    code span.cv { color: #0095ff; } /* CommentVar */
    code span.do { color: #607880; } /* Documentation */
    code span.dt { color: #0057ae; } /* DataType */
    code span.dv { color: #b08000; } /* DecVal */
    code span.er { color: #bf0303; text-decoration: underline; } /* Error */
    code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
    code span.fl { color: #b08000; } /* Float */
    code span.fu { color: #644a9b; } /* Function */
    code span.im { color: #ff5500; } /* Import */
    code span.in { color: #b08000; } /* Information */
    code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
    code span.op { color: #ca60ca; } /* Operator */
    code span.ot { color: #006e28; } /* Other */
    code span.pp { color: #006e28; } /* Preprocessor */
    code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
    code span.sc { color: #3daee9; } /* SpecialChar */
    code span.ss { color: #ff5500; } /* SpecialString */
    code span.st { color: #bf0303; } /* String */
    code span.va { color: #0057ae; } /* Variable */
    code span.vs { color: #bf0303; } /* VerbatimString */
    code span.wa { color: #bf0303; } /* Warning */
  </style>
  <link rel="stylesheet" href="03-interp-maxmod_files/libs/revealjs/dist/theme/quarto-b6d264701717e1a38d32b7b2d78c33cb.css">
  <link href="03-interp-maxmod_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="03-interp-maxmod_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="03-interp-maxmod_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="03-interp-maxmod_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="03-interp-maxmod_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="03-interp-maxmod_files/libs/revealjs/plugin/reveal-attribution/attribution.css" rel="stylesheet">
  <link href="03-interp-maxmod_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
  $(document).ready(function() {
      $('.cell').each(function() {
          let highlightLines = $(this).attr('data-output-line-numbers');
          if (highlightLines) {
              let lines = highlightLines.split(',').map(x => parseInt(x));
              $(this).find('.cell-output-stdout pre code').html(function(_, html) {
                  return html.split('\n').map((line, index) => {
                      if (lines.includes(index + 1)) {
                          return '<span style="background-color: #D0D8FC;">' + line + '</span>';
                      } else {
                          return line;
                      }
                  }).join('\n');
              });
          }
      });
  });
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#88B04B" class="quarto-title-block center">
  <h1 class="title">Interpreting LMMs and <br> building maximal models</h1>
  <p class="subtitle"><br>Data Analysis for Psychology in R 3</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Elizabeth Pankratz (elizabeth.pankratz@ed.ac.uk) 
</div>
        <p class="quarto-title-affiliation">
            <br>Department of Psychology<br>University of Edinburgh<br>2026–2027
          </p>
    </div>
</div>

</section>
<section>
<section id="course-overview" class="title-slide slide level1 center" data-background-color="white">
<h1>Course Overview</h1>
<p><br></p>
<div class="cell" data-layout-align="center">
<table style="border: 1px solid black;>
  <tr style=" padding:="" 0="" 1em="" 1em;"="">
    <tbody><tr><td rowspan="5" style="border: 1px solid black;padding: 0 1em 0 1em;opacity:1;text-align:center;vertical-align: middle">
        <b>Linear mixed models<br>(with Dr. Elizabeth Pankratz)</b></td>
    <td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:1">
        Regression refresher, intro to group-structured data</td>
  </tr>
  <tr><td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:1">
        Modelling group-structured data using random effects</td></tr>
  <tr><td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:1">
        <b>Interpreting LMMs and building maximal models</b></td></tr>
  <tr><td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4">
        Troubleshooting model fit, checking assumptions + diagnostics</td></tr>
  <tr><td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4">
        LMMs: Practice analysis</td></tr>

  <tr style="padding: 0 1em 0 1em;">
    <td rowspan="5" style="border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4;text-align:center;vertical-align: middle">
        <b>factor analysis<br>working with multi-item measures<br>(with Dr. Josiah King)</b></td>
    <td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4">
        measurement and dimensionality</td>
  </tr>
  <tr><td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4">
        exploring underlying constructs (EFA)</td></tr>
  <tr><td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4">
        testing theoretical models (CFA)</td></tr>
  <tr><td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4">
        reliability and validity</td></tr>
  <tr><td style="border: 1px solid black;padding: 0 1em 0 1em;opacity:0.4">
        recap &amp; exam prep</td></tr>
</tbody></table>
</div>
</section>
<section id="this-weeks-learning-objectives" class="slide level2">
<h2>This week’s learning objectives</h2>
<p><br></p>
<div class="dapr3callout fragment">
<p>How do we interpret the random effects part of a model summary?</p>
<!-- - Always relative to the fixed effects. -->
<!-- - The fixed effect is the mean of a Normal distribution of group-level adjustments. -->
<!-- - The SD of that Normal distribution is given in the random effects summary table. -->
<!-- - There is no significance testing involved for random effects. -->
<!-- - When interpreting random effects, we are interested in questions like: -->
<!--   - Is there greater variability within one grouping variable than another? -->
<!--   - For slope adjustments: does the model predict that any specific levels of the grouping variable show the opposite direction of effect (e.g., a negative effect if the fixed effect is positive)? -->
</div>
<div class="dapr3callout fragment">
<p>How do we know if a model can include random intercepts for a given grouping variable?</p>
<!-- - We think about the data generating process, and specifically the kind of variability that the grouping variable contributes to the data. -->
<!-- - If the grouping variable contributes random variability to the data, then a model of that data must include random intercepts for that grouping variable. -->
</div>
<div class="dapr3callout fragment">
<p>How do we know if a model can include random slopes over a given predictor for a given grouping variable?</p>
<!-- - Check if the data contains more than one value of a given predictor within at least some levels of the grouping variable. -->
<!-- - (Why? Because we need at least two observations to fit a line. If there's only one value for a given predictor and a given participant, then we have no idea what a line fit to that data would look like because we don't know the second point that the line would connect.) -->
</div>
<div class="dapr3callout fragment">
<p>What is a maximal model?</p>
<!-- - A model that contains all possible random effects that are permitted by the data structure and the RQ. -->
</div>
</section></section>
<section>
<section id="recap-linear-mixed-models-lmms" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>Recap: Linear mixed models (LMMs)</h1>

</section>
<section id="the-data-log-reaction-times-in-the-implicit-association-test-iat" class="slide level2">
<h2>The data: Log reaction times in the <br> Implicit Association Test (IAT)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a>implicit_data <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pairing, <span class="at">y =</span> logRT)) <span class="sc">+</span></span>
<span id="cb1-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb1-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb1-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="cn">NULL</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="03-interp-maxmod_files/figure-revealjs/unnamed-chunk-3-1.svg" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:45%;">
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a>implicit_data <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 x 4
   ppt_id item_id pairing      logRT
   &lt;chr&gt;  &lt;chr&gt;   &lt;fct&gt;        &lt;dbl&gt;
 1 ppt1   item1   Associated    4.33
 2 ppt1   item1   Unassociated  4.70
 3 ppt2   item1   Associated    4.17
 4 ppt2   item1   Unassociated  4.91
 5 ppt3   item1   Associated    4.45
 6 ppt3   item1   Unassociated  5.13
 7 ppt4   item1   Associated    4.41
 8 ppt4   item1   Unassociated  6.54
 9 ppt5   item1   Associated    5.19
10 ppt5   item1   Unassociated  6.64
11 ppt6   item1   Associated    4.74
12 ppt6   item1   Unassociated  5.96</code></pre>
</div>
</div>
</div></div>
<div class="dapr3callout">
<p>Why is a simple linear model not appropriate for this data?</p>
<div class="hcenter">
<button class="iframe-trigger" data-src="https://app.wooclap.com/events/FUNOEYF/">woo!</button>
</div>
</div>
</section>
<section id="modelling-this-data-with-an-lmm" class="slide level2">
<h2>Modelling this data with an LMM</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb4-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="" aria-hidden="true" tabindex="-1"></a>implicit_full_lmm <span class="ot">&lt;-</span> <span class="fu">lmer</span>(      <span class="co"># LMMs use lme4::lmer(), not lm()</span></span>
<span id="cb4-4"><a href="" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb4-5"><a href="" aria-hidden="true" tabindex="-1"></a>  logRT <span class="sc">~</span> pairing <span class="sc">+</span>             <span class="co"># fixed effects: predict logRT by pairing</span></span>
<span id="cb4-6"><a href="" aria-hidden="true" tabindex="-1"></a>                                <span class="co"># (0 = Unassociated, 1 = Associated)</span></span>
<span id="cb4-7"><a href="" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-8"><a href="" aria-hidden="true" tabindex="-1"></a>                                <span class="co"># random effects:</span></span>
<span id="cb4-9"><a href="" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">+</span> pairing <span class="sc">|</span> ppt_id) <span class="sc">+</span>    <span class="co"># for each ppt, adjust the intercept and the slope</span></span>
<span id="cb4-10"><a href="" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-11"><a href="" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">+</span> pairing <span class="sc">|</span> item_id),    <span class="co"># for each item, adjust the intercept and the slope</span></span>
<span id="cb4-12"><a href="" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb4-13"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> implicit_data</span>
<span id="cb4-14"><a href="" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="what-does-it-mean-to-adjust-the-intercept" class="slide level2">
<h2>What does it mean to “adjust the intercept”?</h2>
<div class="columns">
<div class="column" style="width:30%;">
<p>The average association between <code>logRT</code> and <code>pairing</code> (the line defined by the fixed intercept and fixed slope):</p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:30%;">
<p>If a participant or an item has a <strong>higher log RT than average</strong>, then they will have a <strong>positive adjustment</strong> to the fixed intercept.</p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:30%;">
<p>If a participant or an item has a <strong>lower log RT than average</strong>, then they will have a <strong>negative adjustment</strong> to the fixed intercept.</p>
</div></div>
<div class="columns">
<div class="column" style="width:30%;">
<p><img data-src="figs/w3-adj-recap-avg.svg"></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:30%;">
<p><img data-src="figs/w3-adj-recap-int-pos.svg"></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:30%;">
<p><img data-src="figs/w3-adj-recap-int-neg.svg"></p>
</div></div>
<p>When the model includes random intercepts by <code>ppt_id</code> and by <code>item_id</code>, it will <strong>estimate how much the fixed intercept should be nudged up or down,</strong> in order to better fit the data from each participant and each item.</p>
</section>
<section id="what-does-it-mean-to-adjust-the-slope" class="slide level2">
<h2>What does it mean to “adjust the slope”?</h2>
<div class="columns">
<div class="column" style="width:30%;">
<p>The average association between <code>logRT</code> and <code>pairing</code> (the line defined by the fixed intercept and fixed slope):</p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:30%;">
<p>If a participant or an item has a <strong>more positive effect of <code>pairing</code> than average</strong>, then they will have a <strong>positive adjustment</strong> to the fixed slope over <code>pairing</code>.</p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:30%;">
<p>If a participant or an item has a <strong>more negative effect of <code>pairing</code> than average</strong>, then they will have a <strong>negative adjustment</strong> to the fixed slope over <code>pairing</code>.</p>
</div></div>
<div class="columns">
<div class="column" style="width:30%;">
<p><img data-src="figs/w3-adj-recap-avg.svg"></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:30%;">
<p><img data-src="figs/w3-adj-recap-slp-pos.svg"></p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:30%;">
<p><img data-src="figs/w3-adj-recap-slp-neg.svg"></p>
</div></div>
<p><br></p>
<p>When the model includes random intercepts by <code>ppt_id</code> and by <code>item_id</code> as well as random slopes over <code>pairing</code> by <code>ppt_id</code> and by <code>item_id</code>, it will</p>
<ul>
<li><strong>estimate how much the fixed intercept should be nudged up or down</strong> (last slide) AND ALSO</li>
<li><strong>how much the fixed slope should be swung up or down</strong> (this slide)</li>
</ul>
<p>in order to better fit the data from each participant and each item.</p>
<!-- ## Reporting this LMM structure -->
<!-- ```{r eval=F} -->
<!-- lmer( -->
<!--   logRT ~ pairing +  -->
<!--     (1 + pairing | ppt_id) +  -->
<!--     (1 + pairing | item_id), -->
<!--   data = implicit_data -->
<!-- ) -->
<!-- ``` -->
<!-- To describe this model in text, we could write -->
<!-- > We fit a linear mixed model to predict log RT as a function of topic pairing (treatment-coded, with the reference level "Unassociated" coded as 0 and "Associated" coded as 1). -->
<!-- This model includes by-participant random intercepts and random slopes over topic pairing, as well as by-item random intercepts and random slopes over topic pairing. -->
<!-- or (less traditional phrasing, but more transparent about what the random effects are actually doing) -->
<!-- > ... This model includes by-participant and by-item adjustments both to the intercept and to the slope over topic pairing. -->
<!-- <br> -->
<!-- The golden rule when describing random effects: **be crystal clear about which grouping variables get which intercept/slope adjustments.** -->
</section></section>
<section>
<section id="interpreting-lmm-summaries" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>Interpreting LMM summaries</h1>

</section>
<section id="the-full-summary" class="slide level2">
<h2>The full summary</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(implicit_full_lmm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: logRT ~ pairing + (1 + pairing | ppt_id) + (1 + pairing | item_id)
   Data: implicit_data

REML criterion at convergence: 10722

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-3.765 -0.669 -0.005  0.666  3.401 

Random effects:
 Groups   Name              Variance Std.Dev. Corr 
 ppt_id   (Intercept)       0.6068   0.779         
          pairingAssociated 0.0986   0.314    -0.83
 item_id  (Intercept)       0.7759   0.881         
          pairingAssociated 0.1508   0.388    -0.77
 Residual                   0.2730   0.522         
Number of obs: 6400, groups:  ppt_id, 100; item_id, 32

Fixed effects:
                  Estimate Std. Error t value
(Intercept)         4.7713     0.1744   27.37
pairingAssociated  -0.7624     0.0766   -9.95

Correlation of Fixed Effects:
            (Intr)
parngAssctd -0.776</code></pre>
</div>
</div>
</section>
<section id="start-with-the-fixed-effects" class="slide level2">
<h2>Start with the fixed effects</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Fixed effects:
                   Estimate Std. Error t value
 (Intercept)         4.7713     0.1744   27.37
 pairingAssociated  -0.7624     0.0766   -9.95</code></pre>
</div>
</div>
<p><br></p>
<p><strong>Interpret the fixed effects the same way you interpret coefficients in a simple linear model.</strong></p>
<p><br></p>
<p><strong><code>(Intercept)</code></strong> = the estimated mean outcome when all predictors are equal to zero.</p>
<ul>
<li>The estimated mean log reaction time when the topic pairing is unassociated (the reference level, coded as 0) is 4.77 log units.</li>
</ul>
<p><strong><code>pairingAssociated</code></strong> = the estimated increase/decrease in the outcome when the predictor moves from 0 to 1.</p>
<ul>
<li>The log reaction time for associated pairings is estimated to be 0.76 log units smaller than the log reaction time for unassociated pairings.</li>
</ul>
<p><br></p>
<p><strong>Where are the p-values?</strong></p>
</section>
<section id="where-are-the-p-values" class="slide level2">
<h2>Where are the p-values?</h2>
<p>The mathematics that make the random effects work (which you do not need to know!) means that we can’t easily translate t-values to p-values. But clever people have come up with good approximations!</p>
<p>Add the approximated p-values into the model summary by</p>
<ul>
<li>loading the library <code>lmerTest</code>, and</li>
<li>re-fitting the LMM using <code>lmer()</code>.</li>
</ul>
<p>This gives you p-values estimated using “Satterthwaite’s method”.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb8-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="" aria-hidden="true" tabindex="-1"></a>implicit_full_lmm <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb8-4"><a href="" aria-hidden="true" tabindex="-1"></a>  logRT <span class="sc">~</span> pairing <span class="sc">+</span>  (<span class="dv">1</span> <span class="sc">+</span> pairing <span class="sc">|</span> ppt_id) <span class="sc">+</span>  (<span class="dv">1</span> <span class="sc">+</span> pairing <span class="sc">|</span> item_id), </span>
<span id="cb8-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> implicit_data</span>
<span id="cb8-6"><a href="" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(implicit_full_lmm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Fixed effects:
                   Estimate Std. Error      df t value Pr(&gt;|t|)    
 (Intercept)         4.7713     0.1744 47.4387   27.37  &lt; 2e-16 ***
 pairingAssociated  -0.7624     0.0766 44.0019   -9.95  7.8e-13 ***</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
...</code></pre>
</div>
</div>
</section>
<section id="fixed-effects-now-with-p-values" class="slide level2">
<h2>Fixed effects, now with p-values</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
 Fixed effects:
                   Estimate Std. Error      df t value Pr(&gt;|t|)    
 (Intercept)         4.7713     0.1744 47.4387   27.37  &lt; 2e-16 ***
 pairingAssociated  -0.7624     0.0766 44.0019   -9.95  7.8e-13 ***</code></pre>
</div>
</div>
<p><br></p>
<p><code>(Intercept)</code>:</p>
<ul>
<li>The estimated mean log reaction time when the topic pairing is unassociated (the reference level, coded as 0) is 4.77 log units.</li>
<li>This estimate is significantly different from zero at <span class="math inline">\(p\)</span> &lt; .001, but that’s not really a surprise … we were already pretty sure that the average log RT would be different from zero!
<ul>
<li>When the outcome variable is continuous, we typically don’t report p-values for intercepts, because it’s not a very interesting hypothesis test</li>
</ul></li>
</ul>
<p><code>pairingAssociated</code>:</p>
<ul>
<li>The log reaction time for associated pairings is estimated to be 0.76 log units smaller than the log reaction time for unassociated pairings.</li>
<li>This estimate is significantly different from zero (<span class="math inline">\(p\)</span> &lt; .001).
<ul>
<li>This <em>is</em> an interesting hypothesis test, because it looks at the difference between conditions, which is the whole point of our experiment</li>
</ul></li>
</ul>
<p><br></p>
</section>
<section id="next-look-at-the-random-effects" class="slide level2">
<h2>Next, look at the random effects</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Random effects:
  Groups   Name              Variance Std.Dev. Corr 
  ppt_id   (Intercept)       0.6068   0.779         
           pairingAssociated 0.0986   0.314    -0.83
  item_id  (Intercept)       0.7759   0.881         
           pairingAssociated 0.1508   0.388    -0.77
  Residual                   0.2730   0.522         
 Number of obs: 6400, groups:  ppt_id, 100; item_id, 32
 </code></pre>
</div>
</div>
<p><strong>First:</strong> Sense check the quantities in the final line.</p>
<ul>
<li>Is the number of observations (6400) correct?</li>
<li>Is the number of distinct levels of <code>ppt_id</code> (100) correct?</li>
<li>Is the number of distinct levels of <code>item_id</code> (32) correct?</li>
</ul>
<p>If not, the data is probably not formatted correctly. Do any fixes you need.</p>
<p><br></p>
<p><strong>Then:</strong> Look at the rest of the output. Read it row by row as a table, like this:</p>

<img data-src="figs/w3-ranef-tab.svg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="intercept-adjustments-for-each-ppt_id-1" class="slide level2">
<h2>Intercept adjustments for each <code>ppt_id</code> (1)</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  Groups   Name              Variance Std.Dev. Corr 
  ppt_id   (Intercept)       0.6068   0.779         </code></pre>
</div>
</div>
<p><br></p>
<p>What this line tells us: <strong>The <code>(Intercept)</code> adjustments for <code>ppt_id</code> have a standard deviation (SD) of 0.78 log units.</strong></p>
<ul>
<li>The variance is just the SD squared (0.779<span class="math inline">\(^2\)</span> = 0.607) so it doesn’t add any useful information.</li>
<li>We will always just focus on the SD.</li>
</ul>
<p>The number 0.78 doesn’t mean much on its own. <strong>We must interpret it with respect to the value that it is adjusting:</strong> the fixed intercept of 4.77 log units.</p>
<p>By combining these numbers, we find the estimated distribution of participant-level intercepts.</p>
<p>This is useful because it helps us understand the variability in participant behaviour in our experiment.</p>
</section>
<section id="intercept-adjustments-for-each-ppt_id-2" class="slide level2">
<h2>Intercept adjustments for each <code>ppt_id</code> (2)</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  Groups   Name              Variance Std.Dev. Corr 
  ppt_id   (Intercept)       0.6068   0.779         </code></pre>
</div>
</div>
<p><br></p>
<div class="r-stack">
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w3-normal-ppt-int-0.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w3-normal-ppt-int-1.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w3-normal-ppt-int-2.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w3-normal-ppt-int-3.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w3-normal-ppt-int-4.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w3-normal-ppt-int-5.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w3-normal-ppt-int-6.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/w3-normal-ppt-int-7.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="intercept-adjustments-for-each-ppt_id-3" class="slide level2">
<h2>Intercept adjustments for each <code>ppt_id</code> (3)</h2>

<img data-src="figs/w3-normal-ppt-int-7.png" class="quarto-figure quarto-figure-center r-stretch"><p><br></p>
<p>Approx 95% of participant-level intercepts are estimated to fall between about 3.21 log units and 6.33 log units.</p>
<p>This means that, <strong>for 95% of participants, the estimated log RT for unassociated pairings is between 3.21 log units and 6.33 log units.</strong></p>
<p>Useful information to report!</p>
</section>
<section id="pairingassociated-adjustments-by-ppt_id" class="slide level2">
<h2><code>pairingAssociated</code> adjustments by <code>ppt_id</code></h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  Groups   Name              Variance Std.Dev. Corr 
  ppt_id   (Intercept)       0.6068   0.779         
           pairingAssociated 0.0986   0.314    -0.83</code></pre>
</div>
</div>
<p><strong>The <code>pairingAssociated</code> adjustments (i.e., adjustments to the slope over <code>pairing</code>) for <code>ppt_id</code> have a SD of 0.31 log units.</strong></p>
<!-- Again, in order to make this number meaningful, we must interpret it in relation to the fixed effect it's adjusting: the `pairingAssociated` fixed slope estimate of –0.76. -->

<!-- Approx 95% of participant-level slopes over `pairing` are estimated to fall between about –1.38 log units and <br> –0.14 log units. -->
<img data-src="figs/w3-normal-ppt-slp.png" class="quarto-figure quarto-figure-center r-stretch"><p><br></p>
<p><strong>At least 95% of participants are estimated to have a negative effect of <code>pairing</code>:</strong> faster RTs for associated pairings compared to unassociated pairings.</p>
</section>
<section id="correlation-between-by-participant-slope-and-intercept-adjustments" class="slide level2">
<h2>Correlation between by-participant slope and intercept adjustments</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  Groups   Name              Variance Std.Dev. Corr 
  ppt_id   (Intercept)       0.6068   0.779         
           pairingAssociated 0.0986   0.314    -0.83</code></pre>
</div>
</div>
<p><br></p>
<p>The participant-level <code>(Intercept)</code> and <code>pairingAssociated</code> adjustments have a correlation of –0.83.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot.ranef.mer</span>(<span class="fu">ranef</span>(implicit_full_lmm))<span class="sc">$</span>ppt_id</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="03-interp-maxmod_files/figure-revealjs/unnamed-chunk-17-1.svg" class="quarto-figure quarto-figure-center r-stretch"></section></section>
<section>
<section id="over-to-you-for-interpreting-item_id-adjustments" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>Over to you for interpreting <code>item_id</code> adjustments</h1>

</section>
<section id="intercept-adjustments-for-each-item_id" class="slide level2">
<h2>Intercept adjustments for each <code>item_id</code></h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  Groups   Name              Variance Std.Dev. Corr </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  item_id  (Intercept)       0.7759   0.881         </code></pre>
</div>
</div>
<p><br></p>
<p>Calculate the range in which the 95% of item-level intercepts are estimated to fall.</p>
<div class="hcenter">
<button class="iframe-trigger" data-src="https://app.wooclap.com/events/FUNOEYF/">woo!</button>
</div>
<p><br></p>

<img data-src="figs/woo/w3-normal-item-int.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="pairingassociated-adjustments-for-item_id" class="slide level2">
<h2><code>pairingAssociated</code> adjustments for <code>item_id</code></h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  Groups   Name              Variance Std.Dev. Corr </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  item_id  (Intercept)       0.7759   0.881         
           pairingAssociated 0.1508   0.388    -0.77</code></pre>
</div>
</div>
<p><br></p>
<p>Calculate the range in which the 95% of item-level slopes over <code>pairing</code> are estimated to fall.</p>
<div class="hcenter">
<button class="iframe-trigger" data-src="https://app.wooclap.com/events/FUNOEYF/">woo!</button>
</div>
<p><br></p>

<img data-src="figs/woo/w3-normal-item-slp.png" class="quarto-figure quarto-figure-center r-stretch" style="width:100.0%"></section>
<section id="correlation-between-by-item-intercept-and-slope-adjustments" class="slide level2">
<h2>Correlation between by-item intercept and slope adjustments</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  Groups   Name              Variance Std.Dev. Corr </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  item_id  (Intercept)       0.7759   0.881         
           pairingAssociated 0.1508   0.388    -0.77</code></pre>
</div>
</div>
<p><br></p>
<p>The item-level <code>(Intercept)</code> and <code>pairingAssociated</code> adjustments have a correlation of –0.77.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot.ranef.mer</span>(<span class="fu">ranef</span>(implicit_full_lmm))<span class="sc">$</span>item_id</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="03-interp-maxmod_files/figure-revealjs/unnamed-chunk-23-1.svg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="residuals" class="slide level2">
<h2>Residuals</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> Groups   Name              Variance Std.Dev. Corr </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> Residual                   0.2730   0.522         </code></pre>
</div>
</div>
<p><br></p>
<ul>
<li><p>A residual is the difference between the value we observed for a data point and the value that the model predicts for it.</p></li>
<li><p>Residuals are how the model deals with the unsystematic leftover variability that is present in the world but not accounted for by variables we’ve included in the model.</p></li>
<li><p>Residual variance/SD is not very informative or useful. You don’t need to interpret or report it.</p></li>
</ul>
</section></section>
<section>
<section id="one-last-thing-to-report-plots-of-model-fitted-values" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>One last thing to report: <br> Plots of model-fitted values</h1>

</section>
<section id="use-effect-to-compute-model-fitted-values" class="slide level2">
<h2>Use <code>Effect()</code> to compute model-fitted values</h2>
<p>In the library <code>effects</code>, there is a function called <code>Effect()</code>.</p>
<p>It gives us the outcome values that the model would estimate/predict for each level of our predictor, as well as the 95% CI around those values. (Same idea as <code>emmeans</code> from DAPR2.)</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb28-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">Effect</span>(</span>
<span id="cb28-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">focal.predictors =</span> <span class="fu">c</span>(<span class="st">"pairing"</span>),   <span class="co"># what predictor(s) do we want predictions for?</span></span>
<span id="cb28-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">mod =</span> implicit_full_lmm            <span class="co"># what model should predictions be based on?</span></span>
<span id="cb28-6"><a href="" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb28-7"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       pairing  fit    se lower upper
1 Unassociated 4.77 0.174  4.43  5.11
2   Associated 4.01 0.125  3.76  4.25</code></pre>
</div>
</div>
<p><br></p>
<ul>
<li><code>fit</code>: the estimated outcome (log RT) value for each level of <code>pairing</code></li>
<li><code>se</code>: the standard error of that estimate</li>
<li><code>lower</code>: the lower bound of the estimate’s 95% CI</li>
<li><code>upper</code>: the upper bound of the estimate’s 95% CI</li>
</ul>
</section>
<section id="visualise-these-estimates" class="slide level2">
<h2>Visualise these estimates</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">Effect</span>(<span class="at">focal.predictors =</span> <span class="fu">c</span>(<span class="st">"pairing"</span>), <span class="at">mod =</span> implicit_full_lmm) <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pairing, <span class="at">y =</span> fit)) <span class="sc">+</span></span>
<span id="cb30-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower, <span class="at">ymax =</span> upper), <span class="at">width =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-7"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">'Log RT'</span>,</span>
<span id="cb30-8"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">'Topic pairing'</span></span>
<span id="cb30-9"><a href="" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

<img data-src="03-interp-maxmod_files/figure-revealjs/unnamed-chunk-27-1.svg" class="quarto-figure quarto-figure-center r-stretch"></section></section>
<section>
<section id="how-to-identify-all-possible-random-effects" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>How to identify all possible random effects</h1>

</section>
<section id="how-to-identify-all-possible-random-effects-1" class="slide level2">
<h2>How to identify all possible random effects</h2>
<p>Four steps that you can apply to any dataset + RQ:</p>
<div class="dapr3callout fragment">
<ol type="1">
<li>Use your RQ to figure out what your model’s outcome and predictors are (i.e., your model’s fixed effects).</li>
</ol>
</div>
<div class="dapr3callout fragment">
<ol start="2" type="1">
<li>For all variables that are not the outcome or predictors, identify whether they are grouping variables.</li>
</ol>
</div>
<div class="dapr3callout fragment">
<ol start="3" type="1">
<li>Identify which of those grouping variables contribute random / non-manipulated / non-controlled variability to your data (think about the data generating process).</li>
</ol>
<p>For every randomly-varying grouping variable, your model must contain a random intercept for that grouping variable.</p>
</div>
<div class="dapr3callout fragment">
<ol start="4" type="1">
<li>Refer back to all predictors you identified in Step 1. For each randomly-varying grouping variable, check whether at least some of its levels appear with more than one value of each predictor (i.e., whether the predictor varies within each level of the grouping variable).</li>
</ol>
<p>If they do, then (in addition to the random intercepts) your model can also contain a random slope over that predictor for that grouping variable.</p>
<p>If they don’t, then a random slope over that predictor is impossible.</p>
</div>
</section></section>
<section>
<section id="example-1-hesitation-markers-and-believability" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>Example 1: Hesitation markers and believability</h1>

</section>
<section id="example-1-hesitation-markers-and-believability-1" class="slide level2">
<h2>Example 1: Hesitation markers and believability</h2>
<p>RQ: Do hesitation markers like “um”/“erm” affect how believable true statements seem?</p>
<div class="columns">
<div class="column" style="width:45%;">
<p><strong>Examples from condition <code>hesitation = No</code>:</strong></p>
<ul>
<li>“A hashtag is technically called an octothorp.”</li>
<li>“The largest snowflake was bigger than most pizzas.”</li>
<li>“Pigs don’t sweat.”</li>
</ul>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:50%;">
<p><strong>Examples from condition <code>hesitation = Yes</code>:</strong></p>
<ul>
<li>“Erm … a hashtag is technically called an octothorp.”</li>
<li>“Erm … the largest snowflake was bigger than most pizzas.”</li>
<li>“Erm … pigs don’t sweat.”</li>
</ul>
</div></div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="" aria-hidden="true" tabindex="-1"></a>belief_data <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> hesitation, <span class="at">y =</span> belief, <span class="at">colour =</span> hesitation, <span class="at">fill =</span> hesitation)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">'point'</span>, <span class="at">fun =</span> mean, <span class="at">colour =</span> <span class="st">'black'</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> pal) <span class="sc">+</span></span>
<span id="cb31-7"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal) <span class="sc">+</span></span>
<span id="cb31-8"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb31-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">'none'</span></span>
<span id="cb31-10"><a href="" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="03-interp-maxmod_files/figure-revealjs/unnamed-chunk-29-1.svg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="the-data" class="slide level2">
<h2>The data</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="" aria-hidden="true" tabindex="-1"></a>belief_data <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 x 5
   ppt   sentence statement                                    hesitation belief
   &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;                                        &lt;fct&gt;       &lt;dbl&gt;
 1 ppt_1        1 Candy floss was invented by a dentist        Yes          53.2
 2 ppt_1        2 The first speeding fine was given in 1896    Yes          44.7
 3 ppt_1        3 Honey doesn't go off                         Yes          46.9
 4 ppt_1        4 A dog was voted mayor of a town in Minnesot~ Yes          50.8
 5 ppt_1        5 The largest snowflake was bigger than most ~ Yes          44.5
 6 ppt_1        6 Water makes different sounds depending on i~ Yes          55.9
 7 ppt_1        7 Mickey Mouse was originally called Mortimer  Yes          44.0
 8 ppt_1        8 Cats have 5 paws on their front feet and 4 ~ Yes          49.0
 9 ppt_1        9 It's impossible to hum while holding your n~ Yes          45.2
10 ppt_1       10 You can draw a line 35 miles long using one~ Yes          48.8
11 ppt_1       11 The Sahara desert is only 25% sand           No           53.6
12 ppt_1       12 A hashtag is technically called an octothorp No           42.4
13 ppt_1       13 It would take 19 minutes to fall to the cen~ No           52.2
14 ppt_1       14 Sloths don't fart                            No           55.0
15 ppt_1       15 Pigs don't sweat                             No           46.7
16 ppt_1       16 The Eiffel Tower grows 6 inches in summer    No           51.9
17 ppt_1       17 Flamingos are pink because of their diet     No           44.2
18 ppt_1       18 Rabbits can't be sick                        No           50.5
19 ppt_1       19 The dot over a lowercase i and j is called ~ No           36.4
20 ppt_1       20 The square root of 16 is 4                   No           59.7</code></pre>
</div>
</div>
</section>
<section id="step-1-identify-fixed-effects" class="slide level2">
<h2>Step 1: Identify fixed effects</h2>
<div class="dapr3callout">
<ol type="1">
<li>Use your RQ to figure out what your model’s outcome and predictors are (i.e., your model’s fixed effects).</li>
</ol>
</div>
<p><br></p>
<p>RQ: Do hesitation markers like “um”/“erm” affect how believable true statements seem?</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(belief_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ppt"        "sentence"   "statement"  "hesitation" "belief"    </code></pre>
</div>
</div>
<p><br></p>
<ul>
<li>Outcome variable: <code>belief</code></li>
<li>Predictor variable: <code>hesitation</code></li>
</ul>
<p><br></p>
<p>The fixed effects part of the model formula will be <code>belief ~ hesitation</code>.</p>
</section>
<section id="step-2-identify-grouping-variables" class="slide level2">
<h2>Step 2: Identify grouping variables</h2>
<div class="dapr3callout">
<ol start="2" type="1">
<li>For all variables that are not the outcome or predictors, identify whether they are grouping variables.</li>
</ol>
</div>
<div class="columns">
<div class="column" style="width:47%;">
<p>For <code>ppt</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="" aria-hidden="true" tabindex="-1"></a>belief_data <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ppt) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> # A tibble: 30 x 2
 # Groups:   ppt [30]
    ppt        n
    &lt;chr&gt;  &lt;int&gt;
  1 ppt_1     20
  2 ppt_10    20
  3 ppt_11    20
  4 ppt_12    20
  5 ppt_13    20
  6 ppt_14    20
  7 ppt_15    20
  8 ppt_16    20
  9 ppt_17    20
 10 ppt_18    20</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p><br></p>
<p>Each value of <code>ppt</code> appears more than once. <code>ppt</code> is a grouping variable &nbsp; ✅</p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:47%;">
<p>For <code>sentence</code> (which numbers each statement):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="" aria-hidden="true" tabindex="-1"></a>belief_data <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sentence) <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> # A tibble: 20 x 2
 # Groups:   sentence [20]
    sentence     n
       &lt;dbl&gt; &lt;int&gt;
  1        1    30
  2        2    30
  3        3    30
  4        4    30
  5        5    30
  6        6    30
  7        7    30
  8        8    30
  9        9    30
 10       10    30</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p><br></p>
<p>Each value of <code>sentence</code> appears more than once. <code>sentence</code> is a grouping variable &nbsp; ✅</p>
</div></div>
</section>
<section id="step-3-random-intercepts" class="slide level2">
<h2>Step 3: Random intercepts</h2>
<div class="dapr3callout">
<ol start="3" type="1">
<li>Identify which of those grouping variables contribute random / non-manipulated / non-controlled variability to your data (think about the data generating process).</li>
</ol>
<p>For every randomly-varying grouping variable, your model must contain a random intercept for that grouping variable.</p>
</div>
<p><code>ppt</code>:</p>
<ul>
<li>The RQ doesn’t specify that we manipulate or control for specific people.</li>
<li>If we re-ran the study, we could recruit different participants and still address the RQ.</li>
<li>We want our results to generalise across different people.</li>
<li>Therefore: <strong><code>ppt</code> contributes random variability, and our model needs at least a random intercept by participant.</strong></li>
</ul>
<p><code>sentence</code>:</p>
<ul>
<li>The RQ doesn’t specify that we manipulate or control for specific sentences.</li>
<li>If we re-ran the study, we could show people different sentences and still address the RQ.</li>
<li>We want our results to generalise across different sentences.</li>
<li>Therefore: <strong><code>sentence</code> contributes random variability, and our model needs at least a random intercept by sentence.</strong></li>
</ul>
<p>The minimum LMM formula now: <code>belief ~ hesitation + (1 | ppt) + (1 | sentence)</code></p>
</section>
<section id="step-4-random-slopes" class="slide level2">
<h2>Step 4: Random slopes</h2>
<div class="dapr3callout">
<ol start="4" type="1">
<li>Refer back to all predictors you identified in Step 1. For each randomly-varying grouping variable, check whether at least some of its levels appear with more than one value of each predictor (i.e., whether the predictor varies within each level of the grouping variable).</li>
</ol>
<p>If they do, then (in addition to the random intercepts) your model can also contain a random slope over that predictor for that grouping variable.</p>
<p>If they don’t, then a random slope over that predictor is impossible.</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p>Do at least some levels of <code>ppt</code> appear with more than one value of <code>hesitation</code>?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">xtabs</span>(</span>
<span id="cb42-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> ppt <span class="sc">+</span> hesitation, </span>
<span id="cb42-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> belief_data</span>
<span id="cb42-4"><a href="" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>        hesitation
 ppt      No Yes
   ppt_1  10  10
   ppt_10 10  10
   ppt_11 10  10
   ppt_12 10  10
   ppt_13 10  10
   ppt_14 10  10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p>Yes! So <code>(1 + hesitation | ppt)</code> is possible.</p>
</div><div class="column" style="width:50%;">
<p>Do at least some levels of <code>sentence</code> appear with more than one value of <code>hesitation</code>?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">xtabs</span>(</span>
<span id="cb45-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> sentence <span class="sc">+</span> hesitation, </span>
<span id="cb45-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> belief_data</span>
<span id="cb45-4"><a href="" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>        hesitation
 sentence No Yes
       1  15  15
       2  15  15
       3  15  15
       4  15  15
       5  15  15
       6  15  15</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p>Yes! So <code>(1 + hesitation | sentence)</code> is possible.</p>
</div></div>
</section>
<section id="the-model-with-all-possible-random-effects" class="slide level2">
<h2>The model with all possible random effects</h2>
<p><br></p>
<div class="hcenter">
<p><code>belief ~ hesitation + (1 + hesitation | ppt) + (1 + hesitation | sentence)</code></p>
</div>
<p><br></p>
<p>There’s a specific name for the version of the model that has all possible random effects permitted by the data structure and the RQ.</p>
<p>We call it the <strong>“maximal model”.</strong></p>
</section></section>
<section>
<section id="example-2-test-enhanced-learning" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>Example 2: Test-enhanced learning</h1>

</section>
<section id="example-2-test-enhanced-learning-1" class="slide level2">
<h2>Example 2: Test-enhanced learning</h2>
<p>Two groups of participants learn some new material.</p>
<p>One group studied the material twice (the <code>StudyStudy</code> group), and the other group studied the material once and then tested themselves on it (the <code>StudyTest</code> group).</p>
<p>Recall was tested immediately (one minute) after the learning session and again one week later. Time of testing is recorded in the variable <code>Delay</code>.</p>
<!-- The recall tests are each identified by a keyword (`Test_word`). -->
<p><strong>RQ: Does self-testing improve retention, such that the <code>StudyStudy</code> group may perform better on the immediate test, but the <code>StudyTest</code> group will perform better on the test one week later?</strong></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="" aria-hidden="true" tabindex="-1"></a>tel_data <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Delay, <span class="at">y =</span> TestScore, <span class="at">colour =</span> Delay, <span class="at">fill =</span> Delay)) <span class="sc">+</span></span>
<span id="cb48-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb48-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb48-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Group) <span class="sc">+</span></span>
<span id="cb48-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span> <span class="st">'point'</span>, <span class="at">fun =</span> mean, <span class="at">colour =</span> <span class="st">'black'</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb48-7"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> pal) <span class="sc">+</span></span>
<span id="cb48-8"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal) <span class="sc">+</span></span>
<span id="cb48-9"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb48-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">'none'</span>,</span>
<span id="cb48-11"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb48-12"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">24</span>)</span>
<span id="cb48-13"><a href="" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="03-interp-maxmod_files/figure-revealjs/unnamed-chunk-41-1.svg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="the-data-1" class="slide level2">
<h2>The data</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="" aria-hidden="true" tabindex="-1"></a>tel_data <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 x 5
   Subject_ID  Group     Delay Test_word    TestScore
   &lt;chr&gt;       &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
 1 StudyTest_A StudyTest week  carrot              52
 2 StudyTest_A StudyTest week  cane                60
 3 StudyTest_A StudyTest min   scale               54
 4 StudyTest_A StudyTest min   letter              79
 5 StudyTest_A StudyTest week  cannon              62
 6 StudyTest_A StudyTest week  pencil              30
 7 StudyTest_A StudyTest week  piano               63
 8 StudyTest_A StudyTest week  chimney             46
 9 StudyTest_A StudyTest week  pen                 64
10 StudyTest_A StudyTest week  fireplace           35
11 StudyTest_A StudyTest week  fan                 74
12 StudyTest_A StudyTest week  can                 62
13 StudyTest_A StudyTest week  fireman             52
14 StudyTest_A StudyTest min   knife               40
15 StudyTest_A StudyTest min   lamp                74
16 StudyTest_A StudyTest min   leaf                62
17 StudyTest_A StudyTest week  ring                58
18 StudyTest_A StudyTest week  cheerleaders        48
19 StudyTest_A StudyTest min   saw                 71
20 StudyTest_A StudyTest week  chair               65</code></pre>
</div>
</div>
</section>
<section id="step-1-identify-fixed-effects-1" class="slide level2">
<h2>Step 1: Identify fixed effects</h2>
<div class="dapr3callout">
<ol type="1">
<li>Use your RQ to figure out what your model’s outcome and predictors are (i.e., your model’s fixed effects).</li>
</ol>
</div>
<p><br></p>
<p>RQ: Does self-testing improve retention, such that the <code>StudyStudy</code> group may perform better on the immediate test, but the <code>StudyTest</code> group will perform better on the test one week later?</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(tel_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Subject_ID" "Group"      "Delay"      "Test_word"  "TestScore" </code></pre>
</div>
</div>
<p><br></p>
<ul>
<li>Outcome variable: <code>TestScore</code></li>
<li>Predictor variables: <code>Delay</code>, <code>Group</code>, and their interaction</li>
</ul>
<p><br></p>
<p>The fixed effects part of the model formula will be <code>TestScore ~ Delay * Group</code>.</p>
</section>
<section id="step-2-identify-grouping-variables-1" class="slide level2">
<h2>Step 2: Identify grouping variables</h2>
<div class="dapr3callout">
<ol start="2" type="1">
<li>For all variables that are not the outcome or predictors, identify whether they are grouping variables.</li>
</ol>
</div>
<p>The remaining variables: <code>Subject_ID</code> (categorical) and <code>Test_word</code> (categorical).</p>
<div class="columns">
<div class="column" style="width:47%;">
<p>For <code>Subject_ID</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="" aria-hidden="true" tabindex="-1"></a>tel_data <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Subject_ID) <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> # A tibble: 20 x 2
 # Groups:   Subject_ID [20]
    Subject_ID       n
    &lt;chr&gt;        &lt;int&gt;
  1 StudyStudy_A   347
  2 StudyStudy_B   348
  3 StudyStudy_C   348
  4 StudyStudy_D   348
  5 StudyStudy_E   348
  6 StudyStudy_F   348</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p><br></p>
<p>Each value of <code>Subject_ID</code> appears more than once. <code>Subject_ID</code> is a grouping variable &nbsp; ✅</p>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:47%;">
<p>For <code>Test_word</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="" aria-hidden="true" tabindex="-1"></a>tel_data <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Test_word) <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> # A tibble: 174 x 2
 # Groups:   Test_word [174]
    Test_word     n
    &lt;chr&gt;     &lt;int&gt;
  1 ambulance    40
  2 anchor       40
  3 apple        40
  4 baby         40
  5 ball         40
  6 balloon      40</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p><br></p>
<p>Each value of <code>Test_word</code> appears more than once. <code>Test_word</code> is a grouping variable &nbsp; ✅</p>
</div></div>
</section>
<section id="step-3-random-intercepts-1" class="slide level2">
<h2>Step 3: Random intercepts</h2>
<div class="dapr3callout">
<ol start="3" type="1">
<li>Identify which of those grouping variables contribute random / non-manipulated / non-controlled variability to your data (think about the data generating process).</li>
</ol>
<p>For every randomly-varying grouping variable, your model must contain a random intercept for that grouping variable.</p>
</div>
<p><code>Subject_ID</code>:</p>
<ul>
<li>The RQ doesn’t specify that we manipulate or control for specific people.</li>
<li>If we re-ran the study, we could recruit different subjects and still address the RQ.</li>
<li>We want our results to generalise across different people.</li>
<li>Therefore: <strong><code>Subject_ID</code> contributes random variability, and our model needs at least a random intercept by subject.</strong></li>
</ul>
<p><code>Test_word</code>:</p>
<ul>
<li>The RQ doesn’t specify that we manipulate or control for specific test words.</li>
<li>If we re-ran the study, we could show people different test words and still address the RQ.</li>
<li>We want our results to generalise across different test words.</li>
<li>Therefore: <strong><code>Test_word</code> contributes random variability, and our model needs at least a random intercept by test word.</strong></li>
</ul>
<p>Minimum model now: <code>TestScore ~ Delay * Group + (1 | Subject_ID) + (1 | Test_word)</code></p>
</section>
<section id="step-4-random-slopes-1" class="slide level2">
<h2>Step 4: Random slopes</h2>
<div class="dapr3callout">
<ol start="4" type="1">
<li>Refer back to all predictors you identified in Step 1. For each randomly-varying grouping variable, check whether at least some of its levels appear with more than one value of each predictor (i.e., whether the predictor varies within each level of the grouping variable).</li>
</ol>
<p>If they do, then (in addition to the random intercepts) your model can also contain a random slope over that predictor for that grouping variable.</p>
<p>If they don’t, then a random slope over that predictor is impossible.</p>
</div>
<p><br></p>
<p>We’ll need to check all combinations of grouping variables and predictors:</p>
<ul>
<li>Do at least some levels of <code>Subject_ID</code> appear with more than one value of <code>Delay</code>?</li>
<li>Do at least some levels of <code>Subject_ID</code> appear with more than one value of <code>Group</code>?</li>
<li>Do at least some levels of <code>Test_word</code> appear with more than one value of <code>Delay</code>?</li>
<li>Do at least some levels of <code>Test_word</code> appear with more than one value of <code>Group</code>?</li>
</ul>
</section>
<section id="step-4-random-slopes-by-subject_id" class="slide level2">
<h2>Step 4: Random slopes by <code>Subject_ID</code></h2>
<div class="columns">
<div class="column" style="width:47%;">
<p>Do at least some levels of <code>Subject_ID</code> appear with more than one value of <code>Delay</code>?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">xtabs</span>(</span>
<span id="cb59-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Subject_ID <span class="sc">+</span> Delay, </span>
<span id="cb59-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tel_data</span>
<span id="cb59-4"><a href="" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Delay
 Subject_ID     min week
   StudyStudy_A 173  174
   StudyStudy_B 174  174
   StudyStudy_C 174  174
   StudyStudy_D 174  174
   StudyStudy_E 174  174
   StudyStudy_F 174  174
   StudyStudy_G 174  174
   StudyStudy_H 174  174
   StudyStudy_I 174  174
   StudyStudy_J 174  174</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p>Yes! So a random slope over <code>Delay</code> by <code>Subject_ID</code> is possible.</p>
</div><div class="column" style="width:3%;">

</div><div class="column" style="width:50%;">
<p>Do at least some levels of <code>Subject_ID</code> appear with more than one value of <code>Group</code>?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">xtabs</span>(</span>
<span id="cb62-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Subject_ID <span class="sc">+</span> Group, </span>
<span id="cb62-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tel_data</span>
<span id="cb62-4"><a href="" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Group
 Subject_ID     StudyStudy StudyTest
   StudyStudy_A        347         0
   StudyStudy_B        348         0
   StudyStudy_C        348         0
   StudyStudy_D        348         0
   StudyStudy_E        348         0
   StudyStudy_F        348         0
   StudyStudy_G        348         0
   StudyStudy_H        348         0
   StudyStudy_I        348         0
   StudyStudy_J        348         0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p>No! People are either in one group or the other. We cannot include a random slope over <code>Group</code> by <code>Subject_ID</code>.</p>
</div></div>
<p><br></p>
<p><strong>The maximal random effects term for <code>Subject_ID</code> is <code>(1 + Delay | Subject_ID)</code>.</strong></p>
</section>
<section id="step-4-random-slopes-by-test_word" class="slide level2">
<h2>Step 4: Random slopes by <code>Test_word</code></h2>
<div class="columns">
<div class="column" style="width:47%;">
<p>Do at least some levels of <code>Test_word</code> appear with more than one value of <code>Delay</code>?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">xtabs</span>(</span>
<span id="cb65-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Test_word <span class="sc">+</span> Delay, </span>
<span id="cb65-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tel_data</span>
<span id="cb65-4"><a href="" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Delay
 Test_word      min week
   ambulance     20   20
   anchor        20   20
   apple         20   20
   baby          20   20
   ball          20   20
   balloon       20   20
   banana        20   20
   basket        20   20
   bat           20   20
   beard         20   20</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p>Yes! So a random slope over <code>Delay</code> by <code>Test_word</code> is possible.</p>
</div><div class="column" style="width:3%;">

</div><div class="column" style="width:50%;">
<p>Do at least some levels of <code>Test_word</code> appear with more than one value of <code>Group</code>?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="" aria-hidden="true" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">xtabs</span>(</span>
<span id="cb68-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Test_word <span class="sc">+</span> Group, </span>
<span id="cb68-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tel_data</span>
<span id="cb68-4"><a href="" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>              Group
 Test_word      StudyStudy StudyTest
   ambulance            20        20
   anchor               20        20
   apple                20        20
   baby                 20        20
   ball                 20        20
   balloon              20        20
   banana               20        20
   basket               20        20
   bat                  20        20
   beard                20        20</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>...</code></pre>
</div>
</div>
<p>Yes! So we can also add on a random slope over <code>Group</code> by <code>Test_word</code>.</p>
<p>And because both predictors can have random slopes, we can also include their interaction.</p>
</div></div>
<p><strong>The maximal random effects term for <code>Test_word</code> is <code>(1 + Delay * Group | Test_word)</code>.</strong></p>
</section>
<section id="the-maximal-model" class="slide level2">
<h2>The maximal model</h2>
<p><br></p>
<div class="hcenter">
<p><code>TestScore ~ Delay * Group +  (1 + Delay | Subject_ID) + (1 + Delay * Group | Test_word)</code></p>
</div>
</section></section>
<section>
<section id="why-is-it-useful-to-find-the-maximal-model" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>Why is it useful to find the maximal model?</h1>

</section>
<section id="why-is-it-useful-to-find-the-maximal-model-1" class="slide level2">
<h2>Why is it useful to find the maximal model?</h2>
<p><br></p>
<p>Because the maximal model …</p>
<ul>
<li>… takes into account all the variability that plays a role in our design.</li>
<li>… gives us the most conservative fixed effect estimates, which lowers the risk of Type I error (that is, rejecting the H0 when there is no effect).</li>
<li>… generalises better to the populations that we want to draw conclusions about.</li>
</ul>
<p><br></p>
<p>From a theoretical perspective, the maximal model is what we should fit. <strong>But from a practical perspective, sometimes this is actually impossible to do in R.</strong></p>
<p>For example, take the maximal model for our RQ for <code>tel_data</code>:</p>
<div class="hcenter">
<p><code>TestScore ~ Delay * Group +  (1 + Delay | Subject_ID) + (1 + Delay * Group | Test_word)</code></p>
</div>
<p>If we try to fit this model, R will not be able to do it.</p>
<p>Next week, we’ll learn how to deal with that issue.</p>
<p><br></p>
<p><strong>Regardless of any practical issues that happen when we try to fit the model, we should always start an analysis by finding the maximal model permitted by our dataset and RQ.</strong></p>
</section></section>
<section>
<section id="back-matter" class="title-slide slide level1 center" data-background-color="#88B04B">
<h1>Back matter</h1>

</section>
<section id="learning-objectives-revisited" class="slide level2">
<h2>Learning objectives revisited</h2>
<div class="dapr3callout">
<p><strong>How do we interpret the random effects part of a model summary?</strong></p>
<ul>
<li>Always relative to the fixed effects.</li>
<li>The fixed effect is the mean of a Normal distribution of group-level adjustments.</li>
<li>The SD of that Normal distribution is given in the random effects summary table.</li>
<li>There is no significance testing involved for random effects.</li>
<li>When interpreting random effects, we are interested in questions like:
<ul>
<li>Is there greater variability within one grouping variable than another?</li>
<li>For slope adjustments: does the model predict that any specific levels of the grouping variable show the opposite direction of effect (e.g., a negative effect if the fixed effect is positive)?</li>
</ul></li>
</ul>
</div>
<div class="dapr3callout">
<p><strong>How do we know if a model can include random intercepts for a given grouping variable?</strong></p>
<ul>
<li>We think about the data generating process, and specifically the kind of variability that the grouping variable contributes to the data.</li>
<li>If the grouping variable contributes random variability to the data, then a model of that data must include random intercepts for that grouping variable.</li>
</ul>
</div>
</section>
<section id="learning-objectives-revisited-1" class="slide level2">
<h2>Learning objectives revisited</h2>
<div class="dapr3callout">
<p><strong>How do we know if a model can include random slopes over a given predictor for a given grouping variable?</strong></p>
<ul>
<li>Check if the data contains more than one value of a given predictor within at least some levels of the grouping variable.</li>
<li>(Why? Because we need at least two observations to fit a line. If there’s only one value for a given predictor and a given participant, then we have no idea what a line fit to that data would look like because we don’t know the second point that the line would connect.)</li>
</ul>
</div>
<div class="dapr3callout">
<p><strong>What is a maximal model?</strong></p>
<ul>
<li>A model that contains all possible random effects that are permitted by the data structure and the RQ.</li>
</ul>
</div>
</section>
<section id="to-do-this-week" class="slide level2">
<h2>To do this week</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Tasks:</strong></p>
<p><br></p>
<p><img data-src="figs/labs.svg" style="margin:10px;margin-bottom:-50px" width="80"> Work on exercises in labs</p>
<p><br></p>
<p><img data-src="figs/exam.svg" style="margin:10px;margin-bottom:-45px" width="80"> Complete the weekly quiz</p>
</div><div class="column" style="width:50%;">
<p><strong>Get support:</strong></p>
<p><br></p>
<p><img data-src="figs/flashcards.svg" style="margin:10px;margin-bottom:-30px" width="80"> Consult the <a href="https://uoepsy.github.io/dapr3/2627/flashcards/" target="_blank">flash cards</a></p>
<p><br></p>
<p><img data-src="figs/forum.svg" style="margin:10px;margin-bottom:-50px" width="80"> Ask questions anonymously on Piazza</p>
<p><br></p>
<p><img data-src="figs/oh.svg" style="margin:10px;margin-bottom:-40px" width="80"> We really like seeing you in office hours!</p>
</div></div>
</section></section>
<section>
<section id="appendix" class="title-slide slide level1 appendix center" data-background-color="#88B04B" data-visibility="uncounted">
<h1>Appendix</h1>

</section>
<section id="intercepts" class="slide level2" data-visibility="uncounted">
<h2>Intercepts</h2>

<img data-src="figs/w3-normal-item-int.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li><p>95% of item-level intercepts are estimated to fall between about 3.01 log units and 6.53 log units.</p></li>
<li><p>For 95% of items, the estimated log RT when the item is seen as part of an unassociated pairing is between 3.01 log units and 6.53 log units.</p></li>
<li><p><strong>This range for items is larger than the range for participants, which means that items show more variability around the fixed intercept than participants do.</strong></p></li>
</ul>
</section>
<section id="slopes" class="slide level2" data-visibility="uncounted">
<h2>Slopes</h2>

<img data-src="figs/w3-normal-item-slp.png" class="quarto-figure quarto-figure-center r-stretch"><ul>
<li><p>95% of item-level slopes over <code>pairing</code> are estimated to fall between about –1.54 log units and 0.02 log units.</p></li>
<li><p><strong>This is interesting because some items appear to show a tiny positive effect of <code>pairing</code>!</strong> In other words, they might elicit faster reactions for unassociated pairings and slower reactions for associated pairings—<strong>not the pattern we expected.</strong></p></li>
<li><p>Useful information!!</p></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="03-interp-maxmod_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/reveal-attribution/attribution.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="03-interp-maxmod_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="03-interp-maxmod_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1294,

        height: 1000,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, RevealAttribution, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <style>
      .hide {
        display: none !important;
      }
    </style>


    <script>
      function remove() {
        let footer = document.querySelector('div.footer');
        let slideNo = document.querySelector('div.slide-number');
        slideNo.classList.add('hide');
        footer.classList.add('hide');
      
        Reveal.on('slidechanged', event => {  
          if(Reveal.isFirstSlide()) {
            slideNo.classList.add('hide');
            footer.classList.add('hide');
          } else {
            slideNo.classList.remove('hide');
            footer.classList.remove('hide');
          }
        });
      }
      
      window.onload = remove();
    </script>
    <iframe id="overlayIframe" class="overlay-iframe" title="Overlay content"></iframe>
    <!-- Close button for overlay -->
    <button id="overlayClose" class="overlay-close" title="Close overlay"></button>
    <script>
      // Grab elements
      const overlayIframe = document.getElementById('overlayIframe');
      const overlayClose  = document.getElementById('overlayClose');

      // Show overlay
      function showOverlay(src) {
        overlayIframe.src = src;
        overlayIframe.classList.add('visible');
        overlayClose.classList.add('visible');
      }

      // Hide overlay
      function hideOverlay() {
        overlayIframe.classList.remove('visible');
        overlayClose.classList.remove('visible');
        setTimeout(() => {
          if (!overlayIframe.classList.contains('visible')) {
            overlayIframe.src = 'about:blank';
          }
        }, 300);
      }

      // Trigger overlay on click
      document.addEventListener('click', function (e) {
        if (e.target.classList.contains('iframe-trigger')) {
          const src = e.target.getAttribute('data-src');
          if (src) showOverlay(src);
        }
      });

      // Close button
      overlayClose.addEventListener('click', hideOverlay);

      // Key handling
      document.addEventListener('keydown', function (e) {
        if (overlayIframe.classList.contains('visible')) {
          if (e.key === 'Escape') {
            // Only intercept ESC when overlay is open
            e.preventDefault();
            hideOverlay();
          } else if (["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"," "].includes(e.key)) {
            // Block navigation keys *only* while overlay is visible
            e.preventDefault();
          }
          // Do NOT stopPropagation — let Reveal update UI (slide numbers etc.)
        }
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
            let selectedAnnoteEl;
            const selectorForAnnotation = ( cell, annotation) => {
              let cellAttr = 'data-code-cell="' + cell + '"';
              let lineAttr = 'data-code-annotation="' +  annotation + '"';
              const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
              return selector;
            }
            const selectCodeLines = (annoteEl) => {
              const doc = window.document;
              const targetCell = annoteEl.getAttribute("data-target-cell");
              const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
              const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
              const lines = annoteSpan.getAttribute("data-code-lines").split(",");
              const lineIds = lines.map((line) => {
                return targetCell + "-" + line;
              })
              let top = null;
              let height = null;
              let parent = null;
              if (lineIds.length > 0) {
                  //compute the position of the single el (top and bottom and make a div)
                  const el = window.document.getElementById(lineIds[0]);
                  top = el.offsetTop;
                  height = el.offsetHeight;
                  parent = el.parentElement.parentElement;
                if (lineIds.length > 1) {
                  const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
                  const bottom = lastEl.offsetTop + lastEl.offsetHeight;
                  height = bottom - top;
                }
                if (top !== null && height !== null && parent !== null) {
                  // cook up a div (if necessary) and position it 
                  let div = window.document.getElementById("code-annotation-line-highlight");
                  if (div === null) {
                    div = window.document.createElement("div");
                    div.setAttribute("id", "code-annotation-line-highlight");
                    div.style.position = 'absolute';
                    parent.appendChild(div);
                  }
                  div.style.top = top - 2 + "px";
                  div.style.height = height + 4 + "px";
                  div.style.left = 0;
                  let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
                  if (gutterDiv === null) {
                    gutterDiv = window.document.createElement("div");
                    gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                    gutterDiv.style.position = 'absolute';
                    const codeCell = window.document.getElementById(targetCell);
                    const gutter = codeCell.querySelector('.code-annotation-gutter');
                    gutter.appendChild(gutterDiv);
                  }
                  gutterDiv.style.top = top - 2 + "px";
                  gutterDiv.style.height = height + 4 + "px";
                }
                selectedAnnoteEl = annoteEl;
              }
            };
            const unselectCodeLines = () => {
              const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
              elementsIds.forEach((elId) => {
                const div = window.document.getElementById(elId);
                if (div) {
                  div.remove();
                }
              });
              selectedAnnoteEl = undefined;
            };
              // Handle positioning of the toggle
          window.addEventListener(
            "resize",
            throttle(() => {
              elRect = undefined;
              if (selectedAnnoteEl) {
                selectCodeLines(selectedAnnoteEl);
              }
            }, 10)
          );
          function throttle(fn, ms) {
          let throttle = false;
          let timer;
            return (...args) => {
              if(!throttle) { // first call gets through
                  fn.apply(this, args);
                  throttle = true;
              } else { // all the others get throttled
                  if(timer) clearTimeout(timer); // cancel #2
                  timer = setTimeout(() => {
                    fn.apply(this, args);
                    timer = throttle = false;
                  }, ms);
              }
            };
          }
            const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
            for (let i=0; i<annoteTargets.length; i++) {
              const annoteTarget = annoteTargets[i];
              const targetCell = annoteTarget.getAttribute("data-target-cell");
              const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
              const contentFn = () => {
                const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
                if (content) {
                  const tipContent = content.cloneNode(true);
                  tipContent.classList.add("code-annotation-tip-content");
                  return tipContent.outerHTML;
                }
              }
              const config = {
                allowHTML: true,
                content: contentFn,
                onShow: (instance) => {
                  selectCodeLines(instance.reference);
                  instance.reference.classList.add('code-annotation-active');
                  window.tippy.hideAll();
                },
                onHide: (instance) => {
                  unselectCodeLines();
                  instance.reference.classList.remove('code-annotation-active');
                },
                maxWidth: 300,
                delay: [50, 0],
                duration: [200, 0],
                offset: [5, 10],
                arrow: true,
                appendTo: function(el) {
                  return el.parentElement.parentElement.parentElement;
                },
                interactive: true,
                interactiveBorder: 10,
                theme: 'light-border',
                placement: 'right',
                popperOptions: {
                  modifiers: [
                  {
                    name: 'flip',
                    options: {
                      flipVariations: false, // true by default
                      allowedAutoPlacements: ['right'],
                      fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                    },
                  },
                  {
                    name: 'preventOverflow',
                    options: {
                      mainAxis: false,
                      altAxis: false
                    }
                  }
                  ]        
                }      
              };
              window.tippy(annoteTarget, config); 
            }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>