---
title: "DAPR3_week4_2"
author: "uoepsy"
date: "2022-10-10"
output: html_document
---

```{r}
library(tidyverse)
library(lme4)

alcgad <- read_csv("../../../data/alcgad.csv") %>% mutate(interv = group)
head(alcgad)

ggplot(alcgad, aes(x=gad, y=alcunits,color=factor(ppt))) +
  geom_point(alpha=.4)+
  labs(x="Generalised Anxiety Disorder (GAD-7)",y="Units of Alcohol in previous 7 days")+
  guides(color="none") +
  #geom_smooth(method=lm,se=F)+
  #facet_wrap(~interv)+
  NULL

alcgad <- alcgad %>% group_by(ppt) %>%
  mutate(
    gad_m = mean(gad),
    gad_mc = gad-mean(gad)
  )

ggplot(alcgad, aes(x=gad_mc, y=alcunits,color=factor(ppt))) +
  geom_point(alpha=.4)+
  labs(x="Generalised Anxiety Disorder (GAD-7)",y="Units of Alcohol in previous 7 days")+
  guides(color="none") +
  #geom_smooth(method=lm,se=F)+
  #facet_wrap(~interv)+
  NULL

```

```{r}
fulldat <- read_csv("../../data/countrysleep.csv")

ggplot(fulldat, aes(x=Days,y=Reaction,col=Subject)) + 
  geom_point()+
  geom_smooth(method=lm,se=F) +
  guides(col="none")
```





