---
title: "week 2 dapr3"
author: "uoepsy"
date: "2022-09-25"
output: html_document
---


```{r}
library(tidyverse)
library(lme4)
# CRQ (cross sect)
crq <- read_csv("https://uoepsy.github.io/data/crqdata.csv")
# scotmw <- read_csv("https://uoepsy.github.io/data/LAAwellbeing.csv")
# COG TIME (longitudinal)
cogtime <- read_csv("https://uoepsy.github.io/data/cogtimerpm.csv")
```


# clustering, variance between and within

# compl pooling, no pooling

# pivotting

# fitting multilevel models, summary()

random intercepts, random slopes,

```{r}
m <- lmer(cog ~ visit_n + (1|participant), cogtime)
broom.mixed::augment(m) %>%
  ggplot(.,aes(x=visit_n,y=.fitted,col=factor(participant)))+
  geom_point()+
  geom_line()

m2 <- lmer(cog ~ visit_n + (1 + visit_n |participant), cogtime)
broom.mixed::augment(m2) %>%
  ggplot(.,aes(x=visit_n,y=.fitted,col=factor(participant)))+
  geom_point()+
  geom_line()
```


# inference

```{r}
library(lmerTest)
summary(lmer(cog ~ visit_n + (1 + visit_n |participant), cogtime))
```


