---
title: "dapr3_w5_nurses"
author: "jk"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
nursedf <- read_csv("https://uoepsy.github.io/data/nurse_stress.csv")
nursedf <- nursedf %>%
  mutate(across(c(hospital, expcon, gender, wardtype, hospsize), factor))

head(nursedf)
```

The files nurses.csv contains three-level simulated data from a hypothetical study on stress in hospitals. The data are from nurses working in hospitals. It is a cluster-randomized experiment. In each of 25 hospitals, four wards are selected and randomly assigned to an experimental and a control condition. In the experimental condition, a training
program is offered to all nurses to cope with job-related stress. After the program is completed, a sample of about 10 nurses from each ward is given a test that measures job-related stress. Additional variables are: nurse age (years), nurse experience (years), nurse gender (0 = male, 1 = female), type of ward (0 = general care, 1 = special care), and hospital size (0 = small, 1 = medium, 2 = large).
(From https://multilevel-analysis.sites.uu.nl/datasets/ )

> After accounting for nurses' age, gender and experience, does having been offered a training program to cope with job-related stress appear to reduce levels of stress, and if so, by how much?






