<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>W5 Exercises: Bringing it all together – DAPR3 Lab Exercises</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5460563ecb836ffb649f4b12c4d7a76e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

function toggle_visibility(id1, id2) {

var e = document.getElementById(id1);

var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('jk-circle-right')) {

    f.classList.add('jk-circle-down')

    f.classList.remove('jk-circle-right')

} else {

    f.classList.add('jk-circle-right')

    f.classList.remove('jk-circle-down')

}

}

</script>

<link href="site_libs/panelset-0.3.0/panelset.css" rel="stylesheet">

<script src="site_libs/panelset-0.3.0/panelset.js"></script>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR3 Lab Exercises</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-multi-level-models" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Multi-level Models</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-multi-level-models">    
        <li>
    <a class="dropdown-item" href="./01ex.html">
 <span class="dropdown-text">W1: Regression Refresher</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02ex.html">
 <span class="dropdown-text">W2 Exercises: Introducing MLM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03ex.html">
 <span class="dropdown-text">W3 Exercises: Nested and Crossed Structures</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./04ex.html">
 <span class="dropdown-text">W4 Exercises: Centering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./05ex.html">
 <span class="dropdown-text">W5 Exercises: Bringing it all together</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-measurement--factor-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Measurement &amp; Factor Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-measurement--factor-analysis">    
        <li>
    <a class="dropdown-item" href="./07ex.html">
 <span class="dropdown-text">W7 Exercises: Scale Scores &amp; PCA</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#take-your-pick" id="toc-take-your-pick" class="nav-link active" data-scroll-target="#take-your-pick">Take your pick!</a></li>
  <li><a href="#flashcards-lm-to-lmer" id="toc-flashcards-lm-to-lmer" class="nav-link" data-scroll-target="#flashcards-lm-to-lmer">Flashcards: <code>lm</code> to <code>lmer</code></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">W5 Exercises: Bringing it all together</h1>
</div>



<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<section id="take-your-pick" class="level1">
<h1>Take your pick!</h1>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>You can find all the datasets that we have seen (and more!) as an <a href="https://uoepsy.github.io/lmm/00_datasets.html" target="_blank">additional doc in the readings page</a>.</p>
<p>For each one, there is a quick explanation of the study design which also details the research aims of the project.</p>
<p>Pick one of the datasets and, in your groups:</p>
<ol type="1">
<li>explore the data, and do any required cleaning (most of them are clean already)</li>
<li>conduct an analysis to address the research aims</li>
<li>write a short description of the sample data <a href="https://uoepsy.github.io/lmm/11_writing.html#the-sample-data" target="_blank">(see Chapter 11 #the-sample-data)</a></li>
<li>write a short explanation of your methods <a href="https://uoepsy.github.io/lmm/11_writing.html#the-methods" target="_blank">(see Chapter 11 #the-methods)</a></li>
<li>write a short summary of your results, along with suitable visualisations and tables <a href="https://uoepsy.github.io/lmm/11_writing.html#the-results" target="_blank">(see Chapter 11 #the-results)</a></li>
<li>Post some of your writing on Piazza and we can collectively discuss it!</li>
</ol>
<div class="imp">
<p>Each of the datasets contains some tags that give an indication of the type of study. Anything with either “#binomial-outcome” or “#non-linear” you can ignore as we have not covered this in DAPR3.</p>
</div>
</div>
<p class="question-end">
</p>
<br>
<div class="divider div-transparent div-dot">

</div>
<p><br></p>
</section>
<section id="flashcards-lm-to-lmer" class="level1">
<h1>Flashcards: <code>lm</code> to <code>lmer</code></h1>
<p>In a simple linear regression, there is only considered to be one source of random variability: any variability left unexplained by a set of predictors (which are modelled as fixed estimates) is captured in the model residuals.</p>
<p>Multi-level (or ‘mixed-effects’) approaches involve modelling more than one source of random variability - as well as variance resulting from taking a random sample of observations, we can identify random variability across different groups of observations. For example, if we are studying a patient population in a hospital, we would expect there to be variability across the our sample of patients, but also across the doctors who treat them.</p>
<p>We can account for this variability by allowing the outcome to be lower/higher for each group (a random intercept) and by allowing the estimated effect of a predictor vary across groups (random slopes).</p>
<div class="blue">
<p>Before you expand each of the boxes below, think about how comfortable you feel with each concept.<br>
This content is very cumulative, which means often going back to try to isolate the place which we need to focus efforts in learning.</p>
<p><strong>Study tip:</strong> Choose a topic in one of the boxes below, but don’t expand the box yet. Instead, grab a pen and paper, and first spend two minutes writing down everything you can think of about that topic. After those two minutes, you can expand the box and see if you covered the key information. Write down anything you missed. Another day, try writing about the same topic again, and see if you can include anything you missed the first time.</p>
<p><strong>Why does this work?</strong> Research on learning has shown that if you test yourself at recalling ideas (and especially if you repeatedly test yourself across several days or weeks), you’ll get better at remembering and understanding these ideas in the long term.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Simple Linear Regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="frame">
<p><strong>Formula:</strong></p>
<ul>
<li><span class="math inline">\(y_i = b_0 + b_1 x_i + \epsilon_i\)</span></li>
</ul>
<p><strong>R command:</strong></p>
<ul>
<li><code>lm(outcome ~ predictor, data = dataframe)</code></li>
</ul>
<p><em>Note:</em> this is the same as <code>lm(outcome ~ 1 + predictor, data = dataframe)</code>. The <code>1 +</code> (which represents the intercept, <span class="math inline">\(b_0\)</span>) is always there, even if we don’t explicitly write it. (It’s possible to tell R to remove it, e.g., by explicitly writing <code>0 + predictor</code>, but realistically you probably won’t ever want to fit a model with no intercept.)</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Multi-level data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If our dataset contains multiple observations from the same subject, for example, or multiple observations of the same stimulus, then those data points are not independent. For example:</p>
<ul>
<li>Subject A may behave a particular consistent way, and Subject B may behave a <em>different</em> particular consistent way. So, one data point from Subject A will be closer to the other data points from Subject A than it will be to the data points from Subject B.</li>
<li>Similarly, Stimulus A may provoke a particular reaction, while Stimulus B may provoke a <em>different</em> particular reaction. So a data point from Stimulus A will look more like the other data from Stimulus A than it will to the data from Stimulus B.</li>
</ul>
<p>This is one way for data points to be non-independent. But a simple regression assumes independence. So, we need some extra way to take this non-independence into account. And we do that using random effects.</p>
<p>In other words: when our data is ‘clustered’ or ‘grouped’ such that datapoints are no longer independent, but belong to some grouping such as that of multiple observations from the same subject, we have multiple sources of random variability. A simple regression does not capture this.</p>
<p>To illustrate how a simple regression falls short: If we separate out our data to show an individual plot for each grouping (in this data the grouping is by subjects), we can see how the fitted regression line from <code>lm()</code> is assumed to be the same for each group.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Random intercepts
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>By including a random-intercept term, we are letting our model estimate some variability around the average intercept parameter. The variability reflects how the intercept should be adjusted (nudged up or down) to better suit the data from different members of each group.</p>
<div class="frame">
<p><strong>Formula:</strong><br>
Level 1:</p>
<ul>
<li><span class="math inline">\(y_{ij} = b_{0i} + b_{1} x_{ij} + \epsilon_{ij}\)</span></li>
</ul>
<p>Level 2:</p>
<ul>
<li><span class="math inline">\(b_{0i} = \gamma_{00} + \zeta_{0i}\)</span></li>
</ul>
<p>Where the expected values of <span class="math inline">\(\zeta_{0}\)</span>, and <span class="math inline">\(\epsilon\)</span> are 0, and their variances are <span class="math inline">\(\sigma_{0}^2\)</span> and <span class="math inline">\(\sigma_\epsilon^2\)</span> respectively. We will further assume that these are normally distributed.</p>
<p>(“Random intercepts” are called “random” because the adjustments to the intercept are modelled as <em>random</em> samples from an underlying normal distribution with mean 0 and standard deviation <span class="math inline">\(\sigma_0\)</span>.)</p>
<div class="imp">
<p>Remember, variance is just standard deviation squared!</p>
</div>
<p>We can now see that the intercept estimate <span class="math inline">\(b_{0i}\)</span> for a particular group <span class="math inline">\(i\)</span> is represented by the combination of a mean estimate for the parameter (<span class="math inline">\(\gamma_{00}\)</span>) and a random effect (that is, an adjustment, a nudge) for that group (<span class="math inline">\(\zeta_{0i}\)</span>).</p>
<p><strong>R command:</strong></p>
<ul>
<li><code>lmer(outcome ~ predictor + (1 | grouping), data = dataframe)</code></li>
</ul>
</div>
<p>Notice how the fitted line of the random intercept model has been adjusted for each subject.<br>
Each subject’s line has been moved up or down. The intercepts can be different, but the slopes are all the same.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Another way of comparing the estimates of the random intercept model is to plot all the by-subject lines (the colourful lines) and overlay the fixed effect line (the thick green line):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Here, we see that the green fixed effect line is the average of all the by-subject lines, and that all the by-subject lines have the exact same slope as the fixed effect line—they’ve just been nudged up or down.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pooling &amp; Shrinkage
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If you think about it, we might have done a similar thing to the random intercept with the tools we already had at our disposal, by using <code>lm(y~x+subject)</code>. This would give us a coefficient for the difference between each subject and the reference level intercept, or we could extend this to <code>lm(y~x*subject)</code> to give us an adjustment to the slope for each subject.</p>
<p>However, the estimate of these models will be slightly different. The green lines are the predictions from the model with a random intercept by subject. The purple lines (sometimes hidden behind the green one) are the predictions from the model with a fixed effect of subject.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Why is the purple line for <code>sub_373</code> below the green line? Why is the purple line for <code>sub_374</code> above the green line?</strong> The short answer: “shrinkage”. The green lines (which come from the random intercept model) are “shrunk” closer to the average line than the purple lines (which come from the fixed effect model).</p>
<!-- TODO: confusing "cluster" vocab here -->
<p>In general, when we use multilevel models, the estimates for each member of a group are shrunk toward the average. (How much they are shrunk by depends on how variable the members of a group are, as well as how many data points each member contributes.)</p>
<p>Shrinkage is a benefit of multilevel models for a couple reasons:</p>
<ul>
<li>Shrinkage makes our estimates a bit more conservative (it’s harder to get extreme estimates when they are shrunk toward the average).</li>
<li>Shrinkage means that we can make a more educated guess about the estimates for members of a group, based on the estimates from everyone else in the group.</li>
</ul>
<p>You could think of it like this: In the example above, the multilevel model “borrows information” or “borrows strength” from subjects <code>sub_352</code>, <code>sub_369</code>, and all the others, to inform its estimates for <code>sub_373</code> and about <code>sub_374</code>. “Borrowing information” or “borrowing strength” also gets termed “partial pooling”, because we are partially combining (that is, partially pooling) all the information across members of a group to get an average, but still allowing those group members to vary a little.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>model</th>
<th>pooling</th>
<th>explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>lm(y~x)</td>
<td>complete pooling</td>
<td>all information from all members of a group is combined (pooled) together, and a line is fit that doesn’t take grouping into account at all</td>
</tr>
<tr class="even">
<td>lm(y~group + x)</td>
<td>no pooling</td>
<td>information is divided between the members of the group, and differnences between group members are estimated. Observations from group <span class="math inline">\(i\)</span> contribute <em>only</em> to estimates about group <span class="math inline">\(i\)</span></td>
</tr>
<tr class="odd">
<td>lmer(y~x+(1</td>
<td>group))</td>
<td>partial pooling</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Random slopes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="frame">
<p><strong>Formula:</strong><br>
Level 1:</p>
<ul>
<li><span class="math inline">\(y_{ij} = b_{0i} + b_{1i} x_{ij} + \epsilon_{ij}\)</span></li>
</ul>
<p>Level 2:</p>
<ul>
<li><span class="math inline">\(b_{0i} = \gamma_{00} + \zeta_{0i}\)</span><br>
</li>
<li><span class="math inline">\(b_{1i} = \gamma_{10} + \zeta_{1i}\)</span></li>
</ul>
<p>Where the expected values of <span class="math inline">\(\zeta_0\)</span>, <span class="math inline">\(\zeta_1\)</span>, and <span class="math inline">\(\epsilon\)</span> are 0, and their variances are <span class="math inline">\(\sigma_{0}^2\)</span>, <span class="math inline">\(\sigma_{1}^2\)</span>, <span class="math inline">\(\sigma_\epsilon^2\)</span> respectively. We will further assume that these are normally distributed.</p>
<p>(Like random intercepts, “random slopes” are called “random” because the adjustments to the slope are modelled as <em>random</em> samples from an underlying normal distribution with mean 0 and standard deviation <span class="math inline">\(\sigma_1\)</span>.)</p>
<div class="imp">
<p>Remember, variance is just standard deviation squared!</p>
</div>
<p>As with the intercept <span class="math inline">\(b_{0i}\)</span>, the slope of the predictor <span class="math inline">\(b_{1i}\)</span> is now modelled by a mean <span class="math inline">\(\gamma_{10}\)</span> and a random effect for each group (<span class="math inline">\(\zeta_{1i}\)</span>).</p>
<p><strong>R command:</strong></p>
<ul>
<li><code>lmer(outcome ~ predictor + (1 + predictor | grouping), data = dataframe)</code></li>
</ul>
<p><em>Note:</em> this is the same as <code>lmer(outcome ~ predictor + (predictor | grouping), data = dataframe)</code> . Like in the fixed-effects part, the <code>1 +</code> is assumed in the random-effects part.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model parameters: Fixed effects
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Fixed effects are the parameters estimated for the average group, around which the random effects can vary.</p>
<p>The plot below show the fitted values for each subject from the random slopes model <code>lmer(outcome ~ predictor + (1 + predictor | grouping), data = dataframe)</code></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The thick green line shows the fixed intercept and slope around which the members of the group all vary randomly.</p>
<p>The <em>fixed effects</em> are the parameters that define the thick green line, and we can extract them using the <code>fixef()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(random_slopes_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          x1 
    405.790      -0.672 </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model parameters: Variance components
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Variance components are the variances and covariances of the random effects. A multilevel model estimates variance components as well as fixed effects.</p>
<p>The reason we call random effects “random” is because the adjustments to the fixed effects are modelled as random samples from an underlying normal distribution. The width of these distributions represents how much the group tends to deviate from each fixed effect. We can think of the width of these distributions as the variance components.</p>
<!-- TODO MAYBE: Change the normal distributions in `pltints` and `pltslops` from standard normals to normals with the same SDs as the output of `VarCorr()` below ? -->
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>We can extract these using the <code>VarCorr()</code> function, and we can also see them in the “random effects” part of the <code>summary()</code> output from a model.</p>
<p>Looking at these variance components, we can ask:</p>
<ul>
<li>How much do members of a group vary around the fixed intercept? And around the fixed slope? (This is answered by the standard deviation.)</li>
<li>Do members of a group with higher intercepts also have higher slopes? (This is the correlation between random intercept and random slope.)</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(random_slopes_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups   Name        Std.Dev. Corr 
 subject  (Intercept) 72.72         
          x1           1.36    -0.35
 Residual             25.74         </code></pre>
</div>
</div>
<div class="imp">
<p>Remember, variance is just standard deviation squared!</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Extracting group-member-specific random effects
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<!-- The plots below show the fitted values for each subject from each model that we have gone through in these expandable boxes (simple linear regression, random intercept, and random intercept & slope):  -->
<!-- ```{r} -->
<!-- #| echo: false -->
<!-- #| fig-width: 12 -->
<!-- plotdata2<- -->
<!--   ggplot(dat, aes(x=x1,y=outcome, col=subject))+ -->
<!--   geom_point(alpha=0.5)+geom_path(alpha=0.5)+ -->
<!--   theme_classic()+ -->
<!--   theme(plot.title = element_text(hjust = 0.5), legend.position = "none")+ -->
<!--   scale_y_continuous(breaks=NULL)+scale_x_continuous(breaks=NULL)+ -->
<!--   labs(title="- The data (by subject) - ", y="y", x="x")+ -->
<!--   NULL -->
<!-- #(plot_data + plotdata2 ) / (plot_lm2 + plot_ri + plot_rs) -->
<!-- plot_lm2 + plot_ri + plot_rs -->
<!-- ``` -->
<!-- In the random-intercept model (center panel), the differences from each of the subjects' intercepts to the fixed intercept (thick green line) have mean 0 and standard deviation $\sigma_0$.  The standard deviation (and variance, which is $\sigma_0^2$) is what we see in the random effects part of our model summary (or using the `VarCorr()` function).   -->
<!-- ``` -->
<!-- Random effects: -->
<!--  Groups   Name        Variance Std.Dev. -->
<!--  subject  (Intercept) 5207     72.2     -->
<!--  Residual             1512     38.9     -->
<!-- Number of obs: 185, groups:  subject, 20 -->
<!-- ``` -->
<!-- ```{r} -->
<!-- #| echo: false -->
<!-- #| out-width: "400px" -->
<!-- knitr::include_graphics("images/varcors.PNG") -->
<!-- ``` -->
<!-- In the random-slope model (right panel), the same is true for the differences from each subjects' slope to the fixed slope.  -->
<!-- As our fixed effects are: -->
<!-- ```{r} -->
<!-- fixef(random_slopes_model) -->
<!-- ``` -->
<p>We can extract each group member’s deviations from the group average (i.e., from the fixed effect) using the <code>ranef()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(random_slopes_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$subject
        (Intercept)      x1
sub_308       31.33 -1.4400
sub_309      -28.83  0.4184
sub_310        2.71  0.0599
sub_330       59.40  0.3853
sub_331       74.96  0.1739
sub_332       91.09 -0.2346
sub_333       97.85 -0.1906
sub_334      -54.19 -0.5585
sub_335      -16.90  0.9207
sub_337       52.22 -1.1660
sub_349      -67.76 -0.6844
sub_350       -5.82 -1.2379
sub_351       61.20  0.0550
sub_352       -7.91 -0.6650
sub_369      -47.64 -0.4681
sub_370      -33.12 -1.1100
sub_371       77.58 -0.2040
sub_372      -36.39 -0.4583
sub_373     -197.58  1.7990
sub_374      -52.20  4.6051

with conditional variances for "subject" </code></pre>
</div>
</div>
<p>What do these numbers mean?</p>
<p>These are the differences between the line that fits each subject’s data and the line defined by the fixed intercept and the fixed slope. So the first entry, the line that fits the data from <code>sub_308</code> has an intercept that’s 31.33 higher than the fixed intercept and a slope that is 1.44 below the fixed slope.</p>
<p>If we wanted to find the parameters of each subject’s line, we could compute them with this information and the model’s fixed effects. But the next drop-down box shows us how to find those parameters more simply.</p>
<!-- These are the deviations from the overall intercept ($\widehat \gamma_{00} = 405.79$) and slope ($\widehat \gamma_{10} = -0.672$) for each subject $i$.   -->
<!-- So the first entry, `sub_308`, has an intercept 31.33 above the fixed intercept of 405.79, and has a slope that is -1.44 below the fixed slope of -0.672.   -->
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Extracting group-member-specific coefficients
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can see the estimated intercept and slope for each subject specifically, using the <code>coef()</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(random_slopes_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$subject
        (Intercept)     x1
sub_308         437 -2.112
sub_309         377 -0.254
sub_310         409 -0.612
sub_330         465 -0.287
sub_331         481 -0.498
sub_332         497 -0.907
sub_333         504 -0.863
sub_334         352 -1.231
sub_335         389  0.248
sub_337         458 -1.838
sub_349         338 -1.357
sub_350         400 -1.910
sub_351         467 -0.617
sub_352         398 -1.337
sub_369         358 -1.140
sub_370         373 -1.782
sub_371         483 -0.876
sub_372         369 -1.131
sub_373         208  1.127
sub_374         354  3.933

attr(,"class")
[1] "coef.mer"</code></pre>
</div>
</div>
<p>Let’s confirm that the outcome of <code>coef()</code> is the same as taking the fixed effects and then adding each subject’s random effects (as seen in the previous drop-down box).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">int =</span> <span class="fu">fixef</span>(random_slopes_model)[<span class="dv">1</span>] <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ranef</span>(random_slopes_model)<span class="sc">$</span>subject[,<span class="dv">1</span>],</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">slope =</span> <span class="fu">fixef</span>(random_slopes_model)[<span class="dv">2</span>] <span class="sc">+</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ranef</span>(random_slopes_model)<span class="sc">$</span>subject[,<span class="dv">2</span>]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      int  slope
 [1,] 437 -2.112
 [2,] 377 -0.254
 [3,] 409 -0.612
 [4,] 465 -0.287
 [5,] 481 -0.498
 [6,] 497 -0.907
 [7,] 504 -0.863
 [8,] 352 -1.231
 [9,] 389  0.248
[10,] 458 -1.838
[11,] 338 -1.357
[12,] 400 -1.910
[13,] 467 -0.617
[14,] 398 -1.337
[15,] 358 -1.140
[16,] 373 -1.782
[17,] 483 -0.876
[18,] 369 -1.131
[19,] 208  1.127
[20,] 354  3.933</code></pre>
</div>
</div>
<p>Yes, both of these outcomes are the same.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Plotting random effects
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The quick and easy way to plot your random effects is to use the <code>dotplot.ranef.mer()</code> function in <code>lme4</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>randoms <span class="ot">&lt;-</span> <span class="fu">ranef</span>(random_slopes_model, <span class="at">condVar=</span><span class="cn">TRUE</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dotplot.ranef.mer</span>(randoms)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$subject</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<!-- 

<div class="optional-begin"><button id='opt-start-1' class="jk-circle-right optional-icon clickable" onclick="toggle_visibility('opt-body-1', 'opt-start-1')"> Completely optional - extracting them for plotting in ggplot </button></div><div class="optional-body" id = "opt-body-1" style="display: none;">

 -->
<!-- Sometimes, however, we might want to have a bit more control over our plotting, we can extract the estimates and correlations for each subject:   -->
<!-- ```{r} -->
<!-- #we can get the random effects: -->
<!-- #(note that we use $subject because there might be other groupings, and the ranef() function will give us a list, with one element for each grouping variable) -->
<!-- randoms <- -->
<!--   ranef(random_slopes_model)$subject %>% -->
<!--   mutate(subject = row.names(.)) %>%  # the subject IDs are stored in the rownames, so lets add them as a variable -->
<!--   pivot_longer(cols=1:2, names_to="term",values_to="estimate") # finally, let's reshape it for plotting -->
<!-- #and the same for the standard errors (from the arm package): -->
<!-- randoms_se <- -->
<!--   arm::se.ranef(random_slopes_model)$subject %>% -->
<!--   as.data.frame() %>% -->
<!--   mutate(subject = row.names(.)) %>% -->
<!--   pivot_longer(cols=1:2, names_to="term",values_to="se") -->
<!-- # join them together: -->
<!-- ranefs_plotting <- left_join(randoms, randoms_se) -->
<!-- # it's easier for plotting if we -->
<!-- ggplot(ranefs_plotting, aes(y=subject, x=estimate))+ -->
<!--   geom_errorbarh(aes(xmin=estimate-2*se, xmax=estimate+2*se))+ -->
<!--   facet_wrap(~term, scales="free_x") -->
<!-- ``` -->
<!-- 

</div><p class="optional-end"></p>

 -->
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Assumptions, Influence
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For a simple linear model, <span class="math inline">\(\color{red}{y} = \color{blue}{b_0 + b_1(x)} \color{black}{+ \varepsilon}\)</span>, we distinguish between the systematic model part (<span class="math inline">\(b_0 + b_1(x)\)</span>) and the errors, which randomly vary around the systematic model (<span class="math inline">\(\varepsilon\)</span>). In words, we can summarise the linear model expression as <span class="math inline">\(\color{red}{\text{outcome}} = \color{blue}{\text{model}}\)</span> <span class="math inline">\(+ \text{error}\)</span>.</p>
<p>In the multi-level model, another source of error (i.e., of variation) come from our random effects: <span class="math inline">\(\color{red}{\text{outcome}}\)</span> = <span class="math inline">\(\color{blue}{\text{model}}\)</span> <span class="math inline">\(+ \text{group-error} + \text{individual-error}\)</span>. As such, random effects are another form of residual. Our assumptions of “zero mean, constant variance” apply at both levels of residuals (see <a href="#fig-assump" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-assump" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-assump-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/assump.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-assump-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The black dashed lines show our model assumptions. We assume that the intercept adjustments are normally distributed (the large normal distribution at the y axis), and we further assume that the residuals between the individual data points and the subject-level line are also normally distributed with equal variance across the range of the predictor (the smaller normal distributions around one of the subject-level lines).
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>We can assess these normality of both <code>resid(model)</code> and <code>ranef(model)</code> by constructing plots using functions such as <code>hist()</code>, <code>qqnorm()</code> and <code>qqline()</code>.<br>
</li>
<li>We can also use <code>plot(model, type=c("p","smooth"))</code> to give us our residuals vs fitted plot (smooth line should be horizontal at approx zero, showing zero mean).<br>
</li>
<li><code>plot(model, form = sqrt(abs(resid(.))) ~ fitted(.), type = c("p","smooth"))</code> will give us our scale-location plot (smooth line should be horizontal, showing constant variance).</li>
</ul>
<p>We can also use the <code>check_model()</code> function from the <strong>performance</strong> package to get lots of info at once:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(random_slopes_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- RESUME -->
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Inference
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To get p-values for our coefficients, there are lots of different ways (see <a href="https://uoepsy.github.io/lmm/03_inference.html" target="_blank">Optional Chapter 3</a> if you’re interested).<br>
For DAPR3, we are recommending using the “Satterthwaite” method, which can be done by re-fitting the model using the <strong>lmerTest</strong> package:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>random_slopes_model2 <span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>( outcome <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span>x1<span class="sc">|</span>subject), <span class="at">data=</span>dat)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(random_slopes_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: outcome ~ 1 + x1 + (1 + x1 | subject)
   Data: dat

REML criterion at convergence: 1862

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-4.069 -0.417 -0.014  0.431  5.226 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 subject  (Intercept) 5287.68  72.72         
          x1             1.86   1.36    -0.35
 Residual              662.33  25.74         
Number of obs: 185, groups:  subject, 20

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  405.790     16.666  18.045   24.35    3e-15 ***
x1            -0.672      0.313  16.757   -2.15    0.047 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
   (Intr)
x1 -0.370</code></pre>
</div>
</div>
<p>If we want to test multiple coefficients at once, then we can conduct model comparisons by doing a likelihood ratio test. We start with a full model, and then create a more restricted comparison model by removing the bits that we want to test.</p>
<p>In the example below, the full model is <code>outcome ~ 1 + x1 + x2 + (1 + x1 | subject)</code>. If we wanted to test whether the predictors <code>x1</code> and <code>x2</code> contribute significantly to the model, then we would create a restricted model for comparison by removing those terms. That gives us <code>outcome ~ 1 + (1 + x1 | subject)</code>.</p>
<p>You’ll notice that <code>x1</code> still appears in the random effect: we’re still getting a random slope over <code>x1</code> by subject, even though <code>x1</code> is no longer in the fixed effects. This looks a little weird, but when doing model comparison, it’s OK to have random slopes of predictors that aren’t in the fixed effects.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>( outcome <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> x1 <span class="sc">+</span> x2<span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span>x1<span class="sc">|</span>subject), <span class="at">data=</span>dat)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>model2<span class="fl">.0</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>( outcome <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span>x1<span class="sc">|</span>subject), <span class="at">data=</span>dat)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2<span class="fl">.0</span>, model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Visualising group-member-specific fitted values
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The model fitted (or “model predicted”) values can be obtained a couple ways.</p>
<ul>
<li><code>predict()</code> returns just the predicted values, which is a little inconvenient because you’d have to map them back to the original data that you gave to the model.</li>
<li><code>broom.mixed::augment()</code> returns the predicted values <em>as well as</em> the data that you gave to the model.</li>
</ul>
<p>We would typically like to plot the fitted values for each member of the grouping variable (e.g., for each subject):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(random_slopes_model) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x1, <span class="at">y=</span>.fitted, <span class="at">group=</span>subject))<span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Visualising fixed effects along with the group-member-specific fitted values
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If we want to plot the fixed effects from our model, we have to do something else. A good option is to use the <strong>effects</strong> package to construct a dataframe of the linear prediction across the values of a predictor, plus confidence intervals. We can then pass this to <code>ggplot()</code>, giving us all the control over the aesthetics.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># when you want more control</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>ef <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">effect</span>(<span class="at">term=</span><span class="st">"x1"</span>,<span class="at">mod=</span>random_slopes_model))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ef, <span class="fu">aes</span>(<span class="at">x=</span>x1,<span class="at">y=</span>fit, <span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper))<span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span>.<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>We might then want to combine this with our plot of fitted values to make a plot that shows both the estimates for the average group (this is the fixed effects part) <em>and</em> the amount to which groups vary around that average (this we can see with the fitted values plot)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># when you want more control</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>ef <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">effect</span>(<span class="at">term=</span><span class="st">"x1"</span>,<span class="at">mod=</span>random_slopes_model))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(random_slopes_model) <span class="sc">|&gt;</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>x1))<span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>.fitted,<span class="at">group=</span>subject), <span class="at">alpha=</span>.<span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> ef, <span class="fu">aes</span>(<span class="at">y=</span>fit))<span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> ef, <span class="fu">aes</span>(<span class="at">y=</span>fit,<span class="at">ymin=</span>lower,<span class="at">ymax=</span>upper), </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">col=</span><span class="st">"red"</span>, <span class="at">fill=</span><span class="st">"red"</span>,<span class="at">alpha=</span>.<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05ex_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nested variables
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the following schematic, we have observations from several children, who are each from a particular school.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/structure_nestednew.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
<p>Every school contains multiple children, and each child appears only in a single school. So, the child variable is “nested” within the school variable.</p>
<p>In R, we specify random effects for nested variables using the syntax</p>
<p><code>(1 | school) + (1 | child:school)</code><br>
or<br>
<code>(1 | school) + (1 | school:child)</code></p>
<p>The specific order of the variables around the colon symbol doesn’t matter. (But if you think about nesting like “child within school”, then maybe the <code>child:school</code> order is more intuitive.)</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Crossed variables
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In the following schematic, we have observations from several participants who have each taken part in several tasks.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/structure_fullycrossed.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
<p>Because we have data from every participant for every task, we describe the participant and task variables as “fully crossed”.</p>
<p><br></p>
<p>In contrast: the following schematic shows observations from several participants, who have each only done a subset of the tasks.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/structure_partiallycrossed.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
<p>We have some data from every participant, and we have some data from every task, but it’s not the case that every participant took part in every task. In this case, we describe the participant and task variables as “partially crossed” or “not fully crossed”.</p>
<p><br></p>
<p>In R, we specify random effects for both fully crossed and partially crossed variables as follows:</p>
<p><code>(1 | ppt) + (1 | task)</code></p>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
MLM in a nutshell
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>MLM allows us to model effects in the linear model as <em>varying</em> for different groups.</p>
<p><strong>Important terminology note:</strong> in this box, “group” is used to mean “a single member of a grouping variable”, e.g., an individual participant in a study, whereas in the flash cards above, “group” was used to mean the grouping variable itself, e.g., <code>participant</code>.</p>
<p>The coefficients we remember from simple linear models (the <span class="math inline">\(b\)</span>’s) are now modelled as a distribution: their mean is the effect for the average group, and the variance defines how much the groups vary around the mean. We can see this in <a href="#fig-unlmm" class="quarto-xref">Figure&nbsp;2</a>, where both the intercept and the slope of the line are modelled as varying by-groups. <a href="#fig-unlmm" class="quarto-xref">Figure&nbsp;2</a> shows the overall line in blue, with a given group’s line in green.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-unlmm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-unlmm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/un_lmm.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-unlmm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Multilevel Model. Each group (e.g.&nbsp;the group in the green line) deviates from the overall fixed effects (the blue line), and the individual observations (green points) deviate from their groups line
</figcaption>
</figure>
</div>
</div>
</div>
<p>The formula notation for these models involves separating out our effects <span class="math inline">\(b\)</span> into two parts: the overall effect <span class="math inline">\(\gamma\)</span> + the group deviations <span class="math inline">\(\zeta_i\)</span>:</p>
<p><span class="math display">\[
\begin{align}
&amp; \text{for observation }j\text{ in group }i \\
\quad \\
&amp; \text{Level 1:} \\
&amp; \color{red}{y_{ij}}\color{black} = \color{blue}{b_{0i} \cdot 1 + b_{1i} \cdot x_{ij}}\color{black} + \varepsilon_{ij} \\
&amp; \text{Level 2:} \\
&amp; \color{blue}{b_{0i}}\color{black} = \gamma_{00} + \color{orange}{\zeta_{0i}} \\
&amp; \color{blue}{b_{1i}}\color{black} = \gamma_{10} + \color{orange}{\zeta_{1i}} \\
\quad \\
&amp; \text{Where:} \\
&amp; \gamma_{00}\text{ is the population intercept, and }\color{orange}{\zeta_{0i}}\color{black}\text{ is the deviation of group }i\text{ from }\gamma_{00} \\
&amp; \gamma_{10}\text{ is the population slope, and }\color{orange}{\zeta_{1i}}\color{black}\text{ is the deviation of group }i\text{ from }\gamma_{10} \\
\end{align}
\]</span></p>
<p>The group-specific deviations <span class="math inline">\(\zeta_{0i}\)</span> from the overall intercept are assumed to be normally distributed with mean <span class="math inline">\(0\)</span> and variance <span class="math inline">\(\sigma_0^2\)</span>. Similarly, the deviations <span class="math inline">\(\zeta_{1i}\)</span> of the slope for group <span class="math inline">\(i\)</span> from the overall slope are assumed to come from a normal distribution with mean <span class="math inline">\(0\)</span> and variance <span class="math inline">\(\sigma_1^2\)</span>. The correlation between random intercepts and slopes is $= (<em>{0i}, </em>{1i}):</p>
<p><span class="math display">\[
\begin{bmatrix} \zeta_{0i} \\ \zeta_{1i} \end{bmatrix}
\sim N
\left(
    \begin{bmatrix} 0 \\ 0 \end{bmatrix},
    \begin{bmatrix}
        \sigma_0^2 &amp; \rho_{01}1 \\
        \rho_{01} &amp; \sigma_1^2
    \end{bmatrix}
\right)
\]</span></p>
<p>The random errors, independently from the random effects, are assumed to be normally distributed with a mean of zero<br>
<span class="math display">\[
\epsilon_{ij} \sim N(0, \sigma_\epsilon^2)
\]</span></p>
<p>We fit these models using the R package <strong>lme4</strong>, and the function <code>lmer()</code>. Think of it like building your linear model <code>lm(y ~ 1 + x)</code>, and then allowing effects (i.e.&nbsp;things on the right hand side of the <code>~</code> symbol) to vary by the grouping of your data. We specify these by adding <code>(vary these effects | by these groups)</code> to the model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(y <span class="sc">~</span> x <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> x <span class="sc">|</span> group), <span class="at">data =</span> df)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: y ~ x + (1 + x | group)
   Data: df

REML criterion at convergence: 638

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.4945 -0.5722 -0.0135  0.6254  2.3912 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 group    (Intercept) 2.262    1.504        
          x           0.796    0.892    0.55
 Residual             4.367    2.090        
Number of obs: 132, groups:  group, 20

Fixed effects:
            Estimate Std. Error t value
(Intercept)    1.726      0.967    1.78
x              1.151      0.297    3.88

Correlation of Fixed Effects:
  (Intr)
x -0.552</code></pre>
</div>
</div>
<p>The summary of the <code>lmer</code> output returns estimated values for</p>
<p>Fixed effects:</p>
<ul>
<li><span class="math inline">\(\widehat \gamma_{00} = 1.726\)</span></li>
<li><span class="math inline">\(\widehat \gamma_{10} = 1.151\)</span></li>
</ul>
<p>Variability of random effects:</p>
<ul>
<li><span class="math inline">\(\widehat \sigma_{0} = 1.504\)</span></li>
<li><span class="math inline">\(\widehat \sigma_{1} = 0.892\)</span></li>
</ul>
<p>Correlation of random effects:</p>
<ul>
<li><span class="math inline">\(\widehat \rho = 0.546\)</span></li>
</ul>
<p>Residuals:</p>
<ul>
<li><span class="math inline">\(\widehat \sigma_\epsilon = 2.09\)</span></li>
</ul>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>