---
title: "Untitled"
author: "uoepsy.github.io"
date: "12/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glue)
library(tidyverse)
library(knitr)
```

```{r}


lecs = list.files("lectures", ".html", full.names=T)
labs = list.files("labs", ".html", full.names=T)

data.frame(
  Week = 1:11,
  Lecture = c(
    glue("[Linear Models and Clustered Data]({lecs[1]})"),
    glue("[Introducing Multilevel Models]({lecs[2]})"),
    glue("[Assumptions & Diagnostics for Multilevel Models]({lecs[3]})"),
    glue("[Centering Predictors, and Generalized Multilevel Models]({lecs[4]})"),
    glue("[Multilevel Models: Research Questions; Writing up]({lecs[5]})"),
    glue("Break Week!"),
    glue("[Introducing Path Analysis]({lecs[7]})"),
    glue("[Path Mediation]({lecs[8]})"),
    glue("[Principal Component Analysis (PCA)]({lecs[9]})"),
    glue("[Exploratory Factor Analysis I]({lecs[10]})"),
    glue("[Exploratory Factor Analysis II]({lecs[11]})")
  ),
  Workbook = c(
    glue("[Regression Refresh | Clustered Data]({labs[1]})"),
    glue("[LM to MLM]({labs[2]})"),
    glue("[Assumptions & Diagnostics]({labs[3]})"),
    glue("[Centering | Logistic]({labs[4]})"),
    glue("[Recap]({labs[5]})"),
    glue("--"),
    glue("[Path Analysis]({labs[6]})"),
    glue("[Path Mediation]({labs[7]})"),
    glue("[Dimension Reduction]({labs[8]})"),
    glue("[EFA: Part 1]({labs[9]})"),
    glue("[EFA: Part 2]({labs[10]})")
  )
) %>% kable()

ex = list.files("examples", ".html", full.names=T)
data.frame(
  `Extra Docs` = c(
      glue("[Example Analysis: Rpt & Mixed ANOVA]({ex[1]})"),
      glue("[Example Analysis: MLM Repeated Measures]({ex[2]})"),
      glue("[Example Analysis: MLM Intervention]({ex[3]})"),
      glue("[Example Analysis: MLM Many Trials]({ex[4]})"),
      glue("[Example Analysis: EFA]({ex[7]})"),
      glue("[Explainer: PCA & Unequal Variances]({ex[5]})")
  )
) %>% kable()
```

