---
title: "Overview: Dimension Reduction, Discovery, and Testing"
format: html
---

The key thing we are doing here is:

1. Identify dimensions through their capturing of (co)variability across a set of measured variables
2. Retain a subset of those dimensions

Depending upon what the goal of our research is, the key questions are going to be:

1. how do we find the dimensions?
2. how many dimensions should we retain?
3. how does each dimension relate back to the original measured variables?  
4. How well do the set of dimensions explain the observed data?  
5. How do we represent a person's standing on the dimensions?  



## Naive 'Scale Scores'

**Goal:** Pragmatic. I want 1 thing to use in some other setting (e.g., in a further analysis, or in a clinical setting).  

1. How do we find the dimensions?
    - Assume there's only one
2. How many dimensions should we retain?
    - Assume there's only one
3. How does each dimension relate back to the original measured variables?  
    - All variables are equally related to the dimension
4. How well do the set of dimensions explain the observed data?  
    - Compute a measure of "reliability"
5. How do we represent a person's standing on the dimensions?
    - Add up all the responses on each variable $\text{sum score} = y_{1i} + y_{2i} + y_{3i} +\, ... \, + y_{pi}$, and if you want a mean-score, we then divide by the number of variables: $\text{mean score} = \frac{y_{1i} + y_{2i} + y_{3i} +\, ... \, + y_{pi}}{p}$ (see [Calculating Scale Scores](p01_scalescores.html))
    
For example, the [AQ10](https://embrace-autism.com/aq-10/) is a ten-question survey which (despite some well-established issues) is used by the NHS for autism screening.
Participants essentially respond "agree" or "disagree" to each question, and the result is scored by summing up the number of responses in the expected direction.
People must score above a 6 in order to be referred for autism diagnosis on the NHS.

This is a naive scale score. There is only one dimension (some measure of autism), and all questions are assumed to be equally related to this dimension.



## Principal Component Analysis (PCA)

**Goal:** Pragmatic. I want fewer things for use in a subsequent analysis but don't want to lose too much variability. I want those things to be uncorrelated.^[I might want this if, e.g., I have issues with multicollinearity of predictors in a regression model]

1. How do we find the dimensions?
    - Set of orthogonal (i.e., perpendicular^[like all those that we've seen above] therefore uncorrelated) dimensions that sequentially capture most variability.
    - Found via some complicated maths that feels a bit like magic! It utilises a method called "eigen decomposition", the details of which are beyond the scope of this course, but the high level idea is given below.  
2. How many dimensions should we retain?
    - Pragmatic: defined by either the number of dimensions we want, or the proportion of variability we want to retain
    - Various tools can guide us towards how many dimensions capture a "substantial" amount of variability in the data (See [Identifying the Number of Components/Factors](p01_ndim.html)).
3. how does each dimension relate back to the original measured variables?  
    - Examine correlations between dimensions and variables
    - Somewhat irrelevant for 'pure' PCA, where we are agnostic/don't care about what the dimensions _are._  
4. How well do the set of dimensions explain the observed data?  
    - Strictly speaking, PCA is not an "explanatory" tool. It simply combines variables to preserve variance. The closest we might get is to consider how much variance is captured by each dimension.  
5. How do we represent a person's standing on the dimensions?
    - Extract PCA scores (these are a weighted sum of the scores on each variables: $\text{score}_{\text{component j}} = w_{1j}y_1 + w_{2j}y_2 + w_{3j}y_3 +\, ... \, + w_{pj}y_p$). See [PCA Walkthrough](p01_pca.html#scores).  
    

## Exploratory Factor Analysis (EFA)

**Goal:** Exploratory/Discovery/Measure development. I don't have a strong theoretical model yet, but I believe there are underlying constructs that explain why these variables correlate with each other. I want to understand what those construct(s) might be and how the variables relate to them.

1. How do we find the dimensions?
    - Estimation
    - Models with different numbers of (possibly correlated) latent dimensions are compared
2. How many dimensions should we retain?
    - The model that "best explains" our observed relationships between variables
    - "best explains" = a theoretical question as much as a numerical one!  
3. How does each dimension relate back to the original measured variables?  
    - Examine "loadings" between dimensions and variables
4. How well do the set of dimensions explain the observed data?  
    - For EFA, this question is subsumed into questions 2 and 3. The aim is to settle on the model that makes most sense. 
5. How do we represent a person's standing on the dimensions?
    - The dimensions in EFA are "latent" in that they are never directly observed and people's standing on dimensions cannot be perfectly determined. There are infinitely many sets of scores for the dimensions that would work equally well for a given model ("factor score indeterminacy"). This means that there are many different ways to *estimate* scores. See [EFA Walkthrough](p02_efa.html#scores)
    
## Confirmatory Factor Analysis (CFA)

**Goal:** Theory testing. I have a theoretical model of how these variables relate to these constructs. I want to test how well that model is reflected in these data  

1. How do we find the dimensions?
    - We define them
2. How many dimensions should we retain?
    - Irrelevant as the dimensions are pre-defined
3. How does each dimension relate back to the original measured variables?  
    - Pre-defined mapping of which variables to which dimensions. Magnitudes and directions are estimated.   
4. How well do the set of dimensions explain the observed data?  
    - This is the key part of CFA. There are various measures of "model fit" that are ultimately asking "how well can the model reproduce the observed covariance matrix?"  
5. How do we represent a person's standing on the dimensions?
    - Similar to EFA, standing is represented by estimated "Factor Scores" for the latent dimensions. Because the model structure is pre-defined, these scores are more "theoretically pure" reflections of the construct, though they still carry the same inherent uncertainty (indeterminacy) as EFA scores. 
    - In practice, CFA naturally extends to more advanced methods that allow us to estimate things of interest (e.g., relationships between constructs) _without_ having to ever estimate individual scores on the construct. Rather than a 2 step process of 1) estimate scores, 2) use scores in subsequent analysis, methods such as Structural Equation Modelling (SEM) allow us to do it all in one.
    
    

