---
title: "dapR3 Live R week 10"
author: "Tom Booth"
date: "22/11/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# PCA example

Packages
```{r, warning=FALSE}
library(psych)
```

PCA Big Five Inventory 

```{r}
bfi <- na.omit(bfi)
head(bfi)
```


```{r}
round(cor(bfi[,1:5]),2)
```

Have a look at some IQ test score correlations as a comparison:

```{r}
round(cor(Holzinger[,11:14]), 2)
```

Run some number of components:

```{r}
fa.parallel(bfi[,1:25], fa = "pc")
```

```{r}
((eigen(cor(bfi[,1:5]))$values)/sum(eigen(cor(bfi[,1:5]))$values))*100 
```

```{r}
((eigen(cor(Holzinger[,11:14]))$values)/sum(eigen(cor(Holzinger[,11:14]))$values))*100 
```

Running PCA:

```{r}
principal(bfi[,1:25], nfactors = 5, rotate = "none")
```

```{r}
library(kableExtra)
library(tidyverse)
test <- principal(bfi[,1:25], nfactors = 5, rotate = "none")$loadings
kable(test[,1:5])
```

```{r}
pca_scores <- principal(bfi[,1:25], nfactors = 5, rotate = "none")$scores
pca_scores
```