---
title: "dapR3 Live R week 7"
author: "Tom Booth"
date: "02/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

**Goal for today is to show some more examples of lavaan model code and to relate this to the standard linear model from dapR2.**

Some packages:
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(lavaan)
library(semPlot)
```

Some Data:
```{r, message=FALSE, warning=FALSE}
org <- read_csv("C:/Work/Teaching/org_performance.csv")
```

Have a look at the variables:
```{r}
str(org)
```


Standard linear model:
```{r}
m1 <- lm(Perform ~ Mot + Sex + PubPri, data = org)
summary(m1)
```

lavaan model:
```{r}
path1 = '
Perform ~ Mot + Sex + PubPri
'
```

Running the model:
```{r}
path1_out <- sem(path1, data = org)
summary(path1_out)
```

Standardising:

```{r}
summary(path1_out, std=T)
```

Extending our path model to multiple DVs:
```{r}
path2 = '
Perform ~ Mot
Mot ~ Sex + PubPri
'
```

```{r}
path2_out <- sem(path2, data = org)
summary(path2_out, std = T)
```

```{r}
partable(path2_out)
```
```{r}
semPaths(path2_out)
```

