---
title: "Untitled"
author: "uoepsystat"
date: "10/20/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ICC)
library(lme4)
library(effects)
library(broom.mixed)
library(sjPlot)
library(HLMdiag)
library(lmeresampler)
worms_data <- read_csv("https://uoepsy.github.io/data/worms.csv")
crq <- read_csv("https://uoepsy.github.io/data/crqdata.csv")
cogtime <- read_csv("https://uoepsy.github.io/data/cogtimerpm.csv") %>%
mutate(across(c(participant, sexFemale, alc), factor))
nursedf <- read_csv("https://uoepsy.github.io/data/nurse_stress.csv") %>%
mutate(across(c(hospital, expcon, gender, wardtype, hospsize), factor))
# Data from labs
toys_read <- read_csv("https://uoepsy.github.io/data/toyexample.csv")
bball <-
left_join(
read_csv("https://uoepsy.github.io/data/basketballconditions.csv"),
read_csv("https://uoepsy.github.io/data/bballhrv.csv") %>%
pivot_longer(trial_1:trial_20, names_to = "trial_no", values_to = "hrv")
) %>%
mutate(sub = factor(sub))
load(url("https://uoepsy.github.io/data/WeightMaintain3.rda"))
bnt <- read_csv("https://uoepsy.github.io/data/bntmono.csv")
```


```{r}
library(tidyverse)
library(lme4)
toys_read <- read_csv("https://uoepsy.github.io/data/toyexample.csv")
toys_read$x <- rnorm(nrow(toys_read))
mod <- lm(R_AGE ~ hrs_week+x, data = toys_read)
summary(mod)
library(car)
vif(mod)
library(knitr)
kable(vif(mod))
```



